<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/article/category-list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'articleCategoryID',
                title: '文章分类ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'categoryName',
                title: '分类名称',
                align: 'center',
                valign: 'middle',
                width:200

            }, {
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter,
                width:200

            }]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="编辑" href="javascript:;"  class="col-md-4" rid="' + row.articleCategoryID + '" data-toggle="modal" data-target="#edit_modal"><i class="glyphicon glyphicon-edit"></i></a>',
            '<a href="javascript:;" class="remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认删除该条记录吗？" url="/admin/article-category/del" method="post" params="adminID='+ row.articleCategoryID +'" title=\"Apk hash删除\">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }

    $('#edit_modal').on("show.bs.modal",function(e){
        var btn = $(e.relatedTarget);
        var id = btn.attr('rid');

        $.ajax({
            url : '/admin/article-cateogry/get',
            method : 'post',
            data : {
                adminID : id
            },
            dataType : 'json',
            success : function(data){
                $("#adminID").val(data.adminID);
                $("#username").val(data.username);
            }
        });

    });

</script>
