<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
        <a  class="btn btn-primary" href="/admin/article/add-view"><i class="fa fa-pencil"></i>新增</a>
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/article/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'articleID',
                title: '文章ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'articleName',
                title: '文章名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'categoryName',
                title: '文章分类',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'instime',
                title: '新增时间',
                align: 'center',
                valign: 'middle',
                width:200
            },{
                field: 'isIndexRecommend',
                title: '是否首页推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="首页推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="articleID='+ row.articleID +'&isIndexRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消首页推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="articleID='+ row.articleID +'&isIndexRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isIndexArticleList',
                title: '是否首页列表展示',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="首页展示" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认展示吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="articleID='+ row.articleID +'&isIndexArticleList=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消首页展示" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消展示吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="articleID='+ row.articleID +'&isIndexArticleList=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            }, {
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter,
                width:200

            }]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="编辑" href="/admin/article/add-view?articleID=' + row.articleID + '"><i class="glyphicon glyphicon-edit"></i></a>',
            '<a title="删除" href="javascript:void(0)" class=" remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认删除文章' + row.articleName + '吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="articleID='+ row.articleID +'&isDel=1">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }

</script>
