<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/friendly-link/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'linkID',
                title: '链接ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'linkName',
                title: '链接名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'linkUrl',
                title: '链接地址',
                align: 'center',
                valign: 'middle',
                width:200

            }
            ]
    });

</script>
