<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="pull-left">
        <a  class="btn btn-primary" href="/admin/<?php echo $this->layout()->controllerName; ?>/add-view"><i class="fa fa-pencil"></i>新增</a>
    </div>
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/friendly-link/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'linkID',
                title: '链接ID',
                align: 'center',
                valign: 'middle'
            },
            {
                field: 'img',
                title: '链接图片',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    return '<img src="' + value + '" />';
                }
            },
            {
                field: 'linkUrl',
                title: '链接地址',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:function operateFormatter(value, row, index) {
                    return [
                        "<a title='编辑' href=\"/admin/<?php echo $this->layout()->controllerName;?>/add-view?linkID="+row.linkID+"\" ><i class=\"glyphicon glyphicon-edit\"></i></a>",
                        '<a title="删除" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
                        ' cbody="确认删除吗？" url="/admin/<?php echo $this->layout()->controllerName;?>/del" method="post" params="linkID='+ row.linkID +'">'+
                        '<i class="glyphicon glyphicon-remove"></i>'+
                        '</a>'
                    ].join('');
                }
            }
            ]
    });

</script>
