<?php
echo $this->headLink()
    ->appendStylesheet('/dist/styles/main/space.css')
?>
<div class="mySpace">
    <div class="spaceBanner">
        <div class="center ">
            <div class="spacename "> 古鱼的空间</div>
            <div class="spacetip ">良辰美景奈何天，赏心悦事谁家园。</div>
        </div>
    </div>
    <div class="spacecont">
        <div class="center space_bti">
            <div class="space_bti">
                <ul>
                    <li><a href="spaceIndex.html">首页</a></li>
                    <li><a href="articleList.html">文章列表</a></li>
                    <li><a href="publishArticle.html">发表文章</a></li>
                    <li><a href="aboutAs.html">关于我</a></li>
                    <li class="space_img">
                        <img src="/dist/images/defaultPic.jpg">

                        <div class="space_dp"> 我有店铺</div>
                    </li>
                    <li class="space_gz"><a href="">关注(<span class="ff7519">1255</span>)</a></li>
                    <li><a href="">收藏文章</a></li>
                    <li><a href="">关注空间</a></li>
                    <li><a href="">留言板(<span class="ff7519">1255</span>)</a></li>
                </ul>
            </div>
        </div>
        <div class="center ">
            <div class="space_wz3">
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>

            </div>
        </div>


    </div>

</div>