<?php
echo $this->headLink()
    ->appendStylesheet('/dist/styles/main/space.css')
?>

<div class="mySpace">
    <div class="spaceBanner">
        <div class="center ">
            <div class="spacename "> 古鱼的空间</div>
            <div class="spacetip ">良辰美景奈何天，赏心悦事谁家园。</div>
        </div>
    </div>
    <div class="spacecont">
        <div class="center space_bti">
            <div class="space_bti">
                <ul>
                    <li><a href="spaceIndex.html">首页</a></li>
                    <li><a href="articleList.html">文章列表</a></li>
                    <li><a href="publishArticle.html">发表文章</a></li>
                    <li><a href="aboutAs.html">关于我</a></li>
                    <li class="space_img">
                        <img src="/dist/images/defaultPic.jpg">

                        <div class="space_dp"> 我有店铺</div>
                    </li>
                    <li class="space_gz"><a href="">关注(<span class="ff7519">1255</span>)</a></li>
                    <li><a href="">收藏文章</a></li>
                    <li><a href="">关注空间</a></li>
                    <li><a href="">留言板(<span class="ff7519">1255</span>)</a></li>
                </ul>
            </div>
        </div>
        <div class="center ">
            <div class="space_li1 space_wz2">
                <div class="space_title">
                    <div class="space_title_left"><span class="font30">性格--雍正五题</span><span class="font16">（2016-1-009 20:08）</span>
                    </div>
                    <div class="space_title_right">
                        <ul>
                            <li>报名【有奖征文】</li>
                            <li><a href="">编辑</a></li>
                            <li class="space_title_del"><a href="">删除</a></li>
                        </ul>
                    </div>
                </div>
                <div class="c"></div>
                <div class="space_conts">
                    <p>
                        文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章</p>

                    <p>
                        文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章</p>

                    <p>
                        文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章</p>

                    <div class="space_zzai">
                        <ul>
                            <li>阅读（877）</li>
                            <li>评论 （25）</li>
                            <li class="space_love">（67）<span class="colred">喜欢</span></li>
                            <li class="space_title_del colred"><a href="">收藏本文>></a></li>
                        </ul>

                    </div>
                </div>
            </div>
            <div class=" space_comment">
                <div class="space_comment_left">
                    <textarea class="space_tex"></textarea>
                </div>
                <div class="space_comment_right">
                    <div class="space_fbcom">发表评论</div>
                </div>
            </div>
            <div class="space_pinlun">
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
                <div class="space_cominfo">
                    <div class="space_cominfo_left">
                        <div><span class="space_cominfo_name">壶冰</span><span class="font16">2015-12-30 20:08</span>
                        </div>
                        <div class="space_cominfo_nr">
                            文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文章文
                        </div>
                    </div>
                    <div class="space_cominfo_right">
                        <ul>
                            <li><a href="">举报</a></li>
                            <li class="space_no"><a href="">回复>></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>


    </div>

</div>