<?php echo $this->doctype(); ?>
<html>
<head>
    <?php echo $this->headTitle(); ?>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php
    echo $this->headLink()
        ->appendStylesheet($this->basePath() . '/admin/css/style.css')
        ->appendStylesheet($this->basePath() . '/admin/css/style-responsive.css')
        ->appendStylesheet($this->basePath() . '/admin/css/font-awesome.min.css')
        ->appendStylesheet($this->basePath() . '/admin/css/bootstrap-reset.css')
        ->appendStylesheet($this->basePath() . '/admin/css/bootstrap-table.css')
        ->appendStylesheet($this->basePath() . '/admin/css/bootstrap-datetimepicker.min.css')
        ->appendStylesheet($this->basePath() . '/admin/css/main.css');
    ?>
</head>
<body class="sticky-header">
<section>
    <!-- left side start-->
    <div class="left-side sticky-left-side" >

        <!--logo and iconic logo start-->
        <div class="logo">
            <a href="/admin"><img src="/admin/img/logo.png" alt=""></a>
        </div>

        <div class="logo-icon text-center">
            <a href="/admin"><img src="/admin/img/logo_icon.png" alt=""></a>
        </div>
        <!--logo and iconic logo end-->


        <div class="left-side-inner">
            <!--sidebar nav start-->
            <ul class="nav nav-pills nav-stacked custom-nav">
                <li class="menu-list nav-active">
                    <a href="#"><i class="fa fa-plane"></i><span class=""></span>网站管理</a>
                    <ul class="sub-menu-list nav nav-second-level">
                        <li class="<?php if ($controllerName == 'website') { ?> active<?php } ?>">
                            <a href="/admin/website/index"  class="text-success">网站设置</a>
                        </li>
                        <li class="<?php if ($controllerName == 'ad') { ?> active<?php } ?>">
                            <a href="/admin/ad/index"  class="text-success">广告管理</a>
                        </li>
                        <li class="<?php if ($controllerName == 'customization') { ?> active<?php } ?>">
                            <a href="/admin/customization/index"  class="text-success">定制商品管理</a>
                        </li>
                        <li class="<?php if ($controllerName == 'order' && $actionName == 'customization') { ?> active<?php } ?>">
                            <a href="/admin/order/customization"  class="text-success">定制订单</a>
                        </li>
                        <li class="<?php if ($controllerName == 'artist') { ?> active<?php } ?>">
                            <a href="/admin/artist/index"  class="text-success">名家管理</a>
                        </li>
                        <li class="<?php if ($controllerName == 'store') { ?> active<?php } ?>">
                            <a href="/admin/store/index"  class="text-success">店铺列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'special') { ?> active<?php } ?>">
                            <a href="/admin/special/index"  class="text-success"> 专场列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'product') { ?> active<?php } ?>">
                            <a href="/admin/product/index"  class="text-success"> 拍品列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'article') { ?> active<?php } ?>">
                            <a href="/admin/article/index"  class="text-success">文章列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'order' && $actionName == 'index') { ?> active<?php } ?>">
                            <a href="/admin/order/index"  class="text-success">订单列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'member') { ?> active<?php } ?>">
                            <a href="/admin/member/index"  class="text-success">用户列表</a>
                        </li>
                        <li class="<?php if ($controllerName == 'member-article') { ?> active" <?php } ?>">
                            <a href="/admin/member-article/index"  class="text-success">个人空间文章列表</a>
                        </li>

                        <li class="<?php if ($controllerName == 'sms') { ?> active<?php } ?>">
                            <a href="/admin/sms/sms"  class="text-success">短信列表</a>
                        </li>
                    </ul>
               </li>
            </ul>

        </div>
    </div>
    <!-- left side end-->

    <!-- main content start-->
    <div class="main-content">

        <!-- header section start-->
        <div class="header-section">

            <!--toggle button start-->
            <a class="toggle-btn"><i class="fa fa-bars"></i></a>
            <!--toggle button end-->
            <!--notification menu start -->
            <div class="menu-right">
                <ul class="notification-menu">
                    <li>
                        <a href="#" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            <?php echo $adminName;;?>
                            <span class="caret"></span>
                        </a>

                        <ul id="user-menu-info" class="dropdown-menu dropdown-menu-usermenu pull-right">
                            <li><a href="/admin/user/modifypwd"><i class="fa fa-cog"></i>  密码修改</a></li>
                            <li><a href="/admin/index/logout"><i class="fa fa-sign-out"></i> 退出</a></li>
                        </ul>
                    </li>

                </ul>
            </div>
            <!--notification menu end -->

        </div>
        <!-- header section end-->

        <!-- page heading start-->

        <!--body wrapper start-->


        <?php
        echo $this->headScript()
            ->appendFile($this->basePath() . '/admin/js/jquery-1.10.2.min.js')
            ->appendFile($this->basePath() . '/admin/js/jquery-ui-1.9.2.custom.min.js')
            ->appendFile($this->basePath() . '/admin/js/jquery-migrate-1.2.1.min.js')
            ->appendFile($this->basePath() . '/admin/js/bootstrap.min.js')
            ->appendFile($this->basePath() . '/admin/js/modernizr.min.js')
            ->appendFile($this->basePath() . '/admin/js/jquery.nicescroll.js')
            ->appendFile($this->basePath() . '/admin/js/plupload/plupload.full.min.js')
            ->appendFile($this->basePath() . '/admin/js/plupload/i18n/zh_CN.js')
            ->appendFile($this->basePath() . '/admin/js/bootstrap-table.js')
            ->appendFile($this->basePath() . '/admin/js/bootstrap-datetimepicker.min.js')
            ->appendFile($this->basePath() . '/admin/js/bootstrap-datetimepicker.zh-CN.js', null, array('charset'=>'UTF-8'))
            ->appendFile($this->basePath() . '/admin/js/jquery.comet.js')
            ->appendFile($this->basePath() . '/admin/js/placeholder.js')
            ->appendFile($this->basePath() . '/admin/js/workerman/socketio.js');
        ?>

        <?php echo $this->content; ?>

        <?php echo $this->inlineScript()->setFile($this->basePath() . '/admin/js/scripts.js'); ?>


        <!--通用确认模态框-->
        <div class="modal fade" id="confirmModal" tabindex="-1" role="dialog" aria-labelledby="confirmModalLabel" aria-hidden="true">
            <div class="modal-dialog" id="windowSize">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="confirmModalLabel"></h4>
                    </div>
                    <div class="modal-body" id="confirmModalBody">
                        在这里添加一些文本
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">取消</button>
                        <button id="modal_confirm_btn" type="button" class="btn btn-primary">确定</button>
                    </div>
                </div>
            </div>
        </div>

        <!--body wrapper end-->

        <!--通用提示框 start-->
        <div class="modal fade" id="tipModal" tabindex="-1" role="dialog"
             aria-labelledby="myModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-sm" id="tip-dialog-box">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close"
                                data-dismiss="modal" aria-hidden="true">
                            &times;
                        </button>
                        <h4 class="modal-title">
                            提示
                        </h4>
                    </div>
                    <div class="modal-body" id="tip-body">

                    </div>

                </div><!-- /.modal-content -->
            </div>

        </div>
        <!--通用提示框 end-->
    </div>
    <!-- main content end-->
</section>
<script>
   /* // 连接服务端
    var socket = io('http://120.26.124.179:2120');
    // uid可以是自己网站的用户id，以便针对uid推送以及统计在线人数
    uid = 'sa'+said;
    console.log(uid);
    // socket连接后以uid登录
    socket.on('connect', function(){
        socket.emit('login', uid);
    });
    // 后端推送来消息时
    socket.on('new_msg', function(msg){
        console.log("收到消息:"+msg);
    });
    // 后端推送来在线数据时
    socket.on('update_online_count', function(online_stat){
        //console.log(online_stat);
    });*/
</script>

</body>
</html>
