<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/member-article/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'memberArticleID',
                title: '用户文章ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'memberArticleName',
                title: '用户文章名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'memberArticleContent',
                title: '用户文章内容',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, index, row){
                    return '<a target="_blank" href="'+ value +'">文章内容</a>';
                }

            },{
                field: 'isIllegal',
                title: '是否被举报',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    var str = '';
                    if(value == 1){
                        str += '<font style="color:red;">是</font>';
                    }else{
                        str += '否';
                    }
                    return str;
                }

            },{
                field: 'joinAward',
                title: '是否报名有奖征文',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    var str = '';
                    if(value == 1){
                        str += '是';
                    }else{
                        str += '否';
                    }
                    return str;
                }

            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    return [
                        '<a title="删除" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
                        ' cbody="确认删除吗？" url="/admin/<?=$this->layout()->controllerName;?>/del" method="post" params="memberArticleID='+ row.memberArticleID +'">'+
                        '<i class="glyphicon glyphicon-remove"></i>'+
                        '</a>'
                    ].join('');
                }
            }]
    });

</script>
