


    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>

<script type="text/javascript">
    $(function(){

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?=$this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: false,
            showColumns: false,
            showRefresh: false,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'errorID',
                title: '报错ID',
                align: 'center',
                valign: 'middle'
                /*sortable: true*/
            }, {
                field: 'content',
                title: '报错内容',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'nickName',
                title: '报错人姓名',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'isTreated',
                title: '是否被处理',
                align: 'center',
                valign: 'middle',
                sortable: true,
                formatter : function(value, row, index){
                    var str = '';

                    if(value == 1){
                        str += '<font style="color:red;">是</font>';
                    }else{
                        str += '否';
                        str += '<a title="已处理" href="javascript:void(0)" class="text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认已处理吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="errorID='+ row.errorID +'&isTreated=1"><i class="glyphicon glyphicon-ok"></i></a>';

                    }

                    return str;
                }

            },{
                field: 'instime',
                title: '报错时间',
                align: 'center',
                valign: 'middle',
                width: '200px'
            }]
        });
    });
</script>