
<div class="wrapper" id="page-wrapper">

    <div id="table_toolbar">
        <div class="pull-left">
            <a  class="btn btn-primary" href="/admin/<?php echo $this->layout()->controllerName;?>/add-view"><i class="fa fa-pencil"></i>新增</a>
        </div>
    </div>
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>
</div>

<script type="text/javascript">
    $(function(){

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?php echo $this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: false,
            showColumns: false,
            showRefresh: false,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'productCategoryFilterID',
                title: '拍品分类筛选项ID',
                align: 'center',
                valign: 'middle'
                /*sortable: true*/
            }, {
                field: 'categoryName',
                title: '拍品分类名称',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'filterName',
                title: '拍品分类筛选项名称',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter
            }]
        });
    });
    function operateFormatter(value, row, index) {
        return [
            "<a title='编辑' href=\"/admin/<?php echo $this->layout()->controllerName;?>/add-view?productCategoryFilterID="+row.productCategoryFilterID+"\" ><i class=\"glyphicon glyphicon-edit\"></i></a>",
            '<a title="删除" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认删除吗？" url="/admin/<?php echo $this->layout()->controllerName;?>/del" method="post" params="productCategoryFilterID='+ row.productCategoryFilterID +'">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }
</script>