<link rel="stylesheet" href="/dist/styles/main/index.css">
<div class="hot-shopAd mb20">
    <div class="center"><a href="/">首页</a> > 店铺介绍</div>
</div>
<div class="center">
    <div class="page-box pb30 fz16">
        <?php
            echo $storeInfo['storeDesc'];
        ?>

    </div>
    <div class="pb30 fz16">
        <a style="font-size: 16px;font-family: 'Microsoft Yahei';color:red;" href="/zone/index?zoneID=<?php echo $storeInfo['memberID']; ?>">进入店主的个人空间 >></a>
    </div>
</div>
