
<link rel="stylesheet" type="text/css" href="/he/style/common.css" media="screen" />
<link rel="stylesheet" type="text/css" href="/he/style/style.css" media="screen" />
<div class="exc_bann" style="<?php if(!empty($storeInfo['storeBanner'])){?>background:url('<?php echo $storeInfo['storeBanner'];  ?>') no-repeat center top<?php } ?>">
    <div class="wrap1 pt0">
        <dl class="exc_b_l">
            <dt><img src="<?php echo $storeInfo['storeLogo'] ?>"></dt>
            <dd>
                <span><?php echo $storeInfo['storeName'];?></span> <a qq="<?php echo $storeInfo['storeqq'] ?>" href="javascript:;" class="exc_b tencent-qq">联系卖家</a><br/><?php echo $storeInfo['storeSignature'] ?>
            </dd>
        </dl>
        <!--<div class="exc_code"><img src="/he/images/code.gif"></div>-->
    </div>
</div>
<div class="exc_rank">
    <div class="wrap2">
        <div class="exc_rank_l">
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>" class="<?php if(empty($auctionStatus) && empty($order)) echo 'on'; ?>">全 &nbsp;部</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&auctionStatus=2" class="<?php if($auctionStatus == 2) echo 'on'; ?>">正在拍卖</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&auctionStatus=1" class="<?php if($auctionStatus == 1) echo 'on'; ?>">即将拍卖</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&order=currPrice&sort=desc" class="rank_icon_x1<?php if($order == 'currPrice') echo '_on'; ?>">价&nbsp;格</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&order=interestedCount&sort=desc" class="rank_icon_x<?php if($order == 'interestedCount') echo '_on'; ?>">关注人数</a>
        </div>
        <div class="exc_rank_r">
            <?php
                if(!empty($_memberInfo['storeID']) && $_memberInfo['storeID'] == $storeInfo['storeID']){
            ?>
                    <a href="/member/store-setting">更改抬头图片</a><a href="/member/store-setting">进入店铺设置</a>
            <?php
                }
            ?>
            <a href="javascript:;" class="post-error-btn">站内报错</a></div>
        </div>
</div>
<div class="wrap5">
    <div class="inner_cls">
        <span>店内分类</span>
            <?php
                foreach($storeCategories as $v){
            ?>
                    <a href="/store/detail?storeID=<?php echo $storeInfo['storeID']; ?>&storeCategoryID=<?php echo $v['storeCategoryID']; ?>" class="inner_f"><font>●</font><?php echo $v['storeCategoryName'] ?></a>
            <?php
                }
            ?>
        <font class="fr innder_ab">
                <a href="/store/desc?storeID=<?php echo $storeInfo['storeID']; ?>" target="_blank">关于我</a>&nbsp;&nbsp;&nbsp;
        </font>
    </div>
</div>
<?php /*if(!empty($storeRecommendProducts)){ */?><!--
<div class="exc_tj">
    <div class="wrap2">
        <h3>店铺精选</h3>
        <?php
/*            foreach($storeRecommendProducts as $v){
                echo $this->render('/front/common/product', array('v' => $v));
            }
        */?>
    </div>
</div>
--><?php /*}*/ ?>
<div class="wrap4">
    <div class="wrap2">
        <?php
            foreach($storeProducts as $v){
                echo $this->render('/front/common/product', array('v' => $v));
            }
        ?>
    </div>
    <br style="clear: both;" />
    <?php
        echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/store/detail?storeID='. $storeInfo['storeID'] .'&storeCategoryID=' . $storeCategoryID . '&auctionStatus=' . $auctionStatus . '&order=' . $order . '&sort=' . $sort . '&'));
    ?>
</div>
<script>
    $(function(){
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'product-list');
        });
    })
</script>