<?php
echo $this->headLink()->appendStylesheet('/he/style/common.css')->appendStylesheet('/he/style/style.css');
echo $this->headScript()->appendFile('/he/js/jquery.min.js')->appendFile('/he/js/jquery.datePicker-min.js');
?>
<div class="exc_bann">
    <div class="wrap1 pt0">
        <dl class="exc_b_l">
            <dt><img src="<?php echo $storeInfo['storeLogo'] ?>"></dt>
            <dd>
                <span><?php echo $storeInfo['sotreName'];?></span> <a href="tencent://message/?uin=<?php echo $storeInfo['storeqq'] ?>&Site=www.kaipai123.com&Menu=yes" class="exc_b">联系卖家</a><br/><?php echo $storeInfo['storeSignature'] ?>
            </dd>
        </dl>
        <!--<div class="exc_code"><img src="/he/images/code.gif"></div>-->
    </div>
</div>
<div class="exc_rank">
    <div class="wrap2">
        <div class="exc_rank_l">
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>">全 &nbsp;部</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&auctionStatus=2">正在拍卖</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&auctionStatus=1">即将拍卖</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&order=currPrice&sort=desc" class="rank_icon_x1">价&nbsp;格</a>
            <a href="/store/detail?storeID=<?php echo $storeInfo['storeID'] ?>&order=interestedCount&sort=desc" class="rank_icon_x">关注人数</a>
        </div>
        <div class="exc_rank_r">
            <?php
                if(!empty($_memberInfo['storeID'])){
            ?>
                    <a href="/member/store-setting">更改抬头图片</a><a href="/member/store-setting">进入店铺设置</a>
            <?php
                }
            ?>
            <a href="javascript:;" class="post-error-btn">站内报错</a></div>
        </div>
</div>
<div class="wrap5">
    <div class="inner_cls">
        <span>店内分类</span>
            <?php
                foreach($storeCategories as $v){
            ?>
                    <a href="javascript:;" class="inner_f"><font>●</font><?php echo $v['storeCategoryName'] ?></a>
            <?php
                }
            ?>
                <!--<a href="">关于我</a>&nbsp;&nbsp;&nbsp;-->
        </font>
    </div>
</div>
<?php if(!empty($storeRecommendProducts)){ ?>
<div class="exc_tj">
    <div class="wrap2">
        <h3>店铺精选</h3>
        <?php
            foreach($storeRecommendProducts as $v){
        ?>
                <ul class="exc_list" style="cursor:pointer;;" onclick="location.href='/product/detail?productID=<?php echo $v['productID'] ?>';">
                    <li class="lh32"><a href=""><?php echo $v['productName'] ?></a></li>
                    <li class="lh32">当前价 <span>￥<?php echo $v['currPrice'] ?></span></li>
                    <li class="lh32">距结束 <?php echo $v['leftTime'];  ?></li>
                    <li class="exc_list_img"><img src="<?php echo $v['listImg'] ?>"><font><strong><?php echo $v['auctionCount'] ?></strong><br/>次出价</font></li>
                </ul>
        <?php
            }
        ?>
    </div>
</div>
<?php } ?>
<div class="wrap4">
    <div class="wrap2">
        <?php
            foreach($storeProducts as $v){
        ?>
                <ul class="exc_list mt20" style="cursor: pointer;" onclick="location.href='/product/detail?productID=<?php echo $v['productID'] ?>';">
                    <li class="lh32"><a href=""><?php echo $v['productName'] ?></a></li>
                    <li class="lh32">当前价 <span>￥<?php echo $v['currPrice'] ?></span></li>
                    <li class="lh32">距结束 <?php echo $v['leftTime']; ?></li>
                    <li class="exc_list_img"><img src="<?php echo $v['listImg'] ?>"><font><strong><?php echo $v['auctionCount'] ?></strong><br/>次出价</font></li>
                </ul>
        <?php
            }
        ?>
    </div>
    <br style="clear: both;" />
    <?php
        echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/store/detail?storeID='. $storeInfo['storeID'] .'&auctionStatus=' . $auctionStatus . '&order=' . $order . '&sort=' . $sort . '&'));
    ?>
</div>