<link rel="stylesheet" href="/dist/styles/main/index.css" media="screen" type="text/css" />
<div class="hot-shopAd mb20">
    <div class="center"><a href="/">首页</a> > 热门店铺街</div>
</div>
<div class="center">
    <ul class="hot-shopAd-list clearfix">
        <?php foreach($stores as $v){
        ?>
            <li style="cursor: pointer;" onclick="location.href='/store/detail?storeID=<?php echo $v['storeID'] ?>';">
                <img class="lazy" data-original="<?php echo $v['storeLogo']; ?>" alt="">

                <div class="fr">
                    <h5><?php echo $v['storeName'] ?></h5>

                    <p>
                        <?php echo $v['storeSignature'] ?>
                    </p>
                </div>
            </li>
        <?php
        } ?>
    </ul>

    <?php echo $this->render('/front/common/paginate'); ?>
</div>