<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/store/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'storeID',
                title: '店铺ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'storeName',
                title: '店铺名',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'storeSignature',
                title: '店铺签名',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeDesc',
                title: '店铺简介',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeBanner',
                title: '店铺招牌',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'instime',
                title: '新增时间',
                align: 'center',
                valign: 'middle',
                width:200
            }]
    });

</script>
