<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<!-- Edit Modal Start -->
<div class="row">
    <div class="modal form-modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="edit_modal_label">封停</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="editForm" role="form" method="post" action="/admin/<?php echo $this->layout()->controllerName;?>/close">
                        <table class="table table-bordered">
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label class="col-sm-2 col-md-2 control-label">封停时间</label>
                                        <div class="col-sm-10">
                                            <select class="form-control" name="storeCloseType">

                                                <option value="1">1个月</option>
                                                <option value="2">3个月</option>
                                                <option value="3">永久</option>
                                            </select>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                        </table>
                        <input type="hidden"  name="storeID" value="" />
                    </form>
                </div>
                <div class="modal-footer">
                    <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                    <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Edit Modal End -->

<!-- Edit Modal Start -->
<div class="row">
    <div class="modal form-modal fade" id="edit_modal2" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="edit_modal_label2">设置店铺等级</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="editForm2" role="form" method="post" action="/admin/<?php echo $this->layout()->controllerName;?>/update">
                        <table class="table table-bordered">
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label class="col-sm-2 col-md-2 control-label">店铺等级</label>
                                        <div class="col-sm-10">
                                            <select class="form-control" name="level">
                                                <?php foreach($levels as $v){
                                                ?>
                                                <option value="<?php echo $v['level']; ?>"><?php echo $v['levelName']; ?></option>
                                                <?php
                                                } ?>
                                            </select>
                                        </div>
                                    </div>

                                </td>
                            </tr>
                        </table>
                        <input type="hidden"  name="storeID" value="" />
                    </form>
                </div>
                <div class="modal-footer">
                    <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                    <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Edit Modal End -->

<script>

    $('#edit_modal').on("show.bs.modal",function(e){
        var btn = $(e.relatedTarget);
        var storeID = btn.attr('rid');
        $('#edit_modal input[name=storeID]').val(storeID);
    });
    $('#edit_modal2').on("show.bs.modal",function(e){
        var btn = $(e.relatedTarget);
        var storeID = btn.attr('rid');
        var level = btn.attr('level');
        $('#edit_modal2 input[name=storeID]').val(storeID);
        $('#edit_modal2 select[name=level]').val(level);
    });

    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/store/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'storeID',
                title: '店铺ID',
                align: 'center',
                width : '120px'

            },
            {
                field: 'storeName',
                title: '店铺名',
                align: 'center',
                valign: 'middle'

            },
            {
                field: 'storeSignature',
                title: '店铺签名',
                align: 'center',
                valign: 'middle'

            }/*,{
                field: 'storeDesc',
                title: '店铺简介',
                align: 'center',
                valign: 'middle',
                width:200

            }*/,{
                field: 'storeLogo',
                title: '店铺LOGO',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    var str = '<img src="' + value + '" width="100px" />';
                    return str;
                }
            },{
                field: 'idNumber',
                title: '身份证号',
                align: 'center',
                valign: 'middle'

            },{
                field: 'idPic',
                title: '身份证图片',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    var str = '<img src="' + value + '" width="100px" />';
                    return str;
                }
            },{
                field: 'memberIdPic',
                title: '手持身份证图片',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    var str = '<img src="' + value + '" width="100px" />';
                    return str;
                }
            },{
                field: 'storeMobile',
                title: '商铺绑定手机号',
                align: 'center',
                valign: 'middle'
            },{
                field: 'verifyStatus',
                title: '审核状态',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    var str = '';
                    if(value == 1){
                        var links = [
                            '<a title="审核通过" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&verifyStatus=2"><i class="glyphicon glyphicon-ok"></i></a>',
                            '<a title="审核不通过" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核不通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&verifyStatus=3"><i class="glyphicon glyphicon-remove"></i></a>'
                        ];
                        str = links.join(' ');
                    }else if(value == 2){
                        str = '审核通过';
                    }else if(value == 3){
                        str = '审核未通过';
                    }
                    return str;
                }

            },{
                field: 'isRecommend',
                title: '是否推荐',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger  confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&isRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&isRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isHot',
                title: '是否热门',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="热门" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认热门吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&isHot=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消热门" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消热门吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&isHot=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'levelName',
                title: '店铺等级',
                align: 'center',
                valign: 'middle'
            },{
                field: 'storeID',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:function(value, row, index){
                    var s = '';

                    if(row.storeCloseType > 0){

                        if(row.storeCloseType == 1){
                            s += '封停一个月';
                        }else if(row.storeCloseType == 2){
                            s += '封停三个月';
                        }else if(row.storeCloseType == 3){
                            s += '永久封停';
                        }
                        s += '<a title="解除封停" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认解除吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="storeID='+ row.storeID +'&storeCloseType=0"><i class="glyphicon glyphicon-plus"></i></a>';
                    }else{
                        s += '<a title="封停" href="javascript:void(0)"  class="col-md-4" rid="' + value + '"  data-toggle="modal" data-target="#edit_modal"><i class="glyphicon glyphicon-minus"></i></a>';
                    }
                    s += '<a href="javascript:void(0)" level="' + row.level + '"  class="col-md-4" rid="' + value + '"  data-toggle="modal" data-target="#edit_modal2">设置等级</a>';


                    return s;
                }
            }]
    });

</script>
