<?php
/*echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.config.js');
echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.all.js');
echo $this->inlineScript()->setFile('/admin/ueditor/lang/zh-cn/zh-cn.js');*/
?>
<div class="wrapper">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <?php echo (isset($adInfo['adID'])) ? '编辑广告ID:' . $adInfo['adID'] : '新增广告页面'; ?>
                <a class="text-right" style="float:right;" href="<?php echo '/admin/' . $this->layout()->controllerName . '/index' ?>">返回</a>
            </h3>
        </div>
        <div class="panel-body">
            <div class="container mtop40" style="margin-bottom: 50px; height: auto;">
                <input name="location-url" type="hidden" value="/admin/<?php echo $this->layout()->controllerName ?>/index" />

                <form class="form-horizontal" action="/admin/<?php echo $this->layout()->controllerName ?>/<?= (isset($adInfo)) ? "update" : "add"; ?>" method="post">
                    <div class="form-group">
                        <label for="inputEmail3" class="col-sm-2 control-label">广告图片</label>

                        <div class="col-sm-10 col-md-10 access-upload" id="container">
                            <a id="img" >
                                <img src="<?php echo $adInfo['img'] ?>" alt=""/>
                            </a>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">广告位置</label>
                        <div class="col-sm-4">
                            <select class="form-control input-sm m-bot15" name="position">
                                <?php foreach ($positions as $k => $v){ ?>
                                    <option value="<?php echo $k; ?>" <?php if(isset($adInfo['position']) && $k == $adInfo['position']){echo 'selected';} ?>><?php echo $v; ?></option>
                                <?php } ?>
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">广告权重</label>
                        <div class="col-sm-4">
                            <input name="sort" value="<?php echo $adInfo['sort'];?>" class="form-control" placeholder="广告权重" />

                        </div>
                    </div>
                    <div class="form-group">
                        <label for="inputPassword3" class="col-sm-2 control-label">广告图片文字提示</label>
                        <div class="col-sm-4">
                            <input name="alt" value="<?php echo $adInfo['alt'];?>" class="form-control" placeholder="广告图片文字提示" />

                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">开始时间</label>

                        <div class="col-sm-4">
                            <input type="text" class="" id="start-time" name="startTime" value="<?php echo !empty($adInfo['startTime']) ? date('Y-m-d H:i:s', $adInfo['startTime']) : ''; ?>" >
                        </div>
                    </div>
                    <div class="form-group">
                        <label class="col-sm-2 control-label">结束时间</label>

                        <div class="col-sm-4">
                            <input type="text" class="" id="end-time" name="endTime" value="<?php echo !empty($adInfo['endTime']) ? date('Y-m-d H:i:s', $adInfo['endTime']) : ''; ?>" >
                        </div>
                    </div>
                    <input type="hidden" name="adID" value="<? if(isset($adInfo['adID'])) echo $adInfo['adID']; ?>"/>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <a class="btn btn-primary editModal" onclick="">确定</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    //var ue = UE.getEditor('editor');

    function uploadInit(id){
        //上传组件
        var uploader = new plupload.Uploader({
            runtimes : 'html5,flash,silverlight,html4',
            browse_button : id, // you can pass in id...触发上传窗口
            container: document.getElementById('container'), // ... or DOM Element itself容器
            url : '/admin/index/upload',//上传URL
            flash_swf_url : '../js/Moxie.swf',
            silverlight_xap_url : '../js/Moxie.xap',
            filters : {
                max_file_size : '10mb',//用来限定上传文件的大小
                mime_types: [//用来限定上传文件的类型，为一个数组
                    {title : "Image files", extensions : "jpg,png,jpeg,gif"},
                ],
                prevent_duplicates : false //不允许选取重复文件
            },
            multipart:true,
            max_retries:0,//当发生plupload.HTTP_ERROR错误时的重试次数，为0时表示不重试
            multi_selection:false,//是否可以在文件浏览对话框中选择多个文件
            unique_names:true,
            init: {
                PostInit: function() {
                },
                FilesAdded: function(up, files) {
                    uploader.start();
                    return false;
                },
                FileUploaded:function(up,file,response){
                    //触发
                    var imgObj = eval('(' + response.response + ')');
                    $('#'+id).html('<img src="'+imgObj.path+'">');

                    if($('#'+id).parent().find('input[name=Img]').length < 1){
                        $('#'+id).parent().append('<span title="删除"></span><input type="hidden" name="'+id+'" value="'+imgObj.path+'" />');
                    }else{
                        $('#'+id).parent().find('input[name=Img]').val(imgObj.path);
                    }

                },
                Error: function(up, err) {
                    if(err.status == 413){
                        $(".err-tip-li .licencetip").html("您上传图片过大,请不要上传超过2M的图片");
                    }
                    if(err.code == -601){
                        $(".err-tip-li .licencetip").html("图片格式错误,请重新选择");
                    }
                }
            }
        });
        uploader.init();
    }
    uploadInit("img");
    $('#start-time').datetimepicker({
        language:'zh-CN',
        format: 'yyyy-mm-dd hh:ii:ss'
    });
    $('#end-time').datetimepicker({
        language:'zh-CN',
        format: 'yyyy-mm-dd hh:ii:ss'
    });
</script>