<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
        <a  class="btn btn-primary" href="/admin/ad/add-view"><i class="fa fa-pencil"></i>新增</a>
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/ad/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'adID',
                title: '广告ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'img',
                title: '广告图片',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row){
                    if(row.img){
                        return '<img src="' + row.img +'" width="100px" height="100px" />';
                    }
                    return '';
                }

            },
            {
                field: 'position',
                title: '广告位置',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'sort',
                title: '广告权重',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'alt',
                title: '图片提示',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'startTime',
                title: '开始时间',
                align: 'center',
                valign: 'middle',
                width:200
            }, {
                field: 'endTime',
                title: '结束时间',
                align: 'center',
                valign: 'middle',
                width:200
            },{
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter,
                width:200

            }]
    });
    function operateFormatter(value, row, index) {
        return [
            '<a title="编辑" href="/admin/<?php echo $this->layout()->controllerName; ?>/add-view?adID=' + row.adID + '"><i class="glyphicon glyphicon-edit"></i></a>',
            '<a title="删除" href="javascript:void(0)" class=" remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认删除该广告吗？" url="/admin/<?=$this->layout()->controllerName;?>/del" method="post" params="adID='+ row.adID +'">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }

</script>
