<!--<div class="wrapper" id="page-wrapper">-->

    <!--<div id="table_toolbar">
        <div class="pull-left">
            <strong>专场列表</strong>
        </div>
    </div>-->
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>


    <div class="row">
        <div class="modal form-modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="edit_modal_label">专场审核</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" id="editForm" role="form" method="post" action="/admin/<?php echo $this->layout()->controllerName; ?>/update">
                            <table class="table table-bordered">
                                <tr>
                                    <td>
                                        <div class="form-group">
                                            <label for="desc" class="col-sm-2 col-md-2 control-label">不通过原因</label>
                                            <div class="col-sm-10 col-md-10">
                                                <input type="text" class="form-control" id="deny-reason" name="denyReason" value="">
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            <input type="hidden"  name="specialID" id="special-id" value="" />
                            <input type="hidden"  name="verifyStatus" value="3" />
                        </form>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                        <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--</div>
-->
<script>

    $('#edit_modal').on("show.bs.modal",function(e){
        var btn = $(e.relatedTarget);
        var id = btn.attr('special-id');

        $("#special-id").val(id);
    });

$(function(){
    table = $('#table-pagination').bootstrapTable({
        method: 'get',
        url: '/admin/<?=$this->layout()->controllerName;?>/list',
        cache: false,
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        toolbar:"#table_toolbar",
        minimumCountColumns: 2,
        sidePagination: 'server',
        columns: [
            {
                field: 'specialID',
                title: '专场ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialName',
                title: '专场名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'categoryName',
                title: '专场分类',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeName',
                title: '店铺名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialImg',
                title: '专场图片',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter : function(value, row, index){
                    str = '<img width="100px" src="' + value + '" />';
                    return str;
                }

            },{
                field: 'productCountLimit',
                title: '专场拍品数量',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'startTime',
                title: '专场开始时间',
                align: 'center',
                valign: 'middle',
                sortable: true,
                width:200

            },
            {
                field: 'endTime',
                title: '专场结束时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialID',
                title: '预览链接',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    return '<a href="/special/detail?specialID=' + value + '" target="_blank">预览</a>';
                }

            },
            {
                field: 'verifyStatus',
                title: '审核状态',
                align: 'center',
                valign: 'middle',
                sortable: true,
                width:200,
                formatter: function(value, row, index){
                    var str = '';
                    if(!value){
                        str = '未提交审核';
                    }else if(value == 1){
                        var links = [
                            '<a title="审核通过" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核通过吗？" url="/admin/<?php echo $this->layout()->controllerName;?>/update" method="post" params="specialID='+ row.specialID +'&verifyStatus=2&auctionStatus=1"><i class="glyphicon glyphicon-ok"></i></a>',
                            '<a title="审核不通过" href="javascript:void(0)" class="col-md-4 text-danger" boxsize="modal-sm" special-id="' + row.specialID + '" data-toggle="modal" data-target="#edit_modal"><i class="glyphicon glyphicon-remove"></i></a>'
                        ];
                        str = links.join(' ');
                    }else if(value == 2){
                        str = '审核通过';
                    }else if(value == 3){
                        str = '审核未通过';
                        str += '<br /> 原因:' + row.denyReason;
                    }else{
                        str = '未提交审核';
                    }
                    return str;
                }
            },{
                field: 'isPaid',
                title: '是否付款',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, row, index){
                    var s = '';
                    if(value == 1){
                        s += '已付款';
                    }else if(value == 0){
                        s += '未付款';
                        s += '<a title="确认到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/order/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=3"><i class="glyphicon glyphicon-ok"></i></a>';
                    }

                    return s;
                }

            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter
            }]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="强制下架" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn text-danger" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认强制下架吗？" url="/admin/<?=$this->layout()->controllerName;?>/withdraw" method="post" params="specialID='+ row.specialID +'">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }
});

</script>
