<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/special/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'specialID',
                title: '专场ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialName',
                title: '专场名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialProductCategoryID',
                title: '专场拍品分类',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'specialImg',
                title: '专场图片',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'productCount',
                title: '专场拍品数量',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'startTime',
                title: '专场开始时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'endTime',
                title: '专场结束时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'instime',
                title: '新增时间',
                align: 'center',
                valign: 'middle',
                width:200
            }]
    });

</script>
