<div class="wrapper" id="page-wrapper">

    <div id="table_toolbar">
        <div class="pull-left">
            <strong>专场列表</strong>
        </div>
    </div>
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>

</div>

<script>
$(function(){
    table = $('#table-pagination').bootstrapTable({
        method: 'get',
        url: '/admin/<?=$this->layout()->controllerName;?>/list',
        cache: false,
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: false,
        showColumns: false,
        showRefresh: false,
        toolbar:"#table_toolbar",
        minimumCountColumns: 2,
        sidePagination: 'server',
        columns: [
            {
                field: 'specialID',
                title: '专场ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialName',
                title: '专场名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'categoryName',
                title: '专场分类',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeName',
                title: '店铺名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'specialImg',
                title: '专场图片',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter : function(value, row, index){
                    str = '<img width="100px" src="' + value + '" />';
                    return str;
                }

            },{
                field: 'productCountLimit',
                title: '专场拍品数量',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'startTime',
                title: '专场开始时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'endTime',
                title: '专场结束时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'verifyStatus',
                title: '审核状态',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, row, index){
                    var str = '';
                    if(!value){
                        str = '未提交审核';
                    }else if(value == 1){
                        var links = [
                            '<a title="审核通过" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="specialID='+ row.specialID +'&verifyStatus=2&auctionStatus=1"><i class="glyphicon glyphicon-ok"></i></a>',
                            '<a title="审核不通过" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核不通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="specialID='+ row.specialID +'&verifyStatus=3"><i class="glyphicon glyphicon-remove"></i></a>'
                        ];
                        str = links.join(' ');
                    }else if(value == 2){
                        str = '审核通过';
                    }else if(value == 3){
                        str = '审核未通过';
                    }
                    return str;
                }
            }]
    });
});

</script>
