<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
        <button type="submit" class="btn btn-primary" data-toggle="modal" data-target="#add_modal"><i class="fa fa-pencil"></i>新增</button>
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<!-- Add Modal Start -->
<div class="row">
    <div class="modal form-modal fade" id="add_modal" tabindex="-1" role="dialog" aria-labelledby="add_modal_label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="add_modal_label">添加管理人员</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" role="form" method="post" action="/admin/<?=$this->layout()->controllerName;?>/add">
                        <table class="table table-bordered">
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label for="add_desc" class="col-sm-2 col-md-2 control-label">登录名</label>
                                        <div class="col-sm-10 col-md-10">
                                            <input type="text" class="form-control" name="username">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label class="col-sm-2 col-md-2 control-label">密码</label>
                                        <div class="col-sm-10 col-md-10">
                                            <input type="text" class="form-control" name="passwd">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label class="col-sm-2 col-md-2 control-label">确认密码</label>
                                        <div class="col-sm-10 col-md-10">
                                            <input type="text" class="form-control" name="confirmPasswd">
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </table>
                    </form>
                </div>
                <div class="modal-footer">
                    <!-- btn-block可以在非PC上获取更好的体验 -->
                    <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                    <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Add Modal End -->

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/admin/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'username',
                title: '登录名',
                align: 'center',
                valign: 'middle',
                width:200

            }, {
                field: 'instime',
                title: '新增时间',
                align: 'center',
                valign: 'middle'
            }, {
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter,
                width:200

            }]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="编辑" href="javascript:;"  class="col-md-4" rid="' + row.ProductID + '" data-toggle="modal" data-target="#edit_modal"><i class="glyphicon glyphicon-edit"></i></a>',
            '<a href="javascript:;" class="remove ml10 col-md-4 confirm-btn" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认删除该条记录吗？" url="/admin/<?=$this->layout()->controllerName;?>/del" method="post" params="ApkVersion='+ row.ApkVersion +'&MD5='+ row.MD5 +'" title=\"Apk hash删除\">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }


</script>
