
<div class="wrapper" id="page-wrapper">

    <div id="table_toolbar">


    </div>
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>


    <!-- Edit Modal Start -->
    <div class="row">
        <div class="modal form-modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="edit_modal_label">余额明细</h4>
                    </div>
                    <div class="modal-body" id="recharge-logs" style="height:400px;overflow: scroll;" >

                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Edit Modal End -->
</div>

<script type="text/javascript">
    $(function(){

        $('#edit_modal').on("show.bs.modal",function(e){
            var btn = $(e.relatedTarget);
            var memberID = btn.attr('rid');
            $('#recharge-logs').load('/admin/withdraw/recharge-log?memberID=' + memberID);
        });

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?=$this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: true,
            showColumns: true,
            showRefresh: true,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'logID',
                title: '记录ID',
                align: 'center',
                valign: 'middle'
                /*sortable: true*/
            }, {
                field: 'nickName',
                title: '申请用户账号',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardOwnerName',
                title: '绑定银行卡持卡人姓名',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardNum',
                title: '绑定银行卡卡号',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardBank',
                title: '开户行',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardMobile',
                title: '绑定银行卡手机号',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'money',
                title: '提现金额',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'rechargeMoney',
                title: '用户余额',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'instime',
                title: '申请时间',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'verifyStatus',
                title: '审核状态',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    var str = '';
                    if(value == 1){
                        var links = [
                            '<a title="审核通过" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/verify" method="post" params="logID='+ row.logID +'&verifyStatus=2"><i class="glyphicon glyphicon-ok"></i></a>',
                            '<a title="审核不通过" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核不通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/verify" method="post" params="logID='+ row.logID +'&verifyStatus=3"><i class="glyphicon glyphicon-remove"></i></a>'
                        ];
                        str = links.join(' ');
                    }else if(value == 2){
                        str = '审核通过';
                    }else if(value == 3){
                        str = '审核未通过';
                    }
                    return str;
                }

            },{
                field: 'memberID',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    return [
                        '<a title="查看余额明细" href="javascript:void(0)"  class="col-md-4" rid="' + value + '"  data-toggle="modal" data-target="#edit_modal"><i class="glyphicon glyphicon-flag"></i></a>'
                    ].join('');
                }
            }]
        });
    });

</script>