
<div class="wrapper" id="page-wrapper">

    <div id="table_toolbar">


    </div>
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>
</div>

<script type="text/javascript">
    $(function(){

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?=$this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: false,
            showColumns: false,
            showRefresh: false,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'logID',
                title: '记录ID',
                align: 'center',
                valign: 'middle'
                /*sortable: true*/
            }, {
                field: 'storeName',
                title: '申请店铺名',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardOwnerName',
                title: '绑定银行卡持卡人姓名',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardNum',
                title: '绑定银行卡卡号',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'cardMobile',
                title: '绑定银行卡手机号',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'instime',
                title: '申请时间',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'verifyStatus',
                title: '审核状态',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    var str = '';
                    if(value == 1){
                        var links = [
                            '<a title="审核通过" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/verify" method="post" params="logID='+ row.logID +'&verifyStatus=2"><i class="glyphicon glyphicon-ok"></i></a>',
                            '<a title="审核不通过" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认审核不通过吗？" url="/admin/<?=$this->layout()->controllerName;?>/verify" method="post" params="logID='+ row.logID +'&verifyStatus=3"><i class="glyphicon glyphicon-remove"></i></a>'
                        ];
                        str = links.join(' ');
                    }else if(value == 2){
                        str = '审核通过';
                    }else if(value == 3){
                        str = '审核未通过';
                    }
                    return str;
                }

            }]
        });
    });

</script>