
<form class="form-horizontal" role="form" method="post" action="/admin/withdraw/index">
    <table class="table table-bordered">
        <tr>
            <td>
                <div class="form-group">
                    <div class="col-sm-10 col-md-10">
                        <input type="password" name="password" id="inputPassword3" placeholder="请输入您的密码">
                        <button type="submit" class="btn btn-primary">确认</button>
                    </div>
                </div>
            </td>
        </tr>
    </table>
</form>