<div class="botNav">
    <div class="center">
        <div class="botnav-item botnav-item1">
            <h4>
                <span>诚实信用</span>
                <em>对拍品的如实描述，卖家的承诺服务</em>
            </h4>
            <dl>
                <dt>竞买者保障</dt>
                <dd><a href="#">·关于拍品</a></dd>
                <dd><a href="#">·关于拍卖</a></dd>
                <dd><a href="#">·关于售后</a></dd>
                <dd><a href="#">·其它保障</a></dd>

            </dl>
        </div>
        <div class="erweima fl">
            <p>开拍网公众号</p>
            <span>“开拍网”</span>
        </div>
        <div class="botnav-item botnav-item2">
            <h4>
                <span>双向交流</span>
                <em>专业服务，阳光竞拍</em>
            </h4>
            <dl>
                <dt>个人 | 商家入驻</dt>
                <dd><a href="#">·入驻规则</a></dd>
                <dd><a href="#">·保证金问题</a></dd>
                <dd><a href="#">·诚信问题</a></dd>
                <dd><a href="#">·其它</a></dd>

            </dl>
        </div>
        <div class="botnav-item botnav-item3">
            <h4>
                <span>售后无忧</span>
                <em>明白承诺，周到服务</em>
            </h4>
            <dl>
                <dt>关于我们</dt>
                <dd><a href="#">·免责声明</a></dd>
                <dd><a href="#">·版权声明</a></dd>
                <dd><a href="/index/contact">·联系我们</a></dd>
                <dd><a href="#">·关于开拍</a></dd>

            </dl>
        </div>
    </div>
</div>
<div class="footer">

    <div class="footernav center">
        <a href="/">首页</a><em>|</em>
        <?php
        $count = 0;
        foreach($_categories as $v){
            $count++;
            ?>
            <a href="/product/index?productCategoryID=<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName']; ?></a>
            <em>|</em>
        <?php
        }
        ?>
        <a href="/index/contact">联系我们</a>

        <p>
            公司地址: 浙江省杭州市下城区朝晖路179号嘉汇大厦2号楼5层 电话: 0571-85819321 18867538398 邮箱: kaipai123@sina.com<br>
            版权所有 © 杭州易开拍网络科技有限公司 浙ICP备13004819号-1 网址: www.kaipai123.com
        </p>
    </div>
</div>

<!-- 在线客服 开始 -->
<?php /* ?>
<div id="rightArrow" style="right: -5px; background-position: -50px 0px;display:none;"><a href="javascript:;" title="在线客服"></a></div>
<div id="floatDivBoxs" style="right:-175px;">
    <div class="floatDtt">在线客服</div>
    <div class="floatShadow">
        <ul class="floatDqq">
            <li style="padding-left:0px;"><a target="_blank" href="tencent://message/?uin=1234567890&Site=www.lanrentuku.com&Menu=yes"><img src="/dist/img/common/qq.png" align="absmiddle">&nbsp;&nbsp;在线客服1号</a></li>
            <li style="padding-left:0px;"><a target="_blank" href="tencent://message/?uin=1234567890&Site=www.lanrentuku.com&Menu=yes"><img src="/dist/img/common/qq.png" align="absmiddle">&nbsp;&nbsp;在线客服2号</a></li>
            <li style="padding-left:0px;"><a target="_blank" href="tencent://message/?uin=1234567890&Site=www.lanrentuku.com&Menu=yes"><img src="/dist/img/common/qq.png" align="absmiddle">&nbsp;&nbsp;在线客服3号</a></li>
        </ul>
        <!--<div class="floatDtxt">热线电话</div>
        <div class="floatDtel"><img src="/dist/img/common/online_phone.jpg" width="155" height="45" alt=""></div>
        <div style="text-align:center;padding:10PX 0 5px 0;background:#EBEBEB;"><img src="/dist/img/common/wap_ico.jpg"><br>微信公众账号</div>-->
    </div>
</div>
<?php */ ?>
<?php
echo $this->render('/front/common/post-error');
echo $this->render('/front/common/post-illegal');
?>
<div id="public-content" class="hide">

</div>
<script>
    $(function(){
        $(document).on('click', '.pay-type-list li', function(){
            $(this).addClass('selected-pay-type').siblings().removeClass('selected-pay-type');
        });

        $('.post-error-btn').on('click', function(){
            layer.open({
                skin : 'loginBox',
                title : '站内报错',
                type : 1,
                content : $('#post-error-div').html()
            });
        });
        $(document).on('click', '.post-error-div-btn:visible', function(){
            var data = {
                content : $('input[name=errorContent]:visible').val()
            };
            $.ajax({
                url : '/index/post-error',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    layer.alert(res.msg, function(){
                        layer.closeAll();
                    });
                }
            });
        });

        $('.post-illegal-btn').on('click', function(){
            var data = {
                coreID : $(this).attr('coreID'),
                type : $(this).attr('type')
            };
            $.ajax({
                url : '/index/post-illegal',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    layer.alert(res.msg, function(){
                        layer.closeAll();
                    });
                }
            });
        });

        $(document).on('click', '#qq-login-btn', function(){
            QC.Login.showPopup({
                appID : '101328212',
                redirectURI : 'http://<?php echo $_SERVER['HTTP_HOST'] ?>/notify/qq-login'
            })
        });

    });
</script>
