<div class="botNav">
    <div class="center">
        <div class="botnav-item botnav-item1">
            <h4>
                <span>诚实信用</span>
                <em>对拍品的如实描述，卖家的承诺服务</em>
            </h4>
            <dl>
                <dt>竞买者保障</dt>
                <dd><a href="#">·关于拍品</a></dd>
                <dd><a href="#">·关于拍卖</a></dd>
                <dd><a href="#">·关于售后</a></dd>
                <dd><a href="#">·其它保障</a></dd>

            </dl>
        </div>
        <div class="erweima fl">
            <p>开拍网公众号</p>
            <span>“开拍网”</span>
        </div>
        <div class="botnav-item botnav-item2">
            <h4>
                <span>双向交流</span>
                <em>专业服务，阳光竞拍</em>
            </h4>
            <dl>
                <dt>个人 | 商家入驻</dt>
                <dd><a href="#">·入驻规则</a></dd>
                <dd><a href="#">·保证金问题</a></dd>
                <dd><a href="#">·诚信问题</a></dd>
                <dd><a href="#">·其它</a></dd>

            </dl>
        </div>
        <div class="botnav-item botnav-item3">
            <h4>
                <span>售后无忧</span>
                <em>明白承诺，周到服务</em>
            </h4>
            <dl>
                <dt>关于我们</dt>
                <dd><a href="#">·免责声明</a></dd>
                <dd><a href="#">·版权声明</a></dd>
                <dd><a href="/index/contact">·联系我们</a></dd>
                <dd><a href="#">·关于开拍</a></dd>

            </dl>
        </div>
    </div>
</div>
<div class="footer">

    <div class="footernav center">
        <a href="/">首页</a><em>|</em>
        <?php
        $count = 0;
        foreach($_categories as $v){
            $count++;
            ?>
            <a href="/product/index?productCategoryID=<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName']; ?></a>
            <em>|</em>
        <?php
        }
        ?>
        <a href="/index/contact">联系我们</a>

        <p>
            公司地址: 浙江省杭州市下城区朝晖路179号嘉汇大厦2号楼5层 电话: 0571-85819321 18867538398 邮箱: kaipai123@sina.com<br>
            版权所有 © 杭州易开拍网络科技有限公司 浙ICP备13004819号-1 网址: www.kaipai123.com
        </p>
    </div>
</div>

<script>
    $(function(){
        $(document).on('click', '.pay-type-list li', function(){
            $(this).addClass('selected-pay-type').siblings().removeClass('selected-pay-type');
        });
        $(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.customizationID = $('.pay-price:visible').attr('pay-customization-id');
            data.productID = $('.pay-price:visible').attr('pay-product-id');
            data.customizationCount = $('.pay-price:visible').attr('customization-count');
            data.payType = $('.selected-pay-type:visible').attr('pay-type');
            console.log(data);
            $.ajax({
                url : '/order/generate',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        location.href = response.url;
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }

            });
        });
    });
</script>
