<?php echo $this->doctype(); ?>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title ng-bind="globalTit"></title>
    <meta name="keywords" content="开拍网拍卖会,在线竞拍,在线拍卖,网上拍卖,古玩在线拍卖,艺术品拍卖,中国开拍网在线竞拍"/>
    <meta name="description" content="中国开拍网拍卖会是中国最大的专业艺术品在线竞拍网站,为用户提供一个在线艺术品拍卖、古玩拍卖、古董拍卖、钱币拍卖、玉器拍卖、紫砂拍卖、书画拍卖、瓷器拍卖等藏品的拍卖网站,用户可以在线竞拍最新藏品,最新艺术品。"/>
    <?php
        echo $this->headLink()
            ->appendStylesheet($this->basePath() . '/plugins/layer/skin/layer.css')
            ->appendStylesheet($this->basePath() . '/plugins/jquery-ui/jquery.ui.datepicker.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/common/common.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/main/index.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/main/good.css');

        echo $this->headScript()
            ->appendFile($this->basePath() . '/plugins/jquery/jquery.js')
            ->appendFile($this->basePath() . '/plugins/jquery.lazyload/jquery.lazyload.min.js')
            ->appendFile($this->basePath() . '/dist/js/common.js')
            ->appendFile($this->basePath() . '/plugins/jquery-ui/jquery-ui.min.js')
            ->appendFile($this->basePath() . '/plugins/superSlide/jquery.SuperSlide.2.1.1.js')
            ->appendFile($this->basePath() . '/dist/js/main.js');
    ?>
</head>
<body>

    <?php echo $this->render('/layout/top');?>
    <div class="menuer">
        <div class="center">
            <div class="mlist">
                <a href="/">首页</a>
                <a ui-sref="goodList">所有自由拍</a>
                |
                <?php
                    $count = 0;
                    foreach($_categories as $v){
                        $count++;
                ?>
                        <a ui-sref="goodList" href="/product/index?productCategoryID=<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName']; ?></a>
                        <?php
                            if(count($_categories) != $count){
                        ?>
                                ·
                        <?php
                            }
                        ?>

                <?php
                    }
                ?>
            </div>
        </div>
    </div>

    <?php echo $this->content; ?>
    <?php echo $this->render('/layout/bottom'); ?>


    <script type="text/javascript">
        if($('.date-pop').length){
            $(".date-pop").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                dateFormat: 'yy.mm.dd',
                onSelect: function (dateText, inst) {
                    window.top.location.href = '/special/index?date=' + dateText;
                }
            });
        }

    </script>

</body>