<?php echo $this->doctype(); ?>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title ng-bind="globalTit"></title>
    <meta name="keywords" content="开拍网拍卖会,在线竞拍,在线拍卖,网上拍卖,古玩在线拍卖,艺术品拍卖,中国开拍网在线竞拍"/>
    <meta name="description" content="中国开拍网拍卖会是中国最大的专业艺术品在线竞拍网站,为用户提供一个在线艺术品拍卖、古玩拍卖、古董拍卖、钱币拍卖、玉器拍卖、紫砂拍卖、书画拍卖、瓷器拍卖等藏品的拍卖网站,用户可以在线竞拍最新藏品,最新艺术品。"/>
    <?php
        echo $this->headLink()
            ->appendStylesheet($this->basePath() . '/plugins/layer/skin/layer.css')
            ->appendStylesheet($this->basePath() . '/plugins/jquery-ui/jquery.ui.datepicker.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/common/common.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/main/index.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/main/good.css');

        echo $this->headScript()
            ->appendFile($this->basePath() . '/plugins/jquery/jquery.js')
            ->appendFile($this->basePath() . '/plugins/jquery.lazyload/jquery.lazyload.min.js')
            ->appendFile($this->basePath() . '/dist/js/common.js')
            ->appendFile($this->basePath() . '/plugins/jquery-ui/jquery-ui.min.js')
            ->appendFile($this->basePath() . '/plugins/superSlide/jquery.SuperSlide.2.1.1.js')
            ->appendFile($this->basePath() . '/dist/js/main.js');
    ?>
</head>
<body>

    <div class="toper">
        <div class="center">
            <div class="mlinknav">
                <a href="/">开拍网首页</a>
            </div>
            <div class="uinfonav" style="display: none;">
                <div id="logorout">
                    <span>您好!</span>

                    <div class="user_name">
                        <a class="nameA" ui-sref="indexPersonal">用户名</a>

                        <div id="toperNav">
                            <a ui-sref="listOrderPersonal">我的订单</a>
                            <a ui-sref="collectionAuctionlistPersonal">我的收藏</a>
                            <a ui-sref="mybalanceCustomerPersonal">我的余额</a>
                            <a ui-sref="feedbackListPersonal">意见反馈</a>
                            <a href="javascript:" ng-click="loginOut()">安全退出</a>
                        </div>
                    </div>

                </div>

                <a class="footprint" href="">收藏本站</a>

            </div>

            <div class="uinfonav">
                    <span id="logorout" style="font-size:14px">
                        <a class="register" rel="nofollow" ui-sref="userRegister">免费注册</a>
                        <a target="_self" rel="nofollow" ui-sref="userLogin">用户登录</a>
                        <a target="_self" rel="nofollow" ui-sref="userLogin">关注拍品</a>
                        <a target="_self" rel="nofollow" ui-sref="userLogin">我的拍场</a>
                        <a target="_self" rel="nofollow" ui-sref="userLogin">联系客服</a>
                </span>
                |
                <a class="footprint" href="">收藏本站</a>
            </div>

        </div>
    </div>
    <div class="header">
        <div class="center">
            <a href="#" class="logonav">
                <img src="/dist/img/common/logo.png"/>
            </a>

            <div class="searchnav">
                <form style=" height:35px;" action="/paimai/search/all/">
                    <input type="text" class="ipt" name="t" id="txtKw" value="输入关键词/名称"/>
                    <a href="javascript:;" class="btn paimaisearchbtn">搜索</a>
                </form>
                <div class="hotlink">
                    <a href="#">和田玉</a>
                    <a href="#">和田玉</a>
                    <a href="#">和田玉</a>
                    <a href="#">和田玉</a>
                    <a href="#">和田玉</a>
                </div>
            </div>
        </div>
    </div>
    <div class="menuer">
        <div class="center">
            <div class="mlist">
                <a href="/">首页</a>
                <a ui-sref="goodList">所有自由拍</a>
                |
                <a ui-sref="goodList">国画</a>
                ·
                <a ui-sref="goodList">书法</a>
                ·
                <a ui-sref="goodList">金石篆刻</a>
                ·
                <a ui-sref="goodList">古玩杂项</a>
                ·
                <a ui-sref="goodList">古典陶瓷</a>
                ·
                <a ui-sref="goodList">宗教文化</a>
                ·
                <a ui-sref="goodList">西画雕塑</a>
                ·
                <a ui-sref="goodList">奢侈品</a>
                ·
                <a ui-sref="goodList">宝石翡翠</a>
            </div>
        </div>
    </div>

    <?php echo $this->content; ?>


    <div class="botNav">
        <div class="center">
            <div class="botnav-item botnav-item1">
                <h4>
                    <span>诚实信用</span>
                    <em>对拍品的如实描述，卖家的承诺服务</em>
                </h4>
                <dl>
                    <dt>竞买者保障</dt>
                    <dd><a href="#">·关于拍品</a></dd>
                    <dd><a href="#">·关于拍卖</a></dd>
                    <dd><a href="#">·关于售后</a></dd>
                    <dd><a href="#">·其它保障</a></dd>

                </dl>
            </div>
            <div class="erweima fl">
                <p>开拍网公众号</p>
                <span>“开拍网”</span>
            </div>
            <div class="botnav-item botnav-item2">
                <h4>
                    <span>双向交流</span>
                    <em>专业服务，阳光竞拍</em>
                </h4>
                <dl>
                    <dt>个人 | 商家入驻</dt>
                    <dd><a href="#">·入驻规则</a></dd>
                    <dd><a href="#">·保证金问题</a></dd>
                    <dd><a href="#">·诚信问题</a></dd>
                    <dd><a href="#">·其它</a></dd>

                </dl>
            </div>
            <div class="botnav-item botnav-item3">
                <h4>
                    <span>售后无忧</span>
                    <em>明白承诺，周到服务</em>
                </h4>
                <dl>
                    <dt>关于我们</dt>
                    <dd><a href="#">·免责声明</a></dd>
                    <dd><a href="#">·版权声明</a></dd>
                    <dd><a href="#">·联系我们</a></dd>
                    <dd><a href="#">·关于开拍</a></dd>

                </dl>
            </div>
        </div>
    </div>
    <div class="footer">

        <div class="footernav center">
            <a href="#">首页</a><em>|</em>
            <a href="#">国画</a><em>|</em>
            <a href="#">书法</a><em>|</em>
            <a href="#">金石篆刻</a><em>|</em>
            <a href="#">古玩杂项</a><em>|</em>
            <a href="#">古典陶瓷</a><em>|</em>
            <a href="#">西画雕塑</a><em>|</em>
            <a href="#">宗教文化</a><em>|</em>
            <a href="#">奢侈品</a><em>|</em>
            <a href="#">宝石翡翠</a><em>|</em>
            <a href="#">联系我们</a>

            <p>
                公司地址: 浙江省杭州市下城区朝晖路179号嘉汇大厦2号楼5层 电话: 0571-85819321 18867538398 邮箱: kaipai123@sina.com<br>
                版权所有 © 杭州易开拍网络科技有限公司 浙ICP备13004819号-1 网址: www.kaipai123.com
            </p>
        </div>
    </div>
    <script type="text/javascript">
        $(".date-pop").datepicker({
            showOtherMonths: true,
            selectOtherMonths: true,
            dateFormat: 'yy.mm.dd',
            onSelect: function (dateText, inst) {
                console.log(dateText);
            }
        });
    </script>

</body>