<?php echo $this->doctype(); ?>
<head>
    <meta property="qc:admins" content="37403453200111236375" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title ng-bind="globalTit">开拍网</title>
    <meta name="keywords" content="开拍网拍卖会,在线竞拍,在线拍卖,网上拍卖,古玩在线拍卖,艺术品拍卖,中国开拍网在线竞拍"/>
    <meta name="description" content="中国开拍网拍卖会是中国最大的专业艺术品在线竞拍网站,为用户提供一个在线艺术品拍卖、古玩拍卖、古董拍卖、钱币拍卖、玉器拍卖、紫砂拍卖、书画拍卖、瓷器拍卖等藏品的拍卖网站,用户可以在线竞拍最新藏品,最新艺术品。"/>
    <?php
        echo $this->headLink()
            ->appendStylesheet($this->basePath() . '/plugins/layer/skin/layer.css')
            ->appendStylesheet($this->basePath() . '/plugins/jquery-ui/jquery.ui.datepicker.css')
            ->appendStylesheet($this->basePath() . '/dist/styles/common/common.css?v=1')
            ->appendStylesheet($this->basePath() . '/yaoqin/style/css1.css');

        if($_isIE){
            $this->headScript()->appendFile($this->basePath() . '/plugins/jquery/jquery19.js');
        }else{
            $this->headScript()->appendFile($this->basePath() . '/plugins/jquery/jquery.js');
        }

        $this->headScript()
            ->appendFile($this->basePath() . '/plugins/jquery.lazyload/jquery.lazyload.min.js')
            ->appendFile($this->basePath() . '/dist/js/common.js')
            ->appendFile($this->basePath() . '/plugins/jquery-ui/jquery-ui.min.js')
            ->appendFile($this->basePath() . '/plugins/superSlide/jquery.SuperSlide.2.1.1.js')
            ->appendFile($this->basePath() . '/dist/js/main.js')
            ->appendFile('/plugins/layer/layer.js');

        echo $this->headScript();

    ?>
    <?php
        if(($controllerName == 'product' && $actionName == 'detail') || ($controllerName == 'customization' && $actionName == 'detail') || $controllerName == 'zone'){
    ?>
            <script type="text/javascript" src="http://qzonestyle.gtimg.cn/qzone/openapi/qc_loader.js" data-appid="101328212" data-redirecturi="http://<?php echo $_SERVER['HTTP_HOST'] ?>/notify/qq-login" charset="utf-8"></script>
    <?php
        }
    ?>

</head>
<body>

    <?php echo $this->render('/layout/top');?>
    <div class="menuer">
        <div class="center">
            <div class="mlist">
                <a href="/">首页</a>
                <a ui-sref="goodList" href="/product/index">所有自由拍</a>
                |
                <?php
                    $count = 0;
                    foreach($_categories as $v){
                        $count++;
                ?>
                        <a ui-sref="goodList" href="/product/index?productCategoryID=<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName']; ?></a>
                        <?php
                            if(count($_categories) != $count){
                        ?>
                                ·
                        <?php
                            }
                        ?>

                <?php
                    }
                ?>
            </div>
        </div>
    </div>

    <?php echo $this->content; ?>
    <?php echo $this->render('/layout/bottom'); ?>
    <?php echo $this->render('/front/common/login'); ?>

    <script type="text/javascript">
        if($('.date-pop').length){
            $(".date-pop").datepicker({
                showOtherMonths: true,
                selectOtherMonths: true,
                dateFormat: 'yy-mm-dd',
                onSelect: function (dateText, inst) {
                    window.top.location.href = '/special/index?date=' + dateText;
                },
                defaultDate:'<?php echo $date; ?>'
            });


        }

        function addFavorite2() {
            try {
                window.external.addFavorite(url, title);
            }
            catch (e) {
                try {
                    window.sidebar.addPanel(title, url, "");
                }
                catch (e) {
                    alert("抱歉，您所使用的浏览器无法完成此操作。\n\n加入收藏失败，请进入新网站后使用Ctrl+D进行添加");
                }
            }
        }

        $('#top-search-btn').on('click', function(){
            var data = {};
            data.search = $('.top-search-item').val();
            location.href = '/product/index?search=' + data.search;
        });

        $('#txtKw').on('keydown', function(e){
            var ev = document.all ? window.event : e;
            if(ev.keyCode==13) {
                $('#top-search-btn').click();
            }
        });

    </script>
    <?php echo $this->inlineScript()->appendFile('/dist/js/account.js'); ?>
</body>