<?php echo $this->doctype(); ?>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title ng-bind="globalTit"></title>
    <meta name="keywords" content="开拍网拍卖会,在线竞拍,在线拍卖,网上拍卖,古玩在线拍卖,艺术品拍卖,中国开拍网在线竞拍"/>
    <meta name="description" content="中国开拍网拍卖会是中国最大的专业艺术品在线竞拍网站,为用户提供一个在线艺术品拍卖、古玩拍卖、古董拍卖、钱币拍卖、玉器拍卖、紫砂拍卖、书画拍卖、瓷器拍卖等藏品的拍卖网站,用户可以在线竞拍最新藏品,最新艺术品。"/>
    <?php
    $this->headLink()
        ->appendStylesheet('/plugins/layer/skin/layer.css')
        ->appendStylesheet('/dist/styles/common/common.css')
        ->appendStylesheet('/dist/styles/main/personal.css');
    $this->headScript()
        ->appendFile('/plugins/jquery/jquery.js')
        ->appendFile('/plugins/jquery.lazyload/jquery.lazyload.min.js')
        ->appendFile('/dist/js/common.js')
        ->appendFile('/plugins/jquery-ui/jquery-ui.min.js')
        ->appendFile('/plugins/layer/layer.js');
    if(in_array($actionName, array('add-product', 'store-setting', 'add-special'))){
        $this->headScript()
            ->appendFile('/diyUpload/js/webuploader.html5only.min.js')
            ->appendFile('/diyUpload/js/diyUpload.js');
    }
    if($actionName == 'add-product'){
        $this->headLink()
            ->appendStylesheet('/diyUpload/css/webuploader.css')
            ->appendStylesheet('/diyUpload/css/diyUpload.css')
            ->appendStylesheet('/style/default.css');
    }
    echo $this->headLink();
    echo $this->headScript();
    ?>
    <?php
    if(in_array($actionName, array('add-product', 'store-setting', 'add-special'))) {
        echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.config.js');
        echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.all.js');
        echo $this->inlineScript()->setFile('/admin/ueditor/lang/zh-cn/zh-cn.js');
    }
    ?>
</head>
<body>

<?php echo $this->render('/layout/top') ?>

<div class="menuer">
    <div class="center">
        <div class="mlist">
            <a href="/">首页</a>
            <a ui-sref="goodList" href="/member/auction">我的开拍</a>
            |
            <a ui-sref="goodList" href="/member/notification">站内提醒</a>

            <a ui-sref="goodList" href="/member/settings">帐户设置</a>

            <a ui-sref="goodList" href="/zone/index?zoneID=<?php echo $_memberInfo['memberID'] ?>">个人空间</a>

        </div>
    </div>
</div>

<?php echo $this->content; ?>
<?php echo $this->render('/layout/bottom'); ?>


</body>