<?php if(!empty($_isLowID)){
?>
    <div class="updataBrowser" id="updataBrowser">
        <div class="center">
            当前浏览器版本过底，为了更好体验请升级浏览器，推荐：<a target="_blank" href="http://firefox.com.cn/download/">火狐浏览器</a>、<a href="http://www.google.cn/chrome" target="_blank">谷歌浏览器</a>
        </div>
    </div>
<?php
} ?>

<div class="toper">
    <div class="center">
        <div class="mlinknav">
            <a href="/">开拍网首页</a>
        </div>
        <?php
        /*if(!empty($_memberInfo)){
            ?>
            <div class="uinfonav">
                <div id="logorout">
                    <span>您好!</span>

                    <div class="user_name">
                        <a class="nameA" ui-sref="indexPersonal"><?php  echo $_memberInfo['nickName'] ?></a>

                        <div id="toperNav">
                            <a ui-sref="listOrderPersonal">我的订单</a>
                            <a ui-sref="collectionAuctionlistPersonal">我的收藏</a>
                            <a ui-sref="mybalanceCustomerPersonal">我的余额</a>
                            <a ui-sref="feedbackListPersonal">意见反馈</a>
                            <a href="javascript:" ng-click="loginOut()">安全退出</a>
                        </div>
                    </div>

                </div>

                <a class="footprint" href="">收藏本站</a>

            </div>
        <?php }else{*/ ?>
            <div class="uinfonav">
                        <span id="logorout" style="font-size:14px">
                            <?php
                            if(!empty($_memberInfo)) {
                            ?>
                                <span>您好!</span>

                                <a class="nameA" ui-sref="indexPersonal" href="/member/order"><?php  echo $_memberInfo['nickName'] ?></a>
                                <a href="/member/log-out">退出</a>
                                <a href="/member/notification">站内提醒(<em style="color: #ed8000;"><?php echo $_memberInfo['notReadCount'] ?  $_memberInfo['notReadCount'] : 0?></em>)</a>
                            <?php
                            }else{
                            ?>
                                <a class="register" rel="nofollow" ui-sref="userRegister" href="/login/reg">免费注册</a>
                                <a target="_self" rel="nofollow" ui-sref="userLogin" href="/login/do-login">用户登录</a>
                            <?php
                            }
                            ?>

                            <a target="_self" rel="nofollow" ui-sref="userLogin" href="/member/interest-product">关注拍品</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin" href="/member/auction">我的拍场</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin" qq="<?php echo $_siteSettings['qq'] ?>" href="javascript:;" class="contact-custom-service tencent-qq">联系客服</a>
                    </span>
                |
                <a class="footprint" href="javascript:;" onclick="addFavorite2();">收藏本站</a>
            </div>
        <?php // } ?>
    </div>
</div>
<div class="header">
    <div class="center">
        <a href="/" class="logonav">
            <img src="<?php echo $_siteSettings['logo'] ?>"/>
        </a>
        <div class="searchnav">
            <input type="text" class="ipt top-search-item" name="t" id="txtKw" placeholder="请输入拍品名称"/>
            <a href="javascript:;" class="btn paimaisearchbtn" id="top-search-btn">搜索</a>
        </div>
    </div>
</div>
<script>
    function iframeHeight(id) {

        var ifm= document.getElementById(id);

        var subWeb = document.frames ? document.frames[id].document :

            ifm.contentDocument;

        if(ifm != null && subWeb != null) {

            ifm.height = subWeb.body.scrollHeight;

        }

    }
</script>