<div class="toper">
    <div class="center">
        <div class="mlinknav">
            <a href="/">开拍网首页</a>
        </div>
        <?php
        if(!empty($_memberInfo)){
            ?>
            <div class="uinfonav">
                <div id="logorout">
                    <span>您好!</span>

                    <div class="user_name">
                        <a class="nameA" ui-sref="indexPersonal"><?php  echo $_memberInfo['nickName'] ?></a>

                        <div id="toperNav">
                            <a ui-sref="listOrderPersonal">我的订单</a>
                            <a ui-sref="collectionAuctionlistPersonal">我的收藏</a>
                            <a ui-sref="mybalanceCustomerPersonal">我的余额</a>
                            <a ui-sref="feedbackListPersonal">意见反馈</a>
                            <a href="javascript:" ng-click="loginOut()">安全退出</a>
                        </div>
                    </div>

                </div>

                <a class="footprint" href="">收藏本站</a>

            </div>
        <?php }else{ ?>
            <div class="uinfonav">
                        <span id="logorout" style="font-size:14px">
                            <a class="register" rel="nofollow" ui-sref="userRegister" href="/login/reg">免费注册</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin" href="/login/do-login">用户登录</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin">关注拍品</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin">我的拍场</a>
                            <a target="_self" rel="nofollow" ui-sref="userLogin">联系客服</a>
                    </span>
                |
                <a class="footprint" href="">收藏本站</a>
            </div>
        <?php } ?>
    </div>
</div>
<div class="header">
    <div class="center">
        <a href="#" class="logonav">
            <img src="/dist/img/common/logo.png"/>
        </a>

        <div class="searchnav">
            <form style=" height:35px;" action="/paimai/search/all/">
                <input type="text" class="ipt" name="t" id="txtKw" value="输入关键词/名称"/>
                <a href="javascript:;" class="btn paimaisearchbtn">搜索</a>
            </form>
        </div>
    </div>
</div>