<div id="loginPopBox" class="hide">
    <div class="loginPop fr">

        <form method="post">
            <span style="color: red;"></span>

            <div class="inputBox"><i class="phone"></i>
                <input name="mobile" id="loginMobile" placeholder="手机号码" type="text" value=""/>
            </div>

            <div class="inputBox"><i class="key"></i>
                <input name="password" placeholder="输入密码" type="password"/>
            </div>

            <p>
                <label>
                    <input data-val="true" name="rememberMe" type="checkbox" value="true"/>
                    下次自动登录
                </label>
                <a ui-sref="userForgetpwd" href="/login/reset-pwd">忘记密码？</a>
            </p>
            <input id="do-login" type="button" class="submit" value="登录">
        </form>
        <h5>
            没有账号？
            <a ui-sref="userRegister" href="/login/reg">免费注册>></a>
        </h5>

        <div class="xtj_hzzh_pop">
            <p>使用合作网站账号登录：</p>

            <div>
                <a class="i_01" href="javascript:;" id="qq-login-btn">QQ</a>
                <a class="i_03" href="https://open.weixin.qq.com/connect/qrconnect?appid=wx8599ed3526a343ea&redirect_uri=<?php echo urlencode('http://www.kaipai123.com/login/wx-login'); ?>&response_type=code&scope=snsapi_login&state=<?php echo md5(123456); ?>#wechat_redirect">微信</a>
                <!--<a class="i_04" style="border-right:none;" href="javascript:;">新浪微博</a>-->

            </div>
        </div>
    </div>
</div>