<div id="paging">
    <a href="<?php echo $url?>pageNum=<?php echo $pages->first; ?>">首页</a>
    <a href="<?php echo $url?>pageNum=<?php echo ($pages->current - 1) <= $pages->first ? $pages->first : ($pages->current - 1) ?>" style="width:60px">上一页</a>
    <?php
        foreach($pages->pagesInRange as $v){
    ?>
            <a href="<?php echo $url ?>pageNum=<?php echo $v; ?>" class="<?php if($v == $pages->current){echo 'selected';} ?>"><?php echo $v; ?></a>
    <?php
        }
    ?>
    <a href="<?php echo $url?>pageNum=<?php echo ($pages->current + 1) < $pages->last ? ($pages->current + 1) : $pages->last ?>" style="width:60px">下一页</a>
    <a href="<?php echo $url?>pageNum=<?php echo $pages->last; ?>">尾页</a>
    <span>共 <?php echo $pages->pageCount;?> 页</span>
    <span>到<input type="text" id="redirect-paginate-num" />页</span><a href="javascript:;" class="redirect-paginate-num-btn">确定</a>
</div>

<script>
    $(function(){
        $('.redirect-paginate-num-btn').on('click', function(){
            var pageNum = $('#redirect-paginate-num').val();
            pageNum = parseInt(pageNum);
            if(pageNum < <?php echo $pages->first ?> || pageNum > <?php echo $pages->last; ?>){
                layer.alert('请输入正确的页数');
                return false;
            }
            location.href = '<?php echo $url; ?>pageNum=' + pageNum;
        });

    })
</script>