<div id="pay-div" class="hide">
    <div class="Fixyue">
        <div class="Fixyue3">付款金额<span class="Fixyue3num pay-price" unite-pay-id="" pay-customization-id="" pay-product-id="" customization-count=""></span></div>
        <div class="Fixyue1">
            <ul class="pay-type-list">
                <li class="" pay-type="1"><img src="/jinren/images/zf_03.png"> 余额支付</li>
                <li class="" pay-type="2"><img src="/jinren/images/zf_06.png"> 支付宝</li>
                <li class="" pay-type="5"><img src="images/zf_12.png"> 微信钱包</li>
                <li class="" pay-type="3"><img src="/jinren/images/zf_14.png" style="width:52px;height:51px;"> 银联支付</li>
                <li class="" pay-type="4"><img src="/jinren/images/zf_20.png"> 银行汇款</li>
            </ul>
        </div>
        <div class="Fixyue2 confirm-pay">确认支付</div>
    </div>
</div>
