<link rel="stylesheet" href="/dist/styles/main/index.css">
<link rel="stylesheet" href="/dist/styles/main/good.css">

<style type="text/css">
    body {
        background-color: #f7f5e9;
    }
</style>
<div class="hot-shopAd mb20">
    <div class="center">
        <a href="/">首页</a>
        > 名家详情
    </div>
</div>
<div class="center">
    <div class="avatar-box">
        <div class="avatar-img">
            <img src="<?php echo $info['artistAvatar'] ?>" alt=""></div>
        <div class="avatar-info">
            <img src="/dist/img/upload/img33.jpg" alt=""></div>
    </div>
</div>

<div class="zj-tit">
    <div class="center"><span>个人介绍</span></div>
</div>
<div class="center">
    <iframe src="/artist/artist-detail?artistID=<?php echo $info['artistID'] ?>" frameborder="0" width="100%"></iframe>
</div>
<div class="zj-tit">
    <div class="center"><span>经历和著述</span></div>
</div>
<div class="center">
    <iframe src="/artist/artist-awards?artistID=<?php echo $info['artistID'] ?>" frameborder="0" width="100%"></iframe>

</div>
<div class="zj-tit">
    <div class="center"><span>作品欣赏</span></div>
</div>
<div class="center">
    <iframe src="/artist/artist-productions?artistID=<?php echo $info['artistID'] ?>" frameborder="0" width="100%"></iframe>
</div>

