<link rel="stylesheet" href="/dist/styles/main/index.css" media="screen" type="text/css" />
<link rel="stylesheet" href="/dist/styles/main/good.css"></head>

<div class="mingjia-top">
    <div class="center">
        <h4 class="fl">潜力推荐</h4>

        <p class="fl">
            <?php echo $_siteSettings['artistTopText']; ?></p>
    </div>
</div>
<div class="mingjia-nav">
    <div class="center ">
        <ul>

            <li>专业领域></li>
            <li class="<?php if(empty($artistCategoryID)) echo 'on'; ?>" style="cursor: pointer;" onclick="location.href='/artist/recommend'">全部</li>
            <?php
            foreach($artistCategories as $v){
                ?>
                <li class="<?php echo $artistCategoryID == $v['artistCategoryID'] ? 'on' : ''; ?>" style="cursor: pointer;" onclick="location.href='/artist/recommend?artistCategoryID=<?php echo $v['artistCategoryID'] ?>'"><?php echo $v['categoryName']; ?></li>
            <?php
            }
            ?>
        </ul>

    </div>
</div>
<div class="center">
    <ul class="qltj-list clearfix">
        <?php
            foreach($artists as $v){
        ?>
                <li>
                    <a href="/artist/detail?artistID=<?php echo $v['artistID'] ?>"><img src="<?php echo $v['artistAvatar'] ?>" alt=""></a>
                    <h5><?php echo $v['artistName'] ?></h5>

                    <p class="qltj-info"><?php echo $v['shortDesc'] ?></p>
                </li>
        <?php
            }
        ?>
    </ul>
</div>