<link rel="stylesheet" href="/dist/styles/main/index.css">
<div class="hot-shopAd mb20">
    <div class="center"><a href="/">首页</a> > 专场介绍</div>
</div>
<div class="center">
    <div class="page-box pb30 fz16">

        <iframe frameborder="no" border="0" scrolling="no" src="/special/desc-content?specialID=<?php echo $specialInfo['specialID'] ?>" width="100%" id="iframepage" name="iframepage" onload="iframeHeight('iframepage');">
        </iframe>

    </div>
</div>
