<?php
echo $this->headLink()
    ->appendStylesheet('/dist/styles/common/common.css');

?>
<style>
    body {
        background: #fff;
    }

    .wrap4 {
        clear: both;
        background: #fff;
        overflow: hidden;
        padding-bottom: 30px;
        width: 1200px;
        margin: 0 auto;
    }

    .exc_list {
        background: #f5f5f5;
        width: 258px;
        padding: 10px 10px 20px;
        font-size: 16px;
        color: #222;
        float: left;
        margin-right: 15px;
        border: 1px solid #c5c1be;
    }

    .exc_list li a {
        color: #222;
        font-size: 22px;
        padding-bottom: 10px;
    }

    .exc_list li span {
        color: #800000;
        font-size: 24px;
        font-weight: bold;
    }

    .exc_list li span.exc_q {
        color: #222 !important;
        font-size: 20px !important;
        font-weight: normal !important;
    }

    .lh32 {
        line-height: 32px;
    }

    .exc_list_img {
        border: 1px solid #908a8a;
        height: 258px;
        width: 258px;
        display: table-cell;
        vertical-align: middle;
        text-align: center;
        *display: block;
        *font-size: 175px;
        *font-family: Arial;
        position: relative;
        top: 10px;
    }

    .exc_list_img font {
        background: #800000;
        position: absolute;
        top: 0px;
        right: 0px;
        padding: 6px 15px 10px;
        font-size: 14px;
        color: #fff;
    }

    .exc_list_img strong {
        font-size: 26px;
    }

    .exc_num_bg {
        background: #61b5d7 !important;
    }

    .exc_strat {
        color: #61b5d7 !important;
        font-weight: bold;
        font-size: 18px;
    }

    .exc_rank {
        background: #a8a7a2;
        height: 52px;
        line-height: 52px;
        font-size: 16px;
        width: 100%;
    }

    .exc_rank_l {
        width: 690px;
        float: left;
    }

    .exc_rank_r {
        width: 460px;
        float: left;
        text-align: right;
    }

    .exc_rank_l a {
        padding: 0px 15px;
        display: inline-block;
        margin-right: 10px;
        background: #eeeef0;
        color: #222;

    }

    .exc_rank_l a.rank_icon_x {
        background: #eeeef0 url(/he/images/arrow_up.png) no-repeat 90px center;
        display: inline-block;
        padding: 0px 40px 0px 15px;

    }

    .exc_rank_l a.rank_icon_x1 {
        background: #eeeef0 url(/he/images/arrow_up.png) no-repeat 70px center;
        display: inline-block;
        padding: 0px 45px 0px 15px;

    }

    .exc_rank_r a {
        color: #fff;
        margin-left: 30px;
    }

    .wrap2 {
        width: 1200px;
        margin: 0 auto;
        clear: both;

    }
</style>
<div class="kp_main">
    <div class="theme_sf_banner" style="<?php if(!empty($specialInfo['specialImg'])){ ?>background:url(<?php echo $specialInfo['specialImg'] ?>) no-repeat top center;<?php } ?>">
        <div class="center ">

            <div class="sf_show">

                    <?php if($specialInfo['auctionStatus'] == 0){
                    ?>
                        <div class="sf_show_top" style="background:#61B6D8 none repeat scroll 0% 0%">
                            <p class="sf_title"><?php echo $specialInfo['specialName']; ?></p>

                            <p class="sf_overtime">
                                <em>开拍时间 <?php echo date('m月d日 H时i分', $specialInfo['startTime']); ?></em>
                            </p>
                        </div>
                    <?php
                        }elseif($specialInfo['auctionStatus'] == 1){
                    ?>
                        <div class="sf_show_top" style="background:#61B6D8 none repeat scroll 0% 0%">
                            <p class="sf_title"><?php echo $specialInfo['specialName']; ?></p>

                            <p class="sf_overtime">
                                <em>即将开拍 <?php echo date('m月d日 H时i分', $specialInfo['startTime']); ?></em>
                            </p>
                        </div>
                    <?php
                        }elseif($specialInfo['auctionStatus'] == 2){
                    ?>
                        <div class="sf_show_top">
                            <p class="sf_title"><?php echo $specialInfo['specialName']; ?></p>

                            <p class="sf_overtime yomibox2-special" data="<?php echo date('Y/m/d H:i:s', $specialInfo['endTime']); ?>">

                            </p>
                        </div>
                    <?php
                        }elseif($specialInfo['auctionStatus'] == 3){
                    ?>
                        <div class="sf_show_top" style="background:#61B6D8 none repeat scroll 0% 0%">
                            <p class="sf_title"><?php echo $specialInfo['specialName']; ?></p>

                            <p class="sf_overtime">
                                <em>已结束 <?php echo date('m月d日 H时i分', $specialInfo['endTime']); ?></em>
                            </p>
                        </div>
                    <?php
                        }
                    ?>


                <div class="sf_tip">
                    <ul>
                        <li>拍品：<?php echo $specialInfo['productCountLimit']; ?>件</li>
                        <li>围观：<?php echo $specialInfo['viewCount']; ?>次</li>
                        <li>出价：<?php echo $specialInfo['auctionCount']; ?>次</li>
                    </ul>
                    <div>
            <span class="sf_spjg">
              送拍机构：
              <a href="/store/detail?storeID=<?php echo $specialInfo['storeID'] ?>" target="_blank" class="sf_ys"><?php echo $specialInfo['storeName']; ?>></a>
            </span>
            <span>
              <a href="">专场更多信息></a>
            </span>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="exc_rank">
    <div class="wrap2">
        <div class="exc_rank_l">
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>">默 &nbsp;认</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=auctionCount" class="rank_icon_x">出价次数</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=currPrice" class="rank_icon_x1">价 &nbsp;格</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=interestedCount" class="rank_icon_x">关注人数</a>
        </div>
        <div class="exc_rank_r">
            <a href="javascript:;" class="post-error-btn">站内报错</a>
        </div>
    </div>
</div>
<div class="wrap4">
    <div class="wrap2">
        <?php
        foreach($products as $v){

            echo $this->render('/front/common/product', array('v' => $v, 'specialInfo' => $specialInfo));
        }
        ?>
    </div>
</div>
<?php echo $this->render('/front/common/paginate', array('url' => '/special/detail?order=' . $order . '&specialID=' . $specialInfo['specialID'] . '&', 'pages' => $pages)); ?>
<script>
    $(function(){
        $(".yomibox2-special").each(function () {
            $(this).yomi(_CurrentServerTime, 'special-detail')
        });
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'product-list')
        });
    })
</script>