<?php
echo $this->headLink()
    ->appendStylesheet('/dist/styles/common/common.css')
    ->appendStylesheet('/yaoqin/style/css1.css');
?>
<style>
    body {
        background: #fff;
    }

    .wrap4 {
        clear: both;
        background: #fff;
        overflow: hidden;
        padding-bottom: 30px;
        width: 1200px;
        margin: 0 auto;
    }

    .exc_list {
        background: #f5f5f5;
        width: 258px;
        padding: 10px 10px 20px;
        font-size: 16px;
        color: #222;
        float: left;
        margin-right: 15px;
        border: 1px solid #c5c1be;
    }

    .exc_list li a {
        color: #222;
        font-size: 22px;
        padding-bottom: 10px;
        font-family: SketchRockwell;
    }

    .exc_list li span {
        color: #800000;
        font-size: 24px;
        font-weight: bold;
    }

    .exc_list li span.exc_q {
        color: #222 !important;
        font-size: 20px !important;
        font-weight: normal !important;
    }

    .lh32 {
        line-height: 32px;
    }

    .exc_list_img {
        border: 1px solid #908a8a;
        height: 258px;
        width: 258px;
        display: table-cell;
        vertical-align: middle;
        text-align: center;
        *display: block;
        *font-size: 175px;
        *font-family: Arial;
        position: relative;
        top: 10px;
    }

    .exc_list_img font {
        background: #800000;
        position: absolute;
        top: 0px;
        right: 0px;
        padding: 6px 15px 10px;
        font-size: 14px;
        color: #fff;
    }

    .exc_list_img strong {
        font-size: 26px;
    }

    .exc_num_bg {
        background: #61b5d7 !important;
    }

    .exc_strat {
        color: #61b5d7 !important;
        font-weight: bold;
        font-size: 18px;
    }

    .exc_rank {
        background: #a8a7a2;
        height: 52px;
        line-height: 52px;
        font-size: 16px;
        width: 100%;
    }

    .exc_rank_l {
        width: 690px;
        float: left;
    }

    .exc_rank_r {
        width: 460px;
        float: left;
        text-align: right;
    }

    .exc_rank_l a {
        padding: 0px 15px;
        display: inline-block;
        margin-right: 10px;
        background: #eeeef0;
        color: #222;

    }

    .exc_rank_l a.rank_icon_x {
        background: #eeeef0 url(/he/images/arrow_up.png) no-repeat 90px center;
        display: inline-block;
        padding: 0px 40px 0px 15px;

    }

    .exc_rank_l a.rank_icon_x1 {
        background: #eeeef0 url(/he/images/arrow_up.png) no-repeat 70px center;
        display: inline-block;
        padding: 0px 45px 0px 15px;

    }

    .exc_rank_r a {
        color: #fff;
        margin-left: 30px;
    }

    .wrap2 {
        width: 1200px;
        margin: 0 auto;
        clear: both;

    }
</style>
<div class="kp_main">
    <div class="theme_sf_banner">
        <div class="center ">

            <div class="sf_show">
                <div class="sf_show_top">
                    <p class="sf_title"><?php echo $specialInfo['specialName']; ?></p>

                    <p class="sf_overtime yomibox2" data="<?php echo date('Y/m/d H:i:s', $specialInfo['endTime']); ?>">

                    </p>
                </div>
                <div class="sf_tip">
                    <ul>
                        <li>拍品：<?php echo $specialInfo['productCountLimit']; ?>件</li>
                        <li>围观：<?php echo $specialInfo['interestedCount']; ?>次</li>
                        <li>出价：<?php echo $specialInfo['auctionCount']; ?>次</li>
                    </ul>
                    <div>
            <span class="sf_spjg">
              送拍机构：
              <a href="" class="sf_ys"><?php echo $specialInfo['storeName']; ?>></a>
            </span>
            <span>
              <a href="">专场更多信息></a>
            </span>
                    </div>
                </div>
            </div>

        </div>

    </div>
</div>

<div class="exc_rank">
    <div class="wrap2">
        <div class="exc_rank_l">
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>">默 &nbsp;认</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=auctionCount" class="rank_icon_x">出价次数</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=currPrice" class="rank_icon_x1">价 &nbsp;格</a>
            <a href="/special/detail?specialID=<?php echo $specialInfo['specialID'] ?>&order=interestedCount" class="rank_icon_x">关注人数</a>
        </div>
        <div class="exc_rank_r">
            <a href="javascript:;" class="post-error-btn">站内报错</a>
        </div>
    </div>
</div>
<div class="wrap4">
    <div class="wrap2">
        <?php
        foreach($products as $v){
            if($v['auctionStatus'] == 2){
         ?>
                <ul class="exc_list mt20" onclick="location.href='/product/detail?sourceSpecialID=<?php echo $specialInfo['specialID']; ?>&productID=<?php echo $v['productID']; ?>'">
                    <li class="lh32">
                        <a href="/product/detail?productID=<?php echo $v['productID']; ?>"><?php echo $v['productName'] ?></a>
                    </li>
                    <li class="lh32">
                        当前价
                        <span>￥<?php echo $v['currPrice'] ?></span>
                    </li>
                    <li class="lh32">距结束 <?php echo $v['leftTime']; ?></li>
                    <li class="exc_list_img">
                        <img src="<?php echo $v['listImg']; ?>"> <font><strong><?php echo $v['auctionCount'] ?></strong>
                            <br/>
                            次出价</font>
                    </li>
                </ul>
        <?php
            }elseif($v['auctionStatus'] == 3){
        ?>
                <ul class="exc_list mt20" onclick="location.href='/product/detail?sourceSpecialID=<?php echo $specialInfo['specialID']; ?>&productID=<?php echo $v['productID']; ?>'">
                    <li class="lh32">
                        <a href="/product/detail?productID=<?php echo $v['productID']; ?>"><?php echo $v['productName'] ?></a>
                    </li>
                    <li class="lh32">
                        当前价
                        <span>￥<?php echo $v['currPrice'] ?></span>
                    </li>
                    <li class="lh32">已结束</li>
                    <li class="exc_list_img">
                        <img src="<?php echo $v['listImg']; ?>"> <font><strong><?php echo $v['auctionCount'] ?></strong>
                            <br/>
                            次出价</font>
                    </li>

                </ul>
        <?php
            }else{
        ?>
                <ul class="exc_list mt20" onclick="location.href='/product/detail?sourceSpecialID=<?php echo $specialInfo['specialID']; ?>&productID=<?php echo $v['productID']; ?>'">
                    <li class="lh32">
                        <a href="/product/detail?productID=<?php echo $v['productID']; ?>"><?php echo $v['productName'] ?></a>
                    </li>
                    <li class="lh32">
                        起拍价
                        <span class="exc_q">￥<?php echo $v['currPrice'] ?></span>
                    </li>
                    <li class="lh32 exc_strat"><?php echo date('m月d日 H:i', $v['startTime']) ?> 开拍</li>
                    <li class="exc_list_img">
                        <img src="<?php echo $v['listImg']; ?>">
                        <font class="exc_num_bg">
                            <strong><?php echo $v['auctionCount'] ?></strong>
                            <br>
                            次出价
                        </font>
                    </li>
                </ul>

        <?php
            }
        ?>

        <?php
        }
        ?>
    </div>
</div>
<?php echo $this->render('/front/common/paginate', array('url' => '/special/detail?order=' . $order . '&specialID=' . $specialInfo['specialID'] . '&', 'pages' => $pages)); ?>
<script>
    $(function(){
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'special-detail')
        });
    })
</script>