<?php
echo $this->headLink()->appendStylesheet('/he/style/common.css')->appendStylesheet('/he/style/style.css');
echo $this->inlineScript()->setFile($this->basePath() . '/he/js/jquery.datePicker-min.js');
?>
<div class="wrap">
    <div class="select_list">
        <div class="select_l">
            <p class="f16 canl_t">按日期搜索专场</p>

            <div class="datepicker"></div>
        </div>


        <div class="select_r">
            <ul class="select_cho">
                <?php
                    foreach($categoryThemeOptions as $k => $v){
                ?>
                        <li>
                            <span>[<?php echo $k; ?>]</span>
                            <?php
                                foreach($v as $sv){
                            ?>
                                    <a href="">.<?php echo $sv['optionName'] ?></a>
                            <?php
                                }
                            ?>
                        </li>
                <?php
                    }
                ?>

            </ul>
        </div>
    </div>
    <div class="show_mot">
        <span class="show_tim">2015年12月10日 <font>[显示网站所有专场]</font></span>
        <!--  <span class="show_w">
            <a><i class="show_icon"></i>图片显示</a> |
            <a class="pl10"><i class="show_icon1"></i>列表显示</a>
        </span> -->
    </div>
    <div class="show_con">


        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font>●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font>●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font>●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font>●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <h3 class="s-title">2015年12月30日</h3>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font class="s_c">●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font class="s_c">●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font class="s_c">●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
        <dl class="show_f_list">
            <dt class="w170"><img src="images/show_pic.jpg" height="68" width="148"></dt>
            <dt class="w380"><a href=""><font class="s_c">●</font>近现代名墨专场</a></dt>
            <dd class="show_f_c">
                <ul>
                    <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span> 国画</li>
                    <li class="w325">共53个拍卖品</li>
                    <li><span>选送商家</span> 至真观</li>
                    <li class="w325"><span>拍卖时间</span> 2015/12/10 10:00 ~ 12/30 22:00</li>
                </ul>
            </dd>
        </dl>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){

        $(".datepicker").datePicker({
            inline:true,
            selectMultiple:false,
            clickInput: function () {
                console.log(111);
            }
        });

        $("#datepicker").datePicker({
            clickInput:true
        });

    });
</script>