<?php
echo $this->headLink()->appendStylesheet('/he/style/style.css');
?>
<div class="wrap">
    <div class="select_list">
        <div class="select_l">
            <div class="pop-datatit pa">
                按日期搜索专场
            </div>
            <div class="date-pop"></div>
        </div>


        <div class="select_r">
            <ul class="select_cho">
                <?php
                    foreach($categoryThemeOptions as $k => $v){
                ?>
                        <li>
                            <span>[<?php echo $k; ?>]</span>
                            <?php
                                foreach($v as $sv){
                            ?>
                                    <a href="">.<?php echo $sv['optionName'] ?></a>
                            <?php
                                }
                            ?>
                        </li>
                <?php
                    }
                ?>

            </ul>
        </div>
    </div>
    <div class="show_mot">
        <span class="show_tim"><?php echo date('Y年m月d日', strtotime($date)); ?><font style="cursor:pointer;" onclick="location.href='/special/index';">[显示网站所有专场]</font></span>
        <!--  <span class="show_w">
            <a><i class="show_icon"></i>图片显示</a> |
            <a class="pl10"><i class="show_icon1"></i>列表显示</a>
        </span> -->
    </div>
    <div class="show_con">
        <?php
            foreach($specials as $v){
        ?>
                <dl class="show_f_list">
                    <dt class="w170"><img src="<?php echo $v['specialBanner'] ?>" height="68" width="148"></dt>
                    <dt class="w380"><a href="/special/detail?specialID=<?php echo $v['specialID'] ?>"><font>●</font><?php echo $v['specialName'] ?></a></dt>
                    <dd class="show_f_c">
                        <ul>
                            <li><span>分 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;类</span><?php echo $v['categoryName'] ?></li>
                            <li class="w325">共<?php echo $v['productCountLimit']; ?>个拍卖品</li>
                            <li><span>选送商家</span><?php echo $v['storeName'] ?></li>
                            <li class="w325"><span>拍卖时间</span><?php echo date('Y/m/d H:i', $v['startTime']) . '~' . date('Y/m/d H:i', $v['endTime']) ?></li>
                        </ul>
                    </dd>
                </dl>
        <?php
            }
        ?>
        <?php echo $this->render('/front/common/paginate', array('url' => '/special/index?', 'pages' => $pages)) ?>
    </div>
</div>
