<link rel="stylesheet" href="/dist/styles/common/common.css">
<link rel="stylesheet" href="/he/style/common.css">
<link rel="stylesheet" href="/he/style/style.css">
<div id="flashBg" style="background-color:#5d5f5c;">
    <div id="flashLine">
        <div id="flash">
            <?php foreach($ads as $v){
            ?>
                <a href="<?php echo $v['url']; ?>" target="_blank" id="flash1" style="display: block; "><img src="<?php echo $v['img'] ?>" height="370"></a>
            <?php
            } ?>

            <div class="flash_bar">
                <?php
                $count = 1;
                foreach($ads as $v){

                    ?>
                    <div class="<?php if($count == 1){echo 'dq';}else{echo 'no';} ?>" id="f<?php echo $count; ?>" onclick="changeflash(<?php echo $count; ?>)"></div>
                <?php
                } ?>
            </div>
        </div>
    </div>
    <div class="date_spe">
        <div style="float:right; margin-top:15px;">
            <div class="pop-datatit ">按日期搜索专场</div>
            <div class="date-pop"></div>
        </div>
    </div>
</div>

<div class="exc_rank spe_title">
    <div class="wrap2">
        <span class="spe_name">进入专场分类</span> |
        <?php
        foreach($_categories as $v){
        ?>
            <a href="/special/index?specialProductCategoryID=<?php echo $v['productCategoryID']; ?>"><font>●</font><?php echo $v['categoryName']; ?></a>

        <?php
        }
        ?>
    </div>
</div>
<div class="spe_name_list">
    <div class="wrap2">
        <div class="spe_name_l"><a href="/special/today" class="<?php if($filter == 'today'){ echo 'active'; } ?>">今日专场<i></i></a><a href="/special/today?filter=tomorrow" class="<?php if($filter == 'tomorrow'){ echo 'active'; } ?>">明日专场<i></i></a><a href="/special/today?filter=on" class="<?php if($filter == 'on'){ echo 'active'; } ?>">正在预展<i></i></a>
        </div>
        <div class="spe_name_r">

            <div class="picScroll-left">
                <div class="hd">
                    <a class="next"></a>
                    <ul></ul>
                    <a class="prev"></a>
                    <span class="pageState"></span>
                </div>
                <div class="bd">
                    <div id="slideBox" class="slideBox">
                        <div class="hd">
                            <ul><?php foreach($secondAds as $k => $v){ ?><li><?php echo $k+1; ?></li><?php } ?></ul>
                        </div>
                        <div class="bd">
                            <ul>
                                <?php foreach($secondAds as $k => $v){ ?><li><a href="<?php echo $v['url']; ?>"><img src="<?php echo $v['img'] ?>" height="120"></a></li><?php } ?>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="wrap4">
    <div class="spe_con">
        <div class="spe_con_l">
            <?php
                foreach($specials as $v){
            ?>
                    <?php
                        if($v['auctionStatus'] == 1){
                    ?>
                            <dl class="spe_con_list" style="cursor:pointer;" onclick="location.href='/special/detail?specialID=<?php echo $v['specialID']; ?>';">
                                <dd class="ztCalss2">
                                    <h4><a href="/special/detail?specialID=<?php echo $v['specialID']; ?>"><?php  echo $v['specialName']?></a></h4>

                                    <p class="spe_str"><span>选送商家</span><?php echo $v['storeName'] ?></p>

                                    <p class="ztTime"><em>即将开拍 <?php echo date('m月d日 H时i分', $v['startTime']); ?></em></p>
                                    <ul class="mt20">
                                        <li class="spe_pri"><span><?php echo $v['viewCount'] ?></span><br/>次围观</li>

                                    </ul>
                                </dd>
                                <dt><img src="<?php echo $v['specialBanner'] ?>" height="260" width="570"></dt>
                            </dl>

                    <?php
                        }elseif($v['auctionStatus'] == 2){
                    ?>
                            <dl class="spe_con_list" style="cursor:pointer;" onclick="location.href='/special/detail?specialID=<?php echo $v['specialID']; ?>';">
                                <dd>
                                    <h4><a href="/special/detail?specialID=<?php echo $v['specialID']; ?>"><?php  echo $v['specialName']?></a></h4>

                                    <p class="spe_str"><span>选送商家</span><?php echo $v['storeName'] ?></p>

                                    <p class="ztTime yomibox2-special" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>"></p>
                                    <ul class="mt20">
                                        <li class="spe_pri"><span><?php echo $v['viewCount'] ?></span><br/>次围观</li>

                                    </ul>
                                </dd>
                                <dt><img src="<?php echo $v['specialBanner'] ?>" height="260" width="570"></dt>
                            </dl>

                    <?php
                        }
                    ?>

            <?php
                }
            ?>
            <dl class="">
                <?php echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/special/today?filter=' . $filter . '&')); ?>

            </dl>
        </div>
        <div class="spe_con_r">
            <h3 class="spe_r_t">热门店铺街</h3>

            <div class="spe_r_con">
                <?php
                foreach($stores as $v){
                    ?>
                    <dl>
                        <dt><a href="/store/detail?storeID=<?php echo $v['storeID']; ?>"><?php echo $v['storeName']; ?> &nbsp;&nbsp;></a></dt>
                        <dd><?php echo $v['storeSignature']; ?></dd>
                    </dl>
                <?php
                }
                ?>
                <?php ?>
                <p class="spe_r_more"><a href="/store/index">更多热铺 ...</a></p>
            </div>
        </div>
    </div>

</div>
<div class="wrap4">
    <div class="wrap2">
        <?php
            foreach($recommendProducts as $v){
                echo $this->render('/front/common/product', array('v' => $v));
            }
        ?>
    </div>

</div>

<script type="text/javascript">
    $(document).ready(function(){

        $(".date-pop").datepicker({
            showOtherMonths: true,
            selectOtherMonths: true,
            dateFormat: 'yy-mm-dd',
            onSelect: function (dateText, inst) {
                window.top.location.href = '/special/index?date=' + dateText;
            }
        });

    });

    var currentindex=1;
    $("#flashBg").css("background-color",$("#flash1").attr("name"));
    function changeflash(i){
        currentindex=i;
        for(j=1;j<=3;j++){
            if(j==i){
                $("#flash"+j).fadeIn("normal");
                $("#flash"+j).css("display","block");
                $("#f"+j).removeClass();
                $("#f"+j).addClass("dq");
                $("#flashBg").css("background-color",$("#flash"+j).attr("name"));
            }else{
                $("#flash"+j).css("display","none");
                $("#f"+j).removeClass();
                $("#f"+j).addClass("no");
            }
        }
    }
    function startAm(){
        timerID = setInterval("timer_tick()",3000);
    }
    function stopAm(){
        clearInterval(timerID);
    }
    function timer_tick(){
        currentindex=currentindex>=3?1:currentindex+1;
        changeflash(currentindex);
    }
    $(document).ready(function(){
        $(".flash_bar div").mouseover(function(){
            stopAm();
        }).mouseout(function(){
            startAm();
        });
        startAm();
    });

    $(function(){
        $(".yomibox2-special").each(function () {
            $(this).yomi(_CurrentServerTime, 'special-today')
        });
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'product-list')
        });


    })
</script>