<div class="center">
    <div class="s-nav">
        <a>在线竞拍</a>
        &gt;
        <a>拍卖专场</a>
        &gt;
        <a href="#">精品典藏 高端艺术品竞拍专场</a>
        &gt;
        江西省工艺美术师康剑作品祥和
    </div>

    <!--产品详细 start-->
    <div class="cpxx">
        <!--左侧图片展示区域-->
        <div class="zoom-section">
            <div class="zoom-small-image">
                <div class="xtj-zdzb"></div>
                <img class="cloudzoom" src="http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d5c8953.jpg"
                     id="zoom1"
                     data-cloudzoom="zoomImage: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d5c8953.jpg',zoomSizeMode:'zoom'"/>
            </div>
            <div class="zoom-desc">
                <p>
                    <img class="cloudzoom-gallery zoom-tiny-image"
                         src="http://res.yufuhui.com/public/upload/paimai/2015-11-30/s/565c12d5c8953.jpg"
                         alt="江西省工艺美术师康剑作品祥和"
                         data-cloudzoom="useZoom: '#zoom1', image: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d5c8953.jpg', zoomImage: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d5c8953.jpg',zoomSizeMode:'zoom'"/>
                    <img class="cloudzoom-gallery zoom-tiny-image"
                         src="http://res.yufuhui.com/public/upload/paimai/2015-11-30/s/565c12df1f031.jpg"
                         alt="江西省工艺美术师康剑作品祥和"
                         data-cloudzoom="useZoom: '#zoom1', image: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12df1f031.jpg', zoomImage: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12df1f031.jpg',zoomSizeMode:'zoom'"/>
                    <img class="cloudzoom-gallery zoom-tiny-image"
                         src="http://res.yufuhui.com/public/upload/paimai/2015-11-30/s/565c12dd33a06.jpg"
                         alt="江西省工艺美术师康剑作品祥和"
                         data-cloudzoom="useZoom: '#zoom1', image: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12dd33a06.jpg', zoomImage: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12dd33a06.jpg',zoomSizeMode:'zoom'"/>
                    <img class="cloudzoom-gallery zoom-tiny-image"
                         src="http://res.yufuhui.com/public/upload/paimai/2015-11-30/s/565c12d84371a.jpg"
                         alt="江西省工艺美术师康剑作品祥和"
                         data-cloudzoom="useZoom: '#zoom1', image: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d84371a.jpg', zoomImage: 'http://res.yufuhui.com/public/upload/paimai/2015-11-30/b/565c12d84371a.jpg',zoomSizeMode:'zoom'"/>
                </p>
            </div>
            <div class="clear"></div>
        </div>
        <!-- 左侧图片展示区域结束 -->

        <!--中间详情 start-->
        <div class="cpxx-c">
            <!--top start-->
            <div class="cpxx-c-top">
                <h2>卿佩天然琥珀蜜蜡霸气吊坠HP35305-442</h2>

                <div class="cpxx-date">
                    <span>正在拍卖</span> <i>距结束</i>

                    <div class="yomibox2" data="2016-05-02 21:59:59"></div>

                    <!--
                <span>拍品已结束</span> <i>结束时间 2016/3/1 22:00:00</i>
                -->
                    <div class="onlookers">围观人数：39</div>

                </div>
            </div>
            <!--top end-->
            <!--start detailed-price-->
            <div class="detailed-price cpxx-c-c">
                <dl>
                    <dt class="present-price">当前价格：</dt>
                    <dd>
                        ￥
                        <span class="f30">55000</span>
                    </dd>
                </dl>

                <dl>
                    <dt>出价金额：</dt>
                    <dd>
                        <a href="javascript:void(0)" id="priceReduce" class="cpxx_cleft"></a>
                        <input class="d-jg" type="text" id="j_addprice" value="57000"/>
                        <a href="javascript:void(0)" id="priceAdd" class="cpxx_cright"></a>
                    </dd>
                </dl>
                <dl>
                    <dt></dt>
                    <dd class="d-btnnav">
                        <input name="我要出价" type="button" class="d-cj btn" id="my_biding" value="我要出价"/>
                        <input name="设置代理价" type="button" class="d-zx btn" id="agent_biding" value="设置代理价"/>
                    </dd>
                </dl>

                <!--  <h3 style="text-align:center;line-height:140px;font-size:24px;">拍品已结束</h3>
            -->
            </div>
            <!--end detailed-price-->
            <div class="cpxx-sjxx">
                <ul>
                    <li>起拍价：￥55000</li>
                    <li>
                        加价幅度：￥
                        <span id="specialIncreaseRange">2000</span>
                    </li>
                    <li>拥金：￥500</li>
                    <li>保留价：有</li>
                    <li>延时周期：5分/次</li>
                    <li>
                        商家：
                        <a ui-sref="mainShop({'id':14})" class="blue">开拍珠宝</a>
                    </li>
                </ul>
            </div>

            <div class="cpxx-sjxxd">
                <p>
                    特色服务：
			<span>
				<i></i>
				资质授权
			</span>
			<span>
				<i></i>
				7天承保
			</span>
                    <span class="margin-left-50">商家信用：艺术网金牌商户</span>
                </p>

                <p class="collection">
                    <a class="collection-p" href="javascript:;" onclick="setcollect(1,1382161);">收藏拍品</a>
                    <a class="collection-d" href="javascript:;" onclick="setcollect(2,100359);">关注店铺</a>
                </p>
            </div>
        </div>
        <!--中间详情 end-->
        <!--右侧出价记录 start-->
        <div class="cpxx-bidrecord">
            <div class="cpxx-bidrecord-top"><b>出价记录
                    <span class="red" id="rightbidtotal">(1)</span></b>
            </div>
            <ul id="rightbid">
                <li style="color:#333">
                    <span class="num_01">&nbsp;</span>
                    <span class="num_02">竞拍人</span>
                    <span class="num_03">价格</span>
                    <span class="num_04">时间</span>
                </li>
                <li>
                    <span class="num_01 n_01"></span>
                    <span class="num_02 font_b">15***226</span>
                    <span class="num_03 font_b">*****</span>
                    <span class="num_04 font_b">16/03/01</span>
                </li>
                <li>
                    <span class="num_01 n_01"></span>
                    <span class="num_02 ">15***226</span>
                    <span class="num_03 ">*****</span>
                    <span class="num_04 ">16/03/01</span>
                </li>
                <div class="cpxx-ckmore">查看全部出价</div>
            </ul>

        </div>
        <!--end 右侧出价记录-->
    </div>
    <!--end 产品详细-->
    <div class="center cpxxy">
        <!--相关推荐 start-->
        <div class="rnav">

            <div class="rnav-tit">
                相关推荐
            </div>
            <ul class="rnav-list">
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>
                <li>
                    <img src="/images/img2.jpg" alt="">

                    <p class="rnav-info">
                        西冷凶载 李平<br>
                        《妙造自然》<br>
                        当前价 <em>￥3000</em>
                    </p>
                </li>

            </ul>


        </div>
        <!--相关推荐 end-->

        <!--底部 left start-->
        <div class="cpxx-left">
            <!--start 竞拍流程-->
            <div class="detailed-step">
                <span>竞拍流程：</span>
                <dl>
                    <dt>
                        <i class="icon1"></i>
                    </dt>
                    <dd>免/交保证金</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon2"></i>
                    </dt>
                    <dd>出价竞拍</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon3"></i>
                    </dt>
                    <dd>竞拍成功</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon4"></i>
                    </dt>
                    <dd>支付款项</dd>
                </dl>
                <dl style="background:none; padding:0px;">
                    <dt>
                        <i class="icon5"></i>
                    </dt>
                    <dd>签收货物</dd>
                </dl>

            </div>
            <!--end 竞拍流程-->

            <!--left 拍品描述 start-->
            <div class="detailed-xx" id="cjjlxtj">
                <!--detailed-xx-top start-->
                <div class="detailed-xx-top">
                    <a class="on" href="javascript:void(0)" target="_self">拍品描述</a>
                    <a href="javascript:void(0)" target="_self" class="cjjlxx">
                        出价记录
                        <span class="red">(0)</span>
                    </a>
                    <a href="javascript:void(0)" target="_self">竞拍须知</a>
                    <a href="javascript:void(0)" target="_self">服务保障</a>
                </div>
                <!--detailed-xx-top end-->
                <!--detailed-xx-down start-->
                <div class="detailed-xx-down" id="detailed-xx-down">
                    <!----start 拍品描述-->
                    <div class="xtj-ppms lstpp shop-show-item">
                        <!--detailed-xx-ul start-->
                        <div
                            style="border:1px solid #dbcca3;background-color:#ede5d1;color:#a47f1a;padding:8px;margin-top:20px;margin-bottom:20px">


                            <p>
                                [友情提醒]<br>
                                1、真伪：送拍机构的企业资质已审核，但拍品介绍（图片、文字、视频等）及拍品资质文件（来源证明、鉴定证书等）均由机构自行发布并上传，所有拍品相关信息由送拍机构自行承担相应担保责任；<br>
                                2、售后：拍品多为孤品性质类商品，“7天退货”服务为卖家可选服务保障，不强制送拍机构提供，竞拍前请充分考虑；
                            </p>
                        </div>

                        <div class="detailed-xx-ultitle"><b>商品属性</b>
                        </div>


                        <ul class="detailed-xx-ul">
                            <li>
                                <p>
                                    <span>编号</span>
                                    1382161
                                </p>

                                <p>
                                    <span>存货地</span>
                                    广东省深圳
                                </p>
                            </li>
                            <li>
                                <p>
                                    <span>类型</span>
                                    琥珀
                                </p>

                                <p>
                                    <span>重量</span>
                                    100.87克
                                </p>
                            </li>
                            <li>
                                <p>
                                    <span>尺寸</span>
                                </p>

                                <p>
                                    <span>创作年代</span>
                                    现代
                                </p>
                            </li>
                            <div class="dxu-li">
                                <span class="l">商品简介</span>

                                <div class="r">卿佩天然琥珀蜜蜡霸气吊坠总重：100.87g 尺寸：6.9cm*7.2cm*3.0cm .</div>
                            </div>
                        </ul>
                        <!--detailed-xx-ul start-->
                        <!--产品图 start-->
                        <div class="detailed-xx-ultitle">
                            <b>拍品展示</b>
                        </div>
                        <p>
                            <img
                                src="http://res.yufuhui.com/public/upload/paimai/2016-01-13/art_a848438e-a8a6-4ee4-994f-7e2ec6a24f63.jpg"
                                width="800px"></p>

                        <p>
                            <br></p>

                        <!--产品图 end-->
                    </div>

                    <!----start 拍品描述-->
                    <!--出价记录 start-->
                    <div class="detailed-xx-cjjl  shop-show-item">
                        <ul>
                            <li class="bg">
                                <span class="num_01">状态</span>
                                <span class="num_02">竞拍人</span>
                                <span class="num_03">价格</span>
                                <span class="num_04">时间</span>
                            </li>
                        </ul>
                        <ul id="bottombid">
                            <div style="text-align:center;margin-top:20px;">正努力加载中...</div>
                        </ul>
                    </div>
                    <!----出价记录 end-->
                    <!--竞拍须知 start-->
                    <div class="xtj-jpxz shop-show-item" style="display: none;">
                        <div class="detailed-xx-ultitle">
                            <b>竞拍须知</b>
                        </div>
                        <ul class="detailed-xx-ul xz">
                            <div class="dxu-li">
						<span class="l">
							<b>关于尺寸</b>
						</span>

                                <div class="r">藏品尺寸均为人工测量，会存在0.1-0.3cm/1-3克左右的误差，若有介意，请慎拍；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于真品</b>
						</span>

                                <div class="r">
                                    商家承诺所送拍藏品均为真品，支持复检，如假包退；如需鉴定，请在收到藏品的30天内和客服说明需鉴定，会延长收货时间，过期不受理；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于出价</b>
						</span>

                                <div class="r">请参拍的客户遵守竞拍规则，拍前提前评估好，一旦出价，无法撤销，请勿盲目出价；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>&nbsp;</b>
						</span>

                                <div class="r" style="color:#666666">
                                    <p>支付货款请打至中国艺术网指定账户，如下：</p>

                                    <p>【银行转账】</p>

                                    <p>账户名：上海永佳网络科技有限公司；</p>

                                    <p>开户行：北京银行股份有限公司 - 上海杨浦支行；</p>

                                    <p>账号：0013 0698 100120 10801 6681。</p>

                                    <p>【支付宝账户】</p>

                                    <p>用户名：上海永佳网络科技有限公司</p>

                                    <p>账户名：15601791750@163.com</p>

                                    <p>充值后请尽快告知客服，如若打入其他账户，一切后果自负。</p>

                                    <p>在艺术网后台或掌拍艺术APP的“用户中心→在线竞拍→拍到的拍品“处付款</p>
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于延时竞拍</b>
						</span>

                                <div class="r">
                                    为了将给到用户更加充分的参与竞拍的机会，应广大客户的要求，我们制定了拍品竞价的自动延时规则，具体内容如下：每增加一个竞买人出价，那么该专场拍卖时间将自动延时5分钟。建议在22:00专场显示结束时刷新下当前的页面，以最后出价者成交此藏品！
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于色差</b>
						</span>

                                <div class="r">
                                    藏品是实物多角度拍照，除对图片进行裁剪外，无其他处理。由于受光线、显示器、拍照设备的影响，难免会存在一定色差，不属于质量问题，介意者请慎拍；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于退货</b>
						</span>

                                <div class="r">
                                    商家不支持7天无理由退换的藏品会在详情里说明，除此之外均享受7天无理由退换货；签收7天后（不含7天）或藏品已影响二次销售的情况不予退换货；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于发票</b>
						</span>

                                <div class="r">藏品成交价不含税，默认不提供发票，如需要，请联系客服补缴税点；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于发货</b>
						</span>

                                <div class="r">
                                    付款成功后商家会在72小时内发货，若出现商家成交不卖行为，将货款全额返还竞买人并从商家经营保证金扣除货款的5%（上限不超过500元）的现金抵用款（非现金）补偿给竞买人；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于物流</b>
						</span>

                                <div class="r">商家发货不指定具体快递，除港、澳、台及国外全部免首次首重邮费；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于签收</b>
						</span>

                                <div class="r">
                                    由于藏品贵重，请务必现场当面验货。若送货员拒绝验货或您验货时发现实物尺寸、价格不一致、物品为赝品现象时，可直接拒绝签收并退货，签字确认后出现的破损一概不予退货；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于须知</b>
						</span>

                                <div class="r">出价前请认真阅读本须知，竞拍成功默认认同本须知；</div>
                            </div>

                        </ul>
                    </div>
                    <!--end 竞拍须知-->

                    <!--服务保障 start-->
                    <div class="detailed-service shop-show-item">
                        <div class="detailed-service-top">服务保障</div>
                        <p>
                            <span>售后服务</span>
                            <br>
                            1. 如果有藏品发错货物等问题，请在48小时内提供照片，我们会及时更换
                            <br>
                            2. 收到藏品有任何问题请联系在线客服，我们竭力做到让您满意；
                            <br>
                            3. 客服热线：400 878 2221
                            <br></p>
                    </div>
                    <!--服务保障 end-->
                </div>

            </div>
        </div>
    </div>
</div>
<?php
echo $this->headScript()->appendFile('/plugins/CloudZoom/cloudzoom.js');
?>
<script type="text/javascript">
    $(function () {
        //产品详情图片展示
        CloudZoom.quickStart();
        _PageTag = "detail";
        console.log(_CurrentServerTime);
        $(".yomibox2").each(function () {
            console.log('dd');
            $(this).yomi(_CurrentServerTime, _PageTag)
        });
        initEvent();
    });

    function initEvent() {
        $('#detailed-xx-down').delegate('[data-role="addres"]', 'click', function (event) {
            console.log('[data-role="addres"]');
        });
        //产品详情介绍的tab
        $('.detailed-xx-top').delegate('a', 'click', function () {
            $(this).addClass('on').siblings().removeClass('on');
            var J_index = $(this).index();
            console.log(J_index);
            var J_detailed_xx_down = $('#detailed-xx-down .shop-show-item');
            J_detailed_xx_down.hide();
            J_detailed_xx_down.eq(J_index).show();


        });
    }
</script>