<link rel="stylesheet" type="text/css" href="/dist/styles/main/good.css" media="screen" />
<div class="center">
    <div class="s-nav">
        <!--<a href="/">在线竞拍</a>-->
        <?php if(!empty($sourceSpecialInfo)){?>
            <a href="/special/index?specialProductCategoryID=<?php echo $sourceSpecialInfo['specialProductCategoryID']; ?>"><?php echo $sourceSpecialInfo['categoryName']; ?></a>
            &gt;
            <a href="/special/detail?specialID=<?php echo $sourceSpecialInfo['specialID']; ?>"><?php echo $sourceSpecialInfo['specialName']; ?></a>
            &gt;
            拍品详情
        <?php }else{
        ?>
            <a href="/store/detail?storeID=<?php echo $productInfo['storeID']; ?>"><?php echo $productInfo['storeName'] ?></a>
            &gt;
            拍品详情
        <?php
        } ?>
    </div>

    <!--产品详细 start-->
    <div class="cpxx">
        <!--左侧图片展示区域-->
        <div class="zoom-section">
            <div class="zoom-small-image">
                <div class="xtj-zdzb"></div>
                <img class="cloudzoom" src="<?php echo $productInfo['listImg'] ?>"
                     id="zoom1"
                     data-cloudzoom="zoomImage: '<?php echo $productInfo['listImg'] ?>',zoomSizeMode:'zoom'"/>
            </div>
            <div class="zoom-desc">
                <p>
                    <?php
                    foreach($detailImgs as $v){
                        ?>
                        <img class="cloudzoom-gallery zoom-tiny-image"
                             src="<?php echo $v; ?>"
                             alt=""
                             data-cloudzoom="useZoom: '#zoom1', image: '<?php echo $v; ?>', zoomImage: '<?php echo $v; ?>',zoomSizeMode:'zoom'"/>
                    <?php
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <!-- 左侧图片展示区域结束 -->

        <!--中间详情 start-->
        <div class="cpxx-c">
            <!--top start-->




            <?php
                if($productInfo['auctionStatus'] == 2 || $productInfo['auctionStatus'] == 1){
            ?>
                    <div class="cpxx-c-top">
                        <h2><?php echo $productInfo['productName'] ?></h2>
                            <div class="cpxx-date">
                                <?php
                                    if($productInfo['auctionStatus'] == 2){
                                ?>
                                        <span>正在拍卖</span> <i>距结束</i>
                                        <div class="yomibox2" data="<?php echo date('Y/m/d H:i:s', $productInfo['endTime']); ?>"></div>
                                <?php
                                    }else{
                                ?>
                                        <span>即将开拍</span> <i>开拍时间</i>
                                        <i><?php echo date('Y/m/d H:i:s', $productInfo['startTime']); ?></i>
                                <?php
                                    }
                                ?>

                                <div class="onlookers">围观人数：<?php echo $productInfo['viewCount']; ?></div>

                            </div>
                    </div>

                    <!--top end-->
                    <!--start detailed-price-->
                    <div class="detailed-price cpxx-c-c">
                        <dl>
                            <dt class="present-price">当前价格：</dt>
                            <dd>
                                ￥
                                <span class="f30"><?php echo $productInfo['currPrice']; ?></span>
                            </dd>
                        </dl>

                        <dl>
                            <dt>出价金额：</dt>
                            <dd>
                                <a href="javascript:void(0)" id="priceReduce" class="cpxx_cleft"></a>
                                <input class="d-jg" type="text" id="j_addprice" value="<?php if(empty($auctionLogs)){echo $productInfo['currPrice'];}else{echo $productInfo['currPrice'] + $productInfo['auctionPerPrice'];}  ?>"/>
                                <a href="javascript:void(0)" id="priceAdd" class="cpxx_cright"></a>
                            </dd>
                        </dl>
                        <dl>
                            <dt></dt>
                            <dd class="d-btnnav">
                                <input name="我要出价" type="button" class="d-cj btn" id="my_biding" value="我要出价"/>
                                <input name="设置代理价" type="button" class="d-zx btn" id="set-agent_biding" value="设置代理价"/>
                            </dd>
                        </dl>
                    </div>
                    <!--end detailed-price-->
            <?php
                }elseif($productInfo['auctionStatus'] == 3){
            ?>
                    <div class="cpxx-c-top">
                        <h2><?php echo $productInfo['productName'] ?></h2>
                        <div class="cpxx-date">

                            <span>拍卖已结束</span> <i>结束时间</i>
                            <i><?php echo date('Y/m/d H:i:s', $productInfo['endTime']); ?></i>

                            <div class="onlookers">围观人数：<?php echo $productInfo['viewCount']; ?></div>

                        </div>
                    </div>
                    <div class="detailed-price cpxx-c-c"><h3 style="text-align:center;line-height:140px;font-size:24px;">拍卖已结束</h3></div>
            <?php
                }
            ?>



            <div class="cpxx-sjxx">
                <ul>
                    <li>起拍价：￥<?php echo $productInfo['startPrice']; ?></li>
                    <li>
                        加价幅度：￥
                        <span id="specialIncreaseRange"><?php echo $productInfo['auctionPerPrice']; ?></span>
                    </li>
                    <?php if(!empty($productInfo['commision'])){
                    ?>
                        <li>佣金：<?php echo $productInfo['commision']; ?>%</li>
                    <?php
                    }else{
                    ?>
                        <li>佣金：￥0</li>
                    <?php
                    } ?>

                    <!--<li>保留价：<?php /*if(!empty($productInfo['existKeepPrice'])){echo '有';}else{echo '无';} */?></li>-->
                    <li>延时周期：<?php if($productInfo['delayType'] == 1){echo '5分/次';}else{echo '无';} ?></li>
                    <li>邮费：￥<?php echo !empty($productInfo['deliveryPrice']) ? $productInfo['deliveryPrice'] : 0;?></li>
                    <li>
                        商家：
                        <a ui-sref="mainShop({'id':14})" class="blue" href="/store/detail?storeID=<?php echo $productInfo['storeID'] ?>"><?php echo $productInfo['storeName'] ?></a>
                    </li>
                </ul>
            </div>

            <div class="cpxx-sjxxd">
                <p>
                    特色服务：

                <?php if(!empty($productInfo['auctionAuth'])){
                ?>
                    <span>
                        <i></i>
                        文物拍卖资质
                    </span>
                <?php
                } ?>
                <?php /*if(!empty($productInfo['fidelity'])){
                    */?><!--
                    <span>
                        <i></i>
                        保真
                    </span>
                --><?php
/*                }*/ ?>
                <?php if(!empty($productInfo['certificateCard'])){
                    ?>
                    <span>
                        <i></i>
                        省级资质机构以上鉴定证书
                    </span>
                <?php
                } ?>
                <?php if(!empty($productInfo['authorAuth'])){
                    ?>
                    <span>
                        <i></i>
                        作者授权
                    </span>
                <?php
                } ?>
                <?php if(!empty($productInfo['refundInDays'])){
                    ?>
                    <span>
                        <i></i>
                        三日内可退
                    </span>
                <?php
                } ?>

                </p>
                <p>
                    <a qq="<?php echo $productInfo['storeqq'] ?>" href="javascript:;" class="tencent-qq" style="color:#ad0015">在线咨询</a>
                </p>

                <p class="collection">
                    <a class="collection-p" href="javascript:;" id="interest-product"><?php echo !empty($interestProduct) ? '取消关注' : '关注拍品';?></a>
                    <a class="collection-d" href="javascript:;" id="interest-store"><?php echo !empty($interestStore) ? '取消关注' : '关注店铺';?></a>
                </p>
            </div>
        </div>
        <!--中间详情 end-->
        <!--右侧出价记录 start-->
        <div class="cpxx-bidrecord">
            <div class="cpxx-bidrecord-top"><b>出价记录
                    <span class="red" id="rightbidtotal">(<?php echo $productInfo['auctionCount'] ?>)</span></b>
            </div>
            <ul id="rightbid">
                <li style="color:#333">
                    <span class="num_02">竞拍人</span>
                    <span class="num_03">价格</span>
                    <span class="num_04">时间</span>
                </li>
                <?php
                    foreach($auctionLogs as $v){
                ?>
                        <li>
                            <span class="num_02 font_b"><?php echo $v['nickName'] ?></span>
                            <span class="num_03 font_b"><?php echo $v['auctionPrice'] ?></span>
                            <span class="num_04 font_b"><?php echo date('m-d H:i', strtotime($v['instime'])) ?></span>
                        </li>
                <?php
                    }
                ?>

                <!--<div class="cpxx-ckmore">查看全部出价</div>-->
            </ul>

        </div>
        <!--end 右侧出价记录-->
    </div>
    <!--end 产品详细-->
    <div class="center cpxxy">
        <!--相关推荐 start-->
        <div class="rnav">

            <div class="rnav-tit">
                相关推荐
            </div>
            <ul class="rnav-list">
                <?php
                    foreach($recommendProducts as $v){
                ?>
                        <li style="cursor: pointer" onclick="location.href='/product/detail?productID=<?php echo $v['productID'] ?>';">
                            <img src="<?php echo $v['listImg'] ?>" alt="">

                            <p class="rnav-info">
                                <?php echo $v['productName'] ?><br>
                                当前价 <em>￥<?php echo $v['currPrice'] ?></em>
                            </p>
                        </li>
                <?php
                    }
                ?>
            </ul>
        </div>
        <!--相关推荐 end-->

        <!--底部 left start-->
        <div class="cpxx-left">
            <!--start 竞拍流程-->
            <div class="detailed-step">
                <span>竞拍流程：</span>
                <dl>
                    <dt>
                        <i class="icon2"></i>
                    </dt>
                    <dd>出价竞拍</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon3"></i>
                    </dt>
                    <dd>竞拍成功</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon4"></i>
                    </dt>
                    <dd>支付款项</dd>
                </dl>
                <dl style="background:none; padding:0px;">
                    <dt>
                        <i class="icon5"></i>
                    </dt>
                    <dd>签收货物</dd>
                </dl>

            </div>
            <!--end 竞拍流程-->

            <!--left 拍品描述 start-->
            <div class="detailed-xx" id="cjjlxtj">
                <!--detailed-xx-top start-->
                <div class="detailed-xx-top">
                    <a class="on" href="javascript:void(0)" target="_self">拍品描述</a>
                    <a href="javascript:void(0)" target="_self" class="cjjlxx">
                        出价记录
                        <span class="red">(<?php echo $productInfo['auctionCount'] ?>)</span>
                    </a>
                    <a href="javascript:void(0)" target="_self">竞拍须知</a>
                    <a href="javascript:void(0)" target="_self">服务保障</a>
                    <span class="zrjb-link fr"><em post-illegal-btn" type="4" coreID="<?php echo $productInfo['productID']; ?>>站内举报</em> | <em class="post-error-btn">报错</em></span>
                </div>
                <!--detailed-xx-top end-->
                <!--detailed-xx-down start-->
                <div class="detailed-xx-down" id="detailed-xx-down">
                    <!----start 拍品描述-->
                    <div class="xtj-ppms lstpp shop-show-item">
                        <!--detailed-xx-ul start-->
                        <div
                            style="border:1px solid #dbcca3;background-color:#ede5d1;color:#a47f1a;padding:8px;margin-top:20px;margin-bottom:20px">


                            <p>
                                [友情提醒]<br>
                                <?php echo $_siteSettings['friendlyNotification']; ?>
                            </p>
                        </div>

                        <div class="detailed-xx-ultitle"><b>商品属性</b>
                        </div>


                        <ul class="detailed-xx-ul">
                            <?php
                                foreach($properties as $v){
                            ?>
                                    <li>
                                        <?php
                                            foreach($v as $sv){
                                        ?>
                                                <p>
                                                    <span><?php echo $sv['propertyName'] ?></span>
                                                    <?php echo $sv['value'] ?>
                                                </p>
                                        <?php
                                            }
                                        ?>
                                    </li>
                            <?php
                                }
                            ?>
                            <!--<div class="dxu-li">
                                <span class="l">商品简介</span>

                                <div class="r" id="product-detail"><?php /*echo $productInfo['productDetail'] */?></div>
                            </div>-->
                        </ul>
                        <!--detailed-xx-ul start-->
                        <!--产品图 start-->
                        <div class="detailed-xx-ultitle">
                            <b>拍品详情</b>
                        </div>
                        <div class="product-detail">
                            <iframe frameborder="no" border="0" scrolling="no" src="/product/iframe-detail?productID=<?php echo $productInfo['productID'] ?>" width="100%" id="iframepage" name="iframepage" onload="iframeHeight('iframepage');">
                            </iframe>
                        </div>

                        <!--产品图 end-->
                    </div>

                    <!----start 拍品描述-->
                    <!--出价记录 start-->
                    <div class="detailed-xx-cjjl  shop-show-item">
                        <ul>
                            <li class="bg">
                                <span class="num_02">竞拍人</span>
                                <span class="num_03">价格</span>
                                <span class="num_04">时间</span>
                            </li>

                            <?php
                            foreach($auctionLogs as $v){
                                ?>
                                <li>
                                    <li >
                                        <span class="num_02"><?php echo $v['nickName'] ?></span>
                                        <span class="num_03"><?php echo $v['auctionPrice'] ?></span>
                                        <span class="num_04"><?php echo date('m-d H:i', strtotime($v['instime'])) ?></span>
                                    </li>
                                </li>
                            <?php
                            }
                            ?>



                        </ul>
                    </div>
                    <!----出价记录 end-->
                    <!--竞拍须知 start-->
                    <div class="xtj-jpxz shop-show-item" style="display: none;">
                        <iframe frameborder="no" border="0" scrolling="no" src="/article/setting-detail?settingName=biddingKnow" width="100%" id="iframepage1" name="iframepage1" onload="iframeHeight('iframepage1');">
                        </iframe>

                        <!--<div class="detailed-xx-ultitle">
                            <b>竞拍须知</b>
                        </div>
                        <ul class="detailed-xx-ul xz">
                            <div class="dxu-li">
						<span class="l">
							<b>关于尺寸</b>
						</span>

                                <div class="r">藏品尺寸均为人工测量，会存在0.1-0.3cm/1-3克左右的误差，若有介意，请慎拍；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于真品</b>
						</span>

                                <div class="r">
                                    商家承诺所送拍藏品均为真品，支持复检，如假包退；如需鉴定，请在收到藏品的30天内和客服说明需鉴定，会延长收货时间，过期不受理；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于出价</b>
						</span>

                                <div class="r">请参拍的客户遵守竞拍规则，拍前提前评估好，一旦出价，无法撤销，请勿盲目出价；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>&nbsp;</b>
						</span>

                                <div class="r" style="color:#666666">
                                    <p>支付货款请打至中国艺术网指定账户，如下：</p>

                                    <p>【银行转账】</p>

                                    <p>账户名：上海永佳网络科技有限公司；</p>

                                    <p>开户行：北京银行股份有限公司 - 上海杨浦支行；</p>

                                    <p>账号：0013 0698 100120 10801 6681。</p>

                                    <p>【支付宝账户】</p>

                                    <p>用户名：上海永佳网络科技有限公司</p>

                                    <p>账户名：15601791750@163.com</p>

                                    <p>充值后请尽快告知客服，如若打入其他账户，一切后果自负。</p>

                                    <p>在艺术网后台或掌拍艺术APP的“用户中心→在线竞拍→拍到的拍品“处付款</p>
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于延时竞拍</b>
						</span>

                                <div class="r">
                                    为了将给到用户更加充分的参与竞拍的机会，应广大客户的要求，我们制定了拍品竞价的自动延时规则，具体内容如下：每增加一个竞买人出价，那么该专场拍卖时间将自动延时5分钟。建议在22:00专场显示结束时刷新下当前的页面，以最后出价者成交此藏品！
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于色差</b>
						</span>

                                <div class="r">
                                    藏品是实物多角度拍照，除对图片进行裁剪外，无其他处理。由于受光线、显示器、拍照设备的影响，难免会存在一定色差，不属于质量问题，介意者请慎拍；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于退货</b>
						</span>

                                <div class="r">
                                    商家不支持7天无理由退换的藏品会在详情里说明，除此之外均享受7天无理由退换货；签收7天后（不含7天）或藏品已影响二次销售的情况不予退换货；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于发票</b>
						</span>

                                <div class="r">藏品成交价不含税，默认不提供发票，如需要，请联系客服补缴税点；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于发货</b>
						</span>

                                <div class="r">
                                    付款成功后商家会在72小时内发货，若出现商家成交不卖行为，将货款全额返还竞买人并从商家经营保证金扣除货款的5%（上限不超过500元）的现金抵用款（非现金）补偿给竞买人；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于物流</b>
						</span>

                                <div class="r">商家发货不指定具体快递，除港、澳、台及国外全部免首次首重邮费；</div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b style="line-height:56px;">关于签收</b>
						</span>

                                <div class="r">
                                    由于藏品贵重，请务必现场当面验货。若送货员拒绝验货或您验货时发现实物尺寸、价格不一致、物品为赝品现象时，可直接拒绝签收并退货，签字确认后出现的破损一概不予退货；
                                </div>
                            </div>
                            <div class="dxu-li">
						<span class="l">
							<b>关于须知</b>
						</span>

                                <div class="r">出价前请认真阅读本须知，竞拍成功默认认同本须知；</div>
                            </div>

                        </ul>-->
                    </div>
                    <!--end 竞拍须知-->

                    <!--服务保障 start-->
                    <div class="detailed-service shop-show-item" style="display: none;">
                        <iframe frameborder="no" border="0" scrolling="no" src="/article/setting-detail?settingName=serviceProtocol" width="100%" id="iframepage2" name="iframepage2" onload="iframeHeight('iframepage2');">
                        </iframe>
                    </div>
                    <!--服务保障 end-->
                </div>

            </div>
        </div>
    </div>
</div>
<?php
echo $this->render('set-proxy-price');
?>
<?php
echo $this->inlineScript()->appendFile('/plugins/CloudZoom/cloudzoom.js');
?>
<script type="text/javascript">

    $(function () {

        //产品详情图片展示
        CloudZoom.quickStart();
        _PageTag = "detail";
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, _PageTag);
        });
        initEvent();

        $('#interest-product').on('click', function(){
            var obj = $(this);
            var text = obj.html();
            var url;
            var replace;
            if(text == '关注拍品'){
                url = '/member/add-interest-product';
                replace = '取消关注';
            }else{
                url = '/member/remove-interest-product';
                replace = '关注拍品';
            }
            $.ajax({
                url : url,
                type : 'post',
                dataType : 'json',
                data : {
                    productID : '<?php echo $productInfo['productID']; ?>'
                },
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg);
                        obj.html(replace);
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });
        $('#interest-store').on('click', function(){
            var obj = $(this);
            var text = obj.html();
            var url;
            var replace;
            if(text == '关注店铺'){
                url = '/member/add-interest-store';
                replace = '取消关注';
            }else{
                url = '/member/remove-interest-store';
                replace = '关注店铺';
            }
            $.ajax({
                url : url,
                type : 'post',
                dataType : 'json',
                data : {
                    storeID : '<?php echo $productInfo['storeID']; ?>'
                },
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg);
                        obj.html(replace);
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });

        $('#priceAdd').on('click', function(){
            var val = parseInt($('#j_addprice').val()) + <?php echo $productInfo['auctionPerPrice'] ?>;
            $('#j_addprice').val(val);
        });
        $('#priceReduce').on('click', function(){
            var val = parseInt($('#j_addprice').val())- <?php echo $productInfo['auctionPerPrice'] ?>;
            $('#j_addprice').val(val);
        });

        $('#my_biding').on('click', function(){
            var data = {};
            data.auctionPrice = $('#j_addprice').val();
            layer.confirm(
                '确认出价' + data.auctionPrice + '元吗?',
                {btn : ['确认', '取消']},
                function(){
                    data.productID = <?php echo $productInfo['productID'] ?>;
                    $.ajax({
                        url : '/auction/bidding',
                        dataType : 'json',
                        type : 'post',
                        data : data,
                        success : function(response){
                            if(response.flag > 0){
                                layer.alert(response.msg, function(){location.reload();});
                            }else if(response.flag == -102){
                                loginPOP();
                            }else{
                                layer.alert(response.msg);
                            }

                        }
                    });
                }
            );

        });

        $('#set-agent_biding').on('click', function(){
            layer.open({
                skin: 'loginBox',
                title:'设置代理价',
                type: 1,
                content: $('#set-proxy-price').html()
            });
            <?php if(!empty($proxyPrice)){
            ?>
                $('input[name=proxy-price]:visible').val('<?php echo $proxyPrice; ?>');
            <?php
            } ?>

        });
        $(document).on('click', '#set-proxy-price-btn', function(){
            var data = {};
            data.productID = <?php echo $productInfo['productID'] ?>;
            data.proxyPrice = $('input[name=proxy-price]:visible').val();
            $.ajax({
                url : '/auction/set-proxy-price',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg, function(){location.reload();});
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });
    });

    function initEvent() {
        $('#detailed-xx-down').delegate('[data-role="addres"]', 'click', function (event) {
            console.log('[data-role="addres"]');
        });
        //产品详情介绍的tab
        $('.detailed-xx-top').delegate('a', 'click', function () {
            $(this).addClass('on').siblings().removeClass('on');
            var J_index = $(this).index();
            var J_detailed_xx_down = $('#detailed-xx-down .shop-show-item');
            J_detailed_xx_down.hide();
            J_detailed_xx_down.eq(J_index).show();
            if(J_index == 2){
                iframeHeight('iframepage1');
            }else if(J_index == 3){
                iframeHeight('iframepage2');
            }


        });
    }


</script>