
<link rel="stylesheet" href="/dist/styles/main/index.css?v=1" media="screen" type="text/css" />
<div class="center">
    <div class="main-ad-box">

        <div class="mainad left">

            <div class="slideBox">
                <div class="hd">
                    <ul>
                        <?php
                            foreach($leftAds as $v){
                        ?>
                                <li></li>
                        <?php
                            }
                        ?>
                    </ul>
                </div>
                <div class="bd">
                    <ul>
                        <?php
                            foreach($leftAds as $v){
                        ?>
                                <li>
                                    <a href="<?php echo $v['url']; ?>" target="_blank">
                                        <img src="<?php echo $v['img'];?>"/>
                                    </a>
                                </li>
                        <?php
                            }
                        ?>
                    </ul>
                </div>

                <!-- 下面是前/后按钮代码，如果不需要删除即可 -->
                <a class="prev" href="javascript:void(0)"></a>
                <a class="next" href="javascript:void(0)"></a>

            </div>

        </div>
        <div class="mainad right">

            <div class="slideBox">
                <div class="hd">
                    <ul>
                        <?php
                        foreach($rightAds as $v){
                        ?>
                            <li></li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>
                <div class="bd">
                    <ul>
                        <?php
                        foreach($rightAds as $v){
                        ?>
                            <li>
                                <a href="<?php echo $v['url']; ?>" target="_blank">
                                    <img src="<?php echo $v['img'];?>"/>
                                </a>
                            </li>
                        <?php
                        }
                        ?>
                    </ul>
                </div>

                <a class="prev" href="javascript:void(0)"></a>
                <a class="next" href="javascript:void(0)"></a>

            </div>
        </div>
    </div>
</div>
<!--广告 end-->
<!--main开始-->
<div class="kp_main">
    <div class="center ">

        <!--分类-->
        <div id="main-content">
            <?php if(!empty($categoryInfo)){
            ?>
                <div class="fl_liebie">分类拍品 > <?php echo $categoryInfo['categoryName']; ?></div>
                <div class="fl_shaixuan">
                    <div class="fl_shaixuan_left">筛选></div>
                    <div class="fl_shaixuan_right">
                        <?php
                        foreach($options as $v){
                            ?>
                            <ul>
                                <li class="fl_tc">
                                    <a href="javascript:;">
                                    <?php echo $v['filterName'] ?>
                                    </a>
                                </li>
                                <?php
                                if(!empty($v['options'])){
                                    foreach($v['options'] as $sv) {
                                        ?>
                                        <li class="fl_li_other">
                                            <a href="javascript:;" class="product-category-filter-option" product-category-filter-option-id="<?php echo $sv['optionID']; ?>"><?php echo $sv['optionName'] ?></a>
                                        </li>
                                    <?php
                                    }
                                }
                                ?>
                            </ul>
                        <?php
                        }
                        ?>
                    </div>
                </div>
            <?php
            } ?>

            <div class="fl_zhuangtai">
                <ul>
                    <li>状态></li>
                    <li>
                        <a href="javascript:;" class="product-status" status="all">全部</a>
                    </li>
                    <li>
                        <a href="javascript:;" class="product-status" status="processing">正在进行</a>
                    </li>
                    <li>
                        <a href="javascript:;" class="product-status" status="coming">即将开始</a>
                    </li>
                </ul>
            </div>
            <div class="sf_jiage">
                价格区间
                <input class="mt_input" type="text" placeholder="" id="price-begin">
                —
                <input class="mt_input" type="text" placeholder="" id="price-end">
<span class="sf_btn">
  <a href="javascript:;" id="price-search-btn">确定</a>
</span>
                <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-auction-auth">
                有文物拍卖资质
                <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-cover-delivery">
                包邮
                <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-refund-in-days">
                3天包退
                <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-certificate-card">
                鉴定证书
                <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-author-auth">作者授权
                <!--<input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox " id="is-fidelity">是否保真-->
            </div>
            <div class="sf_paixu">
                <ul>
                    <li>
                        <a href="javascript:;" id="sort-default">默认</a>
                    </li>
                    <li>
                        <a href="javascript:;" id="sort-endTime">
                            结拍时间
                            <img src="/yaoqin/images/ss_03.jpg"></a>
                    </li>
                    <li>
                        <a href="javascript:;" id="sort-price">
                            价格
                            <img src="/yaoqin/images/ss_03.jpg"></a>
                    </li>
                    <li>
                        <a href="javascript:;" id="sort-interest">关注度</a>
                    </li>

                    <li class="tpli">
                        <a href="/product/index?show=pic&productCategoryID=<?php echo $productCategoryID; ?>">
                            显示图片
                            <img src="/yaoqin/images/ss_05.jpg"></a>
                    </li>
                    <li class="">
                        <a href="/product/index?show=list&productCategoryID=<?php echo $productCategoryID; ?>">
                            列表显示
                            <img src="/yaoqin/images/ss_07.jpg"></a>
                    </li>
                    <li>
                        <a href="">合并店铺</a>
                    </li>
                    <li class="ym ym1">页码</li>
                    <li class="ym">
                        <a href="javascript:;" id="preview-page">
                            <img src="/yaoqin/images/a_03.jpg"></a>
                    </li>
                    <li class="ym" id="products-page">0/<em id="total-page">0</em></li>
                    <li class="ym">
                        <a href="javascript:;", id="next-page">
                            <img src="/yaoqin/images/a_05.jpg"></a>
                    </li>
                </ul>
            </div>
        </div>

    </div>

    <div class="center mt20">
        <div class="index-box clearfix">
            <div class="indexBox-left fl" id="products">

            </div>
            <div class="indexBox-right fr">
                <h2 class="leftBox-tit">热推店铺街</h2>
                <ul class="indexBox-right-list">
                    <?php
                        foreach($stores as $v){
                    ?>
                            <li>
                                <h3 style="cursor: pointer;" onclick="location.href='/store/detail?storeID=<?php echo $v['storeID']; ?>';"><em><img src="<?php echo $v['storeLogo'] ?>"></em><span><?php echo $v['storeName'] ?> ></span></h3>

                                <p class="indexBox-right-info"><?php echo $v['storeSignature']; ?></p>
                            </li>
                    <?php
                        }
                    ?>
                </ul>
            </div>
        </div>
    </div>
</div>

<?php if(!empty($productIndexRecommendProducts)){ ?>
<div class="center">
    <div class="probot-ad">
        <div class="bd">
            <ul class="picList">
                <?php
                    foreach($productIndexRecommendProducts as $v){
                ?>
                        <li>
                            <div class="pic"><a href="/product/detail?productID=<?php echo $v['productID'] ?>"target="_blank"><img src="<?php echo $v['listImg'] ?>" /></a></div>
                            <div class="ad-bg"></div>
                            <div class="title"><a href="/product/detail?productID=<?php echo $v['productID'] ?>" target="_blank"><?php echo $v['productName'] ?></a></div>
                        </li>
                <?php
                    }
                ?>
            </ul>
        </div>
    </div>

</div>
<?php } ?>
<script type="text/javascript">
    $(function(){
        $(".slideBox").slide({
            mainCell: ".bd ul",
            autoPlay: true,
            effect: "left",
            delayTime: 700
        });

        var params = {
            pageNum : 1,
            limit : 18,
            order : 'default',
            sort : 'desc',
            priceBegin : '',
            priceEnd : '',
            isAuctionAuth : 0,
            isCoverDelivery : 0,
            isRefundInDays : 0,
            isCertificateCard : 0,
            isAuthorAuth : 0,
            status : 'all',
            scroll : 0
        }
        function refresh(params){
            if($('#is-auction-auth').is(':checked')){
                params.isAuctionAuth = 1;
            }else{
                params.isAuctionAuth = 0;
            }
            if($('#is-cover-delivery').is(':checked')){
                params.isCoverDelivery = 1;
            }else{
                params.isCoverDelivery = 0;
            }
            if($('#is-refund-in-days').is(':checked')){
                params.isRefundInDays = 1;
            }else{
                params.isRefundInDays = 0;
            }
            if($('#is-certificate-card').is(':checked')){
                params.isCertificateCard = 1;
            }else{
                params.isCertificateCard = 0;
            }
            if($('#is-author-auth').is(':checked')){
                params.isAuthorAuth = 1;
            }else{
                params.isAuthorAuth = 0;
            }
            if($('#is-fidelity').is(':checked')){
                params.fidelity = 1;
            }else{
                params.fidelity = 0;
            }

            if($('.product-status.hover').length){
                params.status = $('.product-status.hover').attr('status');
            }
            if($('.product-category-filter-option.hover').length){
                var filterOptions = new Array();
                $('.product-category-filter-option.hover').each(function(){
                    filterOptions.push($(this).attr('product-category-filter-option-id'));
                });
                params.productCategoryFilterOptionID = filterOptions;
            }
            params.priceBegin = $('#price-begin').val();
            params.priceEnd = $('#price-end').val();
            params.productCategoryID = '<?php echo $categoryInfo['productCategoryID']; ?>';
            params.search = '<?php echo $search; ?>';
            params.show = '<?php echo $show; ?>';
            $.ajax({
                type : 'post',
                url : '/product/list',
                data : params,
                success : function(data){
                    $('#products').html(data);
                }
            });
            if(params.scroll){
                $('html,body').animate({scrollTop: $("#main-content").offset().top}, 500);
            }

        }


        $('#preview-page').on('click', function(){
            params.pageNum = params.pageNum - 1;
            if(params.pageNum > 0) {
                refresh(params);
            }else{
                params.pageNum = 1;
            }
        });
        $('#next-page').on('click', function(){

            params.pageNum = params.pageNum + 1;
            var totalPage = parseInt($('#total-page').html());

            if(params.pageNum <= totalPage) {
                refresh(params);
            }else{
                params.pageNum = totalPage;
            }
        });
        $('#sort-default').on('click', function(){
            params.order = 'default';
            if(params.sort == 'desc') {
                params.sort = 'asc';
            }else{
                params.sort = 'desc';
            }
            refresh(params)
        });
        $('#sort-endTime').on('click', function(){
            params.order = 'endTime';
            if(params.sort == 'desc') {
                params.sort = 'asc';
            }else{
                params.sort = 'desc';
            }
            refresh(params)
        });
        $('#sort-price').on('click', function(){
            params.order = 'price';
            if(params.sort == 'desc') {
                params.sort = 'asc';
            }else{
                params.sort = 'desc';
            }
            refresh(params)
        });
        $('#sort-interest').on('click', function(){
            params.order = 'interest';
            if(params.sort == 'desc') {
                params.sort = 'asc';
            }else{
                params.sort = 'desc';
            }
            refresh(params)
        });
        $('#is-auction-auth').on('change', function(){
            refresh(params)
        });
        $('#is-cover-delivery').on('change', function(){
            refresh(params)
        });
        $('#is-refund-in-days').on('change', function(){
            refresh(params)
        });
        $('#is-certificate-card').on('change', function(){
            refresh(params)
        });
        $('#is-author-auth').on('change', function(){
            refresh(params)
        });
        $('#is-fidelity').on('change', function(){
            refresh(params)
        });
        $('#price-search-btn').on('click', function(){
            refresh(params)
        });
        $('.product-category-filter-option').on('click', function(){
            $(this).parent().siblings().each(function(){
                $(this).find('a').removeClass('hover');
            });
            $(this).addClass('hover');
            refresh(params)
        });
        $('.product-status').on('click', function(){
            $(this).parent().siblings().each(function(){
                $(this).find('a').removeClass('hover');
            })
            $(this).addClass('hover');
            refresh(params);
        });
        refresh(params);


        $(".probot-ad").slide({mainCell:".bd ul",autoPlay:true,effect:"leftMarquee",vis:4,interTime:10});



        $(document).on('click', '.paginate-front-page', function(){
            params.pageNum = 1;
            params.scroll = 1;
            refresh(params);
        });
        $(document).on('click', '.paginate-preview-page', function(){
            params.scroll = 1;
            params.pageNum = params.pageNum - 1;
            if(params.pageNum <= 0) params.pageNum = 1;

            refresh(params);

        });
        $(document).on('click', '.paginate-page', function(){
            $(this).addClass('selected').siblings().removeClass('selected');
            params.pageNum = parseInt($(this).html());
            params.scroll = 1;
            refresh(params);
        });
        $(document).on('click', '.paginate-next-page', function(){
            params.scroll = 1;
            params.pageNum = params.pageNum + 1;
            var totalPages = parseInt($(this).attr('total-pages'));
            if(params.pageNum > totalPages) params.pageNum = totalPages;
            refresh(params);
        });
        $(document).on('click', '.paginate-rear-page', function(){
            params.pageNum = parseInt($(this).attr('total-pages'));
            params.scroll = 1;
            refresh(params);
        });
        $(document).on('click', '.redirect-paginate-num-btn', function(){

            var pageNum = $('#redirect-paginate-num').val();
            pageNum = parseInt(pageNum);
            var totalPages = parseInt($(this).attr('total-pages'));
            if(pageNum < 1 || pageNum > totalPages){
                layer.alert('请输入正确的页数');
                return false;
            }
            params.pageNum = pageNum;
            params.scroll = 1;
            refresh(params);
        });
    })

</script>