<?php if($show == 'pic' || empty($show)) { ?>

    <ul class="indexPro">
        <?php
        foreach ($products as $v) {
            ?>
            <?php if ($v['auctionStatus'] == 1) {
                ?>
                <li class="start" onclick="window.open('/product/detail?productID=<?php echo $v['productID']; ?>');">
                    <h3><?php echo $v['productName'] ?></h3>

                    <p class="indexPro-price">
                        起拍价 <em>￥<?php echo $v['currPrice'] ?></em>
                    </p>

                    <p class="indexPro-time"><?php echo date('m月d日 H:i', $v['startTime']) ?> 开拍</p>

                    <div class="indexPro-img">
                        <img src="<?php echo $v['listImg']; ?>">

                        <p class="indexPro-num"><em><?php echo $v['auctionCount'] ?></em>
                            次出价
                        </p>
                    </div>
                </li>
            <?php
            } else {

                ?>
                <li onclick="window.open('/product/detail?productID=<?php echo $v['productID']; ?>');">
                    <h3><?php echo $v['productName'] ?></h3>

                    <p class="indexPro-price">
                        当前价 <em>￥<?php echo $v['currPrice'] ?></em>
                    </p>

                    <p class="indexPro-time">距结束 <span class="yomibox2"
                                                       data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>"></span>
                    </p>

                    <div class="indexPro-img">
                        <img src="<?php echo $v['listImg']; ?>">

                        <p class="indexPro-num"><em><?php echo $v['auctionCount'] ?></em>
                            次出价
                        </p>
                    </div>
                </li>
            <?php
            } ?>

        <?php
        }
        ?>

    </ul>
<?php
}else{
?>
    <dl class="proTextList">
        <dt>
            <span class="item1">类别</span>
            <span class="item2">拍品</span>
            <span class="item3">当前价</span>
            <span class="item4">拍卖时间</span>
        </dt>

        <?php
        foreach ($products as $v) {
            ?>
            <?php if ($v['auctionStatus'] == 1) {
                ?>
                <dd class="status2">
                    <span class="item1"><?php echo $v['categoryName'] ?></span>
                    <span class="item2" style="cursor:pointer;" onclick="window.open('/product/detail?productID=<?php echo $v['productID']; ?>');"><?php echo $v['productName'] ?></span>
                    <span class="item3">￥<?php echo $v['currPrice'] ?></span>
                    <span class="item4">开始时间：<em><?php echo date('Y-m-d H:i:s', $v['startTime']); ?></em></span>
                </dd>
            <?php
            } else {

                ?>
                <dd>
                    <span class="item1"><?php echo $v['categoryName'] ?></span>
                    <span class="item2" style="cursor:pointer;" onclick="window.open('/product/detail?productID=<?php echo $v['productID']; ?>');"><?php echo $v['productName'] ?></span>
                    <span class="item3">￥<?php echo $v['currPrice'] ?></span>
                    <span class="item4">距结束：<em class="yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>"></em></span>
                </dd>
            <?php
            } ?>

        <?php
        }
        ?>
    </dl>

<?php
}
?>

<script>
    $(function(){
        if($('#products-page').length){
            $('#products-page').html('<?php echo $currPage; ?>/<em id="total-page"><?php echo $productsPage ?></em>');
        }

        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'product-list');
        });
    })
</script>