<link rel="stylesheet" type="text/css" href="/dist/styles/main/good.css" media="screen" />
<div class="center">
    <div class="s-nav">
        拍品预览
    </div>

    <!--产品详细 start-->
    <div class="cpxx">
        <!--左侧图片展示区域-->
        <div class="zoom-section">
            <div class="zoom-small-image">
                <div class="xtj-zdzb"></div>
                <img class="cloudzoom" src="<?php echo $productInfo['listImg'] ?>"
                     id="zoom1"
                     data-cloudzoom="zoomImage: '<?php echo $productInfo['listImg'] ?>',zoomSizeMode:'zoom'"/>
            </div>
            <div class="zoom-desc">
                <p>
                    <?php
                    foreach($detailImgs as $v){
                        ?>
                        <img class="cloudzoom-gallery zoom-tiny-image"
                             src="<?php echo $v; ?>"
                             alt=""
                             data-cloudzoom="useZoom: '#zoom1', image: '<?php echo $v; ?>', zoomImage: '<?php echo $v; ?>',zoomSizeMode:'zoom'"/>
                    <?php
                    }
                    ?>
            </div>
            <div class="clear"></div>
        </div>
        <!-- 左侧图片展示区域结束 -->

        <!--中间详情 start-->
        <div class="cpxx-c">
            <!--top start-->
            <div class="cpxx-c-top">
                <h2><?php echo $productInfo['productName'] ?></h2>
            </div>
            <!--top end-->
            <!--start detailed-price-->
            <div class="detailed-price cpxx-c-c">
                <dl>
                    <dt class="present-price">当前价格：</dt>
                    <dd>
                        ￥
                        <span class="f30"><?php echo $productInfo['currPrice']; ?></span>
                    </dd>
                </dl>
            </div>
            <!--end detailed-price-->
            <div class="cpxx-sjxx">
                <ul>
                    <li>起拍价：￥<?php echo $productInfo['startPrice']; ?></li>
                    <li>
                        加价幅度：￥
                        <span id="specialIncreaseRange"><?php echo $productInfo['auctionPerPrice']; ?></span>
                    </li>
                    <?php if(!empty($productInfo['commision'])){
                        ?>
                        <li>佣金：<?php echo $productInfo['commision']; ?>%</li>
                    <?php
                    }else{
                        ?>
                        <li>佣金：￥0</li>
                    <?php
                    } ?>

                    <!--<li>保留价：<?php /*if(!empty($productInfo['existKeepPrice'])){echo '有';}else{echo '无';} */?></li>-->
                    <li>延时周期：<?php if($productInfo['delayType'] == 1){echo '5分/次';}else{echo '无';} ?></li>
                    <li>邮费：￥<?php echo !empty($productInfo['deliveryPrice']) ? $productInfo['deliveryPrice'] : 0;?></li>
                    <li>
                        商家：
                        <a ui-sref="mainShop({'id':14})" class="blue" href="/store/detail?storeID=<?php echo $productInfo['storeID'] ?>"><?php echo $productInfo['storeName'] ?></a>
                    </li>
                </ul>
            </div>

            <div class="cpxx-sjxxd">
                <p>
                    特色服务：

                    <?php if(!empty($productInfo['auctionAuth'])){
                        ?>
                        <span>
                        <i></i>
                        文物拍卖资质
                    </span>
                    <?php
                    } ?>
                    <?php /*if(!empty($productInfo['fidelity'])){
                        */?><!--
                        <span>
                        <i></i>
                        保真
                    </span>
                    --><?php
/*                    }*/ ?>
                    <?php if(!empty($productInfo['certificateCard'])){
                        ?>
                        <span>
                        <i></i>
                        省级资质机构以上鉴定证书
                    </span>
                    <?php
                    } ?>
                    <?php if(!empty($productInfo['authorAuth'])){
                        ?>
                        <span>
                        <i></i>
                        作者授权
                    </span>
                    <?php
                    } ?>
                    <?php if(!empty($productInfo['refundInDays'])){
                        ?>
                        <span>
                        <i></i>
                        三日内可退
                    </span>
                    <?php
                    } ?>

                </p>
                <p>
                    <a qq="<?php echo $productInfo['storeqq'] ?>" href="javascript:;" class="tencent-qq" style="color:#ad0015">在线咨询</a>
                    <span class="fr">中国 <?php echo $productInfo['deliveryRegionInfo']['provinceName']  ?> <?php echo $productInfo['deliveryRegionInfo']['cityName'] ?></span>
                </p>

                <p class="collection">
                    <a class="collection-p" href="javascript:;" id="interest-product"><?php echo !empty($interestProduct) ? '取消关注' : '关注拍品';?></a>
                    <a class="collection-d" href="javascript:;" id="interest-store"><?php echo !empty($interestStore) ? '取消关注' : '关注店铺';?></a>
                </p>
            </div>
        </div>
        <!--中间详情 end-->
        <!--右侧出价记录 start-->
        <div class="cpxx-bidrecord">
            <div class="cpxx-bidrecord-top"><b>出价记录
                    <span class="red" id="rightbidtotal">(0)</span></b>
            </div>
            <ul id="rightbid">
                <li style="color:#333">
                    <span class="num_02">竞拍人</span>
                    <span class="num_03">价格</span>
                    <span class="num_04">时间</span>
                </li>
                <!--<div class="cpxx-ckmore">查看全部出价</div>-->
            </ul>

        </div>
        <!--end 右侧出价记录-->
    </div>
    <!--end 产品详细-->
    <div class="center cpxxy">
        <!--相关推荐 start-->
        <div class="rnav">

            <div class="rnav-tit">
                相关推荐
            </div>
            <ul class="rnav-list">

            </ul>
        </div>
        <!--相关推荐 end-->

        <!--底部 left start-->
        <div class="cpxx-left">
            <!--start 竞拍流程-->
            <div class="detailed-step">
                <span>竞拍流程：</span>
                <dl>
                    <dt>
                        <i class="icon2"></i>
                    </dt>
                    <dd>出价竞拍</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon3"></i>
                    </dt>
                    <dd>竞拍成功</dd>
                </dl>
                <dl>
                    <dt>
                        <i class="icon4"></i>
                    </dt>
                    <dd>支付款项</dd>
                </dl>
                <dl style="background:none; padding:0px;">
                    <dt>
                        <i class="icon5"></i>
                    </dt>
                    <dd>签收货物</dd>
                </dl>

            </div>
            <!--end 竞拍流程-->

            <!--left 拍品描述 start-->
            <div class="detailed-xx" id="cjjlxtj">
                <!--detailed-xx-top start-->
                <div class="detailed-xx-top">
                    <a class="on" href="javascript:void(0)" target="_self">拍品描述</a>
                    <a href="javascript:void(0)" target="_self" class="cjjlxx">
                        出价记录
                        <span class="red">(0)</span>
                    </a>
                    <a href="javascript:void(0)" target="_self">竞拍须知</a>
                    <a href="javascript:void(0)" target="_self">服务保障</a>
                </div>
                <!--detailed-xx-top end-->
                <!--detailed-xx-down start-->
                <div class="detailed-xx-down" id="detailed-xx-down">
                    <!----start 拍品描述-->
                    <div class="xtj-ppms lstpp shop-show-item">
                        <!--detailed-xx-ul start-->
                        <div
                            style="border:1px solid #dbcca3;background-color:#ede5d1;color:#a47f1a;padding:8px;margin-top:20px;margin-bottom:20px">


                            <p>
                                [友情提醒]<br>
                                <?php echo $_siteSettings['friendlyNotification']; ?>
                            </p>
                        </div>

                        <div class="detailed-xx-ultitle"><b>商品属性</b>
                        </div>


                        <ul class="detailed-xx-ul">
                            <?php
                            foreach($properties as $v){
                                ?>
                                <li>
                                    <?php
                                    foreach($v as $sv){
                                        ?>
                                        <p>
                                            <span><?php echo $sv['propertyName'] ?></span>
                                            <?php echo $sv['value'] ?>
                                        </p>
                                    <?php
                                    }
                                    ?>
                                </li>
                            <?php
                            }
                            ?>
                        </ul>
                        <!--detailed-xx-ul start-->
                        <!--产品图 start-->
                        <div class="detailed-xx-ultitle">
                            <b>拍品详情</b>
                        </div>
                        <div class="product-detail">
                            <iframe frameborder="no" border="0" scrolling="no" src="/product/pre-view-detail?productID=<?php echo $productInfo['productID'] ?>" width="100%" id="iframepage" name="iframepage" onload="iframeHeight('iframepage');">
                            </iframe>
                        </div>

                        <!--产品图 end-->
                    </div>

                    <!----start 拍品描述-->
                    <!--出价记录 start-->
                    <div class="detailed-xx-cjjl  shop-show-item">
                        <ul>
                            <li class="bg">
                                <span class="num_02">竞拍人</span>
                                <span class="num_03">价格</span>
                                <span class="num_04">时间</span>
                            </li>
                        </ul>
                    </div>
                    <!----出价记录 end-->
                    <!--竞拍须知 start-->
                    <div class="xtj-jpxz shop-show-item" style="display: none;">
                        <iframe frameborder="no" border="0" scrolling="no" src="/article/setting-detail?settingName=biddingKnow" width="100%" id="iframepage1" name="iframepage1" onload="iframeHeight('iframepage1');">
                        </iframe>
                    <!--end 竞拍须知-->

                    <!--服务保障 start-->
                    <div class="detailed-service shop-show-item" style="display: none;">
                        <iframe frameborder="no" border="0" scrolling="no" src="/article/setting-detail?settingName=serviceProtocol" width="100%" id="iframepage2" name="iframepage2" onload="iframeHeight('iframepage2');">
                        </iframe>
                    </div>
                    <!--服务保障 end-->
                </div>

            </div>
        </div>
    </div>
</div>
<?php
echo $this->inlineScript()->appendFile('/plugins/CloudZoom/cloudzoom.js');
?>
<script type="text/javascript">
    $(function () {
        //产品详情图片展示
        CloudZoom.quickStart();
        _PageTag = "detail";
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, _PageTag);
        });
        initEvent();
    });
    function initEvent() {
        $('#detailed-xx-down').delegate('[data-role="addres"]', 'click', function (event) {
            console.log('[data-role="addres"]');
        });
        //产品详情介绍的tab
        $('.detailed-xx-top').delegate('a', 'click', function () {
            $(this).addClass('on').siblings().removeClass('on');
            var J_index = $(this).index();
            var J_detailed_xx_down = $('#detailed-xx-down .shop-show-item');
            J_detailed_xx_down.hide();
            J_detailed_xx_down.eq(J_index).show();


        });
    }


</script>