<div id="set-proxy-price" class="hide">
    <div class="commonPop fr">
        <form method="post">
            <div class="inputBox">
                <input name="proxy-price" placeholder="请输入金额" type="text" value=""/>
            </div>
            <input id="set-proxy-price-btn" type="button" class="submit" value="设置">

            <p>
                1. 当您设置了代理竞价后, 只要有其他用户出价, 系统便会自动为您出价。每次出价都是在当前价格上加一口价。每一口价的具体金额由当前的竞价阶梯决定。<br />
                2. 当您已经当前最高价, 系统会自动停止出价。当竞价价格超出您设置的代理价, 则代理竞价失效, 您可以重新设置代理竞价。<br />
                3. 在代理竞价期间, 您也可以手动出价, 一旦手动出价成功, 之前您设置的竞价便会失效, 您可以重新设置代理价。如果手动出价失败, 则之前您设置的代理竞价会继续有效。
            </p>
        </form>
    </div>
</div>