<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/order/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'orderID',
                title: '订单ID',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'productName',
                title: '商品名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeID',
                title: '店铺ID',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'storeName',
                title: '店铺名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'nickName',
                title: '用户名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'mobile',
                title: '用户手机号',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'payMoney',
                title: '支付金额',
                align: 'center',
                valign: 'middle',
                width:200

            },/*{
                field: 'finalPayMoney',
                title: '尾款金额',
                align: 'center',
                valign: 'middle',
                width:200

            },*/
            {
                field: 'businessID',
                title: '订单业务号',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'unitePayID',
                title: '订单支付号',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'isComplained',
                title: '是否被申诉',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    var str = '';
                    if(value == 1){
                        str += '<font style="color:red;">是</font>';
                    }else{
                        str += '否';
                    }
                    return str;
                }
            },
            {
                field: 'payType',
                title: '支付方式',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, row, index){
                    var s = '';
                    if(value == 1){
                        s += '余额';
                    }else if(value == 2){
                        s += '支付宝';
                    }else if(value == 3){
                        s += '银联';
                    }else if(value == 4){
                        s += '银行转账';
                        if(row.orderStatus == 1){
                            s += '<a title="确认到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/<?=$this->layout()->controllerName;?>/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=1"><i class="glyphicon glyphicon-ok"></i></a>';
                        }/*else if(row.orderStatus == 5 && row.orderType == 2){
                            s += '<a title="确认尾款到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/<?=$this->layout()->controllerName;?>/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=4"><i class="glyphicon glyphicon-ok"></i></a>';
                        }*/
                    }

                    return s;
                }

            },{
                field: 'orderStatus',
                title: '订单状态',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter : function(value, row, index){
                    var s = '';
                    if(value == 1){
                        s += '待付款'
                    }else if(value == 2){
                        s += '已付定金';
                    }else if(value == 3){
                        s += '已付全款';
                    }else if(value == 4){
                        s += '已发货'
                    }else if(value == 5){
                        s += '已收货'
                    }else if(value == 6){
                        s += '已付全款'
                    }else if(value == -1){
                        s += '已关闭'
                    }

                    return s;
                }

            }
            ]
    });

</script>
