
<div class="wrapper" id="page-wrapper">

    <div id="table_toolbar">
        <div class="pull-left">
            <a  class="btn btn-primary" href="/admin/notification/add"><i class="fa fa-pencil"></i>推送</a>
        </div>
    </div>
    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>
</div>

<script type="text/javascript">
    $(function(){

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?=$this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: false,
            showColumns: false,
            showRefresh: false,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'notificationID',
                title: '推送ID',
                align: 'center',
                valign: 'middle'
                /*sortable: true*/
            }, {
                field: 'memberID',
                title: '类型',
                align: 'center',
                valign: 'middle',
                formatter : function(value, row, index){
                    if(value){
                        return '单个用户';
                    }else{
                        return '所有用户';
                    }
                }
            },{
                field: 'nickName',
                title: '用户昵称',
                align: 'center',
                valign: 'middle'
            },{
                field: 'content',
                title: '内容',
                align: 'center',
                valign: 'middle',
                width: 600
            },{
                field: 'instime',
                title: '推送时间',
                align: 'center',
                valign: 'middle'
            }]
        });
    });
</script>