<div class="hot-shopAd mb20">
    <div class="center"><a href="/">首页</a> > 热门店铺街</div>
</div>
<div class="center">
    <ul class="hot-shopAd-list clearfix">
        <?php
            foreach($hotStores as $v){
        ?>
                <li>
                    <img class="lazy" data-original="<?php echo $v['storeLogo']; ?>" alt="">

                    <div class="fr">
                        <h5><?php echo $v['storeName']; ?></h5>

                        <p>
                            <?php echo $v['storeSignature']; ?>
                        </p>
                    </div>
                </li>
        <?php
            }
        ?>
    </ul>
    <?php
        echo $this->render('/front/common/paginate', array('url' => '/index/hot-stores?', 'pages' => $pages));
    ?>

</div>