<link rel="stylesheet" href="/dist/styles/main/index.css" media="screen" type="text/css" />
<div id="slideBoxx" class="slideBoxx">
    <div class="center ">
        <div class="pop-zhuangchang">
            <a href="/special/today">专场拍卖会</a>
        </div>
        <div class="pop-datatit pa">
            按日期搜索专场
        </div>
        <div class="date-pop"></div>
    </div>
    <div class="hd" style="width:140px;">
        <ul>
            <?php
            foreach($banners as $v){
                ?>
                <li></li>
            <?php
            }
            ?>
        </ul>
    </div>
    <div class="bd" data-clk="200120">
        <ul>
            <?php
                foreach($banners as $v){
            ?>
                    <li>
                        <a href="<?php echo $v['url']; ?>" target="_blank" ui-sref="zhuanchangMain" title="<?php echo $v['alt']; ?>">
                        <img src="<?php echo $v['img']; ?>"></a>
                    </li>
            <?php
                }
            ?>

        </ul>
    </div>

    <div class="prev" href="javascript:void(0)"></div>
    <div class="next" href="javascript:void(0)"></div>

</div>

<!-- ad end -->
<!--end 横屏-->
<div class="center main-ad-top">
    <div class="main-tymj left" style="background-image: url('<?php echo $_siteSettings['tymj']?>');cursor: pointer;" onclick="location.href='/customization/index';">
    </div>
    <div class="main-qltj left ml10" style="background-image : url('<?php echo $_siteSettings['qltj'] ?>');cursor: pointer;" onclick="location.href='/artist/recommend';">
    </div>
    <div class="main-tjgg right">
        <div class="slideBox">
            <div class="hd">
                <ul>
                    <?php foreach($indexSecondAd as $v){
                    ?>
                        <li></li>
                    <?php

                    } ?>
                </ul>
            </div>
            <div class="bd">
                <ul>
                    <?php foreach($indexSecondAd as $v){
                    ?>
                        <li>
                            <a href="<?php echo $v['url'] ?>" target="_blank">
                                <img src="<?php echo $v['img']; ?>"/>
                            </a>
                        </li>
                    <?php

                    } ?>
                </ul>
            </div>

            <!-- 下面是前/后按钮代码，如果不需要删除即可 -->
            <a class="prev" href="javascript:void(0)"></a>
            <a class="next" href="javascript:void(0)"></a>

        </div>
    </div>
</div>
<div class="center clearfix">
    <div class="main-newsBox mt10">
        <?php
            foreach($indexRecommendArticles as $v){
        ?>
                <div class="news-item1">
                    <a href="<?php if(!empty($v['url'])){echo $v['url'];}else{ ?>/article/detail?articleID=<?php echo $v['articleID'] ?><?php } ?>"><h4><?php echo $v['articleName'] ?></h4>

                        <p class="news-item1-infotxt">
                            <?php echo $v['articleContent'] ?>
                        </p>
                        ……
                    </a>
                </div>
        <?php
            }
        ?>

        <ul class="news-list">
            <?php
                foreach($indexArticleList as $v){
            ?>
                    <li><a href="/article/index?articleCategoryID=<?php echo $v['articleCategoryID']; ?>" class="news-cate">[<?php echo $v['categoryName'] ?>]</a><a href="<?php if(!empty($v['url'])){echo $v['url'];}else{?>/article/detail?articleID=<?php echo $v['articleID'] ?><?php } ?>"><?php echo $v['articleName']; ?></a></li>
            <?php
                }
            ?>

            <li><a href="/article/index" class="more">更多>></a></li>
        </ul>

    </div>
</div>
<!--广告 start-->
<div class="center">
    <div class="main-ad-box">

        <div class="mainad left">

            <div class="slideBox">
                <div class="hd">
                    <ul>
                        <?php foreach($indexThirdLeftAd as $v){
                        ?>
                            <li></li>
                        <?php

                        } ?>
                    </ul>
                </div>
                <div class="bd">
                    <ul>
                        <?php foreach($indexThirdLeftAd as $v){
                        ?>
                            <li>
                                <a href="<?php echo $v['url'] ?>" target="_blank">
                                    <img src="<?php echo $v['img'] ?>"/>
                                </a>
                            </li>
                        <?php

                        } ?>
                    </ul>
                </div>

                <!-- 下面是前/后按钮代码，如果不需要删除即可 -->
                <a class="prev" href="javascript:void(0)"></a>
                <a class="next" href="javascript:void(0)"></a>

            </div>

        </div>
        <div class="mainad right">

            <div class="slideBox">
                <div class="hd">
                    <ul>
                        <?php foreach($indexThirdRightAd as $v){
                            ?>
                            <li></li>
                        <?php

                        } ?>
                    </ul>
                </div>
                <div class="bd">
                    <ul>
                        <?php foreach($indexThirdRightAd as $v){
                        ?>
                            <li>
                                <a href="<?php echo $v['url'] ?>" target="_blank" >
                                    <img src="<?php echo $v['img'] ?>"/>
                                </a>
                            </li>
                        <?php

                        } ?>
                    </ul>
                </div>

                <a class="prev" href="javascript:void(0)"></a>
                <a class="next" href="javascript:void(0)"></a>

            </div>
        </div>
    </div>
</div>
<!--广告 end-->
<div class="center">
    <div class="index-box clearfix">
        <div class="indexBox-left fl">
            <?php echo $this->render('/front/product/list') ?>
        </div>
        <div class="indexBox-right fr">
            <h2 class="leftBox-tit">店铺一言坊</h2>
            <ul class="indexBox-right-list">
                <?php
                    foreach($stores as $v){
                ?>
                        <li>
                            <h3 style="cursor: pointer;" onclick="location.href='/store/detail?storeID=<?php echo $v['storeID']; ?>';"><em><img src="<?php echo $v['storeLogo'] ?>"></em><span><?php echo $v['storeName'] ?> ></span></h3>

                            <p class="indexBox-right-info"><?php echo $v['storeSignature']; ?></p>
                        </li>
                <?php
                    }
                ?>
            </ul>
        </div>
    </div>
</div>

<div class="friend-box clearfix">
    <div class="friend-tit">
        <div class="center">
            <div class="friend-titimg"></div>
        </div>
    </div>

    <ul class="center friendUl">
        <?php
            foreach($friendlyLinks as $v){
        ?>
                <li>
                    <a target="_blank" href="<?php echo $v['linkUrl']; ?>">
                        <img src="<?php echo $v['img'] ?>" alt="" style="width:154px;height: 60px;">
                    </a>
                </li>
        <?php
            }
        ?>
    </ul>

</div>