<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'special')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div>
                <span class="gl_cjzc"><a href="">创建专场 +</a></span>
            </div>

            <!-- 定时上架 -->
            <div class="ind_jrzc  ">
                <?php
                    echo $this->render('time');
                ?>
                <p class="kp_tsinfo1">注：专场拍卖时间固定为日场10:00-22:00，夜场22:00-次日10:00</p>

            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">所属类目</span>
                <select class="ind_dp1" id="special-product-category-id">
                    <?php
                        foreach($productCategories as $v){
                    ?>
                            <option value="<?php echo $v['productCategoryID'] ?>"><?php echo $v['categoryName']; ?></option>
                    <?php
                        }
                    ?>
                </select>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场标题</span>
                <input class="gl_ppinput" type="text" placeholder="限12字以内" id="special-name">
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场海报</span>
                <div class="dianpbai curfile" id="imghead1"><img src=""></div>
                <input type="file" class="fileEle" />尺寸：1920*300 图片容量不大于1M
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场首焦</span>
                <div class="dianpbai curfile" id="imghead2"><img src=""></div>
                <input type="file" class="fileEle" />尺寸：660*301 图片容量不大于1M
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">拍品数量</span>
                <input class="mt_input" type="text" placeholder="" id="product-count-limit"> 个 *限制20-60个
            </div>
            <div class="mt20  ycsd">
                <span class="ind_jrzz" style="float:left"><span class="bold">专场介绍 </span><br> <p class="gl_zyi">
                        注：图片宽度限制860以内</p></span>

                <div style="width:540px; background:#fff; float:left">
                    <script id="qqq" name="specialDesc" type="text/plain" style="width:700px;height:300px;"><?php if(!empty($specialInfo)){echo $specialInfo['specialDesc'];} ?></script>
                </div>
            </div>

            <div class="ind_licj" id="add-special-btn"><?php echo !empty($specialInfo) ? '提交修改' : '立即创建' ?></div>


        </div>


    </div>
</div>
<?php
echo $this->render('/front/common/pay');
echo $this->render('/front/common/transfer-account');
?>
<script type="text/javascript">
    var qqq = UE.getEditor('qqq');
    $(function(){
        //alert(1);

        /*$('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });*/
        <?php if(!empty($specialInfo)){
        ?>
                $('#start-time-year').val(<?php echo $specialInfo['startTimeYear'] ?>);
                $('#start-time-month').val(<?php echo $specialInfo['startTimeMonth'] ?>);
                $('#start-time-hour').val(<?php echo $specialInfo['startTimeHour'] ?>);
                $('#start-time-minute').val('<?php echo $specialInfo['startTimeMin'] ?>');
                $('#end-time-year').val(<?php echo $specialInfo['endTimeYear'] ?>);
                $('#end-time-month').val(<?php echo $specialInfo['endTimeMonth'] ?>);
                $('#end-time-hour').val(<?php echo $specialInfo['endTimeHour'] ?>);
                $('#end-time-minute').val('<?php echo $specialInfo['endTimeMin'] ?>');
                $('#special-product-category-id').val(<?php echo $specialInfo['specialProductCategoryID'] ?>);
                $('#special-name').val('<?php echo $specialInfo['specialName'] ?>');
                $('#imghead1').find('img').attr('src', '<?php echo $specialInfo['specialImg'] ?>');
                $('#imghead2').find('img').attr('src', '<?php echo $specialInfo['specialBanner'] ?>');
                $('#product-count-limit').val(<?php echo $specialInfo['productCountLimit'] ?>);

        <?php
        } ?>
    });

    $('#add-special-btn').on('click', function(){
        var data = {};
        <?php if(!empty($specialInfo)){

        ?>
                data.specialID = <?php echo $specialInfo['specialID'] ?>;
        <?php
        } ?>
        var specialStartTimeYear = $('#start-time-year').val();
        var specialStartTimeMonth = $('#start-time-month').val();
        var specialStartTimeDay = $('#start-time-day').val();
        var specialStartTimeHour = $('#start-time-hour').val();
        var specialStartTimeMinute = $('#start-time-minute').val();
        data.startTime = specialStartTimeYear + '-' + specialStartTimeMonth + '-' + specialStartTimeDay + ' ' + specialStartTimeHour + ':' + specialStartTimeMinute + ':00';
        var specialEndTimeYear = $('#end-time-year').val();
        var specialEndTimeMonth = $('#end-time-month').val();
        var specialEndTimeDay = $('#end-time-day').val();
        var specialEndTimeHour = $('#end-time-hour').val();
        var specialEndTimeMinute = $('#end-time-minute').val();
        data.endTime = specialEndTimeYear + '-' + specialEndTimeMonth + '-' + specialEndTimeDay + ' ' + specialEndTimeHour + ':' + specialEndTimeMinute + ':00';
        data.specialProductCategoryID = $('#special-product-category-id').val();
        data.specialName = $('#special-name').val();
        data.specialImg = $('#imghead1').find('img').attr('src');
        data.specialBanner = $('#imghead2').find('img').attr('src');
        data.productCountLimit = $('#product-count-limit').val();
        data.specialDesc = qqq.getContent();

        if(!data.specialName){
            layer.open({
                content : '请填写专场标题'
            });
            return false;
        }

        if(!data.specialImg){
            layer.open({
                content : '请上传专场海报图片'
            });
            return false;
        }

        if(!data.specialBanner){
            layer.open({
                content : '请上传专场首焦图片'
            });
            return false;
        }

        if(!data.productCountLimit){
            layer.open({
                content : '请填写拍品数量'
            });
            return false;
        }

        if(!data.specialDesc){
            layer.open({
                content : '请填写专场介绍'
            });
            return false;
        }


        $.ajax({
            url : '/member/add-special',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                if(res.flag > 0){
                    layer.alert(res.msg, function(){
                        location.href = '/member/special';
                    });
                }else{
                    layer.open({
                        content : res.msg
                    });
                }
            }
        });
    });
</script>