
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'add-product')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div>
                <span class="bold">所属类目</span>
                <select class="kp_year1 ml20" id="product-category-sel">
                    <?php foreach($productCategories as $v){
                    ?>
                        <option value="<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName'] ?></option>
                    <?php
                    } ?>
                </select>

                <span class="ind_x">*</span>
                <span class="ml20"><a href="javascript:;" class="category-introduction">类目说明 >></a></span>
            </div>
            <div class="ind_fg">
                <div><span class="ind_dx">单选</span><span class="ind_dx1">请仔细选择筛选项，以便有更大几率被搜索显示</span></div>
                <div id="add-product-category">

                </div>
            </div>
            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left ind_zpinfo_leftinfo bold">作品信息</div>
                <div class="ind_zpinfo_right" id="category-property-info">

                </div>
            </div>
            <div class="ind_ppbt "><span class="bold">拍品标题</span>
                <input id="product-name" class="ind_ppinput ind_uu" type="text" placeholder="请输入标题">
                <span class="ind_x"> *</span>
            </div>

            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left ind_zpinfo_lefta"><span class="bold">拍品图片 </span>

                    <div class="gl_zyi">注：<br>不超过4张限550kb以内, 宽大于等于400像素</div>
                </div>
                <input type="hidden" id="detail-imgs" />
                <div id="as"></div>
                <?php if(!empty($productInfo)){
                    ?>

                    <div style="width: <?php echo 180 * count($productInfo['detailImgs']); ?>px;" class="parentFileBox">
                        <ul class="fileBoxUl">
                            <?php foreach($productInfo['detailImgs'] as $v){
                                ?>
                                <li class="">
                                    <div class="viewThumb">
                                        <img src="<?php echo $v; ?>">
                                    </div>
                                    <div style="display: block;" class="diyCancel product-detail-img" product-id="<?php echo $productInfo['productID'] ?>" pic-val="<?php echo $v; ?>"></div>
                                </li>
                            <?php
                            } ?>

                        </ul>
                    </div>
                <?php
                } ?>
            </div>
            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left"><span class="bold">拍品详情</span>

                    <div class="gl_zyi">注：<br>图片宽度限840像素内。</div>
                    <!--<div class="ind_dnb"><a href="">电 脑 版</a></div>
                    <div class="ind_dnb1"><a href="">手 机 版</a></div>
                    <div class="ind_dnb2"><a href="">立即保存</a></div>-->
                </div>
                <div class="ind_zpinfo_right">
                    <div style="width:700px;  background:#fff">
                        <script id="qqq" name="productDetail" type="text/plain" style="width:700px;height:300px;"><?php if(!empty($productInfo)) echo $productInfo['productDetail']; ?></script>
                    </div>

                </div>
            </div>
            <p class="kp_tsinfo1 ">注：【店内分类】与【专场分类】只能选择进入一个。【店铺分类】最多选择三项，不选择进入默认“未分类”</p>

            <div class="mt30 ind_dash">
                <div class="" id="store-category-div">
                    <span class="ind_jrzz bold">店内分类</span>
                    <input checked name="Fruit" type="radio" class="ind_radio" value="1" id="store-category-radio"/>
                    <input type="checkbox" name="storeCategory1" value="checkbox" class="ind_checkbox store-category-chk" id="first-store-category-chk" >
                    <select class="ind_dp1" id="first-store-category">
                        <?php
                        foreach($storeCategory as $v){
                            ?>
                            <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                    <input type="checkbox" name="storeCategory2" value="checkbox" class="ind_checkbox store-category-chk" id="second-store-category-chk">
                    <select class="ind_dp1" id="second-store-category">
                        <?php
                        foreach($storeCategory as $v){
                            ?>
                            <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                    <input type="checkbox" name="storeCategory3" value="checkbox" class="ind_checkbox store-category-chk" id="third-store-category-chk">
                    <select class="ind_dp1" id="third-store-category">
                        <?php
                        foreach($storeCategory as $v){
                            ?>
                            <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="ind_jrzc">
                    <span class="ind_jrzz bold">进入专场</span>
                    <input name="Fruit" type="radio" class="ind_checkbox" value="2" id="join-special-radio" />
                    <select class="ind_dp1"  id="product-special-id">
                        <?php
                            foreach($specials as $v){
                        ?>
                                <option value="<?php echo $v['specialID'] ?>"><?php echo $v['specialName']; ?></option>
                        <?php
                            }
                        ?>
                    </select>
                </div>
            </div>


            <div class="ind_jrzc">
                <div>
                    <span class="ind_jrzz bold">特色服务</span>
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="auctionAuth"> 有文物拍卖资质
                    <!--<input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="fidelity"> 保真-->
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="certificateCard"> 省级资质机构以上鉴定证书
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="authorAuth"> 作者授权
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="refundInDays"> 三天无理由退货
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">起拍价</span>
                    <input class="mt_input" type="text" placeholder="" id="start-price" value="0"> 元
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">加价幅度</span>
                    <input class="mt_input" type="text" placeholder="" id="auction-per-price" value="0"> 元
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">佣金</span>
                    <input name="yogjin" type="radio" class="ind_checkbox commision" id="commision-radio"/>
                    <input class="mt_input2" type="text" placeholder="" id="commision" value="0"> %
                    <input checked name="yogjin" type="radio" class="ind_checkbox wu commision" id="commision-radio-wu"/> 无
                </div>
                <!--<div class="mt20">
                    <span class="ind_jrzz bold">保留价</span>
                    <input name="baoliu" type="radio" class="ind_checkbox keep-price" id="keep-price-radio" />
                    <input class="mt_input2" type="text" placeholder="" id="keep-price" value="0" > 元
                    <input checked name="baoliu" type="radio" class="ind_checkbox wu keep-price" id="keep-price-wu" /> 无
                </div>-->
                <div class="mt20">
                    <span class="ind_jrzz bold">延时周期</span>
                    <input name="yogjins" type="radio" class="ind_checkbox delayType" value="1" id="delayType1"  />5分钟/次
                    <input checked name="yogjins" type="radio" class="ind_checkbox wu delayType" value="2" id="delayType2"  />不延时
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">发货地区</span>
                    <select class="ind_dp1" id="country-select">
                        <option value="1">中国</option>
                    </select>
                    <select class="ind_dp1" id="province-select">

                    </select>

                    <select class="ind_dp1" id="city-select">

                    </select>
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">运费</span>
                    <input name="yunfei" type="radio" class="ind_checkbox delivery-price" id="cover-delivery-radio"/>
                    <input class="mt_input2" type="text" placeholder="" id="delivery-price" value="0"> 元
                    <input checked name="yunfei" type="radio" class="ind_checkbox wu delivery-price" id="cover-delivery-wu" /> 包邮
                </div>

            </div>

            <div class="ind_jrzc">
                <span class="ind_ymyl" id="product-preview-btn"><a href="javascript:;">页面预览</a></span><span class="ind_ymyl ind_ymy2 ind_ymy3" id="save-repo-btn"><a
                        href="javascript:;">存入仓库</a></span>
            </div>
            <!-- 定时上架 -->
            <div class="ind_jrzc">
                <?php //echo $this->render('time'); ?>
                <p class="kp_tsinfo1">注：自由拍卖时间不超过48小时,每日上线限5件</p>

            </div>

            <!--<div class="ind_jrzc ind_botom">
                <span class="ind_ymy3" id="product-publish-btn"><a href="javascript:;">立即发布</a></span>

                <p class="kp_tsinfo1">提示：多项可进入拍品仓库批量发布</p>
            </div>-->


        </div>


    </div>
</div>
<?php
//echo $this->render('/front/common/pay');
//echo $this->render('/front/common/transfer-account');
?>

<script type="text/javascript">
    $(function(){
        //alert(1);
        /*$('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });*/
        var qqq = UE.getEditor('qqq');

        <?php if(!empty($productInfo)){
        ?>
        /*$('#start-time-year').val(<?php //echo $productInfo['startTimeYear'] ?>);
        $('#start-time-month').val(<?php //echo $productInfo['startTimeMonth'] ?>);
        $('#start-time-hour').val(<?php //echo $productInfo['startTimeHour'] ?>);
        $('#start-time-minute').val('<?php //echo $productInfo['startTimeMin'] ?>');
        $('#end-time-year').val(<?php //echo $productInfo['endTimeYear'] ?>);
        $('#end-time-month').val(<?php //echo $productInfo['endTimeMonth'] ?>);
        $('#end-time-hour').val(<?php //echo $productInfo['endTimeHour'] ?>);
        $('#end-time-minute').val('<?php //echo $productInfo['endTimeMin'] ?>');*/

        $('#product-name').val('<?php echo $productInfo['productName'] ?>');
        $('#product-category-sel').val(<?php echo $productInfo['productCategoryID'] ?>);
        $('#detail-imgs').val('<?php echo implode(',', $productInfo['detailImgs']) . ','; ?>');

        <?php if($productInfo['storePlateForm'] == 1){
        ?>
            $('#store-category-radio').attr('checked', 'checked');
            <?php
                if(!empty($productInfo['firstStoreCategoryID'])){
            ?>
                    $('#first-store-category-chk').attr('checked', 'checked');
                    $('#first-store-category').val(<?php echo $productInfo['firstStoreCategoryID']; ?>);
            <?php
                }
            ?>

            <?php
                if(!empty($productInfo['secondStoreCategoryID'])){
            ?>
                    $('#second-store-category-chk').attr('checked', 'checked');
                    $('#second-store-category').val(<?php echo $productInfo['secondStoreCategoryID']; ?>);
            <?php
                }
            ?>

            <?php
                if(!empty($productInfo['thirdStoreCategoryID'])){
            ?>
                    $('#third-store-category-chk').attr('checked', 'checked');
                    $('#third-store-category').val(<?php echo $productInfo['thirdStoreCategoryID']; ?>);
            <?php
                }
            ?>
        <?php
        }elseif($productInfo['storePlateForm'] == 2){
        ?>
            $('#join-special-radio').attr('checked', 'checked');
            $('#product-special-id').val(<?php echo $productInfo['specialID']; ?>);
        <?php
        }
        ?>


        <?php
         if(!empty($productInfo['authorAuth'])){
         ?>
            $('#auctionAuth').attr('checked', 'checked');
        <?php
         }
         ?>
        <?php
         if(!empty($productInfo['fidelity'])){
         ?>
            $('#fidelity').attr('checked', 'checked');
        <?php
         }
         ?>
        <?php
         if(!empty($productInfo['certificateCard'])){
         ?>
            $('#certificateCard').attr('checked', 'checked');
        <?php
         }
         ?>
        <?php
         if(!empty($productInfo['authorAuth'])){
         ?>
            $('#authorAuth').attr('checked', 'checked');
        <?php
         }
         ?>
        <?php
         if(!empty($productInfo['refundInDays'])){
         ?>
            $('#refundInDays').attr('checked', 'checked');
        <?php
         }
         ?>

        $('#start-price').val('<?php echo $productInfo['startPrice'] ?>');
        $('#auction-per-price').val('<?php echo $productInfo['auctionPerPrice'] ?>');
        <?php if(!empty($productInfo['commision'])){
        ?>
            $('#commision-radio').attr('checked', 'checked');
            $('#commision').val('<?php echo $productInfo['commision'] ?>');
        <?php
        }else{
        ?>
            $('#commision-radio-wu').attr('checked', 'checked');
        <?php
        } ?>
        <?php /*if(!empty($productInfo['existKeepPrice'])){
        */?>/*
            $('#keep-price-radio').attr('checked', 'checked');
            $('#keep-price').val('<?php /*echo $productInfo['keepPrice'] */?>');
        <?php
/*        }else{
        */?>
            $('#keep-price-wu').attr('checked', 'checked');
        */<?php
/*        }*/ ?>

        <?php
        if($productInfo['delayType'] == 1){
        ?>
            $('#delayType1').attr('checked', 'checked');
        <?php
        }elseif($productInfo['delayType'] == 2){
        ?>
            $('#delayType2').attr('checked', 'checked');
        <?php
        }
        ?>
        <?php if(!empty($productInfo['coverDelivery'])){
        ?>
            $('#cover-delivery-wu').attr('checked', 'checked');

        <?php
        }else{
        ?>
            $('#cover-delivery-radio').attr('checked', 'checked');
            $('#delivery-price').val('<?php echo $productInfo['deliveryPrice'] ?>');
        <?php
        } ?>


        <?php
        }
        ?>

        <?php if(!empty($specialID)){
        ?>

        $('#store-category-div').remove();
        $('#join-special-radio').attr('checked', 'checked');
        $('#product-special-id').val(<?php echo $specialID ?>);
        <?php
        } ?>

        /*
         * 服务器地址,成功返回,失败返回参数格式依照jquery.ajax习惯;
         * 其他参数同WebUploader
         */
        $('#test').diyUpload({
            url: '/index/file-upload',
            success: function (data) {
                console.info(data);
            },
            error: function (err) {
                console.info(err);
            }
        });

        $('#as').diyUpload({
            url: '/index/file-upload',
            success: function (data) {
                var detailImgs = $('#detail-imgs').val();
                detailImgs += data.data['picPath'] + ',';
                $('#detail-imgs').val(detailImgs);
            },
            error: function (err) {
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '图片上传失败',
                    shadeClose: true,
                    time: 2000
                });
            },
            buttonText: '选择文件',
            chunked: true,
            // 分片大小
            chunkSize: 512 * 1024,
            //最大上传的文件数量, 总文件大小,单个文件大小(单位字节);
            fileNumLimit: 4,
            fileSizeLimit: 500000 * 1024,
            fileSingleSizeLimit: 50000 * 1024,
            accept: {}
        });


        $('#product-category-sel').on('change', function(){
            addProductCategoryRefresh()
        });
        function addProductCategoryRefresh(){
            var productCategoryID = $('#product-category-sel').val();
            $('#add-product-category').load('/member/add-product-category?productCategoryID=' + productCategoryID, function(){
                <?php
                    if(!empty($productCategoryFilterOptions)){
                        foreach($productCategoryFilterOptions as $v){

                ?>
                            $('.filter-option-<?php echo $v['productCategoryFilterOptionID'] ?>').attr('checked', 'checked');
                <?php
                        }
                    }
                ?>
            });
            $('#category-property-info').load('/member/category-property?productCategoryID=' + productCategoryID, function(){
                <?php
                    if(!empty($productPropertyValues)){
                        foreach($productPropertyValues as $v){

                ?>
                            $('.category-property-<?php echo $v['productCategoryPropertyID'] ?>').val('<?php echo $v['value']; ?>');
                <?php
                        }
                    }
                ?>
            });
        }
        addProductCategoryRefresh();

        $.ajax({
            url : '/region/list',
            type : 'post',
            dataType : 'json',
            data : {
                pid : 1
            },
            success : function(data){
                var options = '';

                for(var i in data.data){
                    var selected = '';

                    if(data.data[i].regionID == 31){
                        selected = 'selected';
                    }
                    options += '<option ' + selected + ' value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                }
                $('#province-select').html(options);
                <?php if(!empty($productInfo)){
                ?>
                    $('#province-select').val(<?php echo $productInfo['deliveryProvinceID'] ?>);
                <?php
                }elseif(!empty($defaultDeliveryProvinceID)){
                ?>
                    $('#province-select').val(<?php echo $defaultDeliveryProvinceID ?>);
                <?php
                } ?>

                $.ajax({
                    url : '/region/list',
                    type : 'post',
                    dataType : 'json',
                    data : {
                        pid : <?php if(!empty($productInfo)){echo $productInfo['deliveryProvinceID'];}elseif(!empty($defaultDeliveryProvinceID)){echo $defaultDeliveryProvinceID;}else{echo 31;} ?>
                    },
                    success : function(data){
                        var options = '';
                        for(var i in data.data){
                            var selected = '';

                            if(data.data[i].regionID == 383){
                                selected = 'selected';
                            }
                            options += '<option ' + selected + ' value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                        }
                        $('#city-select').html(options);
                        <?php if(!empty($productInfo)){
                        ?>
                            $('#city-select').val(<?php echo $productInfo['deliveryCityID'] ?>);
                        <?php
                        }elseif(!empty($defaultDeliveryCityID)){
                        ?>
                        $('#city-select').val(<?php echo $defaultDeliveryCityID ?>);
                        <?php
                        } ?>
                    }
                });
            }
        });
        $('#province-select').on('change', function(){
            var pid = $(this).val();
            $.ajax({
                url : '/region/list',
                type : 'post',
                dataType : 'json',
                data : {
                    pid : pid
                },
                success : function(data){
                    var options = '';
                    for(var i in data.data){
                        options += '<option value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                        $('#city-select').html(options);
                    }
                }
            });
        });


        $(document).on('change', '.jinshizhuanke-ticai', function(){
            var val = $(this).val();
            if(val == '拓片'){
                $('.category-property-18').hide();
                $('.category-property-19').show();
                $('.category-property-13').show();
                $('.category-property-14').show();
            }else if(val == '观赏名石'){
                $('.category-property-18').show();
                $('.category-property-20').show();
                $('.category-property-19').hide();
                $('.category-property-13').hide();
                $('.category-property-14').hide();
            }else{
                $('.category-property-18').show();
                $('.category-property-13').show();
                $('.category-property-14').show();
                $('.category-property-20').hide();
                $('.category-property-19').hide();
            }
        });

        function getProductFormData(){
            var data = {};
            <?php if(!empty($productInfo)){
            ?>
                data.productID = <?php echo $productInfo['productID']; ?>;
            <?php
            } ?>
            data.productCategoryID = $('#product-category-sel').val();
            data.productCategoryFilters = new Array();
            $('.product-category-filter:checked').each(function(){
                var optionID = $(this).attr('option-id');
                data.productCategoryFilters.push(optionID);
            });
            data.productCategoryProperty = {};
            $('.category-property:visible').each(function(){
                var productCategoryPropertyID = $(this).attr('product-category-property-id');
                data.productCategoryProperty[productCategoryPropertyID] = $(this).val();
            });
            data.productName = $('#product-name').val();
            data.detailImgs = $('#detail-imgs').val();
            data.productDetail = qqq.getContent();
            data.storePlateForm = $('input[name=Fruit]:checked').val();

            if(data.storePlateForm == 1){
                if($('input[name=storeCategory1]').is(':checked')){
                    data.firstStoreCategoryID = $('#first-store-category').val();
                }
                if($('input[name=storeCategory2]').is(':checked')){
                    data.secondStoreCategoryID = $('#second-store-category').val();
                }
                if($('input[name=storeCategory3]').is(':checked')){
                    data.thirdStoreCategoryID = $('#third-store-category').val();
                }

            }else if(data.storePlateForm == 2){
                data.specialID = $('#product-special-id').val();
            }
            data.auctionAuth = $('#auctionAuth').is(':checked');
            if(data.auctionAuth){
                data.auctionAuth = 1;
            }else{
                data.auctionAuth = 0;
            }
            data.fidelity = $('#fidelity').is(':checked');
            if(data.fidelity){
                data.fidelity = 1;
            }else{
                data.fidelity = 0;
            }
            data.certificateCard = $('#certificateCard').is(':checked');
            if(data.certificateCard){
                data.certificateCard = 1;
            }else{
                data.certificateCard = 0;
            }
            data.authorAuth = $('#authorAuth').is(':checked');
            if(data.authorAuth){
                data.authorAuth = 1;
            }else{
                data.authorAuth = 0;
            }
            data.refundInDays = $('#refundInDays').is(':checked');
            if(data.refundInDays){
                data.refundInDays = 1;
            }else{
                data.refundInDays = 0;
            }
            data.startPrice = $('#start-price').val();
            data.auctionPerPrice = $('#auction-per-price').val();
            if(!$('.commision:checked').hasClass('wu')){
                data.commision = $('#commision').val();
            }
            /*if(!$('.keep-price:checked').hasClass('wu')){
                data.existKeepPrice = 1;
                data.keepPrice = $('#keep-price').val();
            }else{
                data.existKeepPrice = 0;
            }*/
            data.delayType = $('.delayType:checked').val();
            data.deliveryCityID = $('#city-select').val();
            if(!$('.delivery-price:checked').hasClass('wu')){
                data.deliveryPrice = $('#delivery-price').val();
                data.coverDelivery = 0;
            }else{
                data.coverDelivery = 1;
                data.deliveryPrice = 0;
            }
            /*var auctionStartTimeYear = $('#start-time-year').val();
            var auctionStartTimeMonth = $('#start-time-month').val();
            var auctionStartTimeDay = $('#start-time-day').val();
            var auctionStartTimeHour = $('#start-time-hour').val();
            var auctionStartTimeMinute = $('#start-time-minute').val();
            data.startTime = auctionStartTimeYear + '-' + auctionStartTimeMonth + '-' + auctionStartTimeDay + ' ' + auctionStartTimeHour + ':' + auctionStartTimeMinute + ':00';
            var auctionEndTimeYear = $('#end-time-year').val();
            var auctionEndTimeMonth = $('#end-time-month').val();
            var auctionEndTimeDay = $('#end-time-day').val();
            var auctionEndTimeHour = $('#end-time-hour').val();
            var auctionEndTimeMinute = $('#end-time-minute').val();
            data.endTime = auctionEndTimeYear + '-' + auctionEndTimeMonth + '-' + auctionEndTimeDay + ' ' + auctionEndTimeHour + ':' + auctionEndTimeMinute + ':00';*/

            if(!data.productName){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写拍品标题',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.detailImgs){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请上传拍品图片',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.productDetail){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写拍品详情',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }

            if(!data.startPrice){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写起拍价',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.auctionPerPrice){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写加价幅度',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }


            return data;
        }

        $('#product-preview-btn').on('click', function(){
            var data = getProductFormData();
            if(!data) return false;
            var result;
            $.ajax({
                url : '/member/save-product-preview',
                type : 'post',
                dataType : 'json',
                async : false,
                data : data,
                success : function(res){
                    result = res;
                }
            });
            if(result.flag > 0){
                window.open('/product/pre-view?productID=' + result.data['productID']);
            }else{
                layer.alert(result.msg);
            }
        });

        $('#save-repo-btn').on('click', function(){
            var data = getProductFormData();
            if(!data) return false;
            $.ajax({
                url : '/member/save-product',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            if(data.specialID){
                                location.href = '/member/special-product?specialID='+data.specialID;
                            }else{
                                location.href = '/member/product';
                            }

                        });
                    }else{
                        layer.alert(res.msg);
                    }

                }
            });
        });

        /*$('#product-publish-btn').on('click', function(){
            var data = getProductFormData();
            if(!data) return false;
            data.publish = 1;
            $.ajax({
                url : '/member/save-product',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.data['unitePayID']){
                            <?php
                            //if($_siteSettings['productMoney'] > 0) {
                            ?>

                                layer.open({
                                    skin: '',
                                    title: '',
                                    type: 1,
                                    content: $('#pay-div').html()
                                });
                                $('.pay-price:visible').html(<?php //echo $_siteSettings['productMoney']; ?>);
                                $('.pay-price:visible').attr('unite-pay-id', res.data['unitePayID']);
                            <?php
                            //}else{
                            ?>
                                layer.alert(res.msg, function(){
                                    if(data.specialID){
                                        location.href = '/member/special-product?specialID='+data.specialID;
                                    }else{
                                        location.href = '/member/product';
                                    }
                                });
                            <?php
                            //}
                            ?>
                        }else{
                            layer.alert(res.msg, function(){
                                if(data.specialID){
                                    location.href = '/member/special-product?specialID='+data.specialID;
                                }else{
                                    location.href = '/member/product';
                                }
                            });
                        }
                    }else{
                        layer.alert(res.msg);
                    }

                }
            });
        });*/

        /*$(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.payType = $('.selected-pay-type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            data.unitePayID = $('.pay-price:visible').attr('unite-pay-id');
            $.ajax({
                url : '/order/pay-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            layer.alert('申请开通中');
                            return false;
                            location.href = res.data['coreData'];
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }else if(res.flag == 5){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: '<img src="/qrcode/' + res.data['coreData'] + '" />'
                            });
                        }
                        setInterval('checkOrderStatus(' + data.unitePayID + ', 2)', 2000);
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });*/

        $('.product-detail-img').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.path = $(this).attr('pic-val');
            $(this).parent('li').remove();
            var detailImgs = $('#detail-imgs').val();
            detailImgs = detailImgs.split(',');
            for(var i in detailImgs){
                if(detailImgs[i] == data.path){
                    detailImgs.splice(i, 1);
                }
            }

            $('#detail-imgs').val(detailImgs.join(','));
        })

        $('.category-introduction').on('click', function(){
            layer.open({
                type : 1,
                content : '<?php echo $_siteSettings['categoryIntroduction'] ?>'
            });
        });
    });

</script>