
<?php
    foreach($options as $v){
?>
        <div class="ind_fge1">
            <span class="ind_fge"><?php echo $v['filterName']; ?></span>
            <?php
                foreach($v['options'] as $sv){
            ?>
                    <input name="y02" type="radio" class="ind_checkbox" option-id="<?php echo $sv['optionID'];  ?>"/> <?php echo $sv['optionName'] ?>
            <?php
                }
            ?>


        </div>
<?php
    }
?>
