
<?php
    foreach($options as $v){
?>
        <div class="ind_fge1">
            <span class="ind_fge" style="margin-right: 0px;width:90px;"><?php echo $v['filterName']; ?></span>
            <?php
                $i = 0;
                foreach($v['options'] as $sv){
            ?>
                    <input <?php echo empty($i) ? 'checked' : ''; ?> name="<?php echo $v['filterName'] ?>" type="radio" class="product-category-filter ind_checkbox filter-option-<?php echo $sv['optionID'] ?>" option-id="<?php echo $sv['optionID'] ?>" /> <?php echo $sv['optionName'] ?>
            <?php
                    $i++;
                }
            ?>
        </div>
<?php
    }
?>
