<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'add-product')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div>
                <span class="bold">所属类目</span>
                <select class="kp_year1 ml20" id="product-category-sel">
                    <?php foreach($productCategories as $v){
                    ?>
                        <option value="<?php echo $v['productCategoryID']; ?>"><?php echo $v['categoryName'] ?></option>
                    <?php
                    } ?>
                </select>

                <span class="ind_x">*</span>
                <span class="ml20"><a href="">类目说明 >></a></span>
            </div>
            <div class="ind_fg">
                <div><span class="ind_dx">单选</span><span class="ind_dx1">请仔细选择筛选项，以便有更大几率被搜索显示</span></div>
                <div id="add-product-category">

                </div>
            </div>
            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left ind_zpinfo_leftinfo bold">作品信息</div>
                <div class="ind_zpinfo_right" id="category-property-info">

                </div>
            </div>
            <div class="ind_ppbt "><span class="bold">拍品标题</span> <input id="product-name" class="ind_ppinput ind_uu" type="text"
                                                                         placeholder="请输入标题"> <span
                    class="ind_x"> *</span></div>

            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left ind_zpinfo_lefta"><span class="bold">拍品图片 </span>

                    <div class="gl_zyi">注：<br>不超过5张限550kb以内张</div>
                </div>
                <input type="hidden" id="detail-imgs" />
                <div id="as"></div>


            </div>
            <div class="ind_zpinfo">
                <div class="ind_zpinfo_left"><span class="bold">拍品详情</span>

                    <div class="gl_zyi">注：<br>图片宽度限860像素内。</div>
                    <!--<div class="ind_dnb"><a href="">电 脑 版</a></div>
                    <div class="ind_dnb1"><a href="">手 机 版</a></div>
                    <div class="ind_dnb2"><a href="">立即保存</a></div>-->
                </div>
                <div class="ind_zpinfo_right">
                    <div style="width:700px;  background:#fff">
                <textarea id="qqq">
                 
                  
                </textarea>
                    </div>

                </div>
            </div>
            <p class="kp_tsinfo1 ">注：【店内分类】与【专场分类】只能选择进入一个。【店铺分类】最多选择三项，不选择进入默认“未分类”</p>

            <div class="mt30 ind_dash">
                <div class="">
                    <span class="ind_jrzz bold">店内分类</span>
                    <input checked name="Fruit" type="radio" class="ind_radio" value="1"/>
                    <input type="checkbox" name="storeCategory1" value="checkbox" class="ind_checkbox store-category-chk">
                    <select class="ind_dp1">
                        <?php
                            foreach($storeCategory as $v){
                        ?>
                                <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                            }
                        ?>
                    </select>
                    <input type="checkbox" name="storeCategory2" value="checkbox" class="ind_checkbox store-category-chk">
                    <select class="ind_dp1">
                        <?php
                        foreach($storeCategory as $v){
                            ?>
                            <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                    <input type="checkbox" name="storeCategory3" value="checkbox" class="ind_checkbox store-category-chk">
                    <select class="ind_dp1">
                        <?php
                        foreach($storeCategory as $v){
                        ?>
                            <option value="<?php echo $v['storeCategoryID']; ?>"><?php echo $v['storeCategoryName']; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                </div>
                <div class="ind_jrzc">
                    <span class="ind_jrzz bold">进入专场</span>
                    <input name="Fruit" type="radio" class="ind_checkbox" value="2"/>
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox">
                    <select class="ind_dp1"  id="product-special-id">
                        <?php
                            foreach($specials as $v){
                        ?>
                                <option value="<?php echo $v['specialID'] ?>"><?php echo $v['specialName']; ?></option>
                        <?php
                            }
                        ?>
                    </select>

                </div>
            </div>


            <div class="ind_jrzc">
                <div>
                    <span class="ind_jrzz bold">特色服务</span>
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="auctionAuth"> 有文物拍卖资质
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="fidelity"> 保真
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="certificateCard"> 省级资质机构以上鉴定证书
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="authorAuth"> 作者授权
                    <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox" id="refundInDays"> 三天无理由退货
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">起拍价</span>
                    <input class="mt_input" type="text" placeholder="" id="start-price"> 元
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">加价幅度</span>
                    <input class="mt_input" type="text" placeholder="" id="auction-per-price"> 元
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">佣金</span>
                    <input name="yogjin" type="radio" class="ind_checkbox commission"/>
                    <input class="mt_input2" type="text" placeholder="" id="commission"> %
                    <input checked name="yogjin" type="radio" class="ind_checkbox wu commission"/> 无
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">保留价</span>
                    <input name="baoliu" type="radio" class="ind_checkbox keep-price"/>
                    <input class="mt_input2" type="text" placeholder="" id="keep-price"> 元
                    <input checked name="baoliu" type="radio" class="ind_checkbox wu keep-price"/> 无
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">延时周期</span>
                    <input name="yogjins" type="radio" class="ind_checkbox delayType" value="1" />5分钟/次
                    <input checked name="yogjins" type="radio" class="ind_checkbox wu delayType" value="2" />不延时
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">发货地区</span>
                    <select class="ind_dp1" id="country-select">
                        <option value="1">中国</option>
                    </select>
                    <select class="ind_dp1" id="province-select">

                    </select>

                    <select class="ind_dp1" id="city-select">

                    </select>
                </div>
                <div class="mt20">
                    <span class="ind_jrzz bold">运费</span>
                    <input name="yunfei" type="radio" class="ind_checkbox delivery-price"/>
                    <input class="mt_input2" type="text" placeholder="" id="delivery-price"> 元
                    <input checked name="yunfei" type="radio" class="ind_checkbox wu delivery-price" /> 包邮
                </div>

            </div>

            <div class="ind_jrzc">
                <span class="ind_ymyl"><a href="javascript:;" id="product-preview-btn">页面预览</a></span><span class="ind_ymyl ind_ymy2"><a
                        href="" id="save-repo-btn">存入仓库</a></span>
            </div>
            <!-- 定时上架 -->
            <div class="ind_jrzc">
                <div class="kp_timeon">
                    <span class="bold">拍卖时间</span>
                    <select class="kp_year" id="auction-start-time-year">
                        <option value="<?php echo date('Y') ?>"><?php echo date('Y'); ?></option>
                        <option value="<?php echo date('Y', strtotime('+1 year')) ?>"><?php echo date('Y', strtotime('+1 year')) ?></option>
                    </select>
                    <span class="kp_ml8">年</span>
                    <select class="kp_ml9" id="auction-start-time-month">
                        <?php
                            for($i = 1; $i <= 12; $i++){
                        ?>
                                <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php
                            }
                        ?>
                    </select>
                    <span class="kp_ml8">月</span>
                    <select class="kp_ml9" id="auction-start-time-day">

                    </select>
                    <span class="kp_ml8">日</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9" id="auction-start-time-hour">
                            <?php for($i = 0; $i < 24; $i++){
                            ?>
                                <option value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
                    <span class="kp_ml8">时</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9" id="auction-start-time-minute">
                            <?php for($i = 1; $i <= 60; $i++){
                                ?>
                                <option value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
                    <span class="kp_ml8">分</span>
                </div>

                <div class="kp_timeon">
                    <span class="bold">拍卖时间</span>
                    <select class="kp_year" id="auction-end-time-year">
                        <option value="<?php echo date('Y') ?>"><?php echo date('Y'); ?></option>
                        <option value="<?php echo date('Y', strtotime('+1 year')) ?>"><?php echo date('Y', strtotime('+1 year')) ?></option>
                    </select>
                    <span class="kp_ml8">年</span>
                    <select class="kp_ml9" id="auction-end-time-month">
                        <?php
                        for($i = 1; $i <= 12; $i++){
                            ?>
                            <option value="<?php echo $i; ?>"><?php echo $i; ?></option>
                        <?php
                        }
                        ?>
                    </select>
                    <span class="kp_ml8">月</span>
                    <select class="kp_ml9" id="auction-end-time-day">

                    </select>
                    <span class="kp_ml8">日</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9" id="auction-end-time-hour">
                            <?php for($i = 0; $i < 24; $i++){
                                ?>
                                <option value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
                    <span class="kp_ml8">时</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9" id="auction-end-time-minute">
                            <?php for($i = 1; $i <= 60; $i++){
                                ?>
                                <option value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
                    <span class="kp_ml8">分</span>

                </div>
                <p class="kp_tsinfo1">注：自由拍卖时间不超过48小时,每日上线限5件</p>

            </div>

            <div class="ind_jrzc ind_botom">
                <span class="ind_ymy3"><a href="javascript:;" id="product-publish-btn">立即发布</a></span>

                <p class="kp_tsinfo1">提示：多项可进入拍品仓库批量发布</p>
            </div>


        </div>


    </div>
</div>

<script type="text/javascript">
    $(function(){
        //alert(1);
        $('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });

        /*
         * 服务器地址,成功返回,失败返回参数格式依照jquery.ajax习惯;
         * 其他参数同WebUploader
         */
        $('#test').diyUpload({
            url: '/index/file-upload',
            success: function (data) {
                console.info(data);
            },
            error: function (err) {
                console.info(err);
            }
        });

        $('#as').diyUpload({
            url: '/index/file-upload',
            success: function (data) {
                var detailImgs = $('#detail-imgs').val();
                detailImgs += data.data['picPath'] + ',';
                $('#detail-imgs').val(detailImgs);
            },
            error: function (err) {
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '图片上传失败',
                    shadeClose: true,
                    time: 2000
                });
            },
            buttonText: '选择文件',
            chunked: true,
            // 分片大小
            chunkSize: 512 * 1024,
            //最大上传的文件数量, 总文件大小,单个文件大小(单位字节);
            fileNumLimit: 4,
            fileSizeLimit: 500000 * 1024,
            fileSingleSizeLimit: 50000 * 1024,
            accept: {}
        });


        $('#product-category-sel').on('change', function(){
            addProductCategoryRefresh()
        });
        function addProductCategoryRefresh(){
            var productCategoryID = $('#product-category-sel').val();
            $('#add-product-category').load('/member/add-product-category?productCategoryID=' + productCategoryID);
            $('#category-property-info').load('/member/category-property?productCategoryID=' + productCategoryID);
        }
        addProductCategoryRefresh();

        $.ajax({
            url : '/region/list',
            type : 'post',
            dataType : 'json',
            data : {
                pid : 1
            },
            success : function(data){
                var options = '';

                for(var i in data.data){
                    var selected = '';

                    if(data.data[i].regionID == 31){
                        selected = 'selected';
                    }
                    options += '<option ' + selected + ' value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                    $('#province-select').html(options);
                }

                $.ajax({
                    url : '/region/list',
                    type : 'post',
                    dataType : 'json',
                    data : {
                        pid : 31
                    },
                    success : function(data){
                        var options = '';
                        for(var i in data.data){
                            var selected = '';

                            if(data.data[i].regionID == 383){
                                selected = 'selected';
                            }
                            options += '<option ' + selected + ' value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                            $('#city-select').html(options);
                        }
                    }
                });
            }
        });
        $('#province-select').on('change', function(){
            var pid = $(this).val();
            $.ajax({
                url : '/region/list',
                type : 'post',
                dataType : 'json',
                data : {
                    pid : pid
                },
                success : function(data){
                    var options = '';
                    for(var i in data.data){
                        options += '<option value="'+ data.data[i].regionID +'">'+ data.data[i].name +'</option>';
                        $('#city-select').html(options);
                    }
                }
            });
        });

        function refreshTimeDay(year, month, type = 1){
            $.ajax({
                url : '/index/get-day',
                dataType : 'json',
                data : {
                    year : year,
                    month : month
                },
                type : 'post',
                success : function(data){
                    if(data.flag > 0){
                        var options = '';
                        for(var i = 1; i<= data.data; i++){
                            options += '<option value="'+ i +'">' + i + '</option>';
                        }
                        if(type == 1){
                            $('#auction-start-time-day').html(options);
                        }else{
                            $('#auction-end-time-day').html(options);
                        }
                    }
                }
            });
        }
        refreshTimeDay(<?php echo date('Y'); ?>, 1, 1);
        refreshTimeDay(<?php echo date('Y'); ?>, 1, 2);
        $('#auction-start-time-year').on('change', function(){
            var year = $('#auction-start-time-year').val();
            var month = $('#auction-start-time-month').val();
            refreshTimeDay(year, month, 1);
        });
        $('#auction-start-time-month').on('change', function(){
            var year = $('#auction-start-time-year').val();
            var month = $('#auction-start-time-month').val();
            refreshTimeDay(year, month, 1);
        });
        $('#auction-end-time-year').on('change', function(){
            var year = $('#auction-end-time-year').val();
            var month = $('#auction-end-time-month').val();
            refreshTimeDay(year, month, 2);
        });
        $('#auction-end-time-month').on('change', function(){
            var year = $('#auction-end-time-year').val();
            var month = $('#auction-end-time-month').val();
            refreshTimeDay(year, month, 2);
        });
        $(document).on('change', '.jinshizhuanke-ticai', function(){
            var val = $(this).val();
            if(val == '拓片'){
                $('.category-property-18').hide();
                $('.category-property-19').show();
                $('.category-property-13').show();
                $('.category-property-14').show();
            }else if(val == '观赏名石'){
                $('.category-property-18').show();
                $('.category-property-20').show();
                $('.category-property-19').hide();
                $('.category-property-13').hide();
                $('.category-property-14').hide();
            }else{
                $('.category-property-18').show();
                $('.category-property-13').show();
                $('.category-property-14').show();
                $('.category-property-20').hide();
                $('.category-property-19').hide();
            }
        });

        function getProductFormData(){
            var data = {};
            data.productCategoryID = $('#product-category-sel').val();
            data.productCategoryFilters = new Array();
            $('.product-category-filter:checked').each(function(){
                var optionID = $(this).attr('option-id');
                data.productCategoryFilters.push(optionID);
            });
            data.productCategoryProperty = {};
            $('.category-property').each(function(){
                var productCategoryPropertyID = $(this).attr('product-category-property-id');
                data.productCategoryProperty[productCategoryPropertyID] = $(this).val();
            });
            data.productName = $('#product-name').val();
            data.detailImgs = $('#detail-imgs').val();
            data.productDetail = $('#qqq').text();
            data.storePlateForm = $('input[name=Fruit]:checked').val();

            if(data.storePlateForm == 1){
                data.storeCategoryID = new Array();
                $('.store-category-chk:checked').each(function(){
                    data.storeCategoryID.push($(this).next('select').val());
                });
            }else if(data.storePlateForm == 2){
                data.specialID = $('#product-special-id').val();
            }
            data.auctionAuth = $('#auctionAuth').is(':checked');
            data.fidelity = $('#fidelity').is(':checked');
            data.certificateCard = $('#certificateCard').is(':checked');
            data.authorAuth = $('#authorAuth').is(':checked');
            data.refundInDays = $('#refundInDays').is(':checked');
            data.startPrice = $('#start-price').val();
            data.auctionPerPrice = $('#auction-per-price').val();
            if(!$('.commission:checked').hasClass('wu')){
                data.commission = $('#commission').val();
            }
            if(!$('.keep-price:checked').hasClass('wu')){
                data.keepPrice = $('#keep-price').val();
            }
            data.delayType = $('.delayType:checked').val();
            data.deliveryCityID = $('#city-select').val();
            if(!$('.delivery-price:checked').hasClass('wu')){
                data.deliveryPrice = $('#delivery-price').val();
                data.coverDelivery = 0;
            }else{
                data.coverDelivery = 1;
            }
            var auctionStartTimeYear = $('#auction-start-time-year').val();
            var auctionStartTimeMonth = $('#auction-start-time-month').val();
            var auctionStartTimeDay = $('#auction-start-time-day').val();
            var auctionStartTimeHour = $('#auction-start-time-hour').val();
            var auctionStartTimeMinute = $('#auction-start-time-minute').val();
            data.startTime = auctionStartTimeYear + '-' + auctionStartTimeMonth + '-' + auctionStartTimeDay + ' ' + auctionStartTimeHour + ':' + auctionStartTimeMinute + ':00';
            var auctionEndTimeYear = $('#auction-end-time-year').val();
            var auctionEndTimeMonth = $('#auction-end-time-month').val();
            var auctionEndTimeDay = $('#auction-end-time-day').val();
            var auctionEndTimeHour = $('#auction-end-time-hour').val();
            var auctionEndTimeMinute = $('#auction-end-time-minute').val();
            data.endTime = auctionEndTimeYear + '-' + auctionEndTimeMonth + '-' + auctionEndTimeDay + ' ' + auctionEndTimeHour + ':' + auctionEndTimeMinute + ':00';

            if(!data.productName){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写拍品标题',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.detailImgs){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请上传拍品图片',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.productDetail){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写拍品详情',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }

            if(!data.startPrice){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写起拍价',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }
            if(!data.auctionPerPrice){
                layer.open({
                    type : 0,
                    icon : 2,
                    content : '请填写加价幅度',
                    shadeClose: true,
                    time: 2000
                });
                return false;
            }


            return data;
        }

        $('#product-preview-btn').on('click', function(){
            var data = getProductFormData();

            console.log(data);
        });

        $('#save-repo-btn').on('click', function(){

        });

        $('#product-publish-btn').on('click', function(){

        });
    });

</script>