<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'special')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div>
                <span class="gl_cjzc"><a href="">创建专场 +</a></span>
            </div>

            <!-- 定时上架 -->
            <div class="ind_jrzc  ">
                <?php
                    echo $this->render('time');
                ?>
                <p class="kp_tsinfo1">注：专场拍卖时间固定为日场10:00-22:00，夜场22:00-次日10:00</p>

            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">所属类目</span>
                <select class="ind_dp1" id="special-product-category-id">
                    <?php
                        foreach($productCategories as $v){
                    ?>
                            <option value="<?php echo $v['productCategoryID'] ?>"><?php echo $v['categoryName']; ?></option>
                    <?php
                        }
                    ?>
                </select>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场标题</span>
                <input class="gl_ppinput" type="text" placeholder="限20字以内" id="special-name">
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场海报</span>
                <div id="preview1" class="dianpbai"><img id="imghead1" src=""></div>
                <input type="file" name="uploadFile" onchange="previewImage1(this)" class="gl_sctu"/> 尺寸：1900*300 图片容量不大于1M
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">专场首焦</span>
                <div id="preview2" class="dianpbai"><img id="imghead2" src=""></div>
                <input type="file" name="uploadFile" onchange="previewImage2(this)" class="gl_sctu"/> 尺寸：1900*300 图片容量不大于1M
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">拍品数量</span>
                <input class="mt_input" type="text" placeholder="" id="product-count-limit"> 个 *限制20-60个
            </div>
            <div class="mt20  ycsd">
                <span class="ind_jrzz" style="float:left"><span class="bold">专场介绍 </span><br> <p class="gl_zyi">
                        注：图片宽度限制860以内</p></span>

                <div style="width:540px; background:#fff; float:left">
                      <textarea id="qqq"><?php if(!empty($specialInfo)){echo $specialInfo['specialDesc'];} ?></textarea>
                </div>
            </div>
            <div class="ind_licj" id="add-special-btn">立即创建</div>


        </div>


    </div>
</div>
<?php
echo $this->render('/front/common/pay');
echo $this->render('/front/common/transfer-account');
?>
<script type="text/javascript">
    $(function(){
        //alert(1);

        $('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });

        <?php if(!empty($specialInfo)){
        ?>
                $('#start-time-year').val(<?php echo $specialInfo['startTimeYear'] ?>);
                $('#start-time-month').val(<?php echo $specialInfo['startTimeMonth'] ?>);
                $('#start-time-hour').val(<?php echo $specialInfo['startTimeHour'] ?>);
                $('#start-time-minute').val('<?php echo $specialInfo['startTimeMin'] ?>');
                $('#end-time-year').val(<?php echo $specialInfo['endTimeYear'] ?>);
                $('#end-time-month').val(<?php echo $specialInfo['endTimeMonth'] ?>);
                $('#end-time-hour').val(<?php echo $specialInfo['endTimeHour'] ?>);
                $('#end-time-minute').val('<?php echo $specialInfo['endTimeMin'] ?>');
                $('#special-product-category-id').val(<?php echo $specialInfo['specialProductCategoryID'] ?>);
                $('#special-name').val('<?php echo $specialInfo['specialName'] ?>');
                $('#imghead1').attr('src', '<?php echo $specialInfo['specialImg'] ?>');
                $('#imghead2').attr('src', '<?php echo $specialInfo['specialBanner'] ?>');
                $('#product-count-limit').val(<?php echo $specialInfo['productCountLimit'] ?>);

        <?php
        } ?>
    })

    $('#add-special-btn').on('click', function(){
        var data = {};
        <?php if(!empty($specialInfo)){

        ?>
                data.specialID = <?php echo $specialInfo['specialID'] ?>;
        <?php
        } ?>
        var specialStartTimeYear = $('#start-time-year').val();
        var specialStartTimeMonth = $('#start-time-month').val();
        var specialStartTimeDay = $('#start-time-day').val();
        var specialStartTimeHour = $('#start-time-hour').val();
        var specialStartTimeMinute = $('#start-time-minute').val();
        data.startTime = specialStartTimeYear + '-' + specialStartTimeMonth + '-' + specialStartTimeDay + ' ' + specialStartTimeHour + ':' + specialStartTimeMinute + ':00';
        var specialEndTimeYear = $('#end-time-year').val();
        var specialEndTimeMonth = $('#end-time-month').val();
        var specialEndTimeDay = $('#end-time-day').val();
        var specialEndTimeHour = $('#end-time-hour').val();
        var specialEndTimeMinute = $('#end-time-minute').val();
        data.endTime = specialEndTimeYear + '-' + specialEndTimeMonth + '-' + specialEndTimeDay + ' ' + specialEndTimeHour + ':' + specialEndTimeMinute + ':00';
        data.specialProductCategoryID = $('#special-product-category-id').val();
        data.specialName = $('#special-name').val();
        data.specialImg = $('#imghead1').attr('src');
        data.specialBanner = $('#imghead2').attr('src');
        data.productCountLimit = $('#product-count-limit').val();
        data.specialDesc = $('#qqq').val();

        if(!data.specialName){
            layer.open({
                content : '请填写专场标题'
            });
            return false;
        }

        if(!data.specialImg){
            layer.open({
                content : '请上传专场海报图片'
            });
            return false;
        }

        if(!data.specialBanner){
            layer.open({
                content : '请上传专场首焦图片'
            });
            return false;
        }

        if(!data.productCountLimit){
            layer.open({
                content : '请填写拍品数量'
            });
            return false;
        }

        if(!data.specialDesc){
            layer.open({
                content : '请填写专场介绍'
            });
            return false;
        }


        $.ajax({
            url : '/member/add-special',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                if(res.flag > 0){
                    if(res.data['unitePayID']){
                        <?php
                            if($_siteSettings['specialMoney'] > 0) {
                        ?>
                            layer.open({
                                skin: '',
                                title: '',
                                type: 1,
                                content: $('#pay-div').html()
                            });
                            $('.pay-price:visible').html(<?php echo $_siteSettings['specialMoney']; ?>);
                            $('.pay-price:visible').attr('unite-pay-id', res.data['unitePayID']);
                        <?php
                            }else{
                        ?>
                                location.href = '/member/special';
                        <?php
                            }
                        ?>
                    }else{
                        layer.alert(res.msg, function(){
                            location.href = '/member/special';
                        });
                    }
                }else{
                    layer.open({
                        content : res.msg
                    });
                }
            }
        });

        $(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.payType = $('.selected-pay-type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            data.unitePayID = $('.pay-price:visible').attr('unite-pay-id');
            $.ajax({
                url : '/order/pay-special',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            layer.alert('申请开通中');
                            return false;
                            location.href = res.data['coreData'];
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });


    });


    //图片上传预览    IE是用了滤镜。
    function previewImage1(file)
    {
        var MAXWIDTH  = 260;
        var MAXHEIGHT = 180;
        var div = document.getElementById('preview1');
        if (file.files && file.files[0])
        {
            var img = document.getElementById('imghead1');
            img.onload = function(){
                var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
                img.width  =  rect.width;
                img.height =  rect.height;
//                 img.style.marginLeft = rect.left+'px';
                img.style.marginTop = rect.top+'px';
            }
            var reader = new FileReader();
            reader.onload = function(evt){img.src = evt.target.result;}
            reader.readAsDataURL(file.files[0]);
        }
        else //兼容IE
        {
            var sFilter='filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="';
            file.select();
            var src = document.selection.createRange().text;
            var img = document.getElementById('imghead1');
            img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;
            var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
            status =('rect:'+rect.top+','+rect.left+','+rect.width+','+rect.height);
            div.innerHTML = "<div id=divhead style='width:"+rect.width+"px;height:"+rect.height+"px;"+sFilter+src+"\"'></div>";
        }
    }

    //图片上传预览    IE是用了滤镜。
    function previewImage2(file)
    {
        var MAXWIDTH  = 260;
        var MAXHEIGHT = 180;
        var div = document.getElementById('preview2');
        if (file.files && file.files[0])
        {
            var img = document.getElementById('imghead2');
            img.onload = function(){
                var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
                img.width  =  rect.width;
                img.height =  rect.height;
//                 img.style.marginLeft = rect.left+'px';
                img.style.marginTop = rect.top+'px';
            }
            var reader = new FileReader();
            reader.onload = function(evt){img.src = evt.target.result;}
            reader.readAsDataURL(file.files[0]);
        }
        else //兼容IE
        {
            var sFilter='filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="';
            file.select();
            var src = document.selection.createRange().text;
            var img = document.getElementById('imghead2');
            img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;
            var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
            status =('rect:'+rect.top+','+rect.left+','+rect.width+','+rect.height);
            div.innerHTML = "<div id=divhead style='width:"+rect.width+"px;height:"+rect.height+"px;"+sFilter+src+"\"'></div>";
        }
    }

    function clacImgZoomParam( maxWidth, maxHeight, width, height ){
        var param = {top:0, left:0, width:width, height:height};
        if( width>maxWidth || height>maxHeight )
        {
            rateWidth = width / maxWidth;
            rateHeight = height / maxHeight;

            if( rateWidth > rateHeight )
            {
                param.width =  maxWidth;
                param.height = Math.round(height / rateWidth);
            }else
            {
                param.width = Math.round(width / rateHeight);
                param.height = maxHeight;
            }
        }

        param.left = Math.round((maxWidth - param.width) / 2);
        param.top = Math.round((maxHeight - param.height) / 2);
        return param;
    }
</script>