<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'auction')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">

            <div class="jp_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">当前价</span><span class="ys_span3">竞拍操作</span><span class="ys_span3">拍卖时间</span>
            </div>

            <div id="auctions-list">

            </div>

        </div>
    </div>
</div>
<?php
    echo $this->render('/front/product/set-proxy-price');
    echo $this->render('/front/product/post-price');
?>
<script>
    $(function(){


        $(document).on('click', '.set-proxy-price-btn', function(){
            layer.open({
                skin: 'loginBox',
                title:'设置代理价',
                type: 1,
                content: $('#set-proxy-price').html()
            });
            var proxyPrice = $(this).attr('proxy-price');
            var productID = $(this).attr('product-id');
            $('input[name=proxy-price]:visible').val(proxyPrice);
            $('.submit-set-proxy-price:visible').attr('product-id', productID);
        });
        $(document).on('click', '#set-proxy-price-btn', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.proxyPrice = $('input[name=proxy-price]:visible').val();
            $.ajax({
                url : '/auction/set-proxy-price',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg, function(){location.reload();});
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });

        $(document).on('click', '.post-price-btn', function(){
            layer.open({
                skin: 'loginBox',
                title:'出价',
                type: 1,
                content: $('#post-price').html()
            });
            var postPrice = parseFloat($(this).attr('curr-price')) + parseFloat($(this).attr('auction-per-price'));
            var productID = $(this).attr('product-id');
            $('input[name=post-price]:visible').val(postPrice);
            $('.submit-post-price:visible').attr('product-id', productID);
        });
        $(document).on('click', '#post-price-btn', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.auctionPrice = $('input[name=post-price]:visible').val();
            $.ajax({
                url : '/auction/bidding',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg, function(){location.reload();});
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });



    })

    function refreshAuctionList(){
        $('#auctions-list').load('/member/auction-list');
    }
    refreshAuctionList();
    setInterval('refreshAuctionList()', 3000);
</script>