<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'auction')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">

            <div class="jp_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">当前价</span><span class="ys_span3">竞拍操作</span><span class="ys_span3">拍卖时间</span>
            </div>

            <?php
            foreach($auctions as $v){
                ?>
                <div class="ys_tip2 refresh-product-<?php echo $v['productID'] ?>">
                    <div class="ys_tip3">
                        <div class="ys_tip4">
                            <span class="yc_pm1">[拍卖时间] <?php echo date('Y-m-d', $v['startTime']) ?></span>
                            <span class="yc_pm2"><img src="<?php echo $v['storeLogo'] ?>" alt=""><em><?php echo $v['storeName'] ?></em></span>
                            <span class="yc_pm31 lxmj"><a qq="<?php echo $v['storeqq']; ?>" href="javascript:;" class="tencent-qq">在线咨询</a></span>
                        </div>
                        <div class="ys_tip6">
                            <div class="yc_imgleft"><img style="cursor:pointer;" onclick="location.href='/product/detail?productID=<?php echo $v['productID'] ?>';" src="<?php echo $v['listImg']; ?>"></div>
                            <div class="yc_imgleft1">
                                <p class="yc_imgleft2"><span class="yc_ysname"><?php echo $v['productName'] ?></span> <span
                                        class="yc_money ff7 refresh-product-curr-price">￥<?php echo $v['currPrice'] ?></span></p>

                                <div class="yc_ysname1">
                                    <p><span class="yc_ysname">加价幅度</span> <span class="yc_money"><?php echo $v['auctionPerPrice'] ?></span></p>
                                </div>
                            </div>
                            <div class="yc_ddfk yc_imgleft2 refresh-product-middle">
                                <?php
                                /*if(!empty($v['proxyPrice']) && $v['currPrice'] > $v['proxyPrice']){
                                    */?><!--
                                    <a href="javascript:;">
                                        <div class="gz_ccdlj">超出代理价</div>
                                    </a>
                                --><?php
/*                                }else*/if($v['currPrice'] > $v['myCurrPrice']){
                                    ?>
                                    <a href="javascript:;" class="post-price-btn" product-id="<?php echo $v['productID'];?>" auction-per-price="<?php echo $v['auctionPerPrice'] ?>" curr-price="<?php echo $v['currPrice']; ?>">
                                        <div class="njp_cj">出价</div>
                                    </a>
                                <?php
                                }elseif($v['currPrice'] <= $v['myCurrPrice']){
                                    ?>
                                    <a href="javascript:;">
                                        <div class="gz_lx">领先</div>
                                    </a>
                                <?php
                                }
                                ?>


                                <div class="gz_jiaru gz_gr"><a href="javascript:;" proxy-price="<?php echo $v['proxyPrice'] ?>" class="set-proxy-price-btn" product-id="<?php echo $v['productID'];?>">设置代理价></a></div>
                            </div>
                            <div class="yc_ddright yc_imgleft2">

                                <p class="yc_p refresh-product-right"><?php
                                    /*if(!empty($v['proxyPrice']) && $v['currPrice'] > $v['proxyPrice']){
                                        echo '竞价已超出代理价';
                                    }else*/if($v['currPrice'] > $v['myCurrPrice']){
                                        echo '出价已被超越';
                                    }elseif($v['currPrice'] <= $v['myCurrPrice']){
                                        echo '当前为最高价';
                                    }
                                    ?></p>

                                <p class="yc_p">距结束：</p>

                                <p class="yc_p yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>">

                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            <?php
            }
            ?>

        </div>
    </div>
</div>
<?php
    echo $this->render('/front/product/set-proxy-price');
    echo $this->render('/front/product/post-price');
?>
<script>
    $(function(){

        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'member-auction')
        });

        $(document).on('click', '.set-proxy-price-btn', function(){
            layer.open({
                skin: 'loginBox',
                title:'设置代理价',
                type: 1,
                content: $('#set-proxy-price').html()
            });
            var proxyPrice = $(this).attr('proxy-price');
            var productID = $(this).attr('product-id');
            $('input[name=proxy-price]:visible').val(proxyPrice);
            $('.submit-set-proxy-price:visible').attr('product-id', productID);
        });
        $(document).on('click', '#set-proxy-price-btn', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.proxyPrice = $('input[name=proxy-price]:visible').val();
            $.ajax({
                url : '/auction/set-proxy-price',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg, function(){location.reload();});
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });

        $(document).on('click', '.post-price-btn', function(){
            layer.open({
                skin: 'loginBox',
                title:'出价',
                type: 1,
                content: $('#post-price').html()
            });
            var postPrice = parseFloat($(this).attr('curr-price')) + parseFloat($(this).attr('auction-per-price'));
            var productID = $(this).attr('product-id');
            $('input[name=post-price]:visible').val(postPrice);
            $('.submit-post-price:visible').attr('product-id', productID);
        });
        $(document).on('click', '#post-price-btn', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.auctionPrice = $('input[name=post-price]:visible').val();
            $.ajax({
                url : '/auction/bidding',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg, function(){location.reload();});
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });
    });
    function refreshAuctionList(){
        $.ajax({
            url : '/member/auction',
            dataType : 'json',
            type : 'post',
            success : function(res){
                var result = res.data;

                for(var i in result){
                    var tmp = result[i];
                    var currPrice = parseFloat(tmp['currPrice']);
                    var myCurrPrice = parseFloat(tmp['myCurrPrice']);
                    var div = $('.refresh-product-' + tmp['productID']);
                    var middle = '';
                    var right = '';
                    div.find('.refresh-product-curr-price').html(tmp['currPrice']);

                    /*if(tmp['proxyPrice'] && currPrice > tmp['proxyPrice']){
                        middle += '<a href="javascript:;"><div class="gz_ccdlj">超出代理价</div></a>';
                    }else */if(currPrice > myCurrPrice){
                        middle += '<a href="javascript:;" class="post-price-btn" product-id="' + tmp['productID'] + '" auction-per-price="' + tmp['auctionPerPrice'] + '" curr-price="' + tmp['currPrice'] + '"><div class="njp_cj">出价</div></a>';
                    }else if(currPrice <= myCurrPrice){
                        middle += '<a href="javascript:;"><div class="gz_lx">领先</div></a>';
                    }
                    middle += '<div class="gz_jiaru gz_gr"><a href="javascript:;" proxy-price="' + tmp['proxyPrice'] + '" class="set-proxy-price-btn" product-id="' + tmp['productID'] + '">设置代理价></a></div>';


                    /*if(tmp['proxyPrice'] && currPrice > tmp['proxyPrice']){
                        right += '竞价已超出代理价';
                    }else */if(currPrice > myCurrPrice){
                        right += '出价已被超越';
                    }else if(currPrice <= myCurrPrice){
                        right += '当前为最高价';
                    }


                    div.find('.refresh-product-middle').html(middle);
                    div.find('.refresh-product-right').html(right);
                }
            }
        });
    }
    refreshAuctionList();
    setInterval('refreshAuctionList()', 5000);
</script>