<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'auction')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">

            <div class="jp_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">当前价</span><span class="ys_span3">竞拍操作</span><span class="ys_span3">拍卖时间</span>
            </div>

            <?php
                foreach($auctions as $v){
            ?>
                    <div class="ys_tip2">
                        <div class="ys_tip3">
                            <div class="ys_tip4">
                                <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "></span>
                                <span class="yc_pm1">[拍卖时间] <?php echo date('Y-m-d', $v['startTime']) ?></span>
                                <span class="yc_pm2"><?php echo $v['storeName'] ?></span>
                                <span class="yc_pm31 lxmj"><a href="">在线咨询</a></span>
                                <span class="yc_pm5"><a href="">删除</a></span>
                            </div>
                            <div class="ys_tip6">
                                <div class="yc_imgleft"><img src="<?php echo $v['listImg']; ?>"></div>
                                <div class="yc_imgleft1">
                                    <p class="yc_imgleft2"><span class="yc_ysname"><?php echo $v['productName'] ?></span> <span
                                            class="yc_money ff7">￥<?php echo $v['currPrice'] ?></span></p>

                                    <div class="yc_ysname1">
                                        <p><span class="yc_ysname">加价幅度</span> <span class="yc_money"><?php echo $v['auctionPerPrice'] ?></span></p>
                                    </div>
                                </div>
                                <div class="yc_ddfk yc_imgleft2">
                                    <?php
                                        if($v['currPrice'] > $v['proxyPrice']){
                                    ?>
                                            <a href="">
                                                <div class="gz_ccdlj">超出代理价</div>
                                            </a>
                                    <?php
                                        }elseif($v['currPrice'] > $v['myCurrPrice']){
                                    ?>
                                            <a href="">
                                                <div class="njp_cj">出价</div>
                                            </a>
                                    <?php
                                        }elseif($v['currPrice'] < $v['myCurrPrice']){
                                    ?>
                                            <a href="">
                                                <div class="gz_lx">领先</div>
                                            </a>
                                    <?php
                                        }
                                    ?>


                                    <div class="gz_jiaru gz_gr"><a href="">设置代理价></a></div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <?php
                                    if($v['currPrice'] > $v['proxyPrice']){
                                    ?>
                                        <p class="yc_p">竞价已超出代理价</p>
                                    <?php
                                    }elseif($v['currPrice'] > $v['myCurrPrice']){
                                    ?>
                                        <p class="yc_p">出价已被超越</p>
                                    <?php
                                    }elseif($v['currPrice'] < $v['myCurrPrice']){
                                    ?>
                                        <p class="yc_p">当前为最高价</p>
                                    <?php
                                    }
                                    ?>


                                    <p class="yc_p">距结束：</p>

                                    <p class="yc_p yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>">

                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
            <?php
                }
            ?>

        </div>
    </div>
</div>

<script>
    $(function(){
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'member-auction')
        });
    })
</script>