<?php
foreach($auctions as $v){
    ?>
    <div class="ys_tip2">
        <div class="ys_tip3">
            <div class="ys_tip4">
                <span class="yc_pm1">[拍卖时间] <?php echo date('Y-m-d', $v['startTime']) ?></span>
                <span class="yc_pm2"><img src="<?php echo $v['storeLogo'] ?>" alt=""><em><?php echo $v['storeName'] ?></em></span>
                <span class="yc_pm31 lxmj"><a qq="<?php echo $v['storeqq']; ?>" href="javascript:;" class="tencent-qq">在线咨询</a></span>
            </div>
            <div class="ys_tip6">
                <div class="yc_imgleft"><img style="cursor:pointer;" onclick="location.href='/product/detail?productID=<?php echo $v['productID'] ?>';" src="<?php echo $v['listImg']; ?>"></div>
                <div class="yc_imgleft1">
                    <p class="yc_imgleft2"><span class="yc_ysname"><?php echo $v['productName'] ?></span> <span
                            class="yc_money ff7">￥<?php echo $v['currPrice'] ?></span></p>

                    <div class="yc_ysname1">
                        <p><span class="yc_ysname">加价幅度</span> <span class="yc_money"><?php echo $v['auctionPerPrice'] ?></span></p>
                    </div>
                </div>
                <div class="yc_ddfk yc_imgleft2">
                    <?php
                    if(!empty($v['proxyPrice']) && $v['currPrice'] > $v['proxyPrice']){
                        ?>
                        <a href="">
                            <div class="gz_ccdlj">超出代理价</div>
                        </a>
                    <?php
                    }elseif($v['currPrice'] > $v['myCurrPrice']){
                        ?>
                        <a href="javascript:;" class="post-price-btn" product-id="<?php echo $v['productID'];?>" auction-per-price="<?php echo $v['auctionPerPrice'] ?>" curr-price="<?php echo $v['currPrice']; ?>">
                            <div class="njp_cj">出价</div>
                        </a>
                    <?php
                    }elseif($v['currPrice'] <= $v['myCurrPrice']){
                        ?>
                        <a href="">
                            <div class="gz_lx">领先</div>
                        </a>
                    <?php
                    }
                    ?>


                    <div class="gz_jiaru gz_gr"><a href="javascript:;" proxy-price="<?php echo $v['proxyPrice'] ?>" class="set-proxy-price-btn" product-id="<?php echo $v['productID'];?>">设置代理价></a></div>
                </div>
                <div class="yc_ddright yc_imgleft2">
                    <?php
                    if(!empty($v['proxyPrice']) && $v['currPrice'] > $v['proxyPrice']){
                        ?>
                        <p class="yc_p">竞价已超出代理价</p>
                    <?php
                    }elseif($v['currPrice'] > $v['myCurrPrice']){
                        ?>
                        <p class="yc_p">出价已被超越</p>
                    <?php
                    }elseif($v['currPrice'] <= $v['myCurrPrice']){
                        ?>
                        <p class="yc_p">当前为最高价</p>
                    <?php
                    }
                    ?>


                    <p class="yc_p">距结束：</p>

                    <p class="yc_p yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>">

                    </p>
                </div>
            </div>
        </div>
    </div>
<?php
}
?>

<script>
    $(".yomibox2").each(function () {
        $(this).yomi(_CurrentServerTime, 'member-auction')
    });
</script>