<div id="edit-password-div" class="hide">
    <div class="loginPop fr">

        <form method="post">
            <span style="color: red;"></span>

            <div class="inputBox">
                <input name="old-pwd" placeholder="请输入原密码" type="password" value=""/>
            </div>
            <div class="inputBox">
                <input name="new-pwd" placeholder="请输入新密码" type="password" value=""/>
            </div>
            <div class="inputBox">
                <input name="confirm-new-pwd" placeholder="请再次输入新密码" type="password" value=""/>
            </div>

            <input type="button" class="submit edit-password-confirm-btn" value="提交">
        </form>
    </div>
</div>