<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <div class="kp_left">
            <div class="kp_biaot">
                <p class="kp_p">我是买家</p>
                <ul class="kp_ul mt10">
                    <a href="正在竞拍.html">
                        <li>正在竞拍</li>
                    </a>
                    <a href="已购拍品.html">
                        <li>已购拍品</li>
                    </a>
                    <a href="关注拍品.html">
                        <li>关注拍品</li>
                    </a>
                    <a href="关注商家.html">
                        <li class="kp_checked">关注商家</li>
                    </a>
                    <a href="">
                        <li>买家须知</li>
                    </a>
                </ul>
            </div>
            <div class="kp_biaot">
                <p class="kp_p kpdh2">我是商家</p>
                <ul class="kp_ul mt10">
                    <a href="发布拍品.html">
                        <li>发布拍品</li>
                    </a>
                    <a href="拍品仓库.html">
                        <li>拍品仓库</li>
                    </a>
                    <a href="管理专场.html">
                        <li>管理专场</li>
                    </a>
                    <a href="已售拍品.html">
                        <li>已售拍品</li>
                    </a>
                    <a href="商家设置.html">
                        <li>商家设置</li>
                    </a>
                    <a href="认证流程.html">
                        <li>认证流程</li>
                    </a>
                </ul>
            </div>
        </div>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li class="ys_searhc1"><input class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc">搜索</li>
                    <li class="gzsj_qx">取消关注</li>
                    <li><img src="images/del_03.jpg"></li>
                </ul>
            </div>
            <div class="gzsj_li">
                <ul>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                </ul>
            </div>


        </div>


    </div>
</div>