<script src="/plugins/superSlide/jquery.SuperSlide.2.1.1.js"></script>
<!--main开始-->
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'interest-product')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top11">
                <ul>
                    <li class="<?php if(empty($auctionStatus)){echo 'ys_acted'; } ?>" onclick="location.href='/member/interest-product';">所有关注</a></li>
                    <li class="<?php if($auctionStatus == 2){echo 'ys_acted'; } ?>" onclick="location.href='/member/interest-product?auctionStatus=2';">正在进行</li>
                    <li class="<?php if($auctionStatus == 1){echo 'ys_acted'; } ?>" onclick="location.href='/member/interest-product?auctionStatus=1';">即将进行</li>
                    <li class="<?php if($auctionStatus == 3){echo 'ys_acted'; } ?>" onclick="location.href='/member/interest-product?auctionStatus=3';">已结束</li>
                    <li><img src="/dist/images/del_03.png" class="remove-interest-product-batch"></li>
                    <li class="ys_searhc1"><input id="search-item" class="ys_input" value="<?php echo $search; ?>" type="text" placeholder="输入拍品名称"></li>
                    <li class="ys_searhc" id="search-btn">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">竞拍价</span><span class="ys_span3">拍品状态</span><span
                    class="ys_span3">拍卖时间</span>
            </div>
            <?php
                foreach($products as $v){
            ?>
                    <div class="ys_tip2" id="interest-product-<?php echo $v['productID'] ?>">
                        <div class="ys_tip3">
                            <div class="ys_tip4">
                                <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox interest-product-chk" product-id="<?php echo $v['productID'] ?>">  </span>
                                <span class="yc_pm1">[拍卖时间] <?php echo date('Y-m-d', $v['startTime']) ?></span>
                                <span class="yc_pm2"><img src="<?php echo $v['storeLogo'] ?>" alt=""><em><?php echo $v['storeName'] ?></em></span>
                                <span class="yc_pm31 lxmj"><a qq="<?php echo $v['storeqq']; ?>" href="javascript:;" class="tencent-qq">在线咨询</a></span>
                                <span class="yc_pm5"><a href="javascript:;" product-id="<?php echo $v['productID'] ?>" class="remove-interest-product">删除</a></span>
                            </div>
                            <div class="ys_tip6">
                                <div class="yc_imgleft"><img style="cursor:pointer;" onclick="window.open('/product/detail?productID=<?php echo $v['productID'] ?>');" src="<?php echo $v['listImg']; ?>"></div>
                                <div class="yc_imgleft1">
                                    <p class="yc_dqj">当前价</p>

                                    <p><span class="yc_ysname text-left"><?php echo $v['productName'] ?></span> <span class="yc_money ff7">￥<?php echo $v['currPrice'] ?></span></p>

                                    <div class="yc_ysname1">

                                        <p><span class="yc_ysname">佣金</span> <span class="yc_money"><?php echo !empty($v['commision']) ?  $v['commision'] : 0; ?>%</span></p>

                                        <p><span class="yc_ysname">加价幅度</span> <span class="yc_money"><?php echo $v['auctionPerPrice'] ?></span></p>
                                    </div>
                                </div>

                                    <?php
                                    if($v['auctionStatus'] == 2){
                                    ?>
                                        <div class="yc_ddfk yc_imgleft2">
                                            <div class="gz_zzjx">正在进行</div>

                                            <?php
                                            if(!empty($v['auctionMemberID'])){
                                                ?>
                                                <div class="gz_jiaru">已加入拍卖</div>
                                                <div class="gz_gr"><a href="/member/auction">进入个人</a></div>
                                                <div class="gz_gr"><a href="/member/auction">竞拍列表>></a></div>
                                            <?php
                                            }else{
                                            ?>
                                                <a href="javascript:;" class="join-auction-btn" product-id="<?php echo $v['productID'] ?>">
                                                    <div class="gz_ljjr">立即<br/>加入</div>
                                                </a>
                                            <?php
                                            }
                                            ?>
                                        </div>
                                        <div class="yc_ddright yc_imgleft2">
                                            <p class="yc_p">距结束</p>

                                            <p class="yc_p yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>"></p>
                                        </div>
                                    <?php
                                    }elseif($v['auctionStatus'] == 1 || empty($v['auctionStatus'])){
                                    ?>
                                        <div class="yc_ddfk yc_imgleft2">
                                            <div class="yc_ddfk yc_imgleft2">
                                                <div class="gz_jjjx">即将进行</div>
                                            </div>
                                        </div>
                                        <div class="yc_ddright yc_imgleft2">
                                            <p class="yc_p">开始时间</p>

                                            <p class="yc_p"><span class="gz_shi"><?php echo date('m', $v['startTime']); ?></span><span class="gz_shi1">月</span><span
                                                    class="gz_shi"><?php echo date('d', $v['startTime']); ?></span><span class="gz_shi1">日</span><span class="gz_shi"><?php echo date('H:i', $v['startTime']); ?></span></p>
                                        </div>
                                    <?php
                                    }elseif($v['auctionStatus'] == 3){
                                    ?>
                                        <div class="yc_ddfk yc_imgleft2">

                                            <div class="yc_ddfk yc_imgleft2">
                                                <div class="gz_yjs">已结束</div>
                                            </div>
                                        </div>
                                        <div class="yc_ddright yc_imgleft2">
                                            <p class="yc_p">结束时间</p>

                                            <p class="yc_p"><span class="gz_shi"><?php echo date('m', $v['endTime']); ?></span><span class="gz_shi1">月</span><span
                                                    class="gz_shi"><?php echo date('d', $v['endTime']); ?></span><span class="gz_shi1">日</span><span class="gz_shi"><?php echo date('H:i', $v['endTime']); ?></span></p>
                                        </div>
                                    <?php
                                    }
                                    ?>




                            </div>
                        </div>
                    </div>
            <?php
                }
            ?>
            <?php echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/member/interest-product?auctionStatus=' . $auctionStatus . '&')); ?>
        </div>
    </div>
</div>
<?php if(!empty($memberRecommendProducts)){echo $this->render('member-recommend');}  ?>
<script>

    $(function(){
        $('.join-auction-btn').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            $.ajax({
                url : '/auction/attend',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    layer.alert(response.msg);
                }
            });
        });

        function removeInterestProduct(data){
            $.ajax({
                url : '/member/remove-interest-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    layer.alert(response.msg);
                }
            });
        }

        $('.remove-interest-product').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            $('#interest-product-' + data.productID).remove();
            removeInterestProduct(data);

        });

        $('.remove-interest-product-batch').on('click', function(){
            var data = {};
            data.productID = new Array();
            var checkedProducts = $('.interest-product-chk:checked');
            if(!checkedProducts.length){
                layer.alert('请选择要取消关注的拍品');
                return false;
            }
            checkedProducts.each(function(){
                var tmp = $(this).attr('product-id');
                data.productID.push(tmp);
                $('#interest-product-' + tmp).remove();
            });
            removeInterestProduct(data);
        });

        $('#search-btn').on('click', function(){
            var search = $('#search-item').val();
            if(!search){
                layer.alert('请输入搜索内容');
                return false;
            }
            location.href = '/member/interest-product?search=' + search;
        });

        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'member-auction')
        });
    })
</script>