<!--main开始-->
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'interest-product')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top11">
                <ul>
                    <li class="ys_acted">所有关注</a></li>
                    <li>正在进行</li>
                    <li>即将进行</li>
                    <li class="gz_js">已结束</li>
                    <li><img src="images/del_03.jpg"></li>
                    <li class="ys_searhc1"><input class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">竞拍价</span><span class="ys_span3">拍品状态</span><span
                    class="ys_span3">拍卖时间</span>
            </div>
            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox ">  </span>
                        <span class="yc_pm1">[拍卖时间] 2015-10-06</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm31 lxmj"><a href="">在线咨询</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_dqj">当前价</p>

                            <p><span class="yc_ysname">西泠印社  李萍《妙招自然》</span> <span class="yc_money ff7">￥5000</span></p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5%</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="gz_zzjx">正在进行</div>
                            <div class="gz_jiaru">已加入拍卖</div>
                            <div class="gz_gr"><a href="">进入个人</a></div>
                            <div class="gz_gr"><a href="">竞拍列表>></a></div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p">距结束</p>

                            <p class="yc_p"><span class="gz_shi">08</span><span class="gz_shi1">时</span><span
                                    class="gz_shi">08</span><span class="gz_shi1">分</span><span class="gz_shi">08</span><span
                                    class="gz_shi1">秒</span></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox ">  </span>
                        <span class="yc_pm1">[拍卖时间] 2015-10-06</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm31 lxmj"><a href="">在线咨询</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_dqj">当前价</p>

                            <p><span class="yc_ysname">西泠印社  李萍《妙招自然》</span> <span class="yc_money ff7">￥5000</span></p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5%</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="gz_zzjx">正在进行</div>
                            <a href="">
                                <div class="gz_ljjr">立即<br/>加入</div>
                            </a>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p">距结束</p>

                            <p class="yc_p"><span class="gz_shi">08</span><span class="gz_shi1">时</span><span
                                    class="gz_shi">08</span><span class="gz_shi1">分</span><span class="gz_shi">08</span><span
                                    class="gz_shi1">秒</span></p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox ">  </span>
                        <span class="yc_pm1">[拍卖时间] 2015-10-06</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm31 lxmj"><a href="">在线咨询</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_dqj">&nbsp;</p>

                            <p><span class="yc_ysname">西泠印社  李萍《妙招自然》</span> <span class="yc_money ff7">￥5000</span></p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5%</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="gz_jjjx">即将进行</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p">开始时间</p>

                            <p class="yc_p"><span class="gz_shi">08</span><span class="gz_shi1">时</span><span
                                    class="gz_shi">08</span><span class="gz_shi1">分</span><span class="gz_shi">08</span><span
                                    class="gz_shi1">秒</span></p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox ">  </span>
                        <span class="yc_pm1">[拍卖时间] 2015-10-06</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm31 lxmj"><a href="">在线咨询</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_dqj">&nbsp;</p>

                            <p><span class="yc_ysname">西泠印社  李萍《妙招自然》</span> <span class="yc_money ff7">￥5000</span></p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5%</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="gz_yjs">已结束</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p">结束时间</p>

                            <p class="yc_p"><span class="gz_shi">08</span><span class="gz_shi1">时</span><span
                                    class="gz_shi">08</span><span class="gz_shi1">分</span><span class="gz_shi">08</span><span
                                    class="gz_shi1">秒</span></p>
                        </div>
                    </div>
                </div>
            </div>


        </div>
    </div>
</div>
