<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'interest-store')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li class="ys_searhc1"><input class="ys_input"  id="search-item" value="<?php echo $search ?>" type="text" placeholder="输入商家名称"></li>
                    <li class="ys_searhc" id="search-btn">搜索</li>
                    <li class="gzsj_qx">&nbsp;</li>
                    <li class="remove-interest-store-batch"><img src="/jinren/images/del_03.jpg"></li>
                </ul>
            </div>
            <div class="gzsj_li">
                <ul>
                    <?php
                        foreach($stores as $v){
                    ?>
                            <li id="interest-store-<?php echo $v['storeID'] ?>" style="cursor: pointer;" onclick="location.href='/store/detail?storeID=<?php echo $v['storeID'] ?>';">
                                <input type="checkbox" name="checkbox1" value="checkbox" store-id="<?php echo $v['storeID'] ?>" class="ind_checkbox add_lefimg01 interest-store-chk">

                                <div class="gzsj_liimg"><img src="<?php echo $v['storeLogo'] ?>"></div>
                                <div class="gzsj_litit"><?php echo $v['storeName'] ?></div>
                            </li>
                    <?php
                        }
                    ?>
                </ul>
            </div>
            <br style="clear:both;" />
            <?php
            echo $this->render('/front/common/paginate', array('url' => '/member/interest-store?', 'pages' => $pages));
            ?>
        </div>


    </div>
</div>

<script>

    $(function(){
        function removeInterestStore(data){
            $.ajax({
                url : '/member/remove-interest-store',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    layer.alert(response.msg);
                }
            });
        }

        $('.remove-interest-store-batch').on('click', function(){
            var data = {};
            data.storeID = new Array();
            var checkedStore = $('.interest-store-chk:checked');
            if(!checkedStore.length){
                layer.alert('请选择要取消关注的店铺');
                return false;
            }
            checkedStore.each(function(){
                var tmp = $(this).attr('store-id');
                data.storeID.push(tmp);
                $('#interest-store-' + tmp).remove();
            });
            removeInterestStore(data);
        });

        $('#search-btn').on('click', function(){
            var search = $('#search-item').val();
            if(!search){
                layer.alert('请输入搜索内容');
                return false;
            }
            location.href = '/member/interest-store?search=' + search;
        });
    })
</script>