<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'interest-supplier')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li class="ys_searhc1"><input class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc">搜索</li>
                    <li class="gzsj_qx">取消关注</li>
                    <li><img src="images/del_03.jpg"></li>
                </ul>
            </div>
            <div class="gzsj_li">
                <ul>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>
                    <li>
                        <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox  add_lefimg01">

                        <div class="gzsj_liimg"><img src="images/yp_03.png"></div>
                        <div class="gzsj_litit">开源拍卖</div>
                    </li>


                </ul>
            </div>


        </div>


    </div>
</div>