<div class="kp_left">
    <div class="kp_biaot">
        <p class="kp_p" id="kpdh">我是买家</p>
        <ul class="kp_ul mt10" id="kpdh1">
            <a href="/member/auction">
                <li <?php if($leftTab == 'auction'){ ?> class="kp_checked" <?php } ?>>正在竞拍</li>
            </a>
            <a href="/member/order">
                <li <?php if($leftTab == 'order'){ ?> class="kp_checked" <?php } ?>>已购拍品</li>
            </a>
            <a href="/member/interest-product">
                <li <?php if($leftTab == 'interest-product'){ ?> class="kp_checked" <?php } ?>>关注拍品</li>
            </a>
            <a href="/member/interest-store">
                <li <?php if($leftTab == 'interest-store'){ ?> class="kp_checked" <?php } ?>>关注商家</li>
            </a>
            <a href="/member/note">
                <li <?php if($leftTab == 'note'){ ?> class="kp_checked" <?php } ?>>买家须知</li>
            </a>
        </ul>
    </div>
    <div class="kp_biaot">
        <p class="kp_p">我是商家</p>
        <ul class="kp_ul mt10">
            <a href="/member/add-product">
                <li <?php if($leftTab == 'add-product'){ ?> class="kp_checked" <?php } ?>>发布拍品</li>
            </a>
            <a href="/member/product">
                <li <?php if($leftTab == 'product'){ ?> class="kp_checked" <?php } ?>>拍品仓库</li>
            </a>
            <a href="/member/special">
                <li <?php if($leftTab == 'special'){ ?> class="kp_checked" <?php } ?>>管理专场</li>
            </a>
            <a href="/member/store-order">
                <li <?php if($leftTab == 'store-order'){ ?> class="kp_checked" <?php } ?>>已售拍品</li>
            </a>
            <a href="/member/store-setting">
                <li <?php if($leftTab == 'store-setting'){ ?> class="kp_checked" <?php } ?>>商家设置</li>
            </a>
            <a href="/member/store-join">
                <li <?php if($leftTab == 'store-join'){ ?> class="kp_checked" <?php } ?>>认证流程</li>
            </a>
            <a href="/member/my-store">
                <li <?php if($leftTab == 'my-store'){ ?> class="kp_checked" <?php } ?>>进入店铺</li>
            </a>
        </ul>
    </div>
</div>