<!--main开始-->
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <div class="kp_left">
            <div class="kp_biaot">
                <p class="kp_p">站内提醒 (<span class="kp_tixxm"><?php echo $_memberInfo['notReadCount'] ?  $_memberInfo['notReadCount'] : 0?></span>)</p>
                <ul class="kp_ul mt10">
                    <a href="/member/notification?type=1">
                        <li>网站公告</li>
                    </a>
                    <a href="/member/notification?type=2">
                        <li>加盟审核提醒</li>
                    </a>
                    <a href="/member/notification?type=3">
                        <li>拍卖提醒</li>
                    </a>
                    <a href="/member/notification?type=4">
                        <li>订单提醒</li>
                    </a>
                    <a href="/member/notification?type=5">
                        <li>空间提醒</li>
                    </a>
                </ul>
                <p class="kp_tixing" style="color:#444;">* 网站公告永久保存查询。拍卖提醒查询仅提供最近三天，订单提醒查询仅提供最近一个月信息</p>
            </div>

        </div>
        <!-- right部分 -->
        <div class="kp_right kp_back">
            <ul>
                <?php foreach($notifications as $v){
                ?>
                    <li><?php echo $v['content'] ?>（<?php echo $v['instime']; ?>）</li>
                <?php
                } ?>
            </ul>
            <?php
                if(!empty($notifications)){
                    echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/member/notification?type=' . $type . '&'));
                }

            ?>

        </div>


    </div>
</div>

