<!--main开始-->
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <div class="kp_left">
            <div class="kp_biaot">
                <p class="kp_p">站内提醒 (<span class="kp_tixxm">3</span>)</p>
                <ul class="kp_ul mt10">
                    <a href="">
                        <li>站内通知</li>
                    </a>
                    <a href="">
                        <li>拍卖提醒</li>
                    </a>
                    <a href="">
                        <li>订单提醒</li>
                    </a>
                    <a href="">
                        <li>留言板提醒</li>
                    </a>
                </ul>
                <p class="kp_tixing">* 网站公告永久保存查询。拍卖提醒查询仅提供最近三天，订单提醒查询仅提供最近一个月信息</p>
            </div>

        </div>
        <!-- right部分 -->
        <div class="kp_right kp_back">
            <ul>
                <li>您所竞买的拍品“吴山明《行书对联》”已成功竞得，请至您的的已购拍品列表中查询。并请于48小时内付款，逾期将自动关闭交易。（2016-1-19 22:00）</li>
                <li>您所关注的拍品“金恩楠《鹿鸣》”拍卖结束，竞价失败。（2016-1-12 20:40）</li>
                <li>您所关注的拍品“方国梁《室雅》”将在20分钟后结束拍卖。（2016-1-12 20:40）</li>
            </ul>


        </div>


    </div>
</div>

