<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php
            if(!empty($storeView)){
                echo $this->render('left', array('leftTab' => 'store-order'));
            }else{
                echo $this->render('left', array('leftTab' => 'order'));
            }
        ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="yg_pp">
                <div class="yc_pm41">
                    <span class="yc_pm1n">[订单号] <?php echo $info['businessID'] ?></span>
                    <?php
                    if(!empty($storeView)){
                    ?>
                        <span class="yc_pm2" style="background: none;"><?php echo $info['nickName'] ?></span>
                        <span class="yc_pm3 lxmj1 "><a href="tencent://message/?uin=<?php echo $info['qq'] ?>&Site=www.kaipai123.com&Menu=yes">联系买家</a></span>

                    <?php
                    }else{
                    ?>
                        <span class="yc_pm2" style="background: transparent url('<?php echo $info['storeLogo'] ?>') no-repeat scroll 6% center"><?php echo $info['storeName'] ?></span>
                        <span class="yc_pm3 lxmj1 "><a href="tencent://message/?uin=<?php echo $info['storeqq'] ?>&Site=www.kaipai123.com&Menu=yes">联系卖家</a></span>
                    <?php
                    }
                    ?>

                    <span class="yc_pm44">成交时间</span>
                </div>
                <div class="yg_ppname">
                    <div class="yg_ppname_left"><img src="<?php echo $info['product']['listImg'] ?>"></div>
                    <div class="yg_ppname_right">
                        <div class="yg_ppname_right1">
                            <div class="yg_ppname1"><p><?php echo $info['product']['productName'] ?></p>

                                </div>
                            <div class="yg_ppname2"><?php echo date('Y-m-d', strtotime($info['instime'])) ?><br> <?php echo date('H:i', strtotime($info['instime'])) ?></div>
                        </div>
                        <div class="yg_ppname3">成交价：<?php echo $info['productPrice'] ?>元 运费：<?php echo $info['deliveryPrice'] ?>元 佣金：<?php echo $info['commision'] ?>元</div>
                    </div>
                </div>

                <?php if(in_array($info['orderStatus'], array(1, 5)) && empty($storeView)){ ?>
                    <?php if($info['orderStatus'] == 1){ ?>
                        <div id="member-delivery-list">

                        </div>

                        <div class="yg_addresbtn add-member-delivery-btn">添加新地址</div>
                        <div class="yg_bz">
                            <div class="yc_ly">留言备注</div>
                            <textarea class="order-remark"></textarea>
                        </div>

                        <div class="yg_fk">
                            付款金额 <?php echo $info['payMoney']; ?> <span class="yg_sfmoney1">实付金额</span><span class="yg_sfmoney"><?php echo $info['payMoney']; ?></span>
                        </div>
                        <div class="yg_zf">
                            <ul class="order-detail-pay-list">
                                <li class="" pay-type="1"><img src="/jinren/images/zf_03.png"> 余额支付</li>
                                <li class="" pay-type="2"><img src="/jinren/images/zf_06.png"> 支付宝</li>
                                <!--<li class="fix_mor"><img src="images/zf_12.png"> 微信钱包</li>-->
                                <li class="" pay-type="3"><img src="/jinren/images/zf_14.png" style="width:52px;height:51px;"> 银联支付</li>
                                <li class="" pay-type="4"><img src="/jinren/images/zf_20.png"> 银行汇款</li>
                            </ul>
                        </div>
                    <?php }else{
                    ?>
                        <div class="yg_fk">
                            尾款金额 <?php echo $info['finalPrice']; ?> <span class="yg_sfmoney1">实付金额</span><span class="yg_sfmoney"><?php echo $info['finalPrice']; ?></span>
                        </div>
                        <div class="yg_zf">
                            <ul class="order-detail-pay-list">
                                <li class="" pay-type="1"><img src="/jinren/images/zf_03.png"> 余额支付</li>
                                <li class="" pay-type="2"><img src="/jinren/images/zf_06.png"> 支付宝</li>
                                <!--<li class="fix_mor"><img src="images/zf_12.png"> 微信钱包</li>-->
                                <li class="" pay-type="3"><img src="/jinren/images/zf_14.png" style="width:52px;height:51px;"> 银联支付</li>
                                <li class="" pay-type="4"><img src="/jinren/images/zf_20.png"> 银行汇款</li>
                            </ul>
                        </div>
                    <?php
                    }  ?>

                <?php }elseif($info['orderStatus'] >= 4){
                    ?>
                    <div class="yg_addres">
                        <div class="">
                            <div class="yg_addres_left1"></div>
                            <div class="yg_addres_left2">
                                <p class="yg_sjr">收货人：<?php echo $info['receiverName'] ?> <?php echo $info['receiverMobile'] ?></p>

                                <p class="yg_sjr">收货地址：<?php echo $info['receiverAddr']; ?></p>
                                <p class="yg_sjr">快递：<?php echo $info['typeName']; ?></p>
                                <p class="yg_sjr">运单号码：<?php echo $info['deliveryNum']; ?></p>
                            </div>
                        </div>
                    </div>
                <?php
                } ?>
            </div>
            <?php if(in_array($info['orderStatus'], array(1, 5)) && empty($storeView)){ ?>
                <?php if($info['orderStatus'] == 1){
                ?>
                    <div class="yg_qrzf">
                        <a href="javascript:;" id="confirm-pay-btn"><span class="yg_qrzf1"> 确认支付</span></a>
                        <!--<a href=""><span class="yg_qrzf2"> 稍后付款</span></a>-->
                    </div>
                <?php
                }else{
                ?>
                    <div class="yg_qrzf">
                        <a href="javascript:;" id="confirm-pay-final-btn"><span class="yg_qrzf1"> 确认支付</span></a>
                        <!--<a href=""><span class="yg_qrzf2"> 稍后付款</span></a>-->
                    </div>
                <?php
                } ?>

            <?php
            } ?>
        </div>
    </div>
</div>

<div id="add-member-delivery-div" class="hide"  member-delivery-id="">
    <div class="loginPop fr">

        <form method="post">
            <span style="color: red;"></span>

            <div class="inputBox">
                <input name="receiverName" placeholder="收货人姓名" type="text" value=""/>
            </div>

            <div class="inputBox">
                <input name="receiverMobile" placeholder="收货人手机号"/>
            </div>

            <div class="inputBox">
                <input name="receiverAddr" placeholder="收货地址"/>
            </div>

            <input name="member-delivery-submit-button" type="button" class="submit" value="添加">
        </form>
    </div>
</div>

<?php echo $this->render('/front/common/transfer-account'); ?>

<script>
    $(function(){

        function loadMemberDelivery(){
            $('#member-delivery-list').load('/member/member-delivery-list');
        }
        loadMemberDelivery();

        $('.order-detail-pay-list li').on('click', function(){
            $(this).addClass('yg_selected_pay_type').siblings().removeClass('yg_selected_pay_type');
        });

        $('.add-member-delivery-btn').on('click', function(){
            layer.open({
                skin: 'loginBox',
                type: 1,
                title: '添加新地址',
                content: $('#add-member-delivery-div').html()
            });
        });
        $(document).on('click', 'input[name=member-delivery-submit-button]:visible', function(){
            var data = {};
            data.receiverName = $('input[name=receiverName]:visible').val();
            data.receiverMobile = $('input[name=receiverMobile]:visible').val();
            data.receiverAddr = $('input[name=receiverAddr]:visible').val();
            data.memberDeliveryID = $('#add-member-delivery-div').attr('member-delivery-id');
            $.ajax({
                url : '/member/add-member-delivery',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(obj){
                            loadMemberDelivery();
                            layer.closeAll();
                        });
                    }else{
                        layer.alert(res.msg);
                    }


                }
            });
        });
        $(document).on('click', '.edit-member-delivery-btn', function(){

            layer.open({
                skin: 'loginBox',
                type: 1,
                title: '编辑',
                content: $('#add-member-delivery-div').html()
            });
            $('input[name=receiverName]:visible').val($(this).attr('receiver-name'));
            $('input[name=receiverMobile]:visible').val($(this).attr('receiver-mobile'));
            $('input[name=receiverAddr]:visible').val($(this).attr('receiver-addr'));
            $('#add-member-delivery-div').attr('member-delivery-id', $(this).attr('member-delivery-id'));

        });
        $(document).on('click', '.del-member-delivery-btn', function(){
            var data = {};
            data.memberDeliveryID = $(this).attr('member-delivery-id');

            $.ajax({
                url : '/member/del-member-delivery',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    layer.alert(res.msg, function(){
                        $('#member-delivery-' + data.memberDeliveryID).remove();
                        layer.closeAll();
                    });


                }
            });
        });

        $('#confirm-pay-btn').on('click', function() {
            var data = {};
            data.orderID = <?php echo $info['orderID'] ?>;
            data.memberDeliveryID = $('.member-delivery-chk:checked').attr('member-delivery-id');
            if (!data.memberDeliveryID) {
                layer.alert('请选择收货地址');
                return false;
            }
            data.payType = $('.yg_selected_pay_type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            data.orderRemark = $('.order-remark').text();
            $.ajax({
                url : '/order/pay',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            layer.alert('申请开通中');
                            return false;
                            location.href = res.data['coreData'];
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }

                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });
        <?php if(!empty($info['finalUnitePayID'])){ ?>
        $('#confirm-pay-final-btn').on('click', function() {
            var data = {};
            data.unitePayID = <?php echo $info['finalUnitePayID'] ?>;
            data.payType = $('.yg_selected_pay_type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            $.ajax({
                url : '/order/pay-final',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            layer.alert('申请开通中');
                            return false;
                            location.href = res.data['coreData'];
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });
        <?php } ?>
    })
</script>