<script src="/plugins/superSlide/jquery.SuperSlide.2.1.1.js"></script>
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'order')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li onclick="location.href='/member/order';" class="<?php if(empty($orderStatus)){echo 'ys_acted';} ?>">所有订单</a></li>
                    <li onclick="location.href='/member/order?orderStatus=1';" class="<?php if($orderStatus == 1){echo 'ys_acted';} ?>">待付款</li>
                    <li onclick="location.href='/member/order?orderStatus=3';" class="<?php if($orderStatus == 3){echo 'ys_acted';} ?>">待发货</li>
                    <li onclick="location.href='/member/order?orderStatus=4';" class="<?php if($orderStatus == 4){echo 'ys_acted';} ?>">待收货</li>
                    <li onclick="location.href='/member/order?orderStatus=5';" class="<?php if($orderStatus == 5){echo 'ys_acted';} ?>">已完成</li>
                    <li class="del-order-batch"><img src="/dist/images/del_03.png"></li>
                    <li class="ys_searhc1"><input id="search-item" value="<?php echo $search; ?>" class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc" id="search-btn">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">买得价</span><span class="ys_span3">订单操作</span><span
                    class="ys_span3">订单状态</span>
            </div>
            <p class="kp_tsinfo" style="padding-left:0px;">*所有订单请与72小时内付款！超过72小时未付款交易自动关闭，将影响您的信用。</p>
            <?php foreach($orders as $v){
            ?>
                <div class="ys_tip2" id="order-item-<?php echo $v['orderID'] ?>">
                    <div class="ys_tip3">
                        <div class="ys_tip4">
                            <span><input type="checkbox" name="checkbox1" value="checkbox" order-id="<?php echo $v['orderID'] ?>" class="ind_checkbox order-item-chk"><?php echo date('Y-m-d', strtotime($v['instime'])); ?></span>
                            <span class="yc_pm1">[订单号] <?php echo $v['businessID'] ?></span>


                            <span class="yc_pm2"><?php if($v['orderType'] == 1){ ?><img src="<?php echo $v['storeLogo'] ?>" alt=""><em><?php echo $v['storeName'] ?></em><?php } ?></span>
                            <span class="yc_pm3 lxmj"><a qq="<?php echo $v['orderType'] == 1 ? $v['storeqq'] : $_siteSettings['qq']; ?>" href="javascript:;" class="tencent-qq"><?php echo $v['orderType'] == 1 ? '联系卖家' : '联系客服'; ?></a></span>
                            <span class="yc_pm4"><a href="javascript:;" class="post-complain-btn" order-id="<?php echo $v['orderID'] ?>">网站申诉</a></span>
                            <span class="yc_pm5"><a href="javascript:;" class="del-order-btn" order-id="<?php echo $v['orderID'] ?>">删除</a></span>
                        </div>
                        <div class="ys_tip6">
                            <div class="yc_imgleft"><img style="cursor:pointer;" onclick="window.open('<?php if($v['orderType'] == 1){ ?>/product/snap?productID=<?php echo $v['orderID']; ?><?php }else{ ?>/customization/detail?customizationID=<?php echo $v['customizationID']; ?><?php } ?>');" src="<?php echo $v['product']['listImg']; ?>"></div>
                            <div class="yc_imgleft1">
                                <p class="yc_imgleft2"><span class="yc_ysname"><?php echo $v['product']['productName'] ?></span> <span class="yc_money"><?php if($v['orderType'] == 2){ echo sprintf('%.2f', $v['payMoney'] / $v['customizationCount'], 2) . 'X' . $v['customizationCount']; }else{ echo $v['productPrice']; } ?></span>
                                </p>

                                <div class="yc_ysname1">
                                    <?php if($v['commision'] != 0){
                                    ?>
                                        <p><span class="yc_ysname">佣金</span> <span class="yc_money"><?php echo $v['commision'] ?></span></p>
                                    <?php
                                    } ?>
                                    <p><span class="yc_ysname">实付</span> <span class="yc_money"><?php echo $v['payMoney'] ?></span></p>
                                </div>
                            </div>
                            <?php
                            if($v['orderStatus'] == 1){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1" style="cursor: pointer;" onclick="location.href='/member/order-detail?orderID=<?php echo $v['orderID'] ?>';">等待付款</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">等待买家付款</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                    <!--<p class="yc_p"><a href="javascript:;" class="cancel-order-btn" order-id="<?php /*echo $v['orderID'] */?>">关闭交易</a></p>-->
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 2){
                            ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">已付定金</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 3){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">等待发货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">买家已付款</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>

                                    <?php
                                    if($v['orderType'] == 1){
                                        ?>
                                        <?php
                                        if($v['returnStatus'] == 0){
                                            ?>
                                            <p class="yc_p"><a href="javascript:;" class="apply-return-order-btn" order-id="<?php echo $v['orderID'] ?>">退款/退货</a></p>
                                        <?php
                                        }?>
                                    <?php
                                    }
                                    ?>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 4){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1 confirm-delivery-done" order-id="<?php echo $v['orderID'] ?>" style="cursor: pointer;" >确认收货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">卖家已发货</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>

                                    <?php
                                        if($v['orderType'] == 1){
                                    ?>
                                            <?php
                                                if($v['returnStatus'] == 0){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;" class="apply-return-order-btn" order-id="<?php echo $v['orderID'] ?>">退款/退货</a></p>
                                            <?php
                                                }elseif($v['returnStatus'] == 1){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;">等待卖家同意</a></p>
                                            <?php
                                                }elseif($v['returnStatus'] == 2){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;">卖家不同意退款, 可网站申诉</a></p>
                                            <?php
                                                }elseif($v['returnStatus'] == 3){
                                                    ?>
                                                    <p class="yc_p"><a href="javascript:;" class="delivery-return-order-btn" order-id="<?php echo $v['orderID'] ?>">填写退货物流信息</a></p>
                                                    <p class="yc_p"><a href="javascript:;" orderReturnReceiverName="<?php echo $v['orderReturnReceiverName'] ?>" orderReturnReceiverMobile="<?php echo $v['orderReturnReceiverMobile'] ?>" orderReturnReceiverAddr="<?php echo $v['orderReturnReceiverAddr'] ?>" class="check-order-return-addr">查看退货地址</a></p>
                                            <?php
                                                }elseif($v['returnStatus'] == 4){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;" class="check-return-order-delivery" return-delivery-type="<?php foreach($deliveryTypes as $sv){if($sv['deliveryTypeID'] == $v['returnDeliveryType']){echo $sv['typeName'];}} ?>" return-delivery-num="<?php echo $v['returnDeliveryNum']; ?>">退货待卖家签收</a></p>
                                            <?php
                                                }
                                            ?>

                                            <?php
                                                if(in_array($v['returnStatus'], array(0, 2))) {
                                                    if ($v['delayAutoConfirmDeliveryDoneTime']) {
                                            ?>
                                                        <p class="yc_p"><a href="javascript:;">已延长收货时间</a></p>
                                                <?php
                                                    } else {
                                                ?>
                                                        <p class="yc_p"><a href="javascript:;" class="delay-auto-confirm-delivery-done-time-btn" order-id="<?php echo $v['orderID'] ?>">延长收货时间</a>
                                                        </p>
                                            <?php
                                                    }
                                                }
                                            ?>
                                    <?php
                                        }
                                    ?>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 5){
                                ?>
                                <?php
                                    /*if($v['orderType'] == 2){
                                */?><!--
                                        <div class="yc_ddfk yc_imgleft2">
                                            <div class="yc_ddfk1">待付尾款</div>
                                        </div>
                                --><?php
/*                                    }*/
                                ?>

                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">交易成功</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">商品已发货</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == -1 || $v['orderStatus'] == -2){
                            ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_jyjs">交易关闭</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">未按时付款/已退货</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                    <p class="yc_p"><a href="javascript:;">已关闭</a></p>
                                </div>
                            <?php
                            }/*elseif($v['orderStatus'] == 6){
                                */?><!--
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">已付全款</a></p>
                                    <p class="yc_p"><a href="/member/order-detail?orderID=<?php /*echo $v['orderID'] */?>">订单详情</a></p>
                                </div>
                            --><?php
/*                            }*/
                            ?>
                        </div>
                    </div>
                </div>
            <?php
            } ?>
            <?php
                echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/member/order?orderStatus=' . $orderStatus . '&'));
            ?>
        </div>
    </div>
</div>
<?php if(!empty($memberRecommendProducts)){echo $this->render('member-recommend');}  ?>
<?php
echo $this->render('set-delivery-type');
echo $this->render('return-type');
?>
<script>
    $(function(){
        $('#search-btn').on('click', function(){
            var search = $('#search-item').val();
            if(!search){
                layer.alert('请输入搜索内容');
                return false;
            }
            location.href = '/member/order?search=' + search;
        });

        function delOrder(data){
            layer.confirm('确认删除吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/del-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }

                    }
                });
            }, function(){
                layer.closeAll();
            });

        }

        $('.del-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            delOrder(data);

        });

        $('.del-order-batch').on('click', function(){
            var data = {};
            data.orderID = new Array();
            var checkedOrders = $('.order-item-chk:checked');
            if(!checkedOrders.length){
                layer.alert('请选择要取消的订单');
                return false;
            }
            checkedOrders.each(function(){
                var tmpOrderID = $(this).attr('order-id');
                data.orderID.push(tmpOrderID);
            });
            delOrder(data);
        });

        /*$('.cancel-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            layer.confirm('确认关闭交易吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/cancel-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }

                    }
                });
            }, function(){
                layer.closeAll();
            });


        });*/

        $('.confirm-delivery-done').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            layer.confirm('确认收货吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/confirm-delivery-done',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            }, function(){
               layer.closeAll();
            });

        });

        $('.delay-auto-confirm-delivery-done-time-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            $.ajax({
                url : '/member/delay-auto-confirm-delivery-done-time',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.apply-return-order-btn').on('click', function(){
            layer.open({
                skin: 'loginBox',
                title:'申请退款',
                type: 1,
                content: $('#set-return-type-div').html()
            });
            var orderID = $(this).attr('order-id');
            $('.apply-return-confirm-btn:visible').attr('order-id', orderID);
        });

        $(document).on('click', '.apply-return-confirm-btn:visible', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            data.returnType = $('input[name=return-type]:visible:checked').val();
            if(!data.returnType){
                layer.alert('请选择退款类型');

                return false;
            }
            data.applyReturnReason = '';
            if(data.returnType == 2){
                data.applyReturnReason = $('input[name=return-money-only-reason]:visible').val();
            }else if(data.returnType == 3){
                data.applyReturnReason = $('input[name=return-all-reason]:visible').val();
            }

            $.ajax({
                url : '/member/apply-return-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.delivery-return-order-btn').on('click', function(){
            layer.open({
                skin: 'loginBox',
                title:'发货信息',
                type: 1,
                content: $('#set-delivery-type-div').html()
            });
            var orderID = $(this).attr('order-id');
            $('.confirm-delivery-btn:visible').attr('order-id', orderID);
        });
        $(document).on('click', '.confirm-delivery-btn:visible', function() {
            var data = {};
            data.orderID = $(this).attr('order-id');
            data.haveDelivery = $('input[name=have-delivery]:visible:checked').val();
            if(data.haveDelivery){
                data.haveDelivery = 1;
                data.deliveryType = $('select[name=delivery-type]:visible').val();
                data.deliveryNum = $('input[name=delivery-num]:visible').val();
            }else{
                data.haveDelivery = 0;
            }
            $.ajax({
                url : '/member/delivery-return-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.check-return-order-delivery').on('click', function(){
            var returnDeliveryType = $(this).attr('return-delivery-type');
            var returnDeliveryNum = $(this).attr('return-delivery-num');
            if(returnDeliveryType){
                var str = '物流公司: ' + returnDeliveryType + '<br />物流单号: ' + returnDeliveryNum + '<br />';
                layer.alert(str);
            }else{
                layer.alert('无物流信息');
            }
        });

        $('.check-order-return-addr').on('click', function(){
            var orderReturnReceiverName = $(this).attr('orderReturnReceiverName');
            var orderReturnReceiverMobile = $(this).attr('orderReturnReceiverMobile');
            var orderReturnReceiverAddr = $(this).attr('orderReturnReceiverAddr');
            if(orderReturnReceiverAddr){
                var str = '退货地址收货人姓名: ' + orderReturnReceiverName + '<br />退货地址收货人电话: ' + orderReturnReceiverMobile + '<br />退货地址: ' + orderReturnReceiverAddr;
                layer.alert(str);
            }else{
                layer.alert('无退货地址信息');
            }
        });
    })
</script>