<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'order')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="yg_pp">
                <div class="yc_pm41">
                    <span class="yc_pm1n">[订单号] 132346456132123435</span>
                    <span class="yc_pm2">开源拍卖</span>
                    <span class="yc_pm3 lxmj1 "><a href="">联系卖家</a></span>
                    <span class="yc_pm44"><a href="">成交时间</a></span>
                </div>
                <div class="yg_ppname">
                    <div class="yg_ppname_left"><img src=""></div>
                    <div class="yg_ppname_right">
                        <div class="yg_ppname_right1">
                            <div class="yg_ppname1"><p>西泠印社 李平《妙造自然》</p>

                                <p>中国美院书法学博士</p></div>
                            <div class="yg_ppname2">2015-12-10<br> 22:00</div>
                        </div>
                        <div class="yg_ppname3">成交价：5000元 运费：0元 佣金：250元</div>
                    </div>
                </div>
                <div class="yg_addres">
                    <div class="yg_addres_left">
                        <div class="yg_addres_left1"><input name="address" type="radio" class="ind_checkbox"/></div>
                        <div class="yg_addres_left2">
                            <p class="yg_sjr">收货人：张三 13588838833</p>

                            <p class="yg_sjr">收货地址：浙江省 杭州市 下城区 朝晖路179号嘉惠大厦2-5-5（310000）</p>
                        </div>
                    </div>
                    <div class="yg_addres_right">
                        <div><a href="">编辑</a></div>
                        <div><a href="">删除</a></div>
                    </div>
                </div>
                <div class="yg_addres">
                    <div class="yg_addres_left">
                        <div class="yg_addres_left1"><input name="address" type="radio" class="ind_checkbox"/></div>
                        <div class="yg_addres_left2">
                            <p class="yg_sjr">收货人：张三 13588838833</p>

                            <p class="yg_sjr">收货地址：浙江省 杭州市 下城区 朝晖路179号嘉惠大厦2-5-5（310000）</p>
                        </div>
                    </div>
                    <div class="yg_addres_right">
                        <div><a href="">编辑</a></div>
                        <div><a href="">删除</a></div>
                    </div>
                </div>

                <div class="yg_addresbtn">添加新地址</div>
                <div class="yg_bz">
                    <div class="yc_ly">留言备注</div>
                    <textarea></textarea>
                </div>
                <div class="yg_fk">
                    付款金额 5000.00 <span class="yg_sfmoney1">实付金额</span><span class="yg_sfmoney">4750.00</span>
                </div>
                <div class="yg_zf">
                    <ul>
                        <li><img src="images/logoicon.png">余额支付</li>
                        <li><img src="images/vb_05.png">支付宝</li>
                        <li class="acted"><img src="images/vb_07.png">微信钱宝</li>
                        <li><img src="images/vb_20.png">银行汇款</li>
                        <li><img src="images/vb_21.png">银联支付</li>
                    </ul>
                </div>


            </div>
            <div class="yg_qrzf">
                <a href=""><span class="yg_qrzf1"> 确认支付</span></a>
                <a href=""><span class="yg_qrzf2"> 稍后付款</span></a>

            </div>


        </div>


    </div>
</div>