
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'product')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div class="kp_tit">
                <ul>
                    <li id="publish-products-batch" style="cursor: pointer;">上架</li>
                    <li id="withdraw-products-batch" style="cursor: pointer;">下架</li>
                    <li id="recommend-products-btn" style="cursor: pointer;">推荐</li>
                    <li id="choose-auction-time-batch" style="cursor: pointer;">设置拍卖时间</li>
                    <li id="del-products-btn" style="cursor: pointer;">删除</li>
                </ul>
                <span class="kp_zzpm" style="cursor: pointer" onclick="location.href='/member/product?auctionStatus=2';">所有正在拍卖</span>
            </div>
            <p class="kp_tsinfo" style="margin-bottom: 14px;padding-left:0px;">*选择“上架”，系统即默认为立刻上架开拍（最长有一分钟延迟）。24小时内结束。所有拍品上架即无法重新编辑。</p>
            <?php
                foreach($products as $v){
            ?>
                    <div class="kp_shop" id="product-li-<?php echo $v['productID'] ?>">
                        <div class="kp_shop_left">
                            <img style="cursor:pointer;" onclick="window.open('/product/detail?productID=<?php echo $v['productID'] ?>');" src="<?php echo $v['listImg'] ?>">
                            <input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox add_lefimg01 product-item" product-id="<?php echo $v['productID'] ?>">
                        </div>
                        <div class="kp_shop_center">
                            <p class="kp_shop_centerp "><?php echo $v['productName'] ?></p>

                            <?php
                            if($v['auctionStatus'] == 1 || empty($v['auctionStatus'])){
                            ?>
                                <div class="kp_name">
                                    <span>起拍价
                                        <input class="kp_input " type="text" placeholder="" value="<?php echo $v['startPrice'] ?>"> <span product-id="<?php echo $v['productID'] ?>" class="edit-start-price-btn" style="cursor: pointer;">修改</span>
                                    </span>
                                    <!--<span class="kp_bliu">保留价
                                        <input class="kp_input " type="text" placeholder="" value="<?php /*echo $v['keepPrice'] */?>">  <span product-id="<?php /*echo $v['productID'] */?>" class="edit-keep-price-btn" style="cursor: pointer;">修改</span>
                                    </span>-->
                                </div>
                            <?php
                            }elseif($v['auctionStatus'] == 2){
                            ?>
                                <div class="kp_name kp_nameing">
                                    当前价 <span><?php echo $v['currPrice']; ?></span>
                                </div>
                            <?php
                            }
                            ?>
                        </div>

                        <?php
                        if(empty($v['auctionStatus'])){
                        ?>
                            <div class="kp_shop_center01">
                                <p>等待上架</p>

                                <p><?php echo !empty($v['startTime']) ? date('Y-m-d H:i:s', $v['startTime']) : ''; ?></p>
                            </div>
                        <?php
                        }
                        if($v['auctionStatus'] == 1){
                        ?>
                            <div class="kp_shop_center01">
                                <p>即将开拍</p>

                                <p><?php echo date('Y-m-d H:i:s', $v['startTime']); ?></p>
                            </div>
                        <?php
                        }elseif($v['auctionStatus'] == 2){
                        ?>
                            <div class="kp_shop_center01">
                                <p class="kp_nmai">正在拍卖</p>
                                <p><?php echo date('Y-m-d H:i:s', $v['endTime']) ?>结束</p>
                            </div>
                        <?php
                        }elseif($v['auctionStatus'] == 3){
                        ?>
                            <div class="kp_shop_center01">
                                <p>已结束</p>
                            </div>
                        <?php
                        } ?>

                        <div class="kp_shop_right">
                            <div class="kp_bj">
                                <span>
                                    <a href="/member/add-product?productID=<?php echo $v['productID'] ?>">编辑拍品</a>
                                </span>
                                <span class="kp_bjsc">
                                    <a href="javascript:;" class="del-product-btn" product-id="<?php echo $v['productID'] ?>">删除</a>
                                </span>
                            </div>
                            <div class="kp_bj">


                                    <?php
                                        if(in_array($v['auctionStatus'], array(1))){
                                    ?>
                                <span><a href="javascript:;" class="withdraw-product-btn" product-id="<?php echo $v['productID'] ?>">下架</a></span>
                                    <?php

                                        }elseif(empty($v['auctionStatus'])){
                                    ?>
                                <span><a href="javascript:;" class="publish-product-btn" product-id="<?php echo $v['productID'] ?>">上架</a></span>
                                    <?php
                                        }
                                    ?>


                                <span class="kp_bjsc">
                                    <a is-store-recommend="<?php echo $v['isStoreRecommend']; ?>" href="javascript:;" class="store-recommend-product store-recommend-product-<?php echo $v['productID'] ?>" product-id="<?php echo $v['productID'] ?>"><?php
                                            if($v['isStoreRecommend']){
                                                echo '取消推荐';
                                            }else{
                                                echo '推荐';
                                            }
                                        ?></a>
                                </span>
                            </div>
                            <div class="kp_bj">
                                <?php if($v['auctionStatus'] == 1 || empty($v['auctionStatus'])){

                                ?>
                                    <a start-time-year="<?php echo $v['startTimeYear'] ?>" start-time-month="<?php echo $v['startTimeMonth'] ?>" start-time-day="<?php echo $v['startTimeDay'] ?>" start-time-hour="<?php echo $v['startTimeHour'] ?>" start-time-minute="<?php echo $v['startTimeMin'] ?>" end-time-year="<?php echo $v['endTimeYear'] ?>" end-time-month="<?php echo $v['endTimeMonth'] ?>" end-time-day="<?php echo $v['endTimeDay'] ?>" end-time-hour="<?php echo $v['endTimeHour'] ?>" end-time-minute="<?php echo $v['endTimeMin'] ?>" href="javascript:;" class="choose-auction-time" product-id="<?php echo $v['productID'] ?>">选择拍卖时间>></a>
                                <?php
                                    if(!empty($v['specialID'])) {
                                        echo '<br />专场拍品';
                                    }
                                }else{

                                ?>
                                    <!--<a href="javascript:;" class="cancel-keep-price-btn" product-id="<?php /*echo $v['productID'] */?>">取消保留价>></a>-->
                                <?php
                                    if(!empty($v['specialID'])){
                                        echo '<br />专场拍品';
                                    }

                                } ?>

                            </div>
                        </div>
                    </div>


            <?php
                }
            ?>
            <?php
                echo $this->render('/front/common/paginate', array('url' => '/member/product?auctionStatus=' . $auctionStatus . '&', 'pages' => $pages));
            ?>
            <!-- 定时上架 -->
            <!--<div class="hide" id="auction-time-select">
                <div class="kp_time">
                    <?php /*echo $this->render('time'); */?>
                    <input type="button" class="choose-auction-time-confirm-btn layer-submit" value="提交" />
                    <p class="kp_tsinfo1">注：自由拍卖时间不超过48小时</p>
                </div>
            </div>-->
        </div>
    </div>
</div>
<?php
echo $this->render('/front/common/pay');
echo $this->render('/front/common/transfer-account');
?>
<div class="hide" id="auction-time-select">
    <div class="kp_time">
        <?php echo $this->render('time'); ?>
        <p class="kp_tsinfo1">注：自由拍卖时间不超过48小时</p>
    </div>
</div>
<script>
    $(function(){
        function recommendProduct(params){
            $.ajax({
                url : '/member/store-recommend-product',
                type : 'post',
                dataType : 'json',
                data : params,
                success : function(data){
                    layer.alert(data.msg);
                    var tmp;
                    for(var i in params.productID){
                        tmp = $('.store-recommend-product-' + params.productID[i]);
                        if(tmp.html() == '推荐'){
                            tmp.html('取消推荐');
                        }else{
                            tmp.html('推荐');
                        }
                    }
                }
            });
        }
        $('.store-recommend-product').on('click', function(){
            var data = {};
            data.isStoreRecommend = 1;
            data.productID = new Array();
            data.productID.push($(this).attr('product-id'));
            if($(this).html() == '取消推荐'){
                data.isStoreRecommend = 0;
            }
            recommendProduct(data);
        });
        $('#recommend-products-btn').on('click', function(){
            var checkedProducts = $('.product-item:checked');
            if(!checkedProducts.length){
                layer.alert('请选择拍品');
                return false;
            }
            var data = {};
            data.isStoreRecommend = 1;
            data.productID = new Array();
            var tmp;
            checkedProducts.each(function(){
                tmp = $(this).attr('product-id');
                data.productID.push(tmp);
            });
            recommendProduct(data);
        });

        function delProduct(productID){
            layer.confirm('确认删除吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/save-product',
                    type : 'post',
                    dataType : 'json',
                    data : {productID : productID, isDel : 1},
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert('删除成功', function(){
                                location.reload();
                            })
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            }, function(){
                layer.closeAll();
            });

        }
        $('.del-product-btn').on('click', function(){
            var productID = $(this).attr('product-id');
            delProduct(productID);
        })
        $('#del-products-btn').on('click', function(){
            var checkedProducts = $('.product-item:checked');
            if(!checkedProducts.length){
                layer.alert('请选择拍品');
                return false;
            }

            var productID = new Array();
            var tmp;
            checkedProducts.each(function(){
                tmp = $(this).attr('product-id');
                productID.push(tmp);
            });
            delProduct(productID);
        });

        /*$('.edit-keep-price-btn').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.keepPrice = $(this).prev('input').val();
            data.existKeepPrice = 1;
            $.ajax({
                url : '/member/save-product',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(data){
                    layer.alert(data.msg);
                }
            });
        });*/
        $('.edit-start-price-btn').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.startPrice = $(this).prev('input').val();
            /*data.existKeepPrice = 1;*/
            $.ajax({
                url : '/member/save-product',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(data){
                    layer.alert(data.msg);
                }
            });
        });
        /*$('.cancel-keep-price-btn').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            $.ajax({
                url : '/member/cancel-keep-price',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(data){
                    layer.alert(data.msg);
                }
            });
        });*/

        $('.choose-auction-time').on('click', function(){
            /*layer.open({
                title:'选择拍卖时间',
                type: 1,
                content: $('#auction-time-select').html()
            });*/
            var productID = $(this).attr('product-id');

            $('.kp_right').find('.kp_time').remove();
            $('#product-li-' + productID).after($('#auction-time-select').html());

            var startTimeYear = $(this).attr('start-time-year');
            var startTimeMonth = $(this).attr('start-time-month');
            var startTimeDay = $(this).attr('start-time-day');
            var startTimeHour = $(this).attr('start-time-hour');
            var startTimeMinute = $(this).attr('start-time-minute');
            var endTimeYear = $(this).attr('end-time-year');
            var endTimeMonth = $(this).attr('end-time-month');
            var endTimeDay = $(this).attr('end-time-day');
            var endTimeHour = $(this).attr('end-time-hour');
            var endTimeMinute = $(this).attr('end-time-minute');
            $('.choose-auction-time-confirm-btn:visible').attr('product-id', productID);
            if(startTimeYear) $('.layer-start-time-year:visible').val(startTimeYear);
            if(startTimeMonth) $('.layer-start-time-month:visible').val(startTimeMonth);
            if(startTimeDay) $('.layer-start-time-day:visible').attr('day', startTimeDay);
            if(startTimeHour) $('.layer-start-time-hour:visible').val(startTimeHour);
            if(startTimeMinute) $('.layer-start-time-minute:visible').val(startTimeMinute);
            if(endTimeYear) $('.layer-end-time-year:visible').val(endTimeYear);
            if(endTimeMonth) $('.layer-end-time-month:visible').val(endTimeMonth);
            if(endTimeDay) $('.layer-end-time-day:visible').attr('day', endTimeDay);
            if(endTimeHour) $('.layer-end-time-hour:visible').val(endTimeHour);
            if(endTimeMinute) $('.layer-end-time-minute:visible').val(endTimeMinute);
        });

        function setBatchProducts(){
            var checkedProducts = $('.product-item:checked');
            var productID = new Array();
            var tmp;
            checkedProducts.each(function(){
                tmp = $(this).attr('product-id');
                productID.push(tmp);
            });
            productID.join(',');
            $('.choose-auction-time-confirm-btn:visible').attr('product-id', productID);
        }

        $('.product-item').on('click', function(){
            setBatchProducts();
        });
        $('#choose-auction-time-batch').on('click', function(){
            var checkedProducts = $('.product-item:checked');
            if(!checkedProducts.length){
                layer.alert('请选择拍品');
                return false;
            }

            /*layer.open({
                title:'选择拍卖时间',
                type: 1,
                content: $('#auction-time-select').html()
            });*/
            $('.kp_right').find('.kp_time').remove();
            $('.kp_tit').after($('#auction-time-select').html());

            setBatchProducts();

        });

        $(document).on('click', '.choose-auction-time-confirm-btn:visible', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.productID = data.productID.split(',');
            if(!data.productID) {
                layer.alert('请选择拍品');
                return false;
            }
            var auctionStartTimeYear = $('.layer-start-time-year:visible').val();
            var auctionStartTimeMonth = $('.layer-start-time-month:visible').val();
            var auctionStartTimeDay = $('.layer-start-time-day:visible').val();
            var auctionStartTimeHour = $('.layer-start-time-hour:visible').val();
            var auctionStartTimeMinute = $('.layer-start-time-minute:visible').val();
            data.startTime = auctionStartTimeYear + '-' + auctionStartTimeMonth + '-' + auctionStartTimeDay + ' ' + auctionStartTimeHour + ':' + auctionStartTimeMinute + ':00';
            var auctionEndTimeYear = $('.layer-end-time-year:visible').val();
            var auctionEndTimeMonth = $('.layer-end-time-month:visible').val();
            var auctionEndTimeDay = $('.layer-end-time-day:visible').val();
            var auctionEndTimeHour = $('.layer-end-time-hour:visible').val();
            var auctionEndTimeMinute = $('.layer-end-time-minute:visible').val();
            data.endTime = auctionEndTimeYear + '-' + auctionEndTimeMonth + '-' + auctionEndTimeDay + ' ' + auctionEndTimeHour + ':' + auctionEndTimeMinute + ':00';

            $.ajax({
                url : '/member/save-auction-time',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.data && res.data['unitePayID']){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#pay-div').html()
                            });
                            $('.pay-price:visible').html(res.data['price']);
                            $('.pay-price:visible').attr('unite-pay-id', res.data['unitePayID']);
                        }else{
                            layer.alert(res.msg, function(){
                                location.reload();
                            });

                        }
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        /*$('.cancel-keep-price').on('click', function(){
            var data = {};
            data.productID = $(this).attr('product-id');
            data.keepPrice = 0;
            data.existKeepPrice = 0;
            $.ajax({
                url : '/member/save-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });*/

        function publishProducts(productID){
            var data = {};
            data.productID = productID;
            $.ajax({
                url : '/member/publish-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.data && res.data['unitePayID']){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#pay-div').html()
                            });
                            $('.pay-price:visible').html(res.data['price']);
                            $('.pay-price:visible').attr('unite-pay-id', res.data['unitePayID']);
                        }else{
                            layer.alert(res.msg, function(){
                                location.reload();
                            });

                        }
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        }

        $(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.payType = $('.selected-pay-type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            data.unitePayID = $('.pay-price:visible').attr('unite-pay-id');
            $.ajax({
                url : '/order/pay-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            layer.alert('申请开通中');
                            return false;
                            location.href = res.data['coreData'];
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }else if(res.flag == 5){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: '<img src="/qrcode/' + res.data['coreData'] + '" />'
                            });
                        }
                        setInterval('checkOrderStatus(' + data.unitePayID + ', 2)', 2000);
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        function withDrawProducts(productID){
            var data = {};
            data.productID = productID;
            $.ajax({
                url : '/member/withdraw-product',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        }
        $('.publish-product-btn').on('click', function(){
            var productID = $(this).attr('product-id');
            publishProducts(productID);
        });

        $('.withdraw-product-btn').on('click', function(){
            var productID = $(this).attr('product-id');
            withDrawProducts(productID);
        });

        $('#publish-products-batch').on('click', function(){
            var checkedProducts = $('.product-item:checked');
            if(!checkedProducts.length){
                layer.alert('请选择拍品');
                return false;
            }
            var productID = new Array();
            var tmp;
            checkedProducts.each(function(){
                tmp = $(this).attr('product-id');
                productID.push(tmp);
            });
            publishProducts(productID);
        });

        $('#withdraw-products-batch').on('click', function(){
            var checkedProducts = $('.product-item:checked');
            if(!checkedProducts.length){
                layer.alert('请选择拍品');
                return false;
            }
            var productID = new Array();
            var tmp;
            checkedProducts.each(function(){
                tmp = $(this).attr('product-id');
                productID.push(tmp);
            });
            withDrawProducts(productID);
        });

    })
</script>