<div id="reg_success" class="findPassword reg-bodybg" style="display:none;">
    <div class="w1000 clearfix">
        <!-- 注册成功start -->
        <div class="registerSuc">
            <div class="sucImg">
                <img src="/dist/img/account/success.png"/>
            </div>
            <div class="sucFont">恭喜您注册成功！</div>
            <div class="sucTip">
                <p>
                    100元现金券24小时内到帐
                    <a href="/personal/assets/mybalance/">我的资产</a>
                    ，每天上万件1元起拍的
                </p>

                <p>
                    商品等着你&nbsp;&nbsp;&nbsp;
                    <a href="http://www.yishu.com/paimai/" target="_blank">去逛逛>></a>
                </p>
            </div>
            <div class="QR">
                <div class="qrCode">
                    <img src="/dist/img/common/QRcode.jpg"/>
                </div>
                <div class="qrFont">
                    <p>【艺术网服务号】</p>

                    <p>关注微信服务号，获取实时出价通知，中意宝贝不容错过～</p>
                </div>
            </div>
        </div>
        <!-- 注册成功end -->
    </div>
</div>