<div id="set-return-type-div" class="hide">
    <div class="loginPop fr">
        <form method="post">
            <input type="radio" name="return-type" value="1" />超时退款(仅适用于未按网站规定(72小时内)发货, 申请后网站立即达成退款协议, 退款将返还至用户余额, 用户可直接使用余额或至余额提现)
            <br />
            <input type="radio" name="return-type" value="2" />仅退款(适用于卖家已发货, 买家未收到货或不需退货, 仅退款的情况, 请填写原因并等待卖家同意)
            <br />
            <input name="return-money-only-reason" type="text"/><br />
            <input type="radio" name="return-type" value="3" />退款退货(适用于卖家已发货, 退货并退款, 请填写原因并等待卖家同意)
            <br />
            <input name="return-all-reason" type="text"/><br />
            <input type="button" class="submit apply-return-confirm-btn" value="确认">
        </form>
    </div>
</div>