<div id="set-return-addr-div" class="hide">
    <div class="loginPop fr">
        <form method="post">
            <div class="inputBox">
                <input name="orderReturnReceiverName" placeholder="退货地址收货人姓名" type="text"/>
            </div>
            <div class="inputBox">
                <input name="orderReturnReceiverMobile" placeholder="退货地址收货人电话" type="text"/>
            </div>
            <div class="inputBox">
                <input name="orderReturnReceiverAddr" placeholder="退货地址" type="text"/>
            </div>
            <input type="button" class="submit set-return-addr-btn" value="确认">
        </form>
    </div>
</div>