
<link rel="stylesheet" href="/jinnew/style/common.css">

<link rel="stylesheet" href="/jinnew/style/default.css" type="text/css" media="screen" charset="utf-8" />
<link rel="stylesheet" href="/jinnew/style/style.css">
<style>
    .bold1{
        font-size: 16px;
        font-weight: bold;

    }
    .bold3{
        color: #c91c1e;
        font-size: 22px;
        margin-left: 3px;
    }

    .bold31{
        color: #c91c1e;
        font-size: 22px;
        margin-left: 30px;
    }
    .bold32{
        color: #c91c1e;
        font-size: 22px;
        margin-left: 50px;
    }
    .bold9{
        color: #9c91c1e;
        margin-left: 30px;
    }
    .bold5{
        background: #fff;
        width: 486px;
        height: 30px;
    }
    .bold6{
        background: #fff;
        width: 280px;
        height: 30px;
    }
    .bold11{
        background: #fff;
        width: 234px;
        height: 30px;
    }


    .radios1{
        /* margin-left: 260px; */
    }
    .radios2{
        margin-left: 230px;
    }
    .radios4{
        margin-left: 168px;
    }
    .radios3{
        margin-left: 150px;
    }
    .radios33{
        margin-left: 130px;
    }
    .fengexian{
        border: 1px dashed #79756c;
        margin-top: 36px;
    }

    .bold7{
        width: 678px;
        height: 240px;
        background: #fff;

    }
    .bold8{
        float: left;

        display: inline-block;
    }
    .qingchu{
        clear:both;
    }

    .bord10{
        width: 130px;
        height: 36px;
        background: #800000;
        color: #fff;
        display: inline-block;
        margin-top: 44px;
        margin-left:94px;
        text-align: center;
        line-height: 36px;
    }
    /*修改手机号码的弹窗*/
    .win011{width:910px; height: 470px; margin: auto; padding: 30px; overflow: hidden;background: #f7f5e9}

    .bgfix1{ background: #ff7519; opacity: 0.6; position: fixed;width: 100%; height: 100%;}
    .winbg1{position: fixed;z-index: 11; width: 100%; top:200px; }
    .win_close1{ overflow: hidden; height: 40px; width: 100%; cursor: pointer;}
    .win_close1 img{float: right; width: 30px;height: 30px}
    .wintop11{margin-top: 10px}
    /*修改密码的弹窗*/
    .bgfix11{ background: #ff7519; opacity: 0.6; position: fixed;width: 100%; height: 100%;}
    .winbg11{position: fixed;z-index: 11; width: 100%; top:200px; }
    .win_close11{ overflow: hidden; height: 40px; width: 100%; cursor: pointer;}
    .win_close11 img{float: right; width: 30px;height: 30px}
    .wintop111{margin-top: 10px}
    .win0111{width:910px; height: 436px; margin: auto; padding: 30px; overflow: hidden;background: #f7f5e9}
    .genghuanshoujihao{
        margin-top: 40px;
        margin-left: 152px;
    }
    .ind_jrzz41{ margin-left: 32px; width: 80px; display: inline-block;font-size: 20px;}
    .genghuanshoujihao1{
        width: 60px;
        height: 30px;
        background: #800000;
        color: #fff;
        display: inline-block;

        margin-left:5px;
        text-align: center;
        line-height: 30px;

    }
    .genghuanshoujihao2{

        margin-left: 152px;
        margin-top:28px;
        background: #fffdee;
        height: 174px;
        width: 484px;
    }
    .genghuanshoujihao3{
        margin-left: 60px;
        margin-top:12px;
        display: inline-block;

    }
    .genghuanshoujihao4{
        margin-left: 24px;
        margin-bottom:0px;
        font-size: 18px;
        display:inline-block;

    }
    .genghuanshoujihao5{
        width: 100px;
        height: 36px;
        background: #800000;
        color: #fff;
        display: inline-block;

        margin-left:5px;
        text-align: center;
        line-height: 30px;
        margin-left: 320px;
        margin-top: 14px;

    }
    .genghuanshoujihao6{

        margin-top: 42px;
    }
    .ind_jrzz7{margin-left: 36px;width: 80px;display: inline-block;font-size: 20px;}
    .genghuanshoujihao7{
        border: 1px dashed #7b776e;
        margin-top: 40px;
        margin-left: 36px;
        width: 888px;

    }
    .genghuanshoujihao8{

        margin-left: 152px;
        margin-top:28px;
        background: #fffdee;
        height: 218px;
        width: 484px;
    }
    .zhanghuset1 ul li{
        margin-top: 32px;
        margin-left: 5px;
        color: #ffffff;
        font-size: 18px;
        line-height: 30px;
    }

    .touxiang11{
        position:relative;
        top: 76px;
        float:right;
        right: 420px;
    }
    .touxiang12{
        font-size: 16px;
        margin-bottom:5px;
    }

    .dingwei1{
        position: absolute;
        margin-top:0px;
    }
</style>

<!--End头部-->
<!--main开始-->
<div class="kp_main">
    <div class="center " >
        <!-- left部分 -->
        <div class="kp_left">
            <div class="kp_biaot">
                <p class="kp_p" style="color:white;">账户设置</p>
                <div class="zhanghuset1">
                    <ul >
                        <li><span class="bold3">*&nbsp&nbsp&nbsp&nbsp</span>注册完成后，不设置本页内容不影响网站使用
                        </li>
                        <li>
                            <span class="bold3">*&nbsp&nbsp&nbsp&nbsp</span>如绑定手机发生更改，请及时更新信息
                        </li>
                        <li>
                            <span class="bold3">*&nbsp&nbsp&nbsp&nbsp</span>建议定期更改登陆密码，提高账号安全性
                        </li>

                    </ul>
                </div>

            </div>

        </div>
        <!-- right部分 -->
        <div class="kp_right kp_back">
            <span class="ind_jrzz bold ">个人头像 </span>
            <span id="preview2" class="dianpbai"><img src="<?php echo $_memberInfo['avatar'] ?>" id="imghead2"></span>
            <div class="touxiang11">
                <div class="touxiang12">尺寸 500x500.容量不大于500KB</div>
                <div>
                    <input type="file" onchange="previewImage2(this)" />
                </div>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">昵&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp称</span>
                <span class="ind_jrzz bold1"><?php echo $_memberInfo['nickName'] ?></span>
                <span class="ind_jrzz1 bold3">*</span>
                <span class="ind_jrzz2 ">昵称不可修改</span>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">个性签名</span>
                <input type="text" name="signature"  class="bold5" value="<?php echo $memberInfo['signature'] ?>">
                <span class="ind_jrzz3 ">限20字，显示在用户空间</span>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">绑定手机</span>
                <span class="ind_jrzz4 "><?php echo substr_replace($_memberInfo['mobile'], '******', 4) ?></span>
                <span class="bold3" id="edit-mobile-btn" style="cursor: pointer;">更改手机</span>
                <span class="radios2"><input type="radio" <?php echo !empty($_memberInfo['mobileVisible']) ? 'checked' : '' ?> name="mobile-visible" value="1">公开显示  </span>
                <span class="radios1"><input type="radio" <?php echo empty($_memberInfo['mobileVisible']) ? 'checked' : '' ?> name="mobile-visible" value="0">仅互相关注后可见  </span>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">登陆密码</span>
                <span class="bold3" id="edit-password-btn">修改密码</span>
            </div>
            <!--分割线-->
            <div class="fengexian"></div>
            <div class="ind_jrzz5">*为了保护客户隐私,手机和邮箱等信息默认为不公开显示，如需公开显示或显示给特定人群请在设置中选择</div>
            <div class="mt20">
                <span class="ind_jrzz bold">邮箱</span>
                <input type="text" name="email"  class="ind_jrzz6 bold6" value="<?php echo $_memberInfo['email'] ?>">
                <span class="radios33"><input type="radio" <?php echo !empty($_memberInfo['emailVisible']) ? 'checked' : '' ?> name="email-visible" value="1">公开显示  </span>
                <span class="radios1"><input type="radio" <?php echo empty($_memberInfo['emailVisible']) ? 'checked' : '' ?> name="email-visible" value="0">仅互相关注后可见  </span>

            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">QQ</span>
                <input type="text" name="qq"  class="ind_jrzz6 bold6" value="<?php echo $_memberInfo['qq'] ?>">
                <span class="radios33"><input type="radio" <?php echo !empty($_memberInfo['qqVisible']) ? 'checked' : '' ?> name="qq-visible" value="1">公开显示  </span>
                <span class="radios1"><input type="radio" <?php echo empty($_memberInfo['qqVisible']) ? 'checked' : '' ?> name="qq-visible" value="0">仅互相关注后可见  </span>

            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">微信</span>
                <input type="text" name="wechat"  class="ind_jrzz6 bold6">
                <span class="radios33"><input type="radio" <?php echo !empty($_memberInfo['wechatVisible']) ? 'checked' : '' ?> name="wechat-visible" value="1">公开显示  </span>
                <span class="radios1"><input type="radio" <?php echo empty($_memberInfo['wechatVisible']) ? 'checked' : '' ?> name="wechat-visible" value="0">仅互相关注后可见  </span>

            </div>
            <div class="mt20">
                <div class="bold8">
                    <div class="ind_jrzz bold">个人简介</div>
                    <div>*限20字<br>以内</div>
                </div>
                <div class="bold8">
                    <textarea name="self-desc" class="ind_jrzz6 bold7"><?php echo $_memberInfo['selfDesc'] ?></textarea>
                </div>


            </div>

            <div class="bord10" id="save-settings-btn">提交</div>

            <!-- 内容 -->


        </div>


    </div>
</div>
<?php
    echo $this->render('edit-mobile');
    echo $this->render('edit-password');
?>
<script>
    //图片上传预览    IE是用了滤镜。
    function previewImage2(file)
    {
        var MAXWIDTH  = 260;
        var MAXHEIGHT = 180;
        var div = document.getElementById('preview2');
        if (file.files && file.files[0])
        {
            var img = document.getElementById('imghead2');
            img.onload = function(){
                var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
                img.width  =  rect.width;
                img.height =  rect.height;
//                 img.style.marginLeft = rect.left+'px';
                img.style.marginTop = rect.top+'px';
            }
            var reader = new FileReader();
            reader.onload = function(evt){img.src = evt.target.result;}
            reader.readAsDataURL(file.files[0]);
        }
        else //兼容IE
        {
            var sFilter='filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="';
            file.select();
            var src = document.selection.createRange().text;
            var img = document.getElementById('imghead2');
            img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;
            var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
            status =('rect:'+rect.top+','+rect.left+','+rect.width+','+rect.height);
            div.innerHTML = "<div id=divhead style='width:"+rect.width+"px;height:"+rect.height+"px;"+sFilter+src+"\"'></div>";
        }
    }

    function clacImgZoomParam( maxWidth, maxHeight, width, height ){
        var param = {top:0, left:0, width:width, height:height};
        if( width>maxWidth || height>maxHeight )
        {
            rateWidth = width / maxWidth;
            rateHeight = height / maxHeight;

            if( rateWidth > rateHeight )
            {
                param.width =  maxWidth;
                param.height = Math.round(height / rateWidth);
            }else
            {
                param.width = Math.round(width / rateHeight);
                param.height = maxHeight;
            }
        }

        param.left = Math.round((maxWidth - param.width) / 2);
        param.top = Math.round((maxHeight - param.height) / 2);
        return param;
    }

    $('#save-settings-btn').on('click', function(){
        var data = {};
        data.avatar = $('#imghead2').attr('src');
        data.signature = $('input[name=signature]').val();
        data.email = $('input[name=email]').val();
        data.qq = $('input[name=qq]').val();
        data.wechat = $('input[name=wechat]').val();
        data.selfDesc = $('textarea[name=self-desc]').val();
        data.mobileVisible = $('input[name=mobile-visible]:checked').val();
        data.emailVisible = $('input[name=email-visible]:checked').val();
        data.qqVisible = $('input[name=qq-visible]:checked').val();
        data.wechatVisible = $('input[name=wechat-visible]:checked').val();
        $.ajax({
            url : '/member/settings',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                layer.alert(res.msg);
            }
        });
    });

    $('#edit-mobile-btn').on('click', function(){
        layer.open({
            skin: 'loginBox',
            title:'更改手机号',
            type: 1,
            content: $('#edit-mobile-div').html()
        });
        $('input[name=mobile]:visible').val('<?php echo $_memberInfo['mobile']; ?>');
    });
    $(document).on('click', '.edit-mobile-confirm-btn:visible', function(){
        var data = {};
        data.mobile = $('input[name=mobile]:visible').val();
        data.verifyCode = $('input[name=verifyCode]:visible').val();

        $.ajax({
            url : '/member/update-mobile',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(response){
                if(response.flag > 0){
                    layer.alert(response.msg, function(){location.reload();});
                }else{
                    layer.alert(response.msg);
                }
            }
        });
    });
    $('#edit-password-btn').on('click', function(){
        layer.open({
            skin: 'loginBox',
            title:'更改手机号',
            type: 1,
            content: $('#edit-password-div').html()
        });
    });

    $(document).on('click', '.edit-password-confirm-btn:visible', function(){
        var data = {};
        data.oldPwd = $('input[name=old-pwd]:visible').val();
        data.newPwd = $('input[name=new-pwd]:visible').val();
        data.confirmNewPwd = $('input[name=confirm-new-pwd]:visible').val();

        $.ajax({
            url : '/member/update-password',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(response){
                if(response.flag > 0){
                    layer.alert(response.msg, function(){location.reload();});
                }else{
                    layer.alert(response.msg);
                }
            }
        });
    });
</script>