<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'special')); ?>
        <!-- right部分 -->
        <div class="kp_right cj_pdbt">
            <div class="add_one">
                <div class="add_pp_left"><span class="gl_cjzc"><a href="/member/add-special">创建专场 +</a></span></div>
                <div class="add_pp_right11">
                    <table>
                        <tr>
                            <td class="cj_td1"></td>
                            <td class="cj_td2">专场信息</td>
                            <td class="cj_td3">拍品数量</td>
                            <td class="cj_td4">审核状态</td>
                        </tr>
                    </table>
                </div>
            </div>
            <?php
                foreach($specials as $v){
            ?>
                    <div class="kp_tj">

                        <?php
                            if($v['auctionStatus'] == 1){
                        ?>
                                <div class="kp_tj_left cj_jjjs">
                                    <p>即将开始</p>

                                    <p><?php echo date('m月d日 H:i', $v['startTime']) ?></p>

                                    <div class="cj_ad"><a href="javascript:;" class="del-special-btn" special-id="<?php echo $v['specialID'] ?>"> 删除</a></div>
                                </div>
                        <?php
                            }elseif($v['auctionStatus'] == 2) {
                                ?>
                                <div class="kp_tj_left cj_zzjx">
                                    <p>正在进行</p>
                                </div>
                            <?php
                            }elseif($v['auctionStatus'] == 3){
                        ?>
                                <div class="kp_tj_left cj_yjs">
                                    <p>已结束</p>

                                    <div class="cj_jtip">拍卖结束时候后<br>保留72小时</div>
                                    <div class="cj_ad"><a href="javascript:;" class="del-special-btn" special-id="<?php echo $v['specialID'] ?>"> 删除</a></div>
                                </div>
                        <?php
                            }elseif($v['verifyStatus'] == 1){
                        ?>
                                <div class="kp_tj_left">
                                    <p>等待通过</p>

                                    <div class="cj_ad"><a href="javascript:;" class="del-special-btn" special-id="<?php echo $v['specialID'] ?>"> 删除</a></div>
                                </div>
                        <?php
                            }elseif(empty($v['auctionStatus'])){
                        ?>
                                <div class="kp_tj_left">

                                    <p><?php echo $v['verifyStatus'] == 3 ? '等待修改' : '准备提交';?></p>

                                    <div class="cj_ad"><a href="javascript:;" class="special-verify-btn" special-id="<?php echo $v['specialID'] ?>"> 提交</a> <a href="/member/add-special?specialID=<?php echo $v['specialID'] ?>"> 编辑</a> <a href="javascript:;" class="del-special-btn" special-id="<?php echo $v['specialID'] ?>"> 删除</a></div>
                                </div>
                        <?php
                            }
                        ?>

                        <div class="kp_tj_right">
                            <table>
                                <tr>
                                    <td class="cj_info1" rowspan="3"><img <?php if($v['verifyStatus'] == 2){?>style="cursor: pointer;" onclick="location.href='/special/detail?specialID=<?php echo $v['specialID']; ?>'" <?php } ?> src="<?php echo $v['specialBanner'] ?>"></td>
                                    <td class="cj_info2" colspan="3">
                                        [创建时间] <?php echo date('Y-m-d', strtotime($v['instime'])) ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="cj_info2 cj_infoNew" rowspan="2"><?php echo $v['specialName']; ?></td>
                                    <td class="cj_info3">
                                        <?php echo $v['productCountLimit']; ?>
                                    </td>
                                    <td class="cj_info4">
                                        <?php
                                            if(empty($v['verifyStatus'])){
                                                echo '未开始';
                                            }elseif($v['verifyStatus'] == 1){
                                                echo '正在审核';
                                            }elseif($v['verifyStatus'] == 2){
                                                echo '已通过';
                                            }elseif($v['verifyStatus'] == 3){
                                                echo '未通过';
                                            }
                                        ?>
                                    </td>
                                </tr>
                                <tr>
                                    <td class="cj_info3">
                                        <a href="/member/special-product?specialID=<?php echo $v['specialID']; ?>">管理拍品</a>
                                    </td>
                                    <?php
                                        if($v['verifyStatus'] == 3){
                                    ?>
                                            <td class="cj_info4">
                                                <a href="javascript:;" onclick="layer.alert('<?php echo $v['denyReason']; ?>');" class="check-verify-status">查询>></a>
                                            </td>
                                    <?php
                                        }
                                    ?>

                                </tr>
                            </table>
                        </div>
                    </div>
            <?php
                }
            ?>
            <?php echo $this->render('/front/common/paginate', array('url' => '/member/special?', 'pages' => $pages)); ?>
        </div>



    </div>
</div>
<?php
echo $this->render('/front/common/pay');
echo $this->render('/front/common/transfer-account');
?>
<script>
    $(function(){
        $('.special-verify-btn').on('click', function(){
            var data = {};
            data.specialID = $(this).attr('special-id');

            $.ajax({
                url : '/member/special-verify',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.data && res.data['unitePayID']){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#pay-div').html()
                            });
                            $('.pay-price:visible').html(res.data['price']);
                            $('.pay-price:visible').attr('unite-pay-id', res.data['unitePayID']);
                        }else{
                            layer.alert(res.msg, function(){
                                location.reload();
                            });

                        }
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.payType = $('.selected-pay-type').attr('pay-type');
            if(!data.payType) {
                layer.alert('请选择付款方式');
                return false;
            }
            data.unitePayID = $('.pay-price:visible').attr('unite-pay-id');
            $.ajax({
                url : '/order/pay-special',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        if(res.flag == 1){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else if(res.flag == 2){
                            window.open(res.data['coreData']);
                        }else if(res.flag == 3){
                            layer.alert('申请开通中');
                            return false;
                            $('#public-content').html(res.data['coreData']);
                            document.pay_form.submit();
                        }else if(res.flag == 4){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: $('#transfer-account').html()
                            });
                        }else if(res.flag == 5){
                            layer.open({
                                skin: '',
                                title:'',
                                type: 1,
                                content: '<img src="/qrcode/' + res.data['coreData'] + '" />'
                            });
                        }
                        setInterval('checkOrderStatus(' + data.unitePayID + ', 3)', 2000);
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.del-special-btn').on('click', function(){
            var data = {};
            data.specialID = $(this).attr('special-id');
            data.isDel = 1;
            layer.confirm('确认删除吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/add-special',
                    type : 'post',
                    dataType : 'json',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert('删除成功', function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            }, function(){
                layer.closeAll();
            });

        });
    })
</script>