<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'special')); ?>
        <!-- right部分 -->
        <div class="kp_right cj_pdbt">
            <div class="add_one">
                <div class="add_pp_left"><span class="gl_cjzc"><a href="">创建专场 +</a></span></div>
                <div class="add_pp_right11">
                    <table>
                        <tr>
                            <td class="cj_td1"></td>
                            <td class="cj_td2">专场信息</td>
                            <td class="cj_td3">拍品数量</td>
                            <td class="cj_td4">审核状态</td>
                        </tr>
                    </table>
                </div>
            </div>
            <div class="kp_tj">
                <div class="kp_tj_left  cj_zzjx">
                    <p>正在进行</p>
                    <!-- <div class="cj_ad"><a href=""> 提交</a> <a href=""> 编辑</a>  <a href=""> 删除</a></div> -->
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                未开始
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="kp_tj">
                <div class="kp_tj_left">
                    <p>等待通过</p>

                    <div class="cj_ad"><a href=""> 删除</a></div>
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                正在审核
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="kp_tj">
                <div class="kp_tj_left cj_jjjs">
                    <p>即将开始</p>

                    <p>12月30日 10:00</p>

                    <div class="cj_ad"><a href=""> 删除</a></div>
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生内容大师的撒发生的的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                未通过
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="kp_tj">
                <div class="kp_tj_left cj_yjs">
                    <p>已结束</p>

                    <div class="cj_jtip">拍卖结束时刻后<br>保留72小时</div>
                    <div class="cj_ad"><a href=""> 删除</a></div>
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                正在拍卖
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="kp_tj">
                <div class="kp_tj_left">
                    <p>准备提交</p>

                    <div class="cj_ad"><a href=""> 提交</a> <a href=""> 编辑</a> <a href=""> 删除</a></div>
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生的内容大师的撒发生的内容大师的撒发生的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                已通过
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


            <div class="kp_tj ">
                <div class="kp_tj_left">
                    <p>准备提交</p>

                    <div class="cj_ad"><a href=""> 提交</a> <a href=""> 编辑</a> <a href=""> 删除</a></div>
                </div>
                <div class="kp_tj_right">
                    <table>
                        <tr>
                            <td class="cj_info1" rowspan="3"><img src=""></td>
                            <td class="cj_info2" colspan="3">
                                [创建时间] 2015-10-06
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info2" rowspan="2">内容大师的撒发生的方式发鬼地方个</td>
                            <td class="cj_info3">
                                36
                            </td>
                            <td class="cj_info4">
                                已通过
                            </td>
                        </tr>
                        <tr>
                            <td class="cj_info3">
                                <a href="">管理拍品</a>
                            </td>
                            <td class="cj_info4">
                                <a href="">查询>></a>
                            </td>
                        </tr>
                    </table>
                </div>
            </div>


        </div>


    </div>
</div>