<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <div class="kp_left">
            <div class="kp_biaot">
                <p class="kp_p kpdh">我是买家</p>
                <ul class="kp_ul mt10 kpdh1">
                    <a href="">
                        <li>正在竞拍</li>
                    </a>
                    <a href="">
                        <li>已购拍品</li>
                    </a>
                    <a href="">
                        <li>关注拍品</li>
                    </a>
                    <a href="">
                        <li>关注商家</li>
                    </a>
                    <a href="">
                        <li>买家须知</li>
                    </a>
                </ul>
            </div>
            <div class="kp_biaot">
                <p class="kp_p kpdh2">我是商家</p>
                <ul class="kp_ul mt10">
                    <a href="fbPaiPin.html">
                        <li>发布拍品</li>
                    </a>
                    <a href="ppChangKu.html">
                        <li class="kp_checked">拍品仓库</li>
                    </a>
                    <a href="glzhuanchang.html">
                        <li>管理专场</li>
                    </a>
                    <a href="ysPaiPin.html">
                        <li>已售拍品</li>
                    </a>
                    <a href="sjSheZhi.html">
                        <li>商家设置</li>
                    </a>
                    <a href="index.html">
                        <li>认证流程</li>
                    </a>
                </ul>
            </div>
        </div>
        <!-- right部分 -->
        <div class="kp_right">
            <div class="add_one">
                <div class="add_pp_left"><span class="gl_cjzc"><a href="">添加拍品 +</a></span></div>
                <div class="add_pp_right">
                    <span class="add_x"> 先听球会卡死的哈萨> 拍品列表</span>
                    <span class="add_x1"><span><a href="">推荐</a></span><span class="add_x2"><a
                                href="">删除</a></span></span>
                </div>
            </div>
            <div class="add_list">
                <ul>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                    <li>
                        <div class="add_lefimg"><img src=""><input type="checkbox" name="checkbox1" value="checkbox"
                                                                   class="ind_checkbox  add_lefimg01"></div>
                        <div class=" addlicon">
                            <p>信息印社 李萍《妙招自然》</p>

                            <p class="add_qpj">起拍价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <p class="add_qpj10">保留价 <input class="mt_input" type="text" placeholder="" value="1600"> <a
                                    href="">修改</a></p>

                            <div class="add_qpj"><a href="">取消保留价 </a><span class="add_tjian"><a
                                        href="">编辑</a></span><span class="add_x2"><a href="">推荐</a></span><span
                                    class="add_x2"><a href="">删除</a></span></div>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

    </div>
</div>