<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'store-order')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li onclick="location.href='/member/store-order';" class="<?php if(empty($orderStatus)){echo 'ys_acted';} ?>">所有订单</a></li>
                    <li onclick="location.href='/member/store-order?orderStatus=1';" class="<?php if($orderStatus == 1){echo 'ys_acted';} ?>">待付款</li>
                    <li onclick="location.href='/member/store-order?orderStatus=3';" class="<?php if($orderStatus == 3){echo 'ys_acted';} ?>">待发货</li>
                    <li onclick="location.href='/member/store-order?orderStatus=4';" class="<?php if($orderStatus == 4){echo 'ys_acted';} ?>">待收货</li>
                    <li onclick="location.href='/member/store-order?orderStatus=5';" class="<?php if($orderStatus == 5){echo 'ys_acted';} ?>">已完成</li>
                    <li class="del-order-batch"><img src="/dist/images/del_03.png"></li>
                    <li class="ys_searhc1"><input id="search-item" value="<?php echo $search; ?>" class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc" id="search-btn">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">买得价</span><span class="ys_span3">订单操作</span><span
                    class="ys_span3">订单状态</span>
            </div>
            <p class="kp_tsinfo" style="padding-left:0px;">*买家付款后请于72小时内发货，未按时发货买家可直接退款，导致交易关闭，并将直接影响您的信用。</p>
            <?php foreach($orders as $v){
            ?>
            <div class="ys_tip2" id="order-item-<?php echo $v['orderID'] ?>">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" order-id="<?php echo $v['orderID'] ?>" class="ind_checkbox order-item"><?php echo date('Y-m-d', strtotime($v['instime'])); ?></span>
                        <span class="yc_pm1">[订单号] <?php echo $v['businessID'] ?></span>
                        <span class="yc_pm2" style="background: none;"><img src="<?php echo $v['avatar'] ?>" alt="">&nbsp;<span><?php echo $v['nickName'] ?></span></span>
                        <span class="yc_pm3 lxmj"><a qq="<?php echo $v['qq'] ?>" href="javascript:;" class="tencent-qq">联系买家</a></span>
                        <span class="yc_pm4"><a href="javascript:;" class="post-complain-btn" order-id="<?php echo $v['orderID'] ?>">网站申诉</a></span>
                        <span class="yc_pm5" ><a href = "javascript:;" class="del-order-btn" order-id="<?php echo $v['orderID'] ?>" > 删除</a ></span >
                        </div>
                        <div class="ys_tip6">
                            <div class="yc_imgleft"><img style="cursor:pointer;" onclick="window.open('<?php if($v['orderType'] == 1){ ?>/product/snap?productID=<?php echo $v['orderID']; ?><?php }else{ ?>/customization/detail?customizationID=<?php echo $v['customizationID']; ?><?php } ?>');" src="<?php echo $v['product']['listImg']; ?>"></div>
                            <div class="yc_imgleft1">
                                <p class="yc_imgleft2"><span class="yc_ysname1"><?php echo $v['product']['productName'] ?></span> <span class="yc_money"><?php echo $v['productPrice'] ?></span>
                                </p>

                                <div class="yc_ysname2">
                                    <p>
                                        <span class="yc_ysname">佣金</span> <span class="yc_money"><?php echo $v['commision'] ?></span>
                                    </p>
                                    <p>
                                        <span class="yc_ysname">实付</span> <span class="yc_money"><?php echo $v['payMoney'] ?></span>
                                    </p>
                                </div>
                            </div>
                            <?php
                            if($v['orderStatus'] == 1){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">等待付款</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">等待买家付款</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情&rsaquo;&rsaquo;</a></p>
                                    <!--<p class="yc_p"><a href="javascript:;" class="cancel-order-btn" order-id="<?php /*echo $v['orderID'] */?>">关闭交易</a></p>-->
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 3){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1 set-delivery-type" style="cursor: pointer;" order-id="<?php echo $v['orderID']; ?>">请发货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">买家已付款</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情&rsaquo;&rsaquo;</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 4){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">等待收货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">卖家已发货</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情&rsaquo;&rsaquo;</a></p>
                                    <?php
                                        if($v['orderType'] == 1){
                                    ?>
                                            <?php
                                                if($v['returnStatus'] == 1){
                                            ?>
                                                    <?php
                                                        if($v['returnType'] == 2){
                                                    ?>
                                                            <p class="yc_p"><a href="javascript:;" class="accept-return-order-only-money-btn" order-id="<?php echo $v['orderID'] ?>">买家申请退款不退货</a></p>
                                                            <?php if(!empty($v['applyReturnReason'])){
                                                                ?>
                                                                <p class="yc_p">申请理由:<br /><?php echo $v['applyReturnReason']; ?></p>
                                                            <?php
                                                            } ?>

                                                    <?php
                                                        }elseif($v['returnType'] == 3){
                                                    ?>
                                                            <p class="yc_p"><a href="javascript:;" class="accept-return-order-btn" order-id="<?php echo $v['orderID'] ?>">买家申请退款</a></p>
                                                            <?php if(!empty($v['applyReturnReason'])){
                                                                ?>
                                                                <p class="yc_p">申请理由:<br /><?php echo $v['applyReturnReason']; ?></p>
                                                            <?php
                                                            } ?>

                                                    <?php
                                                        }
                                                    ?>


                                            <?php
                                                }elseif($v['returnStatus'] == 3){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;">等待买家发货</a></p>
                                            <?php
                                                }elseif($v['returnStatus'] == 4){
                                            ?>
                                                    <p class="yc_p"><a href="javascript:;" class="check-return-order-delivery" return-delivery-type="<?php foreach($deliveryTypes as $sv){if($sv['deliveryTypeID'] == $v['returnDeliveryType']){echo $sv['typeName'];}} ?>" return-delivery-num="<?php echo $v['returnDeliveryNum']; ?>">买家已发货</a></p>
                                                    <p class="yc_p">
                                                        <a href="javascript:;" class="confirm-return-order-btn" order-id="<?php echo $v['orderID'] ?>">确认到货</a>|<a href="javascript:;" class="no-confirm-return-order-btn" order-id="<?php echo $v['orderID'] ?>">未到货</a>
                                                    </p>
                                            <?php
                                                }
                                            ?>
                                    <?php
                                        }
                                    ?>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 5){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk2">交易成功</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">买家已收货</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情&rsaquo;&rsaquo;</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == -1 || $v['orderStatus'] == -2){
                            ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_jyjs">交易关闭</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="javascript:;">未按时付款/退货</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情&rsaquo;&rsaquo;</a></p>
                                    <p class="yc_p"><a href="javascript:;">已关闭</a></p>
                                </div>
                            <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            <?php
            } ?>
            <?php
            echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/member/store-order?orderStatus=' . $orderStatus . '&'));
            ?>
        </div>
    </div>
</div>
<?php
    echo $this->render('set-delivery-type');
    echo $this->render('set-return-addr');
?>
<script>
    $(function(){
        $('#search-btn').on('click', function(){
            var search = $('#search-item').val();
            if(!search){
                layer.alert('请输入搜索内容');
                return false;
            }
            location.href = '/member/store-order?search=' + search;
        });

        function delOrder(data){
            layer.confirm('确认删除吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/store-del-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            }, function(){
                layer.closeAll();
            });

        }

        $('.del-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            delOrder(data);

        });

        $('.del-orde-batch').on('click', function(){
            var data = {};
            data.orderID = new Array();
            var checkedOrders = $('.order-item-chk:checked');
            if(!checkedOrders.length){
                layer.alert('请选择要取消的订单');
                return false;
            }
            checkedOrders.each(function(){
                var tmpOrderID = $(this).attr('order-id');
                data.orderID.push(tmpOrderID);
            });
            delOrder(data);
        });

        /*$('.cancel-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            layer.confirm('确认关闭交易吗？', {
                btn: ['确认','取消'] //按钮
            }, function(){
                $.ajax({
                    url : '/member/store-cancel-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }

                    }
                });
            }, function(){
                layer.closeAll();
            });


        });*/

        $('.set-delivery-type').on('click', function(){
            layer.open({
                skin: 'loginBox',
                title:'发货信息',
                type: 1,
                content: $('#set-delivery-type-div').html()
            });
            var orderID = $(this).attr('order-id');
            $('.confirm-delivery-btn:visible').attr('order-id', orderID);
        });
        $(document).on('click', '.confirm-delivery-btn:visible', function() {
            var data = {};
            data.orderID = $(this).attr('order-id');
            data.haveDelivery = $('input[name=have-delivery]:visible:checked').val();
            if(data.haveDelivery){
                data.haveDelivery = 1;
                data.deliveryType = $('select[name=delivery-type]:visible').val();
                data.deliveryNum = $('input[name=delivery-num]:visible').val();
            }else{
                data.haveDelivery = 0;
            }
            $.ajax({
                url : '/member/confirm-delivery-info',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });
        $(document).on('click', '.set-return-addr-btn:visible', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            data.accept = 1;
            data.orderReturnReceiverName = $('input[name=orderReturnReceiverName]:visible').val();
            data.orderReturnReceiverMobile = $('input[name=orderReturnReceiverMobile]:visible').val();
            data.orderReturnReceiverAddr = $('input[name=orderReturnReceiverAddr]:visible').val();
            if(!data.orderReturnReceiverName){
                layer.alert('请填写退货地址收货人姓名');
                return false;
            }
            if(!data.orderReturnReceiverMobile){
                layer.alert('请填写退货地址收货人电话');
                return false;
            }
            if(!data.orderReturnReceiverAddr){
                layer.alert('请填写退货地址');
                return false;
            }
            $.ajax({
                url : '/member/accept-return-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.accept-return-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            layer.confirm('是否同意买家退款申请？', {
                btn: ['同意','不同意'] //按钮
            }, function(){

                layer.open({
                    skin: 'loginBox',
                    title:'退货地址',
                    type: 1,
                    content: $('#set-return-addr-div').html()
                });
                $('.set-return-addr-btn:visible').attr('order-id', data.orderID);


            }, function(){
                data.accept = 0;
                $.ajax({
                    url : '/member/accept-return-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            });
        });

        $('.accept-return-order-only-money-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            layer.confirm('是否同意买家退款申请？', {
                btn: ['同意','不同意'] //按钮
            }, function(){
                data.accept = 1;
                $.ajax({
                    url : '/member/accept-return-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            }, function(){
                data.accept = 0;
                $.ajax({
                    url : '/member/accept-return-order',
                    dataType : 'json',
                    type : 'post',
                    data : data,
                    success : function(res){
                        if(res.flag > 0){
                            layer.alert(res.msg, function(){
                                location.reload();
                            });
                        }else{
                            layer.alert(res.msg);
                        }
                    }
                });
            });
        });

        $('.confirm-return-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            $.ajax({
                url : '/member/confirm-return-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.no-confirm-return-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            $.ajax({
                url : '/member/no-confirm-return-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.check-return-order-delivery').on('click', function(){
            var returnDeliveryType = $(this).attr('return-delivery-type');
            var returnDeliveryNum = $(this).attr('return-delivery-num');
            if(returnDeliveryType){
                var str = '物流公司: ' + returnDeliveryType + '\n物流单号: ' + returnDeliveryNum + '\n';
                layer.alert(str);
            }else{
                layer.alert('无物流信息');
            }
        });
    })
</script>