<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'store-order')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li onclick="location.href='/member/store-order';" class="<?php if(empty($orderStatus)){echo 'ys_acted';} ?>">所有订单</a></li>
                    <li onclick="location.href='/member/store-order?orderStatus=1';" class="<?php if($orderStatus == 1){echo 'ys_acted';} ?>">待付款</li>
                    <li onclick="location.href='/member/store-order?orderStatus=3';" class="<?php if($orderStatus == 3){echo 'ys_acted';} ?>">待发货</li>
                    <li onclick="location.href='/member/store-order?orderStatus=4';" class="<?php if($orderStatus == 4){echo 'ys_acted';} ?>">待收货</li>
                    <li onclick="location.href='/member/store-order?orderStatus=5';" class="<?php if($orderStatus == 5){echo 'ys_acted';} ?>">已完成</li>
                    <li class="cancel-order-batch"><img src="/jinren/images/del_03.jpg"></li>
                    <li class="ys_searhc1"><input id="search-item" value="<?php echo $search; ?>" class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc" id="search-btn">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">买得价</span><span class="ys_span3">订单操作</span><span
                    class="ys_span3">订单状态</span>
            </div>
            <?php foreach($orders as $v){
            ?>
            <div class="ys_tip2" id="order-item-<?php echo $v['orderID'] ?>">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><?php if ($v['orderStatus'] > 1) {
                                echo '&nbsp';
                            } else { ?> <input type="checkbox" name="checkbox1" value="checkbox"
                                               order-id="<?php echo $v['orderID'] ?>"
                                               class="ind_checkbox order-item"><?php } ?><?php echo date('Y-m-d', strtotime($v['instime'])); ?></span>
                        <span class="yc_pm1">[订单号] <?php echo $v['businessID'] ?></span>
                        <span class="yc_pm2"
                              style="background:transparent url('<?php echo $v['storeLogo'] ?>') no-repeat scroll 6% center"><?php echo $v['storeName'] ?></span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <?php if ($v['orderStatus'] < 1) {
                        ?>
                        <span class="yc_pm5" ><a href = "javascript:;" class="cancel-order-btn" order-id="<?php echo $v['orderID'] ?>" > 删除</a ></span >
                            <?php
                                }
                            ?>
                        </div>
                        <div class="ys_tip6">
                            <div class="yc_imgleft"><img src="<?php echo $v['product']['listImg']; ?>"></div>
                            <div class="yc_imgleft1">
                                <p class="yc_imgleft2"><span class="yc_ysname"><?php echo $v['product']['productName'] ?></span> <span class="yc_money"><?php echo $v['productPrice'] ?></span>
                                </p>

                                <div class="yc_ysname1">
                                    <?php if(!empty($v['commision'])){
                                        ?>
                                        <p><span class="yc_ysname">佣金</span> <span class="yc_money"><?php echo $v['commision'] ?></span></p>
                                    <?php
                                    } ?>
                                    <p><span class="yc_ysname">实付</span> <span class="yc_money"><?php echo $v['payMoney'] ?></span></p>
                                </div>
                            </div>
                            <?php
                            if($v['orderStatus'] == 1){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">等待付款</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="">等待买家付款</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 3){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1 set-delivery-type" style="cursor: pointer;" order-id="<?php echo $v['orderID']; ?>">请发货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="">买家已付款</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 4){
                                ?>
                                <div class="yc_ddfk yc_imgleft2">
                                    <div class="yc_ddfk1">等待收货</div>
                                </div>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="">卖家已发货</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }elseif($v['orderStatus'] == 5){
                                ?>
                                <div class="yc_ddright yc_imgleft2">
                                    <p class="yc_p"><a href="">买家已收货</a></p>
                                    <p class="yc_p"><a href="/member/store-order-detail?orderID=<?php echo $v['orderID'] ?>">订单详情</a></p>
                                </div>
                            <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            <?php
            } ?>
            <?php
            echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/member/store-order?orderStatus=' . $orderStatus . '&'));
            ?>
        </div>
    </div>
</div>
<?php
    echo $this->render('set-delivery-type');
?>
<script>
    $(function(){
        $('#search-btn').on('click', function(){
            var search = $('#search-item').val();
            if(!search){
                layer.alert('请输入搜索内容');
                return false;
            }
            location.href = '/member/store-order?search=' + search;
        });

        function cancelOrder(data){
            $.ajax({
                url : '/member/store-cancel-order',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    layer.alert(response.msg);
                }
            });
        }

        $('.cancel-order-btn').on('click', function(){
            var data = {};
            data.orderID = $(this).attr('order-id');
            $('#order-item-' + data.orderID).remove();
            cancelOrder(data);

        });

        $('.cancel-orde-batch').on('click', function(){
            var data = {};
            data.orderID = new Array();
            var checkedOrders = $('.order-item-chk:checked');
            if(!checkedOrders.length){
                layer.alert('请选择要取消的订单');
                return false;
            }
            checkedOrders.each(function(){
                var tmpOrderID = $(this).attr('order-id');
                data.orderID.push(tmpOrderID);
                $('#order-item-' + tmpOrderID).remove();
            });
            cancelOrder(data);
        });
        $('.set-delivery-type').on('click', function(){
            layer.open({
                skin: 'loginBox',
                title:'发货信息',
                type: 1,
                content: $('#set-delivery-type-div').html()
            });
            var orderID = $(this).attr('order-id');
            $('.confirm-delivery-btn:visible').attr('order-id', orderID);
        });
        $(document).on('click', '.confirm-delivery-btn:visible', function() {
            var data = {};
            data.orderID = $(this).attr('order-id');
            data.haveDelivery = $('input[name=have-delivery]:visible:checked').val();
            if(data.haveDelivery){
                data.haveDelivery = 1;
                data.deliveryType = $('select[name=delivery-type]:visible').val();
                data.deliveryNum = $('input[name=delivery-num]:visible').val();
            }else{
                data.haveDelivery = 0;
            }
            $.ajax({
                url : '/member/confirm-delivery-info',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });
    })
</script>