<link rel="stylesheet" href="/jinren/style/jiameng.css" media="screen" type="text/css" />
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'store-join')); ?>
        <!-- right部分 -->
        <div class="kp_right jm_main">
            <div><img src="/jinren/images/jm1_03.jpg"></div>
            <p class="jm_shinfo">审核中，请等待审核通过。。。。。</p>

            <p class="jm_shinfo1">审核期约提交日起五个工作日</p>


        </div>


    </div>
</div>