<link href="/jinren/style/jiameng.css" media="screen" rel="stylesheet" type="text/css">
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'store-join')); ?>
        <!-- right部分 -->
        <div class="kp_right jm_main">
            <div><img src="/jinren/images/jm_03.jpg"></div>
            <p>上传实名认证信息</p>

            <div class="jm_sfz">
                <div class="jm_sfz1">身份证号码</div>
                <div class="jm_sfz2"><input type="text" placeholder="身份证号码" id="id-number" value="<?php echo !empty($_storeInfo) ? $_storeInfo['idNumber'] : ''; ?>"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">身份证图片</div>
                <div class="jm_sfz2"><a href="javascript:;" class="a-upload">
                        <input type="file" class="fileEle" target="#id-pic" />上传身份证图片
                    </a>
                </div>
                <div class="jm_sfz5 jm_lef" id="id-pic"><img src="<?php echo !empty($_storeInfo) ? $_storeInfo['idPic'] : '/jinren/images/ewe_03.jpg'; ?>" ></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">&nbsp</div>
                <div class="jm_sfz2"><a href="javascript:;" class="a-upload">
                        <input type="file" class="fileEle" target="#member-id-pic" />上传本人手持身份证图片
                    </a>
                </div>
                <div class="jm_sfz5 jm_lef" id="member-id-pic"><img src="<?php echo !empty($_storeInfo) ? $_storeInfo['memberIdPic'] : '/jinren/images/ewe_03.jpg'; ?>"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">退货地址收件人姓名</div>
                <div class="jm_sfz2"><input type="text" placeholder="退货地址收件人姓名" id="return-receiver-name" value="<?php echo !empty($_storeInfo) ? $_storeInfo['returnReceiverName'] : ''; ?>"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">退货地址收件人电话</div>
                <div class="jm_sfz2"><input type="text" placeholder="退货地址收件人电话" id="return-receiver-mobile" value="<?php echo !empty($_storeInfo) ? $_storeInfo['returnReceiverMobile'] : ''; ?>"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">退货地址</div>
                <div class="jm_sfz2"><input type="text" placeholder="退货地址" id="return-receiver-addr" value="<?php echo !empty($_storeInfo) ? $_storeInfo['returnReceiverAddr'] : ''; ?>"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">绑定手机号</div>
                <div class="jm_sfz2">
                    <input class="jm_sfz2input" type="text" placeholder="手机号码" id="store-mobile" value="<?php echo !empty($_storeInfo) ? $_storeInfo['storeMobile'] : ''; ?>"> <span> <a
                            href="javascript:;" id="btn_getcode">发送验证码>></a></span>
                </div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">&nbsp</div>
                <div class="jm_sfz2">
                    <input class="jm_sfz2input" type="text" placeholder="手机验证码" id="store-mobile-code">
                </div>
            </div>
            <div class="jm_sfz">
                <input type="checkbox" id="join-rules">
                我已经阅读并同意<a href="/article/setting?settingName=joinRule" target="_blank" style="color:#61b7d9">《入驻规则》</a>
            </div>
            <div class="jm_tj" id="submit-verify-btn">
                提交审核
            </div>


        </div>


    </div>
</div>

<script type="text/javascript">
    var lock = true;
    $('#submit-verify-btn').on('click', function(){
        var data = {};
        data.idNumber = $('#id-number').val();
        data.idPic = $('#id-pic').find('img').attr('src');
        data.memberIdPic = $('#member-id-pic').find('img').attr('src');
        data.storeMobile = $('#store-mobile').val();
        data.storeMobileCode = $('#store-mobile-code').val();
        data.returnReceiverName = $('#return-receiver-name').val();
        data.returnReceiverMobile = $('#return-receiver-mobile').val();
        data.returnReceiverAddr = $('#return-receiver-addr').val();
        var joinRuleCheceked = $('#join-rules:checked').length;
        if(!joinRuleCheceked){
            layer.alert('未同意入驻规则');
            return false;
        }
        if(!data.idNumber){
            layer.alert('请输入身份证号码');
            return false;
        }
        if(!data.idPic){
            layer.alert('请上传身份证图片');
            return false;
        }
        if(!data.memberIdPic){
            layer.alert('请上传本人手持身份证图片');
            return false;
        }
        if(!data.returnReceiverName){
            layer.alert('请填写退货地址收件人姓名');
            return false;
        }
        if(!data.returnReceiverMobile){
            layer.alert('请填写退货地址收件人电话');
            return false;
        }
        if(!data.returnReceiverAddr){
            layer.alert('请填写退货地址');
            return false;
        }
        if(!data.storeMobile){
            layer.alert('请输入绑定手机号');
            return false;
        }
        if(!data.storeMobileCode){
            layer.alert('请输入手机验证码');
            return false;
        }

        if(lock){
            lock = false;
            $.ajax({
                url : '/member/store-verify',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(data){
                    if(data.flag > 0){
                        location.href = '/member/store-join';
                    }else{
                        layer.alert(data.msg);
                    }
                }
            });
        }


    });

    var re = /^(((13[0-9]{1})|(15[0-9]{1})|(17[0-9]{1})|(18[0-9]{1}))+\d{8})$/;
    var reSend = true;
    $('#btn_getcode').bind('click', function() {
        var mobile = $('#store-mobile').val();
        if (!re.test(mobile)) {
            layer.alert('请输入正确的手机号码');
            return false;
        };
        if (reSend) {
            var flag = 1;
            $.ajax({
                url : '/index/get-verify-code',
                type : 'post',
                async : false,
                data : {mobile : mobile},
                dataType : 'json',
                success : function(data) {
                    if(data.flag <= 0){
                        flag = 0;
                        layer.alert(data.msg);
                    }
                }
            });
            if(!flag) return;
            reSend = false; //禁止反复发送
            var html = '<b>5</b>秒重新获取';
            $('#btn_getcode').addClass('btn_code_yz');
            $('#btn_getcode').html(html);
            regCodeInterval = setInterval(function() {
                regCodeTimeinterval();
            }, 1000);

        }
    });

    function regCodeTimeinterval() {
        var currTime = $('#btn_getcode').find('b').html();
        var newTime = parseInt(currTime) - 1;
        if (newTime) {
            $('#btn_getcode').find('b').html(newTime);
        } else {
            clearInterval(regCodeInterval);
            $('#btn_getcode').removeClass('btn_code_yz');
            $('#btn_getcode').html('重新发送');
            reSend = true;
        }
    };
</script>