<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'store-setting')); ?>
        <!-- right部分 -->
        <div class="kp_right">
            <div class="mt20">
                <span class="ind_jrzz bold">店铺名称</span>
                <input class="zz_inputqm" type="text" id="storeName" placeholder="" value="<?php echo !empty($_storeInfo['storeName']) ? $_storeInfo['storeName'] : ''; ?>">
                <br> <span class="ind_jrzz"></span>
            </div>
            <div class="mt20">
                <div class="ind_jrzz bold">店铺标志</div>
                <div class="dianpbai curfile" id="imghead"><img src="<?php echo !empty($_storeInfo['storeLogo']) ? $_storeInfo['storeLogo'] : '/images/img_03.jpg'?>"></div>
                <em style="color:red;">*200x200像素</em><input type="file" class="fileEle" />
            </div>
            <div class="mt20">
                <div class="ind_jrzz bold">店铺抬头</div>
                <div class="dianpbai1 curfile" id="imghead1"><img src="<?php echo !empty($_storeInfo['storeBanner']) ? $_storeInfo['storeBanner'] : '/images/img_06.jpg'?>"></div>
                <em style="color:red;">*1200x300像素</em><input type="file" class="fileEle" />
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">店铺签名</span>
                <input class="zz_inputqm" type="text" id="signature" placeholder="" value="<?php echo !empty($_storeInfo['storeSignature']) ? $_storeInfo['storeSignature'] : ''; ?>">
                <br> <span class="ind_jrzz"></span> *限35字以内，显示在店铺名称下方
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">退货地址收件人姓名</span>
                <input class="zz_inputqm" type="text" id="return-receiver-name" placeholder="" value="<?php echo !empty($_storeInfo['returnReceiverName']) ? $_storeInfo['returnReceiverName'] : ''; ?>">
                <br> <span class="ind_jrzz"></span>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">退货地址收件人电话</span>
                <input class="zz_inputqm" type="text" id="return-receiver-mobile" placeholder="" value="<?php echo !empty($_storeInfo['returnReceiverMobile']) ? $_storeInfo['returnReceiverMobile'] : ''; ?>">
                <br> <span class="ind_jrzz"></span>
            </div>
            <div class="mt20">
                <span class="ind_jrzz bold">退货地址</span>
                <input class="zz_inputqm" type="text" id="return-receiver-addr" placeholder="" value="<?php echo !empty($_storeInfo['returnReceiverAddr']) ? $_storeInfo['returnReceiverAddr'] : ''; ?>">
                <br> <span class="ind_jrzz"></span>
            </div>
            <div class="mt20">
                <div class="ind_jrzz bold" id="store-categories">拍品分类</div>
                <?php
                    foreach($storeCategories as $v){
                ?>
                        <input type="text" value="<?php echo $v['storeCategoryName'] ?>" placeholder="分类名称" class="ind_dp1 storeCategory">
                <?php
                    }
                ?>

                <span class="ind_jia" id="add-store-category-btn"> &nbsp</span>
            </div>
            <div class="mt20  ycsd">
                <span class="ind_jrzz bold" style="float:left">店铺自述</span>

                <div><span class="ind_fbxx">发布须知</span><span>不得发布反动，暴恐，色情信息</span></div>

            </div>
            <div class="mt20  ycsd">
                <span class="ind_jrzz" style="float:left"> &nbsp</span>

                <div style="width:540px; background:#fff; float:left">
                    <script id="qqq" name="storeDesc" type="text/plain" style="width:700px;height:300px;"><?php echo !empty($_storeInfo['storeDesc']) ? $_storeInfo['storeDesc'] : ''?></script>
                </div>
            </div>

            <div class="ind_licj" id="store-settings-committ">确认提交</div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        //alert(1);

        /*$('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });*/
        var qqq = UE.getEditor('qqq');

        $('#add-store-category-btn').on('click', function(){
            $('#store-categories').after('<input type="text" value="" placeholder="分类名称" class="ind_dp1 storeCategory">');
        });

        $('#store-settings-committ').on('click', function(){
            var storeLogo = $('#imghead').find('img').attr('src');
            var storeBanner = $('#imghead1').find('img').attr('src');
            var signature = $('#signature').val();
            var storeCategory = new Array();
            $('.storeCategory').each(function(){
                storeCategory.push($(this).val());
            });
            var storeDesc = qqq.getContent();
            var storeName = $('#storeName').val();
            var data = {
                storeLogo : storeLogo,
                storeBanner : storeBanner,
                //recommendImg : recommendImg,
                storeSignature : signature,
                storeCategory : storeCategory,
                storeDesc : storeDesc,
                storeName : storeName
            };
            if(!storeName){
                layer.alert('请填写店铺名称');
                return false;
            }
            if(!storeLogo){
                layer.alert('请上传店铺标志');
                return false;
            }
            if(!storeBanner){
                layer.alert('请上传店铺抬头');
                return false;
            }
            data.returnReceiverName = $('#return-receiver-name').val();
            data.returnReceiverMobile = $('#return-receiver-mobile').val();
            data.returnReceiverAddr = $('#return-receiver-addr').val();

            if(!data.returnReceiverName){
                layer.alert('请填写退货地址收件人姓名');
                return false;
            }
            if(!data.returnReceiverMobile){
                layer.alert('请填写退货地址收件人电话');
                return false;
            }
            if(!data.returnReceiverAddr){
                layer.alert('请填写退货地址');
                return false;
            }


            $.ajax({
                url : '/member/store-setting',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(data){
                    layer.open({
                        type : 0,
                        icon : 1,
                        content : data.msg,
                        shadeClose: true,
                        time: 2000
                    });
                }
            });
        });
    })
</script>