<?php echo $this->headLink()->appendStylesheet('/jinren/style/jiameng.css'); ?>
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'supplier-join')); ?>
        <!-- right部分 -->
        <div class="kp_right jm_main">
            <div><img src="/jinren/images/jm_03.jpg"></div>
            <p>上传实名认证信息</p>

            <div class="jm_sfz">
                <div class="jm_sfz1">身份证号码</div>
                <div class="jm_sfz2"><input type="text" placeholder="4222222222222222222"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">身份证图片</div>
                <div class="jm_sfz2"><a href="javascript:;" class="a-upload">
                        <input type="file" name="" onchange="previewImage(this)">上传身份证图片
                    </a>
                </div>
                <div class="jm_sfz5 jm_lef" id="preview"><img src="/jinren/images/ewe_03.jpg"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">&nbsp</div>
                <div class="jm_sfz2"><a href="javascript:;" class="a-upload">
                        <input type="file" name="" onchange="previewImage1(this)">上传本人手持身份证图片
                    </a>
                </div>
                <div class="jm_sfz5 jm_lef" id="preview1"><img src="/jinren/images/ewe_03.jpg"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">绑定手机号</div>
                <div class="jm_sfz2">
                    <input class="jm_sfz2input" type="text" placeholder="13282111111"> <span> <a
                            href="">发送验证码>></a></span>
                </div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">&nbsp</div>
                <div class="jm_sfz2">
                    <input class="jm_sfz2input" type="text" placeholder="6666"> <span class="jm_yzm"> 绑定</span>
                </div>
            </div>
            <div class="jm_tj">
                提交审核
            </div>


        </div>


    </div>
</div>

<script type="text/javascript">

    //图片上传预览    IE是用了滤镜。
    function previewImage(file) {

        var div = document.getElementById('preview');
        if (file.files && file.files[0]) {
            div.innerHTML = '<img id=imghead>';
            var img = document.getElementById('imghead');
            img.onload = function () {
                var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
                img.width = rect.width;
                img.height = rect.height;
//                 img.style.marginLeft = rect.left+'px';
                img.style.marginTop = rect.top + 'px';
            }
            var reader = new FileReader();
            reader.onload = function (evt) {
                img.src = evt.target.result;
            }
            reader.readAsDataURL(file.files[0]);
        }
        else //兼容IE
        {
            var sFilter = 'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="';
            file.select();
            var src = document.selection.createRange().text;
            div.innerHTML = '<img id=imghead>';
            var img = document.getElementById('imghead');
            img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;
            var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
            status = ('rect:' + rect.top + ',' + rect.left + ',' + rect.width + ',' + rect.height);
            div.innerHTML = "<div id=divhead style='width:" + rect.width + "px;height:" + rect.height + "px;" + sFilter + src + "\"'></div>";
        }
    }
    //图片上传预览    IE是用了滤镜。
    function previewImage1(file) {

        var div = document.getElementById('preview1');
        if (file.files && file.files[0]) {
            div.innerHTML = '<img id=imghead>';
            var img = document.getElementById('imghead');
            img.onload = function () {
                var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
                img.width = rect.width;
                img.height = rect.height;
//                 img.style.marginLeft = rect.left+'px';
                img.style.marginTop = rect.top + 'px';
            }
            var reader = new FileReader();
            reader.onload = function (evt) {
                img.src = evt.target.result;
            }
            reader.readAsDataURL(file.files[0]);
        }
        else //兼容IE
        {
            var sFilter = 'filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(sizingMethod=scale,src="';
            file.select();
            var src = document.selection.createRange().text;
            div.innerHTML = '<img id=imghead>';
            var img = document.getElementById('imghead');
            img.filters.item('DXImageTransform.Microsoft.AlphaImageLoader').src = src;
            var rect = clacImgZoomParam(MAXWIDTH, MAXHEIGHT, img.offsetWidth, img.offsetHeight);
            status = ('rect:' + rect.top + ',' + rect.left + ',' + rect.width + ',' + rect.height);
            div.innerHTML = "<div id=divhead style='width:" + rect.width + "px;height:" + rect.height + "px;" + sFilter + src + "\"'></div>";
        }
    }


    function clacImgZoomParam(maxWidth, maxHeight, width, height) {
        var param = {top: 0, left: 0, width: width, height: height};
        if (width > maxWidth || height > maxHeight) {
            rateWidth = width / maxWidth;
            rateHeight = height / maxHeight;

            if (rateWidth > rateHeight) {
                param.width = maxWidth;
                param.height = Math.round(height / rateWidth);
            } else {
                param.width = Math.round(width / rateHeight);
                param.height = maxHeight;
            }
        }

        param.left = Math.round((maxWidth - param.width) / 2);
        param.top = Math.round((maxHeight - param.height) / 2);
        return param;
    }
</script>