<?php echo $this->headLink()->appendStylesheet('/jinren/style/jiameng.css'); ?>
<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'supplier-join')); ?>
        <!-- right部分 -->
        <div class="kp_right jm_main">
            <div><img src="/jinren/images/jm2_03.jpg"></div>
            <p>实名认证信息</p>

            <div class="jm_sfz">
                <div class="jm_sfz1">身份证号码</div>
                <div class="jm_sfz2 jm_wt">3333*************</div>
                <div class="jm_sfz5"><img src="/jinren/images/jmimg_07.jpg"></div>
            </div>
            <div class="jm_sfz">
                <div class="jm_sfz1">绑定手机号</div>
                <div class="jm_sfz2 jm_wt">130****633</div>
            </div>
            <div class="jm_tj5">
                审核已通过，开始使用商家功能
            </div>


        </div>


    </div>
</div>