<div class="kp_main">
    <div class="center ">
        <!-- left部分 -->
        <?php echo $this->render('left', array('leftTab' => 'supplier-order')); ?>
        <!-- right部分 -->
        <div class="kp_right ys_btom">
            <div class="ys_top">
                <ul>
                    <li class="ys_acted">所有订单</a></li>
                    <li>代付款</li>
                    <li>代发货</li>
                    <li>待收货</li>
                    <li>已完成</li>
                    <li><img src="images/del_03.jpg"></li>
                    <li class="ys_searhc1"><input class="ys_input" type="text" placeholder="输入拍品名称 或 订单号 或 商家"></li>
                    <li class="ys_searhc">搜索</li>
                </ul>
            </div>
            <div class="ys_tip1">
                <span class="ys_span1">拍品</span><span class="ys_span2">没得价</span><span class="ys_span3">订单操作</span><span
                    class="ys_span3">订单状态</span>
            </div>
            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "> 2015-10-06 </span>
                        <span class="yc_pm1">[订单号] 132346456132123435</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_imgleft2"><span class="yc_ysname">信息印社  李萍《妙招自然》</span> <span class="yc_money">5000.00</span>
                            </p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5000.00</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000.00</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="yc_ddfk1">等待付款</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p"><a href="">等待买家付款</a></p>

                            <p class="yc_p"><a href="">订单详情</a></p>

                            <p class="yc_p1"><a href="">关闭交易</a></p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "> 2015-10-06 </span>
                        <span class="yc_pm1">[订单号] 132346456132123435</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_imgleft2"><span class="yc_ysname">信息印社  李萍《妙招自然》</span> <span class="yc_money">5000.00</span>
                            </p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5000.00</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000.00</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="yc_ddfk1">等待收货</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p"><a href="">卖家已发货</a></p>

                            <p class="yc_p"><a href="">订单详情</a></p>

                            <p class="yc_p1"><a href="">关闭交易</a></p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "> 2015-10-06 </span>
                        <span class="yc_pm1">[订单号] 132346456132123435</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_imgleft2"><span class="yc_ysname">信息印社  李萍《妙招自然》</span> <span class="yc_money">5000.00</span>
                            </p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5000.00</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000.00</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="yc_jycg">交易成功</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p"><a href="">买家已收货</a></p>

                            <p class="yc_p"><a href="">订单详情</a></p>

                            <p class="yc_p1"><a href="">交易结束</a></p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "> 2015-10-06 </span>
                        <span class="yc_pm1">[订单号] 132346456132123435</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_imgleft2"><span class="yc_ysname">信息印社  李萍《妙招自然》</span> <span class="yc_money">5000.00</span>
                            </p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5000.00</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000.00</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="yc_ddfk1">请发货</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p"><a href="">买家已付款</a></p>

                            <p class="yc_p"><a href="">订单详情</a></p>

                            <p class="yc_p1"><a href="">关闭交易</a></p>
                        </div>
                    </div>
                </div>
            </div>


            <div class="ys_tip2">
                <div class="ys_tip3">
                    <div class="ys_tip4">
                        <span><input type="checkbox" name="checkbox1" value="checkbox" class="ind_checkbox "> 2015-10-06 </span>
                        <span class="yc_pm1">[订单号] 132346456132123435</span>
                        <span class="yc_pm2">开源拍卖</span>
                        <span class="yc_pm3 lxmj"><a href="">联系卖家</a></span>
                        <span class="yc_pm4"><a href="">网站申诉</a></span>
                        <span class="yc_pm5"><a href="">删除</a></span>
                    </div>
                    <div class="ys_tip6">
                        <div class="yc_imgleft"><img src=""></div>
                        <div class="yc_imgleft1">
                            <p class="yc_imgleft2"><span class="yc_ysname">信息印社  李萍《妙招自然》</span> <span class="yc_money">5000.00</span>
                            </p>

                            <div class="yc_ysname1">
                                <p><span class="yc_ysname">佣金</span> <span class="yc_money">5000.00</span></p>

                                <p><span class="yc_ysname">实付</span> <span class="yc_money">5000.00</span></p>
                            </div>
                        </div>
                        <div class="yc_ddfk yc_imgleft2">
                            <div class="yc_jyjs">交易结束</div>
                        </div>
                        <div class="yc_ddright yc_imgleft2">
                            <p class="yc_p"><a href="">买家已退货</a></p>

                            <p class="yc_p"><a href="">订单详情</a></p>

                            <p class="yc_p1"><a href="">超时/已退货</a></p>
                        </div>
                    </div>
                </div>
            </div>


        </div>


    </div>
</div>