<div class="kp_timeon">
    <span class="bold">拍卖开始时间</span>
    <select class="kp_year layer-start-time-year" id="start-time-year">
        <option value="<?php echo date('Y') ?>"><?php echo date('Y'); ?></option>
        <option value="<?php echo date('Y', strtotime('+1 year')) ?>"><?php echo date('Y', strtotime('+1 year')) ?></option>
    </select>
    <span class="kp_ml8">年</span>
    <select class="kp_ml9 layer-start-time-month" id="start-time-month">
        <?php
        for($i = 1; $i <= 12; $i++){
            ?>
            <option <?php if(date('n') == $i) echo 'selected'; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
        <?php
        }
        ?>
    </select>
    <span class="kp_ml8">月</span>
    <select class="kp_ml9 layer-start-time-day" id="start-time-day" day="<?php echo date('j') ?>">

    </select>
    <span class="kp_ml8">日</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9 layer-start-time-hour" id="start-time-hour">
                            <?php for($i = 0; $i < 24; $i++){
                                ?>
                                <option <?php if(date('G') == $i) echo 'selected'; ?> value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
    <span class="kp_ml8">时</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9 layer-start-time-minute" id="start-time-minute">
                            <?php for($i = 0; $i <= 59; $i++){
                                $tmp = $i < 10 ? '0' . $i : $i;
                                ?>
                                <option <?php if(date('i') == $tmp) echo 'selected'; ?> value="<?php echo $tmp; ?>"><?php echo $tmp;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
    <span class="kp_ml8">分</span>
</div>

<div class="kp_timeon">
    <span class="bold">拍卖结束时间</span>
    <select class="kp_year layer-end-time-year" id="end-time-year">
        <option value="<?php echo date('Y') ?>"><?php echo date('Y'); ?></option>
        <option value="<?php echo date('Y', strtotime('+1 year')) ?>"><?php echo date('Y', strtotime('+1 year')) ?></option>
    </select>
    <span class="kp_ml8">年</span>
    <select class="kp_ml9 layer-end-time-month" id="end-time-month">
        <?php
        for($i = 1; $i <= 12; $i++){
            ?>
            <option <?php if(date('n') == $i) echo 'selected'; ?> value="<?php echo $i; ?>"><?php echo $i; ?></option>
        <?php
        }
        ?>
    </select>
    <span class="kp_ml8">月</span>
    <select class="kp_ml9 layer-end-time-day" id="end-time-day" day="<?php echo date('j') ?>">

    </select>
    <span class="kp_ml8">日</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9 layer-end-time-hour" id="end-time-hour">
                            <?php for($i = 0; $i < 24; $i++){
                                ?>
                                <option <?php if(date('G') == $i) echo 'selected'; ?> value="<?php echo $i; ?>"><?php echo $i;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
    <span class="kp_ml8">时</span>
                    <span class="kp_ml5">
                        <select class="kp_ml9 layer-end-time-minute" id="end-time-minute">
                            <?php for($i = 0; $i <= 59; $i++){
                                $tmp = $i < 10 ? '0' . $i : $i;
                                ?>
                                <option <?php if(date('i') == $tmp) echo 'selected'; ?> value="<?php echo $tmp; ?>"><?php echo $tmp;?></option>
                            <?php
                            } ?>
                        </select>
                    </span>
    <span class="kp_ml8">分</span>

</div>
<script>
$(function(){
    function refreshTimeDay(year, month, type){
        $.ajax({
            url : '/index/get-day',
            dataType : 'json',
            data : {
                year : year,
                month : month
            },
            type : 'post',
            success : function(data){
                if(data.flag > 0){
                    var options = '';

                    for(var i = 1; i<= data.data; i++){

                        options += '<option value="'+ i +'">' + i + '</option>';
                    }
                    if(type == 1){
                        $('.layer-start-time-day:visible').html(options);
                        <?php
                            if(!empty($productInfo['startTimeDay'])){
                        ?>
                                $('.layer-start-time-day:visible').val(<?php echo $productInfo['startTimeDay'] ?>);
                        <?php
                            }elseif(!empty($specialInfo['startTimeDay'])){
                        ?>
                                $('.layer-start-time-day:visible').val(<?php echo $specialInfo['startTimeDay'] ?>);
                        <?php
                            }else{
                        ?>
                                var day =
                                $('.layer-start-time-day:visible').val($('.layer-start-time-day:visible').attr('day'));
                        <?php
                            }
                        ?>
                    }else{
                        $('.layer-end-time-day:visible').html(options);
                        <?php
                            if(!empty($productInfo['endTimeDay'])){
                        ?>
                                $('.layer-end-time-day:visible').val(<?php echo $productInfo['endTimeDay'] ?>);
                        <?php
                            }elseif(!empty($specialInfo['endTimeDay'])){
                        ?>
                                $('.layer-end-time-day:visible').val(<?php echo $specialInfo['endTimeDay'] ?>);
                        <?php
                            }else{
                        ?>
                                $('.layer-end-time-day:visible').val($('.layer-end-time-day:visible').attr('day'));
                        <?php
                            }
                        ?>
                    }
                }
            }
        });
    }
    var startYear = $('.layer-start-time-year:visible').val();
    var startMonth = $('.layer-end-time-month:visible').val();
    var endYear = $('.layer-end-time-year:visible').val();
    var endMonth = $('.layer-end-time-month:visible').val();


    refreshTimeDay(startYear, startMonth, 1);
    refreshTimeDay(endYear, endMonth, 2);
    $('.layer-start-time-year:visible').on('change', function(){
        var year = $('.layer-start-time-year:visible').val();
        var month = $('.layer-start-time-month:visible').val();
        refreshTimeDay(year, month, 1);
    });
    $('.layer-start-time-month:visible').on('change', function(){
        var year = $('.layer-start-time-year:visible').val();
        var month = $('.layer-start-time-month:visible').val();
        refreshTimeDay(year, month, 1);
    });
    $('.layer-end-time-year:visible').on('change', function(){
        var year = $('.layer-end-time-year:visible').val();
        var month = $('.layer-end-time-month:visible').val();
        refreshTimeDay(year, month, 2);
    });
    $('.layer-end-time-month:visible').on('change', function(){
        var year = $('.layer-end-time-year:visible').val();
        var month = $('.layer-end-time-month:visible').val();
        refreshTimeDay(year, month, 2);
    });
});

</script>