<link rel="stylesheet" href="/dist/styles/main/space.css">

<div class="mySpace">
    <?php echo $this->render('banner'); ?>
    <div class="spacecont">
        <?php echo $this->render('top') ?>
        <div class="center ">
            <div class="permyimg">
                <div class="permyimg_left">
                    <img src="/dist/images/defaultPic.jpg">
                </div>
                <div class="permyimg_right">
                    <div class="pro_name">
                        <ul>
                            <li>姓名 <span class="pro_na"><?php echo $_zoneInfo['nickName'] ?></span></li>
                            <li>邮箱 <span class="pro_na"><?php echo $_zoneInfo['emailVisible'] ? $_zoneInfo['email'] : '不公开'; ?></span></li>
                            <li>手机 <span class="pro_na"><?php echo $_zoneInfo['mobileVisible'] ? $_zoneInfo['mobile'] : '不公开'; ?></span></li>
                            <li>微信 <span class="pro_na"><?php echo $_zoneInfo['wechatVisible'] ? $_zoneInfo['wechat'] : '不公开'; ?></span></li>
                            <li>QQ <span class="pro_na"><?php echo $_zoneInfo['qqVisible'] ? $_zoneInfo['qq'] : '不公开'; ?></span></li>
                            <!--<li class="pro_na1">认证 <span class="pro_na">已通过2</span></li>-->
                        </ul>
                    </div>
                    <div class="c"></div>
                    <div class="pro_zs">自述</div>
                    <div class="pro_zscont">
                        <?php
                            echo $_zoneInfo['selfDesc'];
                        ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>