<?php
    echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.config.js');
    echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.all.js?v=1');
    echo $this->inlineScript()->setFile('/admin/ueditor/lang/zh-cn/zh-cn.js');
?>
<link rel="stylesheet" href="/dist/styles/main/space.css">
<div class="mySpace">
    <?php echo $this->render('banner'); ?>
    <div class="spacecont">
        <?php echo $this->render('top') ?>
        <div class="center ">
            <div class="space_fbwz">发表文章</div>
            <div class="space_bioti">
                文章标题<input type="text" name="member-article-name" value="<?php if(!empty($info)) echo $info['memberArticleName'] ?>">
            </div>
            <div class="space_xuz">
                文章内容 <span class="space_xuzbtn">发布须知</span><span class="space_tixing">不得发布反动、暴恐、色情信息。</span></div>
            <div>
                <script id="qqq" name="memberArticleContent" type="text/plain" style="width:100%;height:300px;"><?php if(!empty($info)) echo $info['memberArticleContent']; ?></script>
            </div>
            <div class="space_btn">
                <span class="space_surebtn" id="confirm-btn">确认发表</span>
            </div>


        </div>


    </div>

</div>

<script>
    $(function(){
        /*$('#qqq').wysiwyg({
            controls:"bold,italic,|,undo,redo,image"
        });*/
        var qqq = UE.getEditor('qqq');

        $('#confirm-btn').on('click', function(){
            var data = {};
            data.memberArticleName = $('input[name=member-article-name]').val();
            data.memberArticleContent = qqq.getContent();
            data.zoneID = <?php echo $_zoneInfo['memberID']; ?>;
            <?php
             if(!empty($info)){
            ?>
            data.memberArticleID = <?php echo $info['memberArticleID']; ?>;
            <?php
             }
             ?>
            $.ajax({
                url:'/zone/add-article',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.href = '/zone/article-detail?zoneID='+data.zoneID+'&memberArticleID='+data['memberArticleID'];
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });
    })
</script>