<?php
    function recursiveComment($comment, $pidData, $deep = 0){
        if(empty($pidData[$comment['memberArticleCommentID']])) return false;
        $deep ++;
        foreach($pidData[$comment['memberArticleCommentID']] as $sv){
            global $count;
            global $extend;
            $count ++;
?>
            <div class="space_cominfo space_cominfoChildren <?php if($count > 5) echo 'hide hide-child-space'; ?>">
                <div class="space_cominfo_left">
                    <div><span class="space_cominfo_name"><?php echo $sv['nickName'] ?>&nbsp;回复&nbsp;<?php echo $comment['nickName'] ?></span><span class="font16"><?php echo $sv['instime'] ?></span>
                    </div>
                    <div class="space_cominfo_nr">
                        <?php echo $sv['commentContent'] ?>
                    </div>
                </div>
                <div class="space_cominfo_right space-comment-ctl">
                    <ul>
                        <li class="space_no"><a href="javascript:;" class="post-illegal-btn" coreID="<?php echo $sv['memberArticleCommentID'] ?>" type="2">举报</a></li>
                        <li class="space_no"><a href="javascript:;" class="reply-comment-btn" member-article-id="<?php echo $sv['memberArticleID'] ?>" comment-id="<?php echo $sv['memberArticleCommentID'] ?>">回复>></a></li>
                    </ul>
                </div>

            </div>
            <?php
                if($count >= 5 && !$extend){
                    $extend = 1;
            ?>
                    <div class="msg-icon msg-icon-up"><em>展示更多回复</em></div>
            <?php
                }
            ?>

<?php
            recursiveComment($sv, $pidData, $deep);
        }
    }
    foreach($comments as $v){
?>
        <div class="space_cominfo">
            <div class="space_cominfo_left">
                <div><span class="space_cominfo_name"><?php echo $v['nickName'] ?></span><span class="font16"><?php echo $v['instime'] ?></span>
                </div>
                <div class="space_cominfo_nr">
                    <?php echo $v['commentContent'] ?>
                </div>
            </div>
            <div class="space_cominfo_right space-comment-ctl">
                <ul>
                    <li class="space_no"><a href="javascript:;" class="post-illegal-btn" coreID="<?php echo $v['memberArticleCommentID'] ?>" type="2">举报</a></li>
                    <li class="space_no"><a href="javascript:;" class="reply-comment-btn" member-article-id="<?php echo $v['memberArticleID'] ?>" comment-id="<?php echo $v['memberArticleCommentID'] ?>">回复>></a></li>
                </ul>
            </div>
        </div>

<?php
        $count = 0;
        $extend = 0;
        recursiveComment($v, $pidData, 0, $count);
?>

<?php
    }
?>
<div class="hide" id="reply-commend-div">
    <div class="childrenTextBoxBig space-comment-reply">
        <div class="clear"></div>
        <div class="childrenTextBox">
            <textarea name="commentContent"></textarea>
            <div class="childrenTextBoxBot">
                <div class="childrenBtn reply-comment-div-btn" pid="" member-article-id="">回复</div>
            </div>
        </div>
    </div>
</div>
<?php //echo $this->render('reply-comment'); ?>
<script>
    $(function(){
        $('.reply-comment-btn').on('click', function(){
            /*layer.open({
                skin : 'loginBox',
                title : '回复评论',
                type : 1,
                content : $('#reply-comment-div').html()
            });*/
            $('.space-comment-ctl').siblings('.space-comment-reply').remove();
            $(this).parents('.space-comment-ctl').after($('#reply-commend-div').html());
            console.log($(this).parents('.space-comment-ctl'));
            $('.reply-comment-div-btn:visible').attr('pid', $(this).attr('comment-id'));
            $('.reply-comment-div-btn:visible').attr('member-article-id', $(this).attr('member-article-id'));
        });

        $(document).on('click', '.reply-comment-div-btn:visible', function(){
            var data = {
                commentContent : $('textarea[name=commentContent]:visible').val(),
                zoneID : <?php echo $_zoneInfo['memberID'] ?>,
                pid : $(this).attr('pid'),
                memberArticleID : $(this).attr('member-article-id')
            };
            $.ajax({
                url : '/zone/add-comment',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            if(data.pid){
                                location.reload();
                            }else{
                                layer.closeAll();
                            }

                        });
                    }else if(res.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $(document).on('click', '.msg-icon', function(){
            if($(this).hasClass('msg-icon-up')){
                $(this).siblings('.hide-child-space').removeClass('hide');
                $(this).removeClass('msg-icon-up');
            }else{
                $(this).siblings('.hide-child-space').addClass('hide');
                $(this).addClass('msg-icon-up');
            }
        });
    })
</script>