<link rel="stylesheet" href="/dist/styles/main/space.css">

<div class="mySpace">
    <?php echo $this->render('banner'); ?>
    <div class="spacecont">
        <?php echo $this->render('top') ?>
        <div class="center ">
            <div class="space_wz">
                <?php foreach($articles as $v){
                ?>
                    <div class="space_li">
                        <div class="space_title">
                            <div class="space_title_left"><span class="font30"><?php echo $v['memberArticleName'] ?></span><span class="font16"><?php echo $v['instime'] ?></span></div>
                            <?php if($_isMyZone){ ?>
                                <div class="space_title_right">
                                    <ul>
                                        <li class="join-award-article" member-article-id="<?php echo $v['memberArticleID']; ?>" style="cursor: pointer">报名【有奖征文】</li>
                                        <li><a href="/zone/article-detail?zoneID=<?php echo $_zoneInfo['memberID'] ?>&memberArticleID=<?php echo $v['memberArticleID'] ?>">编辑</a></li>
                                        <li class="space_title_del"><a href="javascript:;" class="member-article-del-btn" member-article-id="<?php echo $v['memberArticleID'] ?>">删除</a></li>
                                        <!--<li class="space_no"><a href="javascript:;" class="post-illegal-btn" coreID="<?php /*echo $v['memberArticleID'] */?>" type="1">举报</a></li>-->
                                        <!--<li class="space_no"><a href="">回复>></a></li>-->
                                    </ul>
                                </div>
                            <?php } ?>
                        </div>
                        <div class="c"></div>
                        <div class="space_conts">
                            <?php echo $v['memberArticleContent'] ?><?php if(empty($v['fullContent'])) echo '...'; ?>
                            <?php
                            if(!empty($v['imgs'])){
                                ?>

                                <div class="space_imgsc">
                                    <ul>
                                        <?php
                                        $i = 0;
                                        foreach($v['imgs'] as $sv){
                                            $i++;
                                            if($i == 4) break;
                                            ?>
                                            <li><img src="<?php echo $sv?>"></li>
                                        <?php
                                        }
                                        ?>
                                    </ul>
                                </div>
                            <?php
                            }
                            ?>
                            <div class="space_zzai">
                                <ul>
                                    <li>阅读(<?php echo $v['readCount']; ?>)</li>
                                    <li>评论(<?php echo $v['commentCount'] ?>)</li>
                                    <!--<li class="space_zzai_del"><a href="javascript:;" class="mark-member-article" member-article-id="<?php /*echo $v['memberArticleID'] */?>">收藏(<?php /*echo $v['markCount'] */?>)</a></li>
                                    <li class="space_zzai_del space_scxm favorite-member-article" member-article-id="<?php /*echo $v['memberArticleID'] */?>">(<?php /*echo $v['favoriteCount'] */?>)</li>-->

                                    <li class="space_zzai_del">收藏(<?php echo $v['markCount'] ?>)</li>
                                    <li class="space_zzai_del space_scxm">(<?php echo $v['favoriteCount'] ?>)</li>
                                </ul>
                                <div class="space_lookall"><a href="/zone/article-detail?zoneID=<?php echo $_zoneInfo['memberID'] ?>&memberArticleID=<?php echo $v['memberArticleID'] ?>" target="_blank">查看全文>></a></div>
                            </div>
                        </div>
                    </div>
                <?php
                } ?>
            </div>
            <?php echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/zone/index?zoneID=' . $_zoneInfo['memberID'])); ?>
        </div>


    </div>

</div>
<script>
    $('.member-article-hide-btn').on('click', function(){
        var data = {};
        data.memberArticleID = $(this).attr('member-article-id');
        data.zoneID = <?php echo $_zoneInfo['memberID'] ?>;
        data.isHide = $(this).attr('data');
        $.ajax({
            url : '/zone/add-article',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                if(res.flag > 0){
                    layer.alert(res.msg, function(){
                        location.reload();
                    });
                }else{
                    layer.alert(res.msg);
                }
            }
        });
    });

    $('.member-article-del-btn').on('click', function(){
        var data = {};
        data.memberArticleID = $(this).attr('member-article-id');
        data.zoneID = <?php echo $_zoneInfo['memberID'] ?>;
        data.isDel = 1;
        layer.confirm('确认删除吗？', {
            btn: ['确认','取消'] //按钮
        }, function(){
            $.ajax({
                url : '/zone/add-article',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        }, function(){
            layer.closeAll();
        });

    });

    $('.join-award-article').on('click', function(){
        var data = {};
        data.memberArticleID = $(this).attr('member-article-id');
        data.zoneID = <?php echo $_zoneInfo['memberID'] ?>;
        $.ajax({
            url : '/zone/join-award-article',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                layer.alert(res.msg);
            }
        });
    });
</script>