<link rel="stylesheet" href="/dist/styles/main/space.css">

<div class="mySpace">
    <?php echo $this->render('banner'); ?>
    <div class="spacecont">
        <?php echo $this->render('top') ?>
        <div class="center ">
            <div class="space_wz3">
                <?php foreach($articles as $v){
                ?>
                    <div class="space_cominfo">
                        <div class="space_cominfo_left" style="cursor: pointer;" onclick="location.href='/zone/article-detail?zoneID=<?php echo $_zoneInfo['memberID'] ?>&memberArticleID=<?php echo $v['memberArticleID'] ?>';">
                            <div><span class="space_cominfo_name"><?php echo $v['memberArticleName'] ?></span><span class="font16"><?php echo $v['instime'] ?></span>
                            </div>
                            <div class="space_cominfo_nr">
                                <?php echo $v['memberArticleContent'] ?>
                            </div>
                            <?php
                            if(!empty($v['imgs'])){
                            ?>

                                <div class="space_imgsc">
                                    <ul>
                            <?php
                                $i = 0;
                                foreach($v['imgs'] as $sv){
                                    $i++;
                                    if($i == 4) break;
                                    ?>
                                        <li><img src="<?php echo $sv?>"></li>
                                <?php
                                }
                            ?>
                                    </ul>
                                </div>
                            <?php
                            }
                            ?>
                        </div>
                        <?php if($_isMyZone){ ?>
                        <div class="space_cominfo_right">
                            <ul>
                                <li><a href="javascript:;" class="member-article-hide-btn" data="<?php echo $v['isHide'] ? 0 : 1 ?>" member-article-id="<?php echo $v['memberArticleID'] ?>"><?php echo $v['isHide'] ? '显示' : '隐藏' ?></a></li>
                                <li><a href="/zone/article-detail?zoneID=<?php echo $_zoneInfo['memberID'] ?>&memberArticleID=<?php echo $v['memberArticleID'] ?>">编辑</a></li>
                                <li class="space_no"><a href="javascript:;" class="member-article-del-btn" member-article-id="<?php echo $v['memberArticleID'] ?>">删除</a></li>
                                <!--<li class="space_no"><a href="javascript:;" class="post-illegal-btn" coreID="<?php /*echo $v['memberArticleID'] */?>" type="1">举报</a></li>-->
                                <!--<li class="space_no"><a href="">回复>></a></li>-->
                            </ul>
                        </div>
                        <?php } ?>
                    </div>
                <?php
                } ?>
            </div>
            <?php echo $this->render('/front/common/paginate', array('pages' => $pages, 'url' => '/zone/index?zoneID=' . $_zoneInfo['memberID'])); ?>
        </div>


    </div>

</div>
<script>
    $('.member-article-hide-btn').on('click', function(){
        var data = {};
        data.memberArticleID = $(this).attr('member-article-id');
        data.zoneID = <?php echo $_zoneInfo['memberID'] ?>;
        data.isHide = $(this).attr('data');
        $.ajax({
            url : '/zone/add-article',
            dataType : 'json',
            type : 'post',
            data : data,
            success : function(res){
                if(res.flag > 0){
                    layer.alert(res.msg, function(){
                        location.reload();
                    });
                }else{
                    layer.alert(res.msg);
                }
            }
        });
    });

    $('.member-article-del-btn').on('click', function(){
        var data = {};
        data.memberArticleID = $(this).attr('member-article-id');
        data.zoneID = <?php echo $_zoneInfo['memberID'] ?>;
        data.isDel = 1;
        layer.confirm('确认删除吗？', {
            btn: ['确认','取消'] //按钮
        }, function(){
            $.ajax({
                url : '/zone/add-article',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            location.reload();
                        });
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        }, function(){
            layer.closeAll();
        });

    });
</script>