<link rel="stylesheet" href="/dist/styles/main/space.css" xmlns="http://www.w3.org/1999/html">
<div class="mySpace">
    <?php echo $this->render('banner'); ?>
  <div class="spacecont">
      <?php echo $this->render('top') ?>
    <div class="center clearfix">
      <div class="msgAddBox clearfix">
        <div class="msgAddTit">
          <span>
            我要对 <em><?php echo $_zoneInfo['nickName'] ?>的空间</em>
            留言
          </span>
        </div>
        <form id="msg_form">
        <div class="msgAddCon">
          <textarea name="content"></textarea>
            <input name="zoneID" value="<?php echo $_zoneInfo['memberID'] ?>" type="hidden">
        </div>
        <div class="msgAddBot">
          <div class="msgAddIcon" id="msgAddIcon">图片</div>
          <div class="msgAddSend">发送</div>
          <div class="clear"></div>

        </div>
        <div id="imgs"></div>
        <div class="msgAddImg " id="msgAddImg">
          <div class="msgAddImg-top"></div>
          <div class="msgAddImgUl">
            <ul >
              <li>
                <input  accept="image/*" class="uploadFile1" name="uploadFile1" type="file"/>
              </li>
              <li>
                <input  accept="image/*" class="uploadFile2" name="uploadFile1" type="file"/>
              </li>
              <li>
                <input  accept="image/*" class="uploadFile3" name="uploadFile1" type="file"/>
              </li>

            </ul>
            <p>最多可添加3张照片</p>
          </div>
        </div>
          </form>
      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  
  function uploadFileAjax(inputEle,imgName, sucFun, flag) {
                inputEle.change(function() {
                    var that = this;
                    console.log("uploadFileAjax");
                    var J_uploadPar = $(that).parent();
                    
                    lrz(that.files[0], {
                            quality: 1
                        })
                        .then(function(rst) {                            
                            if (!flag) {
                                var img = new Image();
                                img.src = rst.base64;   
                                J_uploadPar.find('.icon-del').remove();                             
                                J_uploadPar.find('img').remove();
                                J_uploadPar.append(img);
                                 var html="<div class='icon-del'></div>";
                                J_uploadPar.append(html);
                            }
                            sucFun('data.data');
		                    inputEle.val('');
                            $.ajax({
                                url: "/index/file-upload", // 这个地址做了跨域处理，可以用于实际调试
                                data: rst.formData,
                                processData: false,
                                contentType: false,
                                type: 'POST',
                                success: function(data) {
                                    if (data.flag == 1) {
                                        $("#"+imgName).remove();
                                        html = '<input name="img[]" id="'+imgName+'" value="'+data.data.picPath+'" type="hidden">';

                                        $(html).appendTo("#imgs");

                                    } else {
                                        alert('图片上传失败，请联系管理员！');
                                    }



                                }
                            });

                            return rst;
                        });


                });
                //end
 };

uploadFileAjax($('.uploadFile1'),'uploadFile1',function(data){
   
}); 
uploadFileAjax($('.uploadFile2'),'uploadFile2',function(data){
   
});
uploadFileAjax($('.uploadFile3'),'uploadFile3',function(data){
   
});
$(function(){
   var J_msgAddImg=$("#msgAddImg");
  $('#msgAddIcon').on('click', function(event) {
    event.preventDefault();
    if(J_msgAddImg.is(":hidden")){
       J_msgAddImg.show();
      console.log("hide");
    }else{
        J_msgAddImg.hide();
    }
  });
  //删除
$('.msgAddImgUl').on('click', '.icon-del', function(event) {
  event.preventDefault();
  var J_parent=$(this).parent();
  J_parent.find('.icon-del,img').remove();
    var class_name = J_parent.find('input').attr('class');
    $('#'+class_name).remove();
});
  
  
});



  $(".msgAddSend").on("click", function () {
      var msg_add_url= "/zone/add-Message";
      $.ajax({
          type: "post",
          dataType: "json",
          url: msg_add_url,
          data: $('#msg_form').serialize(),
          success: function ($data) {
                  layer.alert($data.msg, function(){
                      if($data.flag == 1){
                          location.reload();
                      }else{
                          layer.closeAll();
                      }

                  });
          },
      });
  });

</script>
</body>
</html>