<div class="center space_bti">
    <div class="space_bti">
        <ul>
            <li><a href="/zone/index?zoneID=<?php echo $_zoneInfo['memberID'] ?>">首页</a></li>

            <li><a href="/zone/article-list?zoneID=<?php echo $_zoneInfo['memberID'] ?>">文章列表</a></li>

            <?php
            if($_isMyZone){
                ?>
                <li><a href="/zone/add-article?zoneID=<?php echo $_zoneInfo['memberID'] ?>">发表文章</a></li>
            <?php
            }
            ?>

            <li><a href="/zone/about?zoneID=<?php echo $_zoneInfo['memberID'] ?>">关于我</a></li>
            <?php
            if(!$_isMyZone){
            ?>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
                <li>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</li>
            <?php
            }
            ?>

            <li class="space_img">
                <img src="<?php echo $_zoneInfo['avatar'] ?>">
                <?php
                if(!empty($_zoneInfo['storeID'])){
                    ?>
                    <div class="space_dp" style="cursor:pointer;" onclick="location.href='/store/detail?storeID=<?php echo $_zoneInfo['storeID']; ?>';">我有店铺</div>
                <?php
                }
                ?>

            </li>
            <li class="space_gz"><a href="javascript:;">关注(<span class="ff7519"><?php echo $_zoneInfo['interestedCount'] ?></span>)</a></li>
            <?php if($_isMyZone){
                ?>
                <li><a href="/zone/mark?zoneID=<?php echo $_zoneInfo['memberID'] ?>">收藏文章</a></li>
                <li><a href="/zone/interested-zones?zoneID=<?php echo $_zoneInfo['memberID'] ?>">关注的空间</a></li>
                <li><a href="/zone/message?zoneID=<?php echo $_zoneInfo['memberID'] ?>">留言板(<span class="ff7519"><?php echo $_zoneInfo['messageCount'] ?></span>)</a></li>
            <?php
            }else{
                ?>
                <li><a href="javascript:;" class="add-interest-zone-btn" zone-id="<?php echo $_zoneInfo['memberID'] ?>">关注空间</a></li>
                <li><a href="javascript:;" class="add-message-btn">我要留言</a></li>
            <?php
            } ?>

        </ul>
    </div>
</div>
<?php echo $this->render('add-message'); ?>
<?php echo $this->render('/front/common/login'); ?>
<script>
    $(function(){
        $('.add-interest-zone-btn').on('click', function(){

            var data = {};
            data.zoneID = $(this).attr('zone-id');
            $.ajax({
                url : '/member/add-interest-zone',
                type : 'post',
                dataType : 'json',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        layer.alert(response.msg);
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }
            });
        });

        $('.add-message-btn').on('click', function(){
            layer.open({
                skin : 'loginBox',
                title : '留言',
                type : 1,
                content : $('#add-message-div').html()
            });
        });

        $(document).on('click', '.add-message-div-btn:visible', function(){
            var data = {
                content : $('input[name=msg-content]:visible').val(),
                zoneID : <?php echo $_zoneInfo['memberID'] ?>
            };
            var messageID = $(this).attr('message-id');
            if(messageID){
                data.pid = messageID;
            }
            $.ajax({
                url : '/zone/add-message',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(res){
                    if(res.flag > 0){
                        layer.alert(res.msg, function(){
                            if(data.pid){
                                location.reload();
                            }else{
                                layer.closeAll();
                            }

                        });
                    }else if(res.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(res.msg);
                    }
                }
            });
        });

        $('.reply-member-message-btn').on('click', function(){
            layer.open({
                skin : 'loginBox',
                title : '回复留言',
                type : 1,
                content : $('#add-message-div').html()
            });
            $('.add-message-div-btn:visible').attr('message-id', $(this).attr('message-id'));
        });
    })
</script>