<div class="wrapper">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <a class="text-right" style="float:right;" href="<?php echo '/admin/' . $this->layout()->controllerName . '/index' ?>">返回</a>
            </h3>
        </div>
        <div class="panel-body">
            <div class="container mtop40" style="margin-bottom: 50px; height: auto;">
                <form class="form-horizontal" action="/admin/<?php echo $this->layout()->controllerName; ?>/update" method="post">
                    <div class="form-group">
                        <label class="col-sm-2 control-label">等级名称</label>

                        <div class="col-sm-4">
                            <input class="form-control" name="levelName" value="<?php echo !empty($info['levelName']) ? $info['levelName'] : ''; ?>">
                        </div>
                    </div>


                    <div class="form-group">
                        <label class="col-sm-2 control-label">佣金</label>

                        <div class="col-sm-4">
                            <input type="text" class="" name="fees" value="<?php echo !empty($info['fees']) ? $info['fees'] : ''; ?>" >
                        </div>
                    </div>
                    <input type="hidden" name="level" value="<?php if(!empty($info['level'])) echo $info['level']; ?>"/>
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <a class="btn btn-primary editModal" onclick="">确定</a>
                        </div>
                    </div>
                </form>

                <input type="hidden" name="location-url" value="/admin/<?php echo $this->layout()->controllerName; ?>/index"/>
            </div>
        </div>
    </div>
</div>