
<div class="wrapper" id="page-wrapper">

    <div class="adv-table">
        <table id="table-pagination" class="bootstrap_table"></table>
    </div>
    <!-- Edit Modal Start -->
    <!--<div class="row">
        <div class="modal form-modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                        <h4 class="modal-title" id="edit_modal_label">排序设置</h4>
                    </div>
                    <div class="modal-body">
                        <form class="form-horizontal" id="editForm" role="form" method="post" action="/admin/<?/*=$this->layout()->controllerName;*/?>/sort-product">
                            <table class="table table-bordered">
                                <tr>
                                    <td>
                                        <div class="form-group">
                                            <label for="desc" class="col-sm-2 col-md-2 control-label">商品名称</label>
                                            <div class="col-sm-10 col-md-10">
                                                <input type="text" class="form-control" id="product-name" disabled="true" name="productName" value="">
                                            </div>
                                        </div>
                                    </td>
                                </tr>

                                <tr>
                                    <td>
                                        <div class="form-group">
                                            <label for="desc" class="col-sm-2 col-md-2 control-label">产品排序</label>
                                            <div class="col-sm-10 col-md-10">
                                                <input type="text" class="form-control" id="sort" name="sort" value="">
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            </table>
                            <input type="hidden"  name="productID" id="product-id" value="" />
                        </form>
                    </div>
                    <div class="modal-footer">
                        <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                        <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                    </div>
                </div>
            </div>
        </div>
    </div>-->
    <!-- Edit Modal End -->
</div>

<script type="text/javascript">
    /*$('#edit_modal').on("show.bs.modal",function(e){
        var btn = $(e.relatedTarget);
        var id = btn.attr('rid');
        $.get("/admin/product/get/"+id,function(data){
            $("#product-name").val(data.productName);
            $("#sort").val(data.sort);
            $("#product-id").val(data.productID);

        },"json");
    });*/
    $(function(){

        table = $('#table-pagination').bootstrapTable({
            method: 'get',
            url: '/admin/<?=$this->layout()->controllerName;?>/list',
            cache: false,
            height: "auto",
            striped: true,
            pagination: true,
            pageSize: 10,
            pageList: [10, 25, 50, 100, 200],
            search: false,
            showColumns: false,
            showRefresh: false,
            toolbar:"#table_toolbar",
            minimumCountColumns: 2,
            sidePagination: 'server',
            clickToSelect: true,
            columns: [{
                field: 'level',
                title: '等级ID',
                align: 'center',
                valign: 'middle'
            }, {
                field: 'levelName',
                title: '等级名称',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },{
                field: 'fees',
                title: '佣金比例',
                align: 'center',
                valign: 'middle',
                width: '200px'
            },
            {
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter
            }]
        });
    });
    function operateFormatter(value, row, index) {
        return [
            "<a title='编辑' href=\"/admin/<?php echo $this->layout()->controllerName;?>/add-view?level="+row.level+"\" ><i class=\"glyphicon glyphicon-edit\"></i></a>",
        ].join('');
    }
</script>