<link rel="stylesheet" href="/jin/style/common.css" media="screen" type="text/css" />
<link rel="stylesheet" href="/jin/style/css.css" media="screen" type="text/css" />
<div class="kp_main">
    <div class="center ">
        <div class="ty_main01">特约名家 > 定制详情</div>
        <div class="ty_main02">
            <div class="ty_left">
                <img src="<?php echo $info['listImg'] ?>">
            </div>
            <div class="ty_center">
                <div>
                    <?php if(time() < $info['endTime']){?>
                        <span class="ty_new">正在进行</span>
                        <span>距结束</span>
                    <?php } ?>
                        <span class="yomibox2" data="<?php echo date('Y/m/d H:i:s', $info['endTime']); ?>"></span>

                </div>
                <p class="ty_title"><?php echo $info['title'] ?></p>

                <div class="ty_price">
                    <span class="ty_price1">当前价  <span class="ty_col1">￥</span><span
                            class="ty_price2"><?php echo $info['price'] ?></span></span>
                    <span>[<span class="ty_col1"><?php echo $info['boughtCount'] ?></span>次成交]</span>
                </div>
                <div class="ty_price">
                    <span class="ty_price1">订金： ￥<?php echo $info['depositPrice'] ?></span>
                    <span>剩余数量：<?php echo $info['lastNum'] ?></span>
                </div>
                <div class="ty_cont">
                    订制商品属性特殊，不以个人喜好等原因退换。可自定内容请于订单备注中说明，或联系客服。作品交付根据作者创作时间不定，介意慎拍。
                </div>
                <div class="ty_hek">
                    <div class="ty_hekl">
                        <a href="tencent://message/?uin=<?php echo $_siteSettings['qq'] ?>&Site=www.kaipai123.com&Menu=yes"><div class="ty_lxkf">联系客服</div></a>
                        <div class="ty_lxkf1">
                            <span class="ty_lxkf2"><a href="tencent://message/?uin=<?php echo $_siteSettings['qq'] ?>&Site=www.kaipai123.com&Menu=yes">关注</a></span><span class="ty_num1">选择数量</span>
                            <span class="ty_aa">件</span>

                            <div class="ty_addnum">
                                <input type="text" value="1" id="customization-count">
                                <button id="add-customization-count">+</button>
                            </div>

                        </div>


                    </div>
                    <div class="ty_hekr" style="cursor: pointer;" id="buy-customization-btn">订制</div>
                </div>
            </div>
            <div class="ty_right">
                <div class="ty_cjjl"> 成交记录</div>
                <div style="height:auto">
                    <table>
                        <tr class="ty_tabletr">
                            <td width="30%">订制买家</td>
                            <td width="30%">出价</td>
                            <td width="40%">出价时间</td>
                        </tr>
                        <?php
                            foreach($orders as $v){
                        ?>
                                <tr class="ty_tabletd">
                                    <td><?php echo $v['nickName'] ?></td>
                                    <td><?php echo $v['payMoney']; ?></td>
                                    <td><?php echo date('m-d H:i', strtotime($v['instime'])) ?></td>
                                </tr>
                        <?php
                            }
                        ?>
                    </table>
                </div>
            </div>
        </div>
        <div class="ty_main03">
            <ul>
                <li class="ty_act" style="cursor: pointer;">名家介绍</li>
                <li style="cursor: pointer;">成交记录（<?php echo $info['boughtCount']; ?>）</li>
                <li style="cursor: pointer;">服务保障</li>
                <li style="cursor: pointer;">保证金须知</li>
            </ul>
        </div>
        <div id="ty_main03-detail">
            <div>
                <div class="ty_main04">
                    <ul>
                        <li class="ty_01">竞拍流程</li>
                        <li>交保证金</li>
                        <li class="ty_03"><img src="/jin/images/s_07.jpg"></li>
                        <li>出价竞拍</li>
                        <li class="ty_03"><img src="/jin/images/s_07.jpg"></li>
                        <li>竞拍成功</li>
                        <li class="ty_03"><img src="/jin/images/s_07.jpg"></li>
                        <li>攥刻请自备印石邮至我司</li>
                        <li class="ty_03"><img src="/jin/images/s_07.jpg"></li>
                        <li>等待作者创作</li>
                        <li class="ty_03"><img src="/jin/images/s_09.jpg"></li>
                        <li>完成收货</li>
                    </ul>
                </div>
                <div class="ty_main05">
                    <div class="ty_zzleft"><img src="<?php echo $info['artistAvatar'] ?>"></div>
                    <div class="ty_zzcenter">
                        <ul>
                            <li><span class="ty_aut"><?php echo $artistInfo['artistName'] ?></span><span class="ty_aut1">[<?php echo $artistInfo['shortDesc'] ?>]</span></li>
                            <li>
                                <a href="#ge-ren-jian-li"><span class="ty_grjl">个人简历</span></a><a href="#huo-jiang"><span class="ty_grjl">获奖及著作</span></a><a href="#xin-shang"><span class="ty_grjl">作品欣赏</span></a>
                            </li>
                        </ul>
                    </div>
                    <div class="ty_zzright"><img src="/jin/images/tp_03.jpg"></div>

                </div>
                <div class="ty_main06" id="ge-ren-jian-li">
                    <p class="ty_hjiang">个人简历</p>

                    <p class="ty_jianjie1">
                        <iframe src="/artist/artist-detail?artistID=<?php echo $artistInfo['artistID'] ?>" frameborder="0" width="100%"></iframe>
                    </p>

                    <div class="ty_jianjie2"></div>

                </div>
                <!--<div class="ty_main07">
                    <img src="/jin/images/tp_09.jpg">
                </div>-->
                <div class="ty_main08" id="huo-jiang">
                    <p class="ty_hjiang">获奖及著作</p>
                    <iframe src="/artist/artist-awards?artistID=<?php echo $artistInfo['artistID'] ?>" frameborder="0" width="100%"></iframe>
                </div>
                <div class="ty_main09" id="xin-shang">
                    作品欣赏
                </div>
                <div class="ty_main10">
                    <iframe src="/artist/artist-productions?artistID=<?php echo $artistInfo['artistID'] ?>" frameborder="0" width="100%"></iframe>
                </div>


            </div>
            <div class="hide">

            </div>
            <div class="hide">

                <p>
                    <span>售后服务</span>
                    <br>
                    1. 如果有藏品发错货物等问题，请在48小时内提供照片，我们会及时更换
                    <br>
                    2. 收到藏品有任何问题请联系在线客服，我们竭力做到让您满意；
                    <br>
                    3. 客服热线：400 878 2221
                    <br></p>
            </div>
            <div class="hide">


            </div>
        </div>
    </div>
</div>

<?php echo $this->render('/front/common/pay'); ?>

<script>
    $(function(){
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'customization-detail')
        });
        $('#add-customization-count').on('click', function(){
            $('#customization-count').val(parseInt($('#customization-count').val()) + 1);
        });
        $('#buy-customization-btn').on('click', function(){
            var depositPrice = <?php echo $info['depositPrice']; ?>;
            var customizationCount = parseInt($('#customization-count').val());
            var payPrice = depositPrice * customizationCount;

            layer.open({
                skin: '',
                title:'',
                type: 1,
                content: $('#pay-div').html()
            });
            $('.pay-price:visible').html(payPrice);
            $('.pay-price:visible').attr('pay-customization-id', <?php echo $info['customizationID'] ?>);
            $('.pay-price:visible').attr('customization-count', customizationCount);
        });

        $(document).on('click', '.confirm-pay:visible', function(){
            var data = {};
            data.customizationID = $('.pay-price:visible').attr('pay-customization-id');
            data.customizationCount = $('.pay-price:visible').attr('customization-count');
            data.payType = $('.selected-pay-type:visible').attr('pay-type');

            $.ajax({
                url : '/order/generate',
                dataType : 'json',
                type : 'post',
                data : data,
                success : function(response){
                    if(response.flag > 0){
                        location.href = '/member/order-detail?orderID=' + response.data['orderID'];
                    }else if(response.flag == -102){
                        loginPOP();
                    }else{
                        layer.alert(response.msg);
                    }
                }

            });
        });

        //产品详情介绍的tab
        $('.ty_main03').delegate('li', 'click', function () {
            $(this).addClass('ty_act').siblings().removeClass('ty_act');
            var J_index = $(this).index();
            var J_detailed_xx_down = $('#ty_main03-detail > div');
            J_detailed_xx_down.hide();
            J_detailed_xx_down.eq(J_index).show();
        });
    })

</script>