<?php
    echo $this->headLink()->appendStylesheet('/jin/style/common.css')->appendStylesheet('/jin/style/css.css');
?>
<div class="Fixyue">
    <div class="Fixclose"><a href=""><img src="images/clo_03.jpg"></a></div>
    <div class="Fixyue3">付款金额 <span class="Fixyue3num">1000000</span></div>
    <div class="Fixyue1">
        <ul>
            <li class=""><img src="images/zf_03.png"> 余额支付</li>
            <li class=""><img src="images/zf_06.png"> 支付宝</li>
            <li class="fix_mor"><img src="images/zf_12.png"> 微信钱包</li>
            <li class=""><img src="images/zf_14.png"> 网银支付</li>
            <li class=""><img src="images/zf_20.png"> 银行汇款</li>
        </ul>
    </div>
    <div class="Fixyue2">确认支付</div>
</div>

<div class="kp_main">
    <div class="center ">
        <div class="ty_main01">特约名家 > 定制详情</div>
        <div class="ty_main02">
            <div class="ty_left">
                <img src="">
            </div>
            <div class="ty_center">
                <div><span class="ty_new">正在进行</span><span>距结束 <span class="ty_col">5</span>天<span
                            class="ty_col">08</span>时<span class="ty_col">30</span>分<span
                            class="ty_col">20</span>秒</span></div>
                <p class="ty_title"><?php echo $customizationInfo['title'] ?></p>

                <div class="ty_price">
                    <span class="ty_price1">当前价  <span class="ty_col1">￥</span><span
                            class="ty_price2"><?php echo $customizationInfo['price'] ?></span></span>
                    <span>[<span class="ty_col1"><?php echo $customizationInfo['boughtCount'] ?></span>次成交]</span>
                </div>
                <div class="ty_price">
                    <span class="ty_price1">订金： ￥1.000</span>
                    <span>剩余数量：<?php echo $customizationInfo['lastNum'] ?></span>
                </div>
                <div class="ty_cont">
                    订制商品属性特殊，不以个人喜好等原因退换。可自定内容请于订单备注中说明，或联系客服。作品交付根据作者创作时间不定，介意慎拍。
                </div>
                <div class="ty_hek">
                    <div class="ty_hekl">
                        <div class="ty_lxkf">联系客服</div>
                        <div class="ty_lxkf1">
                            <span class="ty_lxkf2"><a href="">关注</a></span><span class="ty_num1">选择数量</span>
                            <span class="ty_aa">件</span>

                            <div class="ty_addnum"><input type="text">
                                <button>+</button>
                            </div>

                        </div>


                    </div>
                    <div class="ty_hekr">订制</div>
                </div>
            </div>
            <div class="ty_right">
                <div class="ty_cjjl"> 成交记录</div>
                <div style="height:auto">
                    <table>
                        <tr class="ty_tabletr">
                            <td width="30%">订制买家</td>
                            <td width="30%">出价</td>
                            <td width="40%">出价时间</td>
                        </tr>
                        <?php
                            foreach($orders as $v){
                        ?>
                                <tr class="ty_tabletd">
                                    <td><?php echo $v['nickName'] ?></td>
                                    <td><?php echo $v['payMoney']; ?></td>
                                    <td><?php echo date('m-d H:i', strtotime($v['instime'])) ?></td>
                                </tr>
                        <?php
                            }
                        ?>
                    </table>
                </div>
            </div>
        </div>
        <div class="ty_main03">
            <ul>
                <a href="">
                    <li class="ty_act">名家介绍</li>
                </a>
                <a href="">
                    <li>出价记录（<?php echo $customization['boughtCount']; ?>）</li>
                </a>
                <a href="">
                    <li>服务保障</li>
                </a>
                <a href="">
                    <li>保证金须知</li>
                </a>
            </ul>
        </div>
        <div class="ty_main04">
            <ul>
                <li class="ty_01">竞拍流程</li>
                <li>交保证金</li>
                <li class="ty_03"><img src="images/s_07.jpg"></li>
                <li>出价竞拍</li>
                <li class="ty_03"><img src="images/s_07.jpg"></li>
                <li>竞拍成功</li>
                <li class="ty_03"><img src="images/s_07.jpg"></li>
                <li>攥刻请自备印石邮至我司</li>
                <li class="ty_03"><img src="images/s_07.jpg"></li>
                <li>等待作者创作</li>
                <li class="ty_03"><img src="images/s_09.jpg"></li>
                <li>完成收货</li>
            </ul>
        </div>
        <div class="ty_main05">
            <div class="ty_zzleft"><img src=""></div>
            <div class="ty_zzcenter">
                <ul>
                    <li><span class="ty_aut"><?php echo $artistInfo['artistName'] ?></span><span class="ty_aut1">[<?php echo $artistInfo['shortDesc'] ?>]</span></li>
                    <li><a href=""><span class="ty_grjl">个人简历</span></a><a href=""><span
                                class="ty_grjl">获奖及著作</span></a><a href=""><span class="ty_grjl">作品欣赏</span></a></li>
                </ul>
            </div>
            <div class="ty_zzright"><img src="images/tp_03.jpg"></div>

        </div>
        <div class="ty_main06">
            <p class="ty_hjiang">个人简历</p>

            <p class="ty_jianjie1">
                <?php echo $artistInfo['artistDetail'] ?>
            </p>

            <div class="ty_jianjie2"></div>

        </div>
        <div class="ty_main07">
            <img src="images/tp_09.jpg">
        </div>
        <div class="ty_main08">
            <p class="ty_hjiang">获奖及著作</p>

            <?php
                echo $artistInfo['awards'];
            ?>
        </div>
        <div class="ty_main09">
            作品欣赏
        </div>
        <div class="ty_main10">
            <?php echo $artistInfo['productions'] ?>
        </div>


    </div>
</div>