<div class="mingjia-top">
    <div class="center">
        <h4 class="fl">特邀名家</h4>

        <p class="fl">
            特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家
            <br>
            特邀名家特邀名家特邀名家特邀名家特邀名家特邀特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家名家
            <br>
            特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家
            <br>
            特邀名家特邀名家特邀名家特邀名家特邀名家特邀名家
            <br></p>
    </div>
</div>
<div class="mingjia-nav">
    <div class="center">
        <ul>
            <li>专业领域></li>

            <li class="on">国画</li>

            <li>书法</li>
            <li>篆刻</li>
            <li>工艺</li>
        </ul>

    </div>
</div>
<div class="center">
    <div class="dz_con">
        <div class="dz_left"><img src=""></div>
        <div class="dz_center">
            <p class="dz_tit">李明辉(五字以内)</p>

            <p class="dz_tit1">[中国美院教师、书法学博士、西泠印社社员]</p>

            <div class="dz_tit2">
                <ul>
                    <li>定制价 <span class="dz_right02"> ￥2400</span></li>
                    <li>剩余数量：2</li>
                    <li>类别：篆刻</li>
                </ul>
            </div>
            <div class="dz_tit3">说明：西泠社员名家，浙江省首批“新峰计划”人才。篆刻印章订制。所刻内容自定，限5字以内。完成购买后需全款预付。攥刻订制需自备印石，如无自备，可联系客服选购

            </div>
        </div>
        <div class="dz_right">
            <div class="dz_right01"><a href="">更多作者介绍内详细 >></a></div>
            <div class="dz_right04">距结束</div>
            <div class="dz_right10">
                <span class="dz_right02 dz_r">2</span>
                <span class="dz_right03">天</span>
                <span class="dz_right02">08</span>
                <span class="dz_right03">时</span>
                <span class="dz_right02">30</span>
                <span class="dz_right03">分</span>
                <span class="dz_right02">20</span>
                <span class="dz_right03">秒</span>
            </div>
            <div class="dz_right05">
                <a href="">
                    <div class="dz_right06">
                        <p>我要</p>

                        <p>订制</p>
                    </div>
                </a>

                <div class="dz_right07">
                    <p class="dz_right08">3</p>

                    <p class="dz_right09">次购买</p>
                </div>
            </div>
        </div>
    </div>

    <div class="dz_con">
        <div class="dz_left"><img src=""></div>
        <div class="dz_center">
            <p class="dz_tit">李明辉(五字以内)</p>

            <p class="dz_tit1">[中国美院教师、书法学博士、西泠印社社员]</p>

            <div class="dz_tit2">
                <ul>
                    <li>定制价 <span class="dz_right02"> ￥2400</span></li>
                    <li>剩余数量：2</li>
                    <li>类别：篆刻</li>
                </ul>
            </div>
            <div class="dz_tit3">说明：西泠社员名家，浙江省首批“新峰计划”人才。篆刻印章订制。所刻内容自定，限5字以内。完成购买后需全款预付。攥刻订制需自备印石，如无自备，可联系客服选购

            </div>
        </div>
        <div class="dz_right">
            <div class="dz_right01"><a href="">更多作者介绍内详细 >></a></div>
            <div class="dz_right04">距结束</div>
            <div class="dz_right10">
                <span class="dz_right02 dz_r">2</span>
                <span class="dz_right03">天</span>
                <span class="dz_right02">08</span>
                <span class="dz_right03">时</span>
                <span class="dz_right02">30</span>
                <span class="dz_right03">分</span>
                <span class="dz_right02">20</span>
                <span class="dz_right03">秒</span>
            </div>
            <div class="dz_right05">
                <a href="">
                    <div class="dz_right06">
                        <p>我要</p>

                        <p>订制</p>
                    </div>
                </a>

                <div class="dz_right07">
                    <p class="dz_right08">3</p>

                    <p class="dz_right09">次购买</p>
                </div>
            </div>
        </div>
    </div>

    <div class="dz_con">
        <div class="dz_left"><img src=""></div>
        <div class="dz_center">
            <p class="dz_tit">李明辉(五字以内)</p>

            <p class="dz_tit1">[中国美院教师、书法学博士、西泠印社社员]</p>

            <div class="dz_tit2">
                <ul>
                    <li>定制价 <span class="dz_right02"> ￥2400</span></li>
                    <li>剩余数量：2</li>
                    <li>类别：篆刻</li>
                </ul>
            </div>
            <div class="dz_tit3">说明：西泠社员名家，浙江省首批“新峰计划”人才。篆刻印章订制。所刻内容自定，限5字以内。完成购买后需全款预付。攥刻订制需自备印石，如无自备，可联系客服选购

            </div>
        </div>
        <div class="dz_right">
            <div class="dz_right01"><a href="">更多作者介绍内详细 >></a></div>
            <div class="dz_right04">距结束</div>
            <div class="dz_right10">
                <span class="dz_right02 dz_r">2</span>
                <span class="dz_right03">天</span>
                <span class="dz_right02">08</span>
                <span class="dz_right03">时</span>
                <span class="dz_right02">30</span>
                <span class="dz_right03">分</span>
                <span class="dz_right02">20</span>
                <span class="dz_right03">秒</span>
            </div>
            <div class="dz_right05">
                <a href="">
                    <div class="dz_right06">
                        <p>我要</p>

                        <p>订制</p>
                    </div>
                </a>

                <div class="dz_right07">
                    <p class="dz_right08">3</p>

                    <p class="dz_right09">次购买</p>
                </div>
            </div>
        </div>
    </div>
    <div class="dz_con">
        <div class="dz_left"><img src=""></div>
        <div class="dz_center">
            <p class="dz_tit">李明辉(五字以内)</p>

            <p class="dz_tit1">[中国美院教师、书法学博士、西泠印社社员]</p>

            <div class="dz_tit2">
                <ul>
                    <li>定制价 <span class="dz_right02"> ￥2400</span></li>
                    <li>剩余数量：2</li>
                    <li>类别：篆刻</li>
                </ul>
            </div>
            <div class="dz_tit3">说明：西泠社员名家，浙江省首批“新峰计划”人才。篆刻印章订制。所刻内容自定，限5字以内。完成购买后需全款预付。攥刻订制需自备印石，如无自备，可联系客服选购

            </div>
        </div>
        <div class="dz_right">
            <div class="dz_right01"><a href="">更多作者介绍内详细 >></a></div>
            <div class="dz_right04">距结束</div>
            <div class="dz_right10">
                <span class="dz_right02 dz_r">2</span>
                <span class="dz_right03">天</span>
                <span class="dz_right02">08</span>
                <span class="dz_right03">时</span>
                <span class="dz_right02">30</span>
                <span class="dz_right03">分</span>
                <span class="dz_right02">20</span>
                <span class="dz_right03">秒</span>
            </div>
            <div class="dz_right05">
                <a href="">
                    <div class="dz_right06">
                        <p>我要</p>

                        <p>订制</p>
                    </div>
                </a>

                <div class="dz_right07">
                    <p class="dz_right08">3</p>

                    <p class="dz_right09">次购买</p>
                </div>
            </div>
        </div>
    </div>

</div>