<link rel="stylesheet" href="/dist/styles/main/index.css" media="screen" type="text/css" />
<div class="mingjia-top">
    <div class="center">
        <h4 class="fl">特邀名家</h4>

        <p class="fl">
            <?php echo $_siteSettings['customizationTopText']; ?>
        </p>
    </div>
</div>
<div class="mingjia-nav">
    <div class="center">
        <ul>
            <li>专业领域></li>

            <?php
            foreach($artistCategories as $v){
            ?>
                <li class="<?php echo $artistCategoryID == $v['artistCategoryID'] ? 'on' : ''; ?>" style="cursor: pointer;" onclick="location.href='/customization/index?artistCategoryID=<?php echo $v['artistCategoryID'] ?>'"><?php echo $v['categoryName']; ?></li>
            <?php
            }
            ?>
        </ul>

    </div>
</div>
<div class="center">
    <?php
        foreach($customizations as $v){
    ?>
            <div class="dz_con">
                <div class="dz_left"><img src="<?php echo $v['listImg'] ?>"></div>
                <div class="dz_center">
                    <p class="dz_tit"><?php echo $v['title']; ?></p>

                    <p class="dz_tit1">[<?php echo $v['shortDesc']; ?>]</p>

                    <div class="dz_tit2">
                        <ul>
                            <li>定制价 <span class="dz_right02"> ￥<?php echo $v['price']; ?></span></li>
                            <li>剩余数量：<?php echo $v['lastNum'] ?></li>
                            <li>类别：<?php echo $v['categoryName'] ?></li>
                        </ul>
                    </div>
                    <div class="dz_tit3">
                        说明：<?php echo $v['desc']; ?>

                    </div>
                </div>
                <div class="dz_right">
                    <div class="dz_right01"><a href="/customization/detail?customizationID=<?php echo $v['customizationID'] ?>">更多作者介绍内详 >></a></div>
                    <?php
                    if(time() < $v['endTime']) {
                    ?>
                        <div class="dz_right04">距结束</div>
                    <?php
                    }
                    ?>


                    <div class="dz_right10 yomibox2" data="<?php echo date('Y/m/d H:i:s', $v['endTime']); ?>">

                    </div>
                    <div class="dz_right05">
                        <div class="dz_right06" style="cursor: pointer;" onclick="location.href='/customization/detail?customizationID=<?php echo $v['customizationID'] ?>';">
                            <p>我要</p>

                            <p>订制</p>
                        </div>

                        <div class="dz_right07">
                            <p class="dz_right08"><?php echo $v['boughtCount'] ?></p>

                            <p class="dz_right09">次购买</p>
                        </div>
                    </div>
                </div>
            </div>
    <?php
        }
    ?>
</div>
<script>
    $(function(){
        $(".yomibox2").each(function () {
            $(this).yomi(_CurrentServerTime, 'customization-index')
        });
    })

</script>