<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/member/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'memberID',
                title: '账号ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'mobile',
                title: '手机号',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'nickName',
                title: '昵称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'signature',
                title: '签名',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'avatar',
                title: '头像',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'email',
                title: 'email',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'qq',
                title: 'qq',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'wechat',
                title: '微信',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'selfDesc',
                title: '自我介绍',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'rechargeMoney',
                title: '余额',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'instime',
                title: '新增时间',
                align: 'center',
                valign: 'middle',
                width:200
            }]
    });

</script>
