<?php
echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.config.js');
echo $this->inlineScript()->setFile('/admin/ueditor/ueditor.all.js');
echo $this->inlineScript()->setFile('/admin/ueditor/lang/zh-cn/zh-cn.js');
?>
<div class="wrapper">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">
                <?php echo (isset($productInfo['ProductID'])) ? '编辑商品ID:' . $productInfo['ProductID'] : '增加商品页面'; ?>
                <a class="text-right" style="float:right;"
                   href="<?php echo '/admin/' . $this->layout()->controllerName . '/index' ?>">返回</a>
            </h3>
        </div>
        <div class="panel-body">

<div class="container mtop40" style="margin-bottom: 50px; height: auto;">
    <form class="form-horizontal" action="/admin/product/<?= (isset($productInfo)) ? "update" : "add"; ?>" method="post">
        <div class="form-group">
            <label for="inputEmail3" class="col-sm-2 control-label">产品名称</label>

            <div class="col-sm-4">
                <input class="form-control" name="Name"
                       value="<?= (isset($productInfo['Name'])) ? $productInfo['Name'] : ''; ?>" placeholder="产品名称">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品分类</label>
            <div class="col-sm-4">
                <select class="form-control input-sm m-bot15" name="Category">
                    <?php foreach ($categories as $v): ?>
                        <option value="<?php echo $v['CategoryID']; ?>" <?php if(isset($productInfo['Category']) && $v['CategoryID'] == $productInfo['Category']){echo 'selected';} ?>><?php echo $v['CategoryName']; ?></option>
                    <?php endforeach; ?>
                </select>
            </div>
        </div>

        <div class="form-group" id="ThirdProductIDDiv" style="display:none">
            <label for="inputPassword3" class="col-sm-2 control-label">第三方平台商品ID</label>

            <div class="col-sm-4">
                <input name="ThirdProductID" class="form-control" placeholder="第三方平台商品ID" value="<?=$productInfo['ThirdProductID']?>"/>
            </div>
        </div>
        
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品描述</label>

            <div class="col-sm-4">
                   <textarea name="ProductDetail" class="form-control" placeholder="产品描述"
                             rows="5"><?= (isset($productInfo['ProductDetail'])) ? $productInfo['ProductDetail'] : ''; ?></textarea>
            </div>
        </div>

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">商品列表图片</label>

            <div class="col-sm-4 access-upload" id="container">
                <a href="" id="ListImg"> <img
                        src="<?= (isset($productInfo['ListImg'])) ? $productInfo['ListImg'] : ''; ?>" alt=""/></a>
                <!--                <input type="hidden" name="DetailImg" value="-->
                <? //= (isset($productInfo['ListImg'])) ? $productInfo['ListImg'] : ''; ?><!--" alt=""/>-->
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">产品静默时间(单位:天)</label>

            <div class="col-sm-4">
                <input class="form-control" name="SilenceTime" value="<?= (isset($productInfo['SilenceTime'])) ? $productInfo['SilenceTime'] : ''; ?>" placeholder="产品静默时间">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品属性</label>

            <div class="col-sm-10 ml20">

                <div class="pro-li-1 pull-left">
                    属性：<input type="text" id="attrName" class="w120" value=""
                              placeholder="属性值">
                </div>
                
                <div class="pro-li-1 pull-left" id="sku_div" sku="no" style="display: none">
                    SKU：<input type="text" id="ThirdSku" class="w120" value=""
                              placeholder="商品SKU">
                </div>

                <div class="pro-li-1 pull-left">
                    价格：<input type="text" id="attrPrice" value="0" class="w120">
                </div>
	
				
                <div class="pro-li-icon pull-left" id="addProAttr" >
                    +
                </div>
            </div>
        </div>

		<?php if(isset($productInfo['properties']) || $isAdd):?>
             
        <div class="form-group" id="addProAttrBox" style="display: block;">
            <label for="inputPassword3" class="col-sm-2 control-label">已加属性</label>
            <?php
                $initNum = 0;
                if(!empty($productInfo['properties'])){
                    $pties = \Base\Functions\Utility::collectField($productInfo['properties'], 'PropertyID');
                    $initNum  = max($pties);
                }
            ?>
			<input type="hidden" value="<?=$initNum?>" id="initNum" />
            <?php
			if(!empty($productInfo['properties'])):
			//$j=$initNum;
			?>
              
			<?php foreach($productInfo['properties'] as $pk=>$p):?>
            
            <dl class="col-sm-10 ml20 pro-attrbox">
                <dt>
                    <div class="pro-li-1 pull-left">属性：<input type="text"  name="property[<?=$productInfo['ProductID']?>-][<?=$p['PropertyID'];?>][PropertyName]" class="w120" value="<?=$p['PropertyName'];?>"> </div>
                    <?php if(in_array($productInfo['Category'],$thirdCategoryIDs)){?>
                    <div class="pro-li-1 pull-left">SKU：<input type="text"  name="property[<?=$productInfo['ProductID']?>-][<?=$p['PropertyID'];?>][ThirdSku]" class="w120" value="<?=$p['ThirdSku'];?>"> </div>
                    <?php } ?>
                    <div class="pro-li-1 pull-left">价格：<input type="text"  name="property[<?=$productInfo['ProductID']?>-][<?=$p['PropertyID'];?>][Price]" class="w120"  value="<?=$p['Price'];?>" ></div>
                    <div class="pro-li-1 pull-left">排序：<input type="text" class="w120"  name="property[<?=$productInfo['ProductID']?>-][<?=$p['PropertyID'];?>][Sort]" placeholder="倒序,不可大于255"  value="<?=$p['Sort'];?>"> </div>
                    <div data-attr="<?=$p['PropertyID'];?>" class="pro-li-3 pull-left addproject" >增加方案</div>
                    <div class="delServiceItem delAttrTit ">-</div>
                </dt>
                <dd>
                    <div class="pro-selected-tit" style="display: block;">
                        <div class="pro-li-4 pull-left">已选方案:</div>
                        <div class="pro-li-1 pull-left">方案分类</div>
                        <div class="pro-li-1 pull-left">方案名称</div>
                        <div class="pro-li-1 pull-left">方案数量</div>
                        <div class="pro-li-5 pull-left">操作</div>
                    </div>
                    
                    <?php if(!empty($productInfo['PropertyParts'][$pk])) foreach($productInfo['PropertyParts'][$pk] as $i=>$pp){?>
                    <?php //print_r($pp);exit;?>
                    <div class="pro-selected-li">
                    	<input type="hidden" value="<?=$pp['PartsCategoryID']?>" name="attrpjClass<?=$p['PropertyID'];?>[]"> 
                        <input type="hidden" value="<?=$pp['PartsID']?>" name="attrpjName<?=$p['PropertyID'];?>[]">
                        <input type="hidden" value="<?=$pp['Num']?>" name="attrpjNum<?=$p['PropertyID'];?>[]">
                        <div class="pro-li-4 pull-left">&nbsp;</div>
                        <div class="pro-li-1 pull-left"><?=$pp['CategoryName']?></div>
                        <div class="pro-li-1 pull-left"><?=$pp['PartsName']?></div>
                        <div class="pro-li-1 pull-left"><?=$pp['Num']?></div>
                        <div class="delServiceItem delProItem">-</div>
                    </div>
                    <?php }?>
                </dd>
            </dl>
            <?php //$j--;?>
			<?php endforeach;
            endif;
            ?>
        </div>
    	<?php endif;?>   


        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品价格</label>

            <div class="col-sm-4">
                <input name="Price" value="<?php echo (isset($productInfo['Price'])) ? $productInfo['Price'] : ''; ?>"
                       class="form-control" id="Price" placeholder="产品价格">
            </div>
        </div>

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品标签</label>

            <div class="col-sm-8">
                <?php
                foreach ($tags as $t):?>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="tag[]" id="inlineCheckbox1"
                            <?= (isset($productInfo['tags']) && in_array($t['TagID'], $productInfo['tags'])) ? 'checked' : ''; ?>
                               value="<?php echo $t['TagID']; ?>">
                        <?php echo $t['TagName']; ?>
                    </label>
                <?php endforeach; ?>
            </div>
        </div>


        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">产品服务项目</label>

            <div class="col-sm-8 ml20">
                <div class="col-sm-4 ml20">
                    <select class="form-control input-sm m-bot15" id='serviceItem'>
                        <option value="0">--选择项目--</option>
                        <?php foreach ($services as $s): ?>
                            <option value="<?php echo $s['ServiceID']; ?>"><?php echo $s['ServiceName']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="col-sm-3 ml20">
                    数量：<input type="text" id="serviceItemNum" style="width: 100px;" value="1" placeholder="(如填写将绑定该服务)">
                </div>

                <div class="col-sm-4 ml20">
                    有效天数：
                    <input type="text" id="serviceItemDay" value="0" style="width: 126px;">
                </div>
                <div class="col-sm-1 ml20" id="addServiceItem">
                    +
                </div>
            </div>
        </div>

        <div class="form-group" id="addServiceBox" style="<?php  if(!$isAdd) echo 'display: block;'?>">
            <label for="inputPassword3" class="col-sm-2 control-label">已加服务项目</label>

            <ul class="col-sm-8 ml20 serviceItem" id="serviceBox">
            <?php
            if(!empty($productInfo['services'])):
                foreach($productInfo['services'] as $sk=>$s):?>
                <li>
                    <div class="col-sm-4 ml20"><?= $services[$s['ServiceID']]['ServiceName'];?></div>
                    <div class="col-sm-3 ml20">数量：<?= $s['ServiceNum'];?></div>
                    <div class="col-sm-4 ml20">有效天数：<?= $s['ValidDays'];?></div>
                    <div class="col-sm-1 ml20 delServiceItem">-</div>
                    <input type="hidden" name="service[<?= $sk;?>][ServiceID]" value="<?= $s['ServiceID'];?>">
                    <input type="hidden" name="service[<?= $sk;?>][ServiceNum]" value="<?= $s['ServiceNum'];?>">
                    <input type="hidden" name="service[<?= $sk;?>][ValidDays]" value="<?= $s['ValidDays'];?>">
                </li>
                <?php endforeach;
            endif;
            ?>
            </ul>
            
        </div>

                <div class="form-group" id="SupplierDiv" style="display:none">
            <label for="inputPassword3" class="col-sm-2 control-label">可服务门店</label>

            <div class="col-sm-4">
                
            </div>
        </div>    

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">商品订金</label>

            <div class="col-sm-4">
                <input class="form-control"
                       value="<?= (isset($productInfo['Deposit'])) ? $productInfo['Deposit'] : ''; ?>"
                       name="Deposit" placeholder="商品订金">
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">商品详情</label>

            <div class="col-sm-4 access-upload">
                <script id="editor" name="DetailImg" type="text/plain" style="width:700px;height:300px;"><?= (isset($productInfo['DetailImg'])) ? $productInfo['DetailImg'] : ''; ?></script>

<!--                <a href="" id="DetailImg"><img-->
<!--                        src="--><?//= (isset($productInfo['DetailImg'])) ? $productInfo['DetailImg'] : ''; ?><!--" alt=""/></a>-->
                <!--                <input type="hidden" name="DetailImg" value="-->
                <? //= (isset($productInfo['DetailImg'])) ? $productInfo['DetailImg'] : ''; ?><!--" alt=""/>-->
            </div>
        </div>



        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">城市站ID</label>

            <div class="col-sm-4">
                <?php foreach ($cityStations as $g): ?>
                    <label class="checkbox-inline">
                        <input type="checkbox" name="CityStationID[]"
                            <?php if (isset($productInfo['choiceCity']) && in_array($g['CityStationID'], $productInfo['choiceCity'])) echo "checked"; ?>
                               value="<?= $g['CityStationID']; ?>"> <?= $g['CityStationName']; ?>
                    </label>
                <?php endforeach; ?>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">是否隐藏</label>

            <div class="col-sm-4">
                <label class="radio-inline">
                    <input type="radio"
                           name="IsHide" <?php if (isset($productInfo['IsHide']) && $productInfo['IsHide'] == 1) echo "checked"; ?>
                           value="1"> 是
                </label>
                <label class="radio-inline">
                    <input type="radio"
                           name="IsHide" <?php if (!isset($productInfo['IsHide']) || $productInfo['IsHide'] == 0) echo "checked"; ?>
                           value="0"> 否
                </label>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">是否可购买</label>

            <div class="col-sm-4">
                <label class="radio-inline">
                    <input type="radio" name="CanBuy"
                           checked="checked" <?php if (isset($productInfo['CanBuy']) && $productInfo['CanBuy'] == 1) echo "checked"; ?>
                           value="1"> 是
                </label>
                <label class="radio-inline">
                    <input type="radio"
                           name="CanBuy" <?php if (!isset($productInfo['CanBuy']) || $productInfo['CanBuy'] == 0) echo "checked"; ?>
                           value="0"> 否
                </label>
            </div>
        </div>
        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">是否固定价格</label>

            <div class="col-sm-4">
                <label class="radio-inline">
                    <input type="radio"
                           name="IsFixed" <?php if (!isset($productInfo['IsFixed']) || $productInfo['IsFixed'] == 1) echo "checked"; ?>
                           value="1"> 是
                </label>
                <label class="radio-inline">
                    <input type="radio"
                           name="IsFixed" <?php if (isset($productInfo['IsFixed']) && $productInfo['IsFixed'] == 0) echo "checked"; ?>
                           value="0"> 否
                </label>
            </div>
        </div>
       

        <div class="form-group">
            <label for="inputPassword3" class="col-sm-2 control-label">是否需要体检</label>

            <div class="col-sm-4">
                <label class="radio-inline">
                    <input type="radio"
                           name="NeedTest" <?php if (isset($productInfo['NeedTest']) && $productInfo['NeedTest'] == 1) echo "checked"; ?>
                           id="inlineRadio1" value="1"> 是
                </label>
                <label class="radio-inline">
                    <input type="radio" name="NeedTest"
                           id="inlineRadio1" <?php if (!isset($productInfo['NeedTest']) || $productInfo['NeedTest'] == 0) echo "checked"; ?>
                           value="0"> 否
                </label>
            </div>
        </div>
        <!--        <div class="form-group">-->
        <!--            <label for="inputPassword3" class="col-sm-2 control-label">是否是付订金商品</label>-->
        <!---->
        <!--            <div class="col-sm-4">-->
        <!--                <label class="radio-inline">-->
        <!--                    <input type="radio"-->
        <!--                           name="IsDepositProduct" --><?php //if (isset($productInfo['IsDepositProduct']) && $productInfo['IsDepositProduct'] == 1) echo "checked"; ?>
        <!--                           id="inlineRadio1" value="1"> 是-->
        <!--                </label>-->
        <!--                <label class="radio-inline">-->
        <!--                    <input type="radio" name="IsDepositProduct"-->
        <!--                        --><?php //if (!isset($productInfo['IsDepositProduct']) || $productInfo['IsDepositProduct'] == 0) echo "checked"; ?>
        <!--                           id="inlineRadio1" value="0"> 否-->
        <!--                </label>-->
        <!--            </div>-->
        <!--        </div>-->

        <input type="hidden" name="ProductID"
               value="<? if(isset($productInfo['ProductID'])) echo $productInfo['ProductID']; ?>"/>
        <input type="hidden" name="location-url" value="<? echo (isset($productInfo['ProductID'])) ? '/admin/product/add-view?pid='.$productInfo['ProductID'] : '/admin/product/index'; ?>"/>

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <a class="btn btn-primary editModal" onclick="">确定</a>
            </div>
        </div>
    </form>
</div>
</div>
</div>
</div>


<!-- Add Modal Start -->
<div class="row">
    <div class="modal form-modal fade" id="add_modal" tabindex="-1" role="dialog" aria-labelledby="add_modal_label" aria-hidden="true">
        <div class="modal-dialog">
           
            </div>
        </div>
    </div>
</div>
<!-- Add Modal End -->
<script>
    $(function () {
        var ue = UE.getEditor('editor');
        uploadInit("ListImg");
        uploadInit("DetailImg");
        serviceItem();
//        $('.datetime').datetimepicker({
//            language: 'zh-CN',
//            format: 'yyyy-mm-dd hh:ii:ss'
//        });
        
        //*****判断是否展示sku*****
        var third = new Array(),j=0;
        var thirdCategoryIDs = eval(<?=json_encode($thirdCategoryIDs)?>);
        for(var i in thirdCategoryIDs){
            third[j] = thirdCategoryIDs[i];
            j++;
        }
        $("select[name='Category']").change(function(){
//            $('#addProAttrBox > dl').remove();
            if($.inArray(Number($(this).val()),third)>-1){
                $('#sku_div').attr('sku','yes');
                $("#ThirdProductIDDiv").show();
                $("#SupplierDiv").show();
                $('#sku_div').show();
            }else{
                $('#sku_div').attr('sku','no');
                $("#ThirdProductIDDiv").hide();
                $("#SupplierDiv").hide();
                $('#sku_div').hide();
            }
        });
        $("select[name='Category']").trigger('change');
        
        attPro();
        serviceStore();
    });
    
    
    function attPro() {
        var i = 0;
        var serviceItemNum = $('#serviceItemNum2');
        var serviceItemDay = $('#serviceItemDay2');
        var serviceBox = $('#serviceBox2');
        var addServiceBox = $('#addServiceBox2');
        $('#addServiceItem2').bind('click', function () {


            if (serviceItemNum.val() == '') {
                alertError('请填写正确的属性!');
                return false;
            };
            if (isNaN(serviceItemDay.val()) || serviceItemDay.val() == '' || serviceItemDay.val() == 0) {
                alertError('请填写正确的价格!');
                return false;
            };

            var liHtml = "<li>" +
                "<div class='col-sm-3 ml20'>属性：<input type='text' style='width: 150px;' name='property[" + i + "][PropertyName]' value='" + serviceItemNum.val() + "'> </div><div class='col-sm-3 ml20'>价格：" +
                "<input type='text' style='width: 126px;' name='property[" + i + "][Price]' value='" + serviceItemDay.val() + "'></div>" +
                '<div class="col-sm-3 ml20">排序：<input type="text" placeholder="倒序,不可大于255" name="property['+ i +'][Sort]" value="" style="width: 126px;"> </div>'+
                "<div class='col-sm-1 ml20 delServiceItem'>" +
                "-" +
                "</div>" +
                "</li>";

            i++;
            addServiceBox.show();
            serviceBox.append(liHtml);


        });

        serviceBox.delegate('li .delServiceItem', 'click', function () {
            $(this).parent('li').remove();
            if (serviceBox.find('li').length == 0) {
                addServiceBox.hide();
            }
        });

    }
    ;

    //服务项目
    function serviceItem() {
        var i = 0;
        var serviceItem = $('#serviceItem');
        var serviceItemNum = $('#serviceItemNum');
        var serviceItemDay = $('#serviceItemDay');
        var serviceBox = $('#serviceBox');
        var addServiceBox = $('#addServiceBox');

        $('#addServiceItem').bind('click', function () {

            if (serviceItem.val() == 0) {
                alertError('请选择服务项目!');
                return false;
            }
            ;
            if (isNaN(serviceItemNum.val()) || serviceItemNum.val() == '' || serviceItemNum.val() < 1) {
                alertError('请填写正确的数量!');
                return false;
            }
            ;
            if (isNaN(serviceItemDay.val()) || serviceItemDay.val() == '' || serviceItemDay.val() == 0) {
                alertError('请填写正确的天数!');
                return false;
            }
            ;
            var liHtml = "<li><div class='col-sm-4 ml20'>" + serviceItem.find("option:selected").text() + "</div><div class='col-sm-3 ml20'>数量：" +
                serviceItemNum.val()
                + "</div>"
                + "<div class='col-sm-4 ml20'>有效天数：" + serviceItemDay.val() + "</div><div class='col-sm-1 ml20 delServiceItem'>-</div><input type='hidden' name='service[" + i + "][ServiceID]' value='" + serviceItem.val() + "'>" +
                "<input type='hidden' name='service[" + i + "][ServiceNum]' value='" + serviceItemNum.val() + "'><input type='hidden' name='service[" + i + "][ValidDays]' value='" + serviceItemDay.val() + "'></li>";

            i++;
            addServiceBox.show();
            serviceBox.append(liHtml);
            serviceStore();

        });

        serviceBox.delegate('li .delServiceItem', 'click', function () {
            $(this).parent('li').remove();
            if (serviceBox.find('li').length == 0) {
                addServiceBox.hide();
            }
            serviceStore();
        });


    }
    ;
    
    /**
    *description 根据条件检索出服务门店 
    *  */
    function serviceStore(){
        var ServiceID = new Array();
        $("#serviceBox li").each(function(i){
            ServiceID.push($(this).find("input:first").val());
        });
        $.get("/admin/product/getSupplier",{ServiceID:ServiceID},function(data){
            var content = '';
            var SupplierIDs = <?php echo json_encode($supplierIDs);?>;
            for(var i in data.msg){
                if($.inArray(data.msg[i].SupplierID,SupplierIDs) > -1){
                    content += '<input type="checkbox" value="'+ data.msg[i].SupplierID +'" name="SupplierIDs[]" checked="checked"/>' + data.msg[i].SupplierName + '&nbsp;&nbsp;';
                }else{
                    content += '<input type="checkbox" value="'+ data.msg[i].SupplierID +'" name="SupplierIDs[]" />' + data.msg[i].SupplierName + '&nbsp;&nbsp;';
                }
            }
            $('#SupplierDiv div').html(content);
        },'json')
    }


    var num = 0;
    function uploadInit(id) {
        //上传组件
        var uploader = new plupload.Uploader({
            runtimes: 'html5,flash,silverlight,html4',
            browse_button: id, // you can pass in id...触发上传窗口
            container: document.getElementById('container'), // ... or DOM Element itself容器
            url: '/admin/file/file-upload',//上传URL
            flash_swf_url: '../js/Moxie.swf',
            silverlight_xap_url: '../js/Moxie.xap',

            filters: {
                max_file_size: '10mb',//用来限定上传文件的大小
                mime_types: [//用来限定上传文件的类型，为一个数组
                    {title: "Image files", extensions: "jpg,png,jpeg,gif"},
                ],
                prevent_duplicates: false //不允许选取重复文件
            },
            multipart: true,
            max_retries: 0,//当发生plupload.HTTP_ERROR错误时的重试次数，为0时表示不重试
            multi_selection: false,//是否可以在文件浏览对话框中选择多个文件
            unique_names: true,
            init: {
                PostInit: function () {
                },
                FilesAdded: function (up, files) {
                    uploader.start();
                    return false;
                },
                FileUploaded: function (up, file, response) {
                    //触发
                    var imgObj = eval('(' + response.response + ')');
                    $('#' + id).html('<img src="' + imgObj.url + '">');
                    $('#' + id).parent().append('<span title="删除"></span><input type="hidden" name="' + id + '" value="' + imgObj.path + '" />');
                },
                Error: function (up, err) {
                    if (err.status == 413) {
                        $(".err-tip-li .licencetip").html("您上传图片过大,请不要上传超过2M的图片");
                    }
                    if (err.code == -601) {
                        $(".err-tip-li .licencetip").html("图片格式错误,请重新选择");
                    }
                }
            }
        });
        uploader.init();
    }

    function moreUploadInit(id) {
        //上传组件
        var uploader = new plupload.Uploader({
            runtimes: 'html5,flash,silverlight,html4',
            browse_button: id, // you can pass in id...触发上传窗口
            container: document.getElementById('proveImg'), // ... or DOM Element itself容器
            url: '/admin/file/upload-file',//上传URL
            flash_swf_url: '../js/Moxie.swf',
            silverlight_xap_url: '../js/Moxie.xap',

            filters: {
                max_file_size: '10mb',//用来限定上传文件的大小
                mime_types: [//用来限定上传文件的类型，为一个数组
                    {title: "Image files", extensions: "jpg,png,jpeg,gif"},
                ],
                prevent_duplicates: false //不允许选取重复文件
            },
            multipart: true,
            max_retries: 0,//当发生plupload.HTTP_ERROR错误时的重试次数，为0时表示不重试
            multi_selection: true,//是否可以在文件浏览对话框中选择多个文件
            unique_names: true,
            init: {
                PostInit: function () {
                },
                FilesAdded: function (up, files) {
                    num = num + files.length;
                    if (num > 4) {
                        num = num - files.length;
                        $(".err-tip-li .licencetip").html("最多可以上传4张图片");
                        uploader.splice(0);
                        return false;
                    }
                    uploader.start();
                    return false;
                },
                FileUploaded: function (up, file, response) {
                    //触发
                    var imgObj = eval('(' + response.response + ')');
                    var str = '<li><a href="#"><img src="' + imgObj.url + '"></a><span title="删除"></span><input type="hidden" name="img[]" value="' + imgObj.path + '" /></li>';
                    $('#proveImg').prepend(str);
                },
                Error: function (up, err) {
                    if (err.status == 413) {
                        $(".err-tip-li .licencetip").html("您上传图片过大,请不要上传超过2M的图片");
                    }
                    if (err.code == -601) {
                        $(".err-tip-li .licencetip").html("图片格式错误,请重新选择");
                    }
                }
            }
        });
        uploader.init();
    }
</script>
<script type="text/javascript" src="/admin/js/addpro.js"></script>