<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>
<div class="row">
    <div class="modal form-modal fade" id="edit_modal" tabindex="-1" role="dialog" aria-labelledby="edit_modal_label" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                    <h4 class="modal-title" id="edit_modal_label">设置推荐时间</h4>
                </div>
                <div class="modal-body">
                    <form class="form-horizontal" id="editForm" role="form" method="post" action="/admin/<?php echo $this->layout()->controllerName;?>/update">
                        <table class="table table-bordered">
                            <tr>
                                <td>
                                    <div class="form-group">
                                        <label class="col-sm-2 control-label">开始时间</label>

                                        <div class="col-sm-4">
                                            <input type="text" class="" id="start-time" name="recommendStartTime">
                                        </div>
                                        <label class="col-sm-2 control-label">结束时间</label>

                                        <div class="col-sm-4">
                                            <input type="text" class="" id="end-time" name="recommendEndTime">
                                        </div>
                                    </div>
                                </td>
                            </tr>

                        </table>
                        <input type="hidden"  name="productID" value="" />
                    </form>
                </div>
                <div class="modal-footer">
                    <div class="col-md-6"><button type="button" class="btn btn-danger btn-block" data-dismiss="modal">关闭</button></div>
                    <div class="col-md-6"><button type="button" class="btn btn-primary editModal btn-block">保存</button></div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $('#start-time,#end-time').datetimepicker({
        language:'zh-CN',
        format: 'yyyy-mm-dd hh:ii:ss'
    });


    $('#edit_modal').on("shown.bs.modal",function(e){

        var btn = $(e.relatedTarget);
        var productID = btn.attr('rid');
        var recommendStartTime = btn.attr('recommendStartTime');
        var recommendEndTime = btn.attr('recommendEndTime');
        $('input[name=productID]').val(productID);
        if(recommendStartTime && recommendStartTime != 'null'){
            $('input[name=recommendStartTime]').val(recommendStartTime);
        }else{
            $('input[name=recommendStartTime]').val('');
        }
        if(recommendEndTime && recommendEndTime != 'null'){
            $('input[name=recommendEndTime]').val(recommendEndTime);
        }else{
            $('input[name=recommendEndTime]').val('');
        }

    });

    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/product/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'productID',
                title: '拍品ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'productName',
                title: '拍品名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'storeName',
                title: '店铺名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'startPrice',
                title: '起拍价',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'currPrice',
                title: '当前价格',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'deliveryPrice',
                title: '运费',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'startTime',
                title: '起拍时间',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'endTime',
                title: '结束时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'isIndexRecommend',
                title: '首页推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isIndexRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isIndexRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isSpecialTodayRecommend',
                title: '专场拍卖推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isSpecialTodayRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isSpecialTodayRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isProductIndexRecommend',
                title: '拍品列表推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isProductIndexRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isProductIndexRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isMemberRecommend',
                title: '个人中心推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isMemberRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isMemberRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'recommendStartTime',
                title: '推荐时间',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    var str = '';
                    if(value){
                        str += '开始时间:' + value + '<br />';
                    }
                    if(row.recommendEndTime){
                        str += '结束时间:' + row.recommendEndTime + '<br />';
                    }
                    str += '<a title="设置推荐时间" href="javascript:void(0)" recommendStartTime="' + row.recommendStartTime + '" recommendEndTime="' + row.recommendEndTime + '"  rid="' + row.productID + '"  data-toggle="modal" data-target="#edit_modal">设置推荐时间</a>';
                    return str;
                }

            },{
                field: 'payType',
                title: '支付方式',
                align: 'center',
                valign: 'middle',
                formatter: function(value, row, index){
                    var s = '';
                    if(value == 1){
                        s += '余额';
                    }else if(value == 2){
                        s += '支付宝';
                    }else if(value == 3){
                        s += '银联';
                    }else if(value == 4){
                        s += '银行转账';
                        if(row.isPaid == 0){
                            s += '<a title="确认到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/order/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=2"><i class="glyphicon glyphicon-ok"></i></a>';
                        }/*else if(row.orderStatus == 5 && row.orderType == 2){
                         s += '<a title="确认尾款到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/<?=$this->layout()->controllerName;?>/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=4"><i class="glyphicon glyphicon-ok"></i></a>';
                         }*/
                    }

                    return s;
                }

            },{
                field: 'isPaid',
                title: '是否付款',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, row, index){
                    var s = '';
                    if(value == 1 && row.payType){
                        s += '已付款';
                    }else if(value == 1){
                        s += '已付款';
                    }else if(value == 0){
                        s += '未付款';
                    }

                    return s;
                }

            },{
                field: 'isIllegal',
                title: '是否被举报',
                align: 'center',
                valign: 'middle',
                sortable: true,
                formatter : function(value, row, index){
                    var str = '';
                    if(value == 2){
                        str += '<font style="color:red;">是</font>';
                        str += '<a title="已处理" href="javascript:void(0)" class="text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认已处理吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isIllegal=1"><i class="glyphicon glyphicon-ok"></i></a>';
                    }else if(value == 1){
                        str += '已处理';
                    }else{
                        str += '否';
                    }
                    return str;
                }

            },{
                field: 'auctionStatus',
                title: '状态',
                align: 'center',
                valign: 'middle',
                formatter:function(value,row,index){
                    if(value == 0){
                        return '等待上架';
                    }else if(value == 1){
                        return '即将开拍';
                    }else if(value == 2){
                        return '正在拍卖中';
                    }else if(value == 3){
                        return '已结束';
                    }
                }
            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter
            }
            ]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="强制下架" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn text-danger" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认强制下架吗？" url="/admin/<?=$this->layout()->controllerName;?>/withdraw" method="post" params="productID='+ row.productID +'">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }

</script>
