<div id="toolbar" class="fixed-table-toolbar col-lg-offset-2">
    <div class="form-inline" role="form">
    </div>
</div>
<div class="fixed-table-body" style="min-height: 1000px;margin-bottom: 60px;">
    <table id="table-javascript" class="bootstrap_table"></table>
</div>

<script>
    $('#table-javascript').bootstrapTable({
        method: 'get',
        url: '/admin/product/list',
        cache: false,
        toolbar:"#toolbar",
        height: "auto",
        striped: true,
        pagination: true,
        pageSize: 10,
        pageList: [10, 25, 50, 100, 200],
        search: true,
        showColumns: true,
        showRefresh: true,
        sidePagination: 'server',
        clickToSelect: true,
        columns: [
            {
                field: 'productID',
                title: '拍品ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'productName',
                title: '拍品名称',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'storeID',
                title: '店铺ID',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'storeName',
                title: '店铺名称',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'startPrice',
                title: '起拍价',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'currPrice',
                title: '当前价格',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'deliveryPrice',
                title: '运费',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'depositPrice',
                title: '保证金',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'auctionCount',
                title: '出价次数',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'startTime',
                title: '起拍时间',
                align: 'center',
                valign: 'middle',
                width:200

            },{
                field: 'endTime',
                title: '结束时间',
                align: 'center',
                valign: 'middle',
                width:200

            },
            {
                field: 'isIndexRecommend',
                title: '首页推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isIndexRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isIndexRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isSpecialTodayRecommend',
                title: '专场拍卖推荐',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter:function(value, row, index){
                    if(value == 0){
                        var str = '<a title="推荐" href="javascript:void(0)" class="col-md-4 text-danger confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isSpecialTodayRecommend=1"><i class="glyphicon glyphicon-remove"></i></a>';
                    }else{
                        var str = '<a title="取消推荐" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认取消推荐吗？" url="/admin/<?=$this->layout()->controllerName;?>/update" method="post" params="productID='+ row.productID +'&isSpecialTodayRecommend=0"><i class="glyphicon glyphicon-ok"></i></a>';
                    }
                    return str;
                }

            },{
                field: 'isPaid',
                title: '是否付款',
                align: 'center',
                valign: 'middle',
                width:200,
                formatter: function(value, row, index){
                    var s = '';
                    if(value == 1){
                        s += '已付款';
                    }else if(value == 0){
                        s += '未付款';
                        s += '<a title="确认到账" href="javascript:void(0)" class="col-md-4 text-success confirm-btn" boxsize="modal-sm" ctitle="确认提示" cbody="确认到账吗?" url="/admin/order/confirm-paid" method="post" params="unitePayID='+ row.unitePayID +'&type=2"><i class="glyphicon glyphicon-ok"></i></a>';
                    }

                    return s;
                }

            },{
                field: 'auctionStatus',
                title: '状态',
                align: 'center',
                valign: 'middle',
                formatter:function(value,row,index){
                    if(value == 0){
                        return '等待上架';
                    }else if(value == 1){
                        return '即将开拍';
                    }else if(value == 2){
                        return '正在拍卖中';
                    }else if(value == 3){
                        return '已结束';
                    }
                }
            },{
                field: 'operate',
                title: '操作',
                align: 'center',
                valign: 'middle',
                formatter:operateFormatter
            }
            ]
    });

    function operateFormatter(value, row, index) {
        return [
            '<a title="强制下架" href="javascript:void(0)" class="remove ml10 col-md-4 confirm-btn text-danger" boxsize="modal-sm" ctitle="确认提示"' +
            ' cbody="确认强制下架吗？" url="/admin/<?=$this->layout()->controllerName;?>/withdraw" method="post" params="productID='+ row.productID +'">'+
            '<i class="glyphicon glyphicon-remove"></i>'+
            '</a>'
        ].join('');
    }

</script>
