<link rel="stylesheet" href="/dist/styles/main/index.css">
<div class="hot-shopAd mb20">
    <div class="center"><a href="/">首页</a> > <?php echo $settingInfo['remark'] ?></div>
</div>
<div class="center">
    <div class="page-box pb30 fz16">
        <iframe src="/article/setting-detail?settingName=<?php echo $settingInfo['settingName'] ?>" frameborder="0px" width="100%" id="iframepage" name="iframepage" onload="iframeHeight('iframepage');">
        </iframe>
    </div>
</div>
